# 1. RAG 평가 개요
- RAG 평가란 RAG 시스템이 주어진 입력에 대해 얼마나 효과적으로 관련 정보를 검색하고, 이를 기반으로 정확하고 유의미한 응답을 생성하는지를 측정하는 과정이다. 
- **평가 요소**
    - **검색 단계 평가**
        - 입력 질문에 대해 검색된 문서나 정보의 관련성과 정확성을 평가.
    - **생성 단계 평가**
        - 검색된 정보를 기반으로 생성된 응답의 품질, 정확성등을 평가.
- **평가 방법**
    - **온/오프라인 평가**
        1. **오프라인 평가**
            - 미리 준비된 데이터셋을 활용하여 RAG 시스템의 성능을 측정한다.
        2. **온라인 평가**
            - 실제 사용자 트래픽과 피드백을 기반으로 시스템의 실시간 성능을 평가한다.
    - **정량적/정성적 평가**
        1. 정량적 평가
            - 자동화된 지표를 사용하여 생성된 텍스트의 품질을 평가한다.
        2. 정성적 평가
            - 전문가나 일반 사용자가 직접 생성된 응답의 품질을 평가하여 주관적인 지표를 평가한다.

# 2. [RAGAS](https://www.ragas.io/)
- RAGAS는 RAG 파이프라인을 **정량적으로 평가하는** 오픈소스 프레임 워크이다. 
- RAGAS 문서: https://docs.ragas.io/en/stable/
## 2.1 설치
- `pip install ragas rapidfuzz`

## 2.2 RAGAS 평가 지표 개요
![ragas_score](figures/ragas_score.png)
- **Generation**
    - llm 모델이 생성한 답변에 대한 평가 지표들.
    - **Faithfulness(신뢰성)**
        -  생성된 답변과 검색된 문서(context)간의 관련성을 평가하는 지표
        -  생성된 답변이 주어진 문맥(context)에 얼마나 충실한지를 평가하는 지표로 할루시네이션에 대한 평가로 볼 수있다.
    - **Answer relevancy(답변 적합성)**
        - 생성된 답변과 사용자의 질문간의 관련성을 평가하는 지표
        - 생성된 답변이 사용자의 질문과 얼마나 관련성이 있는지를 평가하는 지표.
- **Retrieval**
    -  질문에 대해 검색한 문서(context)들에 대한 평가
    -  **Context Precision(문맥 정밀도)**
        -  검색된 문서(context)들 중 질문과 관련 있는 것들이 **얼마나 상위 순위에 위치하는지** 평가하는 지표.
    -  **Context Recall(문맥 재현률)**
        -  검색된 문서(context)가 정답(ground-truth)의 정보를 얼마나 포함하고 있는지 평가하는 지표.
- 이러한 지표들은 RAG 파이프라인의 성능을 다각도로 평가하는 데 활용된다.
![RAGAS_score2](figures/RAGAS_score2.png)

## 2.3 주요 평가지표
### 2.3.1 Generation 평가
- LLM이 생성한 답변에 대한 평가
  
#### 2.3.1.1 Faithfulness (신뢰성)
- 생성된 답변이 얼마나 주어진 검색 문서들(context)를 잘 반영해서 생성되었는지 평가한다. 할루시네이션에 대한 평가라고 할 수 있다. 
- 점수범위: **0 ~ 1** (1에 가까울수록 좋음)
- 답변에 포함된 모든 주장이 context에서 얼마나 추출 가능한지를 확인한다.

##### 2.3.1.1.1평가 방법
1. Answer에서 주장 구문(claim statement)들을 생성(추출)한다. (주장이란, 질문(user input)과 관련된 내용)
    - 예) 
        - **질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요? 
        - **LLM 답변**: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 3000만명이다.
2. 각 주장들을 context로 부터 추론 가능한지 판단한다. 이를 바탕으로 faithfulness 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다. .... 한국의 인구는 5000만명이고 서울에 1000만이 살고 있다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 추론가능한 주장.
            - 한국의 인구는 3000만명이다. -> context에서 추론 불가능한 주장.
3. **Faithfulness score** 를 계산한다. 총 주장 수 중에서 context로 부터 추론가능한 주장의 개수.    
    - 예)
        - Faithfulness Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 유추할 수있다.)
    - LLM 답변에서 주장을 추출 하는 것과 각 주장이 context에서 추론 가능한 지를 판단하는 것은 LLM 을 활용한다.
- 공식
    $$
    \text{Faithfulness Score}\;=\;\cfrac{\text{주어진\;context\;에서\;추론할\;수\;있는\;주장의\;개수}}{\text{총\;주장\;개수}}
    $$

### 2.3.2 Answer relevancy (답변 적합성)
- 생성된 답변이 질문(user input)에 얼마나 잘 부합하는 지를 평가한다.
- 점수 범위: -1~1 (1에 가까울수록 좋음)
- LLM이 생성한 답변을 기반으로 질문들을 생성한다. 이렇게 생성한 질문들과 실제 질문(user input) 간의 유사도를 측정한다.

#### 2.3.2.1 평가방법
1. LLM이 생성한 답변을 기반으로 질문들을 생성한다.
    - 예) 
        - **LLM** 답변: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
2. 실제 질문과 생성한 질문간의 코사인 유사도를 측정한다. 그 평균이 최종 점수가 된다.
    - 예)
        - **실제 질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요?
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
- 공식
  $$
    \cfrac{1}{N} \sum_{i=1}^{N} \text{cosine\_similarity}(q_{\text{user}_{_i}}, q_{\text{generated}})
  $$

## 2.4 Retrieval 평가
Vector store에서 검색한 context에 대한 평가

### 2.4.1 Context Precision
- 검색된 문서(context)들 중 질문과 관련 있는 것들이 얼마나 **상위 순위**에 있는 지 평가.
- 점수 범위: 0~1 (1에 가까울수록 좋음)


#### 2.4.1.1평가방법

- 공식
$$
 \text{Context\;Precision@K} = \frac{\sum_{k=1}^{K} \left( \text{Precision@k} \times v_k \right)}{\ 상위\;K개\;결과에서의\;관련\;항목\;수}
$$
$$
 \text{Precision@k} = \frac{\text{True\;positive@k}}{(\text{True\;positive@k} + \text{False\;positive@k})} \\
$$
- $\text{Precision@k}$: 개별 문서에 대한 Precision
- K: context 의 개수(chuck 수)
- $v_k$: 관련성 여부로 0 또는 1. (0: 관련 없음, 1: 관련 있음)

#### 2.4.1.2 예시
- 질문과 context 관련성의 예
    - 질문: 한국의 수도는 어디이고 인구는 얼마나 되나요?
    - **높은 정밀도 context들**: 질문과 직접적인 관련이 있는 문서들
        - 한국의 수도는 서울이고 인구는 5000만명 입니다. 
        - 한국의 수도는 서울입니다.
        - 한국은 동아시아에 위치해 있는 국가로 수도는 서울입니다.
        - 한국의 인구는 5000만명 입니다.
    - **낮은 정밀도 context**: 한국과 관련있어 검색될 수 있지만 질문과 직접적 관련이 없다. 
        - 한국은 동아시아에 위치한 국가입니다.
        - 한국의 K-pop은 전 세계적으로 유명합니다.
        - 비빔밥, 불고기는 한국의 대표적인 음식입니다.
    - **높은 정밀도의 context이 상위 순위에 위치했으면 높은 점수를 받는다.**

- 점수 계산 예:
    - **상위 5개의 검색 결과 중 1번째, 3번째, 4번째 문서가 관련이 있다고 가정하자.**
    - **Precision@K 계산**
        ```bash
            Precision@1 = 1/1 = 1.0    # True positive@1/(True positive@1 + False positive@1).  1/1(1번 문서 계산 시에는 1개 문서만 있으므로 분모가 1이 된다.)
            Precision@2 = 1/2 = 0.5
            Precision@3 = 2/3 ≈ 0.67    
            Precision@4 = 3/4 = 0.75
            Precision@5 = 3/5 = 0.6
        ```
    - **vk의 값**
        - 1번째: $v_1 = 1$ - 관련있음
        - 2번째: $v_2 = 0$ - 관련없음
        - 3번째: $v_3 = 1$ - 관련있음
        - 4번째: $v_4 = 1$ - 관련있음
        - 5번째: $v_5 = 0$ - 관련없음

    - **Context Precision@5**
        $$
        \text{Context\;Precision@5} = \frac{(1.0 \times 1) + (0.5 \times 0) + (0.67 \times 1) + (0.75 \times 1) + (0.6 \times 0)}{3} = \frac{1.0 + 0 + 0.67 + 0.75 + 0}{3} ≈ 0.807
        $$

### 2.4.2 Context Recall (문맥 재현률)
- 검색된 문서(context)가 얼마나 정답(ground-truth)의 정보를 포함있는 지 평가하는 지표
- 점수 범위: 0~1 (1에 가까울수록 좋음)
- **정답(ground truth)의 각 주장(claim)이 검색된 context와 얼마나 일치**하는지 계산함.

#### 2.4.2.1 평가방법
1. 정답에서 주장(claim)들을 생성(추출)한다.
    - 예) 
        - **정답**: 한국의 수도는 서울이고 인구수는 5000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 5000만명이다.
2. 각 주장(claim)의 정보를 검색된 contexts에서 찾을 수 있는지 판별한다. 이를 바탕으로 context recall 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 찾을 수 있다.
            - 한국의 인구는 5000만명이다. -> context에서 찾을 수 없다.
3. **Context Recall Score** 를 계산한다. 총 주장 수 중에서 context로 부터 찾을 수 있는 주장의 개수.
    - 예)
        - Context Recall Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 찾을 수 있다.)

- 공식
    $$
    \text{Context Recall Score}\;=\;\cfrac{\text{GT의\;주장\;중\;주어진\;context\;에서\;찾을\;수\;있는\;주장의\;개수}}{\text{GT의\;총\;주장\;개수}}
    $$

# 3. RAGAS 평가 실습

In [2]:
# !uv pip install ragas rapidfuzz
# 설치 후 커널 재시작

In [3]:
# docker run -p 6333:6333 -p 6334:6334   -v qdrant_storage:/qdrant/storage   qdrant/qdrant
# termianal에서 실행

## 0. 패키지 설치

In [4]:
# 필요한 library: pymupdf pdfplumber pillow openai qdrant-client langchain-core langchain-openai langchain-qdrant langchain-text-splitters python-dotenv

## 1. 설정 및 클라이언트 준비

In [5]:
import os
import re
import glob
import uuid
from pathlib import Path

import fitz  # PyMuPDF
import pdfplumber
from PIL import Image
from openai import OpenAI
from dotenv import load_dotenv

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, Filter, FieldCondition, MatchValue

from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings
from langchain_qdrant import QdrantVectorStore
from langchain_text_splitters import RecursiveCharacterTextSplitter

load_dotenv()

# ----- 설정값 -----
GUIDANCE_DIR = "./길라잡이"          # 이 폴더 안의 모든 PDF를 찾아서 적재

QDRANT_URL = os.getenv("QDRANT_URL", "http://localhost:6333")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY") or None
COLLECTION_NAME = "guidance_vectordb"

CHAT_MODEL = "gpt-5.4-mini"                          # 표 요약 / 이미지 캐법션용
EMBED_MODEL = "text-embedding-3-large"         # large 임베딩 모델
EMBED_DIM = 3072

CHUNK_SIZE = 800       # 텍스트 청크 최대 글자 수 (splitter 기준)
CHUNK_OVERLAP = 150    # 청크 간 격치는 글자 수 (문맥 끓김 방지)

openai_client = OpenAI()
qdrant_client = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)
embeddings = OpenAIEmbeddings(model=EMBED_MODEL)


def ensure_collection() -> bool:
    """collection이 이미 있으면 True(기존 데이터 존재), 없으면 새로 만들고 False를 반환"""
    existing = [c.name for c in qdrant_client.get_collections().collections]
    if COLLECTION_NAME in existing:
        print(f"'{COLLECTION_NAME}' collection이 이미 존재합니다.")
        return True
    qdrant_client.create_collection(
        collection_name=COLLECTION_NAME,
        vectors_config=VectorParams(size=EMBED_DIM, distance=Distance.COSINE),
    )
    print(f"'{COLLECTION_NAME}' collection 생성 완료 (dim={EMBED_DIM})")
    return False


collection_already_existed = ensure_collection()

vectorstore = QdrantVectorStore(
    client=qdrant_client,
    collection_name=COLLECTION_NAME,
    embedding=embeddings,
)

pdf_paths = sorted(glob.glob(str(Path(GUIDANCE_DIR) / "*.pdf")))
print(f"'{GUIDANCE_DIR}' 안에서 발견된 PDF {len(pdf_paths)}개")
for p in pdf_paths:
    print(" -", p)

'guidance_vectordb' collection이 이미 존재합니다.
'./길라잡이' 안에서 발견된 PDF 2개
 - 길라잡이\사병_길라잡이.pdf
 - 길라잡이\초급간부_길라잡이.pdf

## 2. 텍스트 정제

In [6]:
def clean_text(text: str) -> str:
    # Private Use Area (U+E000–U+F8FF) 문자 제거
    text = re.sub(r'[\ue000-\uf8ff]', '', text)
    # 과도한 공백/빈 줄 정리
    text = re.sub(r'[ \t]+', ' ', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

## 3. 표 추출 → 마크다운 → 요약

In [7]:
def table_to_markdown(table_rows):
    rows = [[cell if cell is not None else "" for cell in row] for row in table_rows]
    if not rows:
        return ""
    header = rows[0]
    body = rows[1:]
    md_lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(["---"] * len(header)) + " |"]
    for row in body:
        md_lines.append("| " + " | ".join(row) + " |")
    return "\n".join(md_lines)


def extract_tables(pdf_path: str):
    tables_out = []
    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, start=1):
            for table in page.extract_tables():
                if not table or len(table) < 2:
                    continue
                md_table = table_to_markdown(table)
                tables_out.append({"page": page_num, "markdown": md_table})
    return tables_out


def summarize_table(table_markdown: str) -> str:
    response = openai_client.chat.completions.create(
        model=CHAT_MODEL,
        max_completion_tokens=300,
        messages=[{
            "role": "user",
            "content": (
                "다음은 문서에서 추출한 표입니다. 이 표가 어떤 내용을 담고 있는지 "
                "검색에 활용할 수 있도록 2~4문장의 한국어로 요약해줘. "
                "컬럼이 의미하는 바와 주요 수치/항목을 포함해줘.\n\n"
                f"{table_markdown}"
            ),
        }],
    )
    return response.choices[0].message.content.strip()

## 4. 텍스트 청킹 (페이지 단위)

In [8]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    separators=["\n\n", "\n", ". ", " ", ""],
)

# 이 길이를 넘는 페이지만 splitter로 추가 분할 (그 외엔 페이지 통째로 한 청크)
PAGE_OVERFLOW_THRESHOLD = 1200


def chunk_text_by_page(pdf_path: str) -> list[dict]:
    """페이지 단위로 청크를 만든다. 페이지가 너무 길 때만 그 페이지 안에서 추가로 나눈다."""
    doc = fitz.open(pdf_path)
    results = []

    for page_num, page in enumerate(doc, start=1):
        page_text = clean_text(page.get_text("text"))

        if not page_text:
            continue  # 텍스트 없는 페이지(이미지만 있는 페이지 등)는 건너뜀

        if len(page_text) <= PAGE_OVERFLOW_THRESHOLD:
            results.append({"page": page_num, "text": page_text})
        else:
            # 이 페이지만 너무 길어서 임베딩이 흐려질 수 있는 경우 -> 페이지 내부에서만 분할
            sub_chunks = text_splitter.split_text(page_text)
            for sub in sub_chunks:
                results.append({"page": page_num, "text": sub})

    doc.close()
    return results

## 5. PDF 1개 → LangChain `Document` 리스트로 통합

In [9]:
ID_NAMESPACE = uuid.NAMESPACE_URL


def make_id(doc_name: str, chunk_type: str, index: int) -> str:
    """같은 PDF를 다시 적재해도 같은 ID가 나오도록 결정론적으로 생성 (재실행 시 upsert로 덮어씀)"""
    return str(uuid.uuid5(ID_NAMESPACE, f"{doc_name}::{chunk_type}::{index}"))


def build_documents_for_pdf(pdf_path: str) -> tuple[list[Document], list[str]]:
    doc_name = Path(pdf_path).name
    documents = []
    ids = []
    counter = 0

    # 1) 텍스트 청크
    text_chunks = chunk_text_by_page(pdf_path)
    for c in text_chunks:
        documents.append(Document(
            page_content=c["text"],
            metadata={"doc_name": doc_name, "page": c["page"], "type": "text"},
        ))
        ids.append(make_id(doc_name, "text", counter))
        counter += 1

    # 2) 표
    tables = extract_tables(pdf_path)
    for t in tables:
        summary = summarize_table(t["markdown"])
        documents.append(Document(
            page_content=summary,
            metadata={
                "doc_name": doc_name, "page": t["page"], "type": "table",
                "table_markdown": t["markdown"], "summary": summary,
            },
        ))
        ids.append(make_id(doc_name, "table", counter))
        counter += 1

    print(f"[{doc_name}] 텍스트 {len(text_chunks)} / 표 {len(tables)} → 총 {len(documents)}개")
    return documents, ids

## 6. 디렉토리 전체 적재 (upsert)

In [10]:
def upsert_documents(documents: list[Document], ids: list[str], batch_size: int = 100):
    for i in range(0, len(documents), batch_size):
        batch_docs = documents[i:i + batch_size]
        batch_ids = ids[i:i + batch_size]
        vectorstore.add_documents(documents=batch_docs, ids=batch_ids)
        print(f"  upsert 진행: {min(i + batch_size, len(documents))}/{len(documents)}")


def run_pipeline(directory: str = GUIDANCE_DIR):
    paths = sorted(glob.glob(str(Path(directory) / "*.pdf")))
    print(f"'{directory}'에서 PDF {len(paths)}개 발견, 적재 시작\n")

    total_chunks = 0
    for pdf_path in paths:
        documents, ids = build_documents_for_pdf(pdf_path)
        upsert_documents(documents, ids)
        total_chunks += len(documents)
        print()

    print(f"완료: PDF {len(paths)}개 / 총 {total_chunks}개 청크 적재")


# collection이 이미 있었다면 재적재를 건너뜀 (PDF 파싱/표 요약/임베딩 API 재호출 비용 방지)
if not collection_already_existed:
    run_pipeline(GUIDANCE_DIR)
else:
    print(f"'{COLLECTION_NAME}' 컴렉션에 이미 데이터가 있어 적재를 건너뜁니다. (재적재하려면 run_pipeline(GUIDANCE_DIR)를 직접 호출하세요)")

'guidance_vectordb' 컴렉션에 이미 데이터가 있어 적재를 건너뜁니다. (재적재하려면 run_pipeline(GUIDANCE_DIR)를 직접 호출하세요)

## 7. 검색 예시

In [11]:
def search(query: str, k: int = 5, type_filter: str = None):
    qfilter = None
    if type_filter:
        qfilter = Filter(must=[FieldCondition(key="metadata.type", match=MatchValue(value=type_filter))])

    results = vectorstore.similarity_search_with_score(query, k=k, filter=qfilter)

    for doc, score in results:
        print(f"[score={score:.3f}] doc={doc.metadata.get('doc_name')} page={doc.metadata.get('page')} type={doc.metadata.get('type')}")
        print(doc.page_content[:200])
        print("-" * 40)

    return results


# 사용 예시:
search("군인 해택 휴양시설알려줘")
# search("휴가 관련 표", type_filter="table")
# search("기차 할인 안내 이미지", type_filter="image")

[score=0.585] doc=사병_길라잡이.pdf page=23 type=text
2026 병 복지 길라잡이 23
 • 국군복지단 휴양시설 현황
구분
시 설 명
위 치
전화번호(군)
전화번호(일반)
직영
서귀포 호텔
제주 서귀포시
960-7703
064-738-0123
화진포 콘도
강원 고성군
960-7706
033-682-0500
청간정 콘도
강원 고성군
822-6470
033-631-9331
송 정 콘도
강원 강릉시
940-38
----------------------------------------
[score=0.549] doc=사병_길라잡이.pdf page=22 type=text
Part 01 생활편의 분야
22 2026 병 복지 길라잡이
휴양시설 이용
이용대상 / 방법 및 혜택
 • 이용대상 : 현역병, 배우자 및 그 직계 존·비속
 * 가족의 경우 가족관계 증빙서류, 신분증 또는 국방가족 모바일증명 제시
 * 국방가족 모바일증명은 국군복지포털 홈페이지를 이용하여 등록
 • 국군복지단 휴양시설 이용방법
 - 국군복지포털 홈페이지
----------------------------------------
[score=0.543] doc=초급간부_길라잡이.pdf page=35 type=text
34
2026 초급간부 길라잡이
•국군복지단 휴양시설 현황
구분
시 설 명
위 치
전화번호(군)
전화번호(일반)
직영
서귀포 호텔
제주 서귀포시
960-7703
064-738-0123
화진포 콘도
강원 고성군
960-7706
033-682-0500
청간정 콘도
강원 고성군
988-7873
033-631-9331
송정 콘도
강원 강릉시
940-3881
----------------------------------------
[score=0.525] doc=초급간부_길라잡이.pdf page=34 type=text
02
Part
생
활
편
의

분
야
33
2026 초급간부 길라잡이
•국군복지단 초급간부전용 객실예약 이용방법
- 국군복지포털 호텔/콘도/컨벤션-객실예약-‘초급간부전용 객실예약’ 활용
- 국군복지단 휴양시설 세부 이용절차
신청/접수
•인터넷 : 국군복지단 홈페이지(www.welfare.mil.kr)
 * 스마트폰 : 국군복지포털 앱 ⇨ 호텔/콘도
----------------------------------------
[score=0.507] doc=초급간부_길라잡이.pdf page=35 type=table
이 표는 국군복지단에서 이용 가능한 숙박·콘도 시설 목록으로, **시설명**, **위치**, **군 전화번호**, **일반 전화번호**를 정리한 자료입니다. 서귀포 호텔, 화진포 콘도, 청간정 콘도, 송정 콘도, 대천 콘도 등 개별 시설과 함께 한화·금호·소노·켄싱턴 같은 제휴 리조트 브랜드별 이용 가능 지역도 포함되어 있습니다. 대표 연락처로는 서귀포 호
----------------------------------------

[(Document(metadata={'doc_name': '사병_길라잡이.pdf', 'page': 23, 'type': 'text', '_id': 'fb4aa98d-c931-5260-82b6-e1fa8da946b5', '_collection_name': 'guidance_vectordb'}, page_content='2026 병 복지 길라잡이 23\n • 국군복지단 휴양시설 현황\n구분\n시 설 명\n위 치\n전화번호(군)\n전화번호(일반)\n직영\n서귀포 호텔\n제주 서귀포시\n960-7703\n064-738-0123\n화진포 콘도\n강원 고성군 \n960-7706\n033-682-0500\n청간정 콘도\n강원 고성군 \n822-6470\n033-631-9331\n송 정 콘도\n강원 강릉시 \n940-3881\n033-652-7573\n대 천 콘도\n충남 보령시 \n960-7705\n041-932-6305\n민영\n한 화\n설악, 용인, 대천, 산정호수, \n해운대, 경주, 제주, 평창, 거제\n국군복지단\n예약실\n984-6584\n국군복지단\n예약실\n1577-9800\n내선 “1번”\n금 호\n통영, 화순, 설악, 제주, 아산\n소 노\n설악, 경주, 단양, 홍천, 양양, \n변산, 거제, 삼척, 진도, 여수, \n고양(호텔), 양평\n켄싱턴\n남원, 설악비치, 충주, 경주,\n가평, 설악밸리, 하동, 서귀포\n무 주\n전북무주\n리 솜\n안면도\n엘도라도\n전남신안\n샤인빌(소노캄)\n제주\n보 광\n제주\n웰리힐리\n강원횡성\n영랑호\n강원 속초\n현대수\n강원 속초\n • 각 군 휴양시설 이용방법 : 각 군 홈페이지 참조\n구분\n시 설 명\n홈페이지 주소\n국방부\n국방컨벤션(웨딩)\nwww.mndconvention.co.kr\n육군\n로카우스 호텔, 계룡스파텔\nwelfare.army.mil.kr\n해군\n해군호텔(서울, 평택, 제주), \n해군회관(진해)\nwelfare.navy.mil.kr\n공군\n공군호텔\nwww.airforcehotel.co.kr\n그린나래호텔\nwww.guerinnarae.com\n해병대\n밀리토피아호텔 바이마린(해병대호텔)\nwww.militopiahotelbymarine.com'),
  0.5851183),
 (Document(metadata={'doc_name': '사병_길라잡이.pdf', 'page': 22, 'type': 'text', '_id': '40497236-80dc-5f46-b78d-a7b918de24d9', '_collection_name': 'guidance_vectordb'}, page_content='Part 01 생활편의 분야\n22 2026 병 복지 길라잡이\n휴양시설 이용\n이용대상 / 방법 및 혜택\n • 이용대상 : 현역병, 배우자 및 그 직계 존·비속\n * 가족의 경우 가족관계 증빙서류, 신분증 또는 국방가족 모바일증명 제시\n * 국방가족 모바일증명은 국군복지포털 홈페이지를 이용하여 등록\n • 국군복지단 휴양시설 이용방법\n - 국군복지포털 홈페이지 메인화면에 ‘병사전용 회원가입 메뉴’ 활용\n * 최소한의 정보(군번, 군구분, 성명 입력 → ID / PW 생성)로 가입 가능\n - 국군복지단 휴양시설 세부 이용절차\n신청/\n접수\n∙ 인터넷 : 국군복지포털 홈페이지(http://www.welfare.mil.kr)\n* 스마트폰 : 국군복지포털 앱 ⇨ 호텔/콘도 ⇨ 현역병 전용 예약\n∙ 예약/회원가입 : 군 984-6584, 일반 1577-9800 내선 1번\n신청시기\n예약확정\n∙ 직영 시설 이용일 기준 30일 전 00시~8일 전 23:59까지 신청\n 민영 시설 이용일 기준 30일 전 00시∼22일 전 23:59\n예약자 \n통보\n∙ 예약확정 시 이용 안내문자 발송\n1회 숙박\n가능기간\n∙ 성수기/ 비수기 주말(금, 토) : 2박 3일(제주지역: 3박 4일)\n∙ 비수기 평일(일 ~ 목) : 4박 5일\n * 여름⋅겨울 성수기(스키장운영 민영콘도만 해당) 기간 중\n 시설 이용은 1인 1회 / 기타 기간은 월 2회\n \n • 혜 택\n - 국군복지단 휴양시설(민영, 직영) 병사(가족) 대상 객실 우선 할당\n * 현역 이용 객실의 20%\n * 예약방법: 국군복지포털 홈페이지 내 ‘현역병 전용 객실예약’ 활용\n - 국군복지단 직영 휴양시설 성수기를 제외한 기간 중 평일 객실 30% 할인 \n * 현역병 본인 투숙 시\n * 직영콘도별 성수기 기간 : (제주) 매년 12월 1일 ∼ 2월 29일 /\n (제주 외) 매년 7월 1일 ~ 8월 31일'),
  0.5488748),
 (Document(metadata={'doc_name': '초급간부_길라잡이.pdf', 'page': 35, 'type': 'text', '_id': '1ae0cc80-62b3-5c57-9da7-42a7b205c3cf', '_collection_name': 'guidance_vectordb'}, page_content='34 \n2026 초급간부 길라잡이\n•국군복지단 휴양시설 현황\n구분\n시 설 명\n위 치\n전화번호(군)\n전화번호(일반)\n직영\n서귀포 호텔\n제주 서귀포시\n960-7703\n064-738-0123\n화진포 콘도\n강원 고성군 \n960-7706\n033-682-0500\n청간정 콘도\n강원 고성군 \n988-7873\n033-631-9331\n송정 콘도\n강원 강릉시 \n940-3881\n033-652-7573\n대천 콘도\n충남 보령시 \n960-7705\n041-932-6305\n민영\n한 화\n 거제, 경주, 대천, \n산정호수, 설악, 용인, \n제주, 평창, 해운대\n국군복지단\n예약실\n984-6499\n국군복지단\n예약실\n1577-9800\n금 호\n 통영, 화순, 설악, 제주, 아산\n소 노\n 경주, 거제, 고양, 단양,\n변산, 삼척, 설악, 진도,\n양양, 양평, 여수, 홍천\n켄싱턴\n남원, 설악비치, 충주, \n경주, 가평, 설악밸리, \n하동, 서귀포\n무 주\n전북 무주\n리 솜\n안면도\n엘도라도\n전남 신안\n샤인빌\n제주\n보 광\n제주\n웰리힐리\n강원 횡성\n영랑호\n강원 속초\n현대수\n강원 속초\n국방부 복지정책과 복지운영담당 | 900-6617\n담당부서'),
  0.54266524),
 (Document(metadata={'doc_name': '초급간부_길라잡이.pdf', 'page': 34, 'type': 'text', '_id': '58b67cb3-15b4-5cad-9036-b93e98e25e44', '_collection_name': 'guidance_vectordb'}, page_content='02\nPart\n생\n활\n편\n의\n \n분\n야\n33 \n2026 초급간부 길라잡이\n•국군복지단 초급간부전용 객실예약 이용방법\n- \x07국군복지포털 호텔/콘도/컨벤션-객실예약-‘초급간부전용 객실예약’ 활용\n- 국군복지단 휴양시설 세부 이용절차\n신청/접수\n•\x07인터넷 : 국군복지단 홈페이지(www.welfare.mil.kr)\n * 스마트폰 : 국군복지포털 앱 ⇨ 호텔/콘도 ⇨ 초급간부 전용 예약\n•\x07예약/회원가입 : 군 984-6499, 일반 1577-9800 내선 1번\n신청시기/ \n예약확정\n•\x07기간 : 이용일 기준 50일 전일 00:00 ∼ 30일 전일 23:59\n•\x07예약확정 확인 : 이용일 기준 29일 전일 10:00 확정(복지포털 확인)\n * 추첨제 탈락 시 : 일반 예약신청(점수제) 자동 전환 / 자동 전환 취소 가능\n예약자 통보\n•\x07예약확정 시 이용 안내문자 발송\n1회 숙박\n가능기간\n•\x07성수기/비수기 주말(금, 토) : 2박 3일(제주지역: 3박 4일)\n•\x07비수기 평일(일 ~ 목) : 4박 5일\n * \x07여름·겨울 성수기(스키장운영 민영콘도만 해당) 기간 중 시설 이용은 1인 1회 / \n기타 기간은 월 2회 \n•비수기 잔여객실 회원초대제도\n- 현역간부, 가족(직계존비속) 외 비회원을 초대하여 단독 이용기회 \n* \x07예약기간 : 내륙-이용일 기준 10일 전 ~ 4일 전, 제주-이용일 기준 25일 전 ~ 4일 전 \n* 요금적용 : 회원요금과 동일(직영시설의 경우 부가가치세 10% 추가)\n* 예약방법 : 잔여객실 예약에서 ‘초대함’ 선택 및 실제 이용자 입력\n* 초대한도 : 연 5회\n•각 군 휴양시설 이용방법 : 각 군 홈페이지 참조\n구분\n시 설 명\n홈페이지\n국방부\n국방컨벤션\nwww.mndconvention.co.kr\n육군\n계룡스파텔, ROKAUS호텔\nwelfare.army.mil.kr\n해군\n해군호텔(서울, 평택, 제주), \n해군회관(진해)\nwelfare.navy.mil.kr\n공군\n공군호텔\nwww.airforcehotel.co.kr\n그린나래호텔\nwww.guerinnarae.com\n해병대\n밀리토피아 호텔 바이마린\nwww.militopiahotelbymarine.com\n* 현역 결혼, 가족 행사시 컨벤션 할인 혜택 : 각 기관 홈페이지 확인'),
  0.5252058),
 (Document(metadata={'doc_name': '초급간부_길라잡이.pdf', 'page': 35, 'type': 'table', 'table_markdown': '| 구분 | 시 설 명 | 위 치 | 전화번호(군) | 전화번호(일반) |\n| --- | --- | --- | --- | --- |\n|  | 서귀포 호텔 | 제주 서귀포시 | 960-7703 |  |\n|  | 화진포 콘도 | 강원 고성군 | 960-7706 |  |\n|  | 청간정 콘도 | 강원 고성군 | 988-7873 |  |\n|  | 송정 콘도 | 강원 강릉시 | 940-3881 |  |\n|  | 대천 콘도 | 충남 보령시 | 960-7705 |  |\n|  | 한 화 | 거제, 경주, 대천,\n산정호수, 설악, 용인,\n제주, 평창, 해운대 | 국군복지단\n예약실\n984-6499 |  |\n|  | 금 호 | 통영, 화순, 설악, 제주, 아산 |  |  |\n|  | 소 노 | 경주, 거제, 고양, 단양,\n변산, 삼척, 설악, 진도,\n양양, 양평, 여수, 홍천 |  |  |\n|  | 켄싱턴 | 남원, 설악비치, 충주,\n경주, 가평, 설악밸리,\n하동, 서귀포 |  |  |\n|  | 무 주 | 전북 무주 |  |  |\n|  | 리 솜 | 안면도 |  |  |\n|  | 엘도라도 | 전남 신안 |  |  |\n|  | 샤인빌 | 제주 |  |  |\n|  | 보 광 | 제주 |  |  |\n|  | 웰리힐리 | 강원 횡성 |  |  |\n|  | 영랑호 | 강원 속초 |  |  |\n|  | 현대수 | 강원 속초 |  |  |', 'summary': '이 표는 국군복지단에서 이용 가능한 숙박·콘도 시설 목록으로, **시설명**, **위치**, **군 전화번호**, **일반 전화번호**를 정리한 자료입니다. 서귀포 호텔, 화진포 콘도, 청간정 콘도, 송정 콘도, 대천 콘도 등 개별 시설과 함께 한화·금호·소노·켄싱턴 같은 제휴 리조트 브랜드별 이용 가능 지역도 포함되어 있습니다. 대표 연락처로는 서귀포 호텔 960-7703, 화진포 콘도 960-7706, 청간정 콘도 988-7873, 송정 콘도 940-3881, 대천 콘도 960-7705가 기재되어 있으며, 한화 예약실은 984-6499로 표시되어 있습니다.', '_id': '7f46223c-b7fa-5103-9b15-f793fae79e32', '_collection_name': 'guidance_vectordb'}, page_content='이 표는 국군복지단에서 이용 가능한 숙박·콘도 시설 목록으로, **시설명**, **위치**, **군 전화번호**, **일반 전화번호**를 정리한 자료입니다. 서귀포 호텔, 화진포 콘도, 청간정 콘도, 송정 콘도, 대천 콘도 등 개별 시설과 함께 한화·금호·소노·켄싱턴 같은 제휴 리조트 브랜드별 이용 가능 지역도 포함되어 있습니다. 대표 연락처로는 서귀포 호텔 960-7703, 화진포 콘도 960-7706, 청간정 콘도 988-7873, 송정 콘도 940-3881, 대천 콘도 960-7705가 기재되어 있으며, 한화 예약실은 984-6499로 표시되어 있습니다.'),
  0.50705904)]

## 8. Retriever 생성

In [12]:
##################################################
# retriever 생성
##################################################

def get_retriever(vectorstore, k: int = 5):
    retriever = vectorstore.as_retriever(
        search_kwargs={"k": k}
    )
    return retriever


retriever = get_retriever(vectorstore)
print(retriever)

tags=['QdrantVectorStore', 'OpenAIEmbeddings'] vectorstore=<langchain_qdrant.qdrant.QdrantVectorStore object at 0x0000026C0D7DF230> search_kwargs={'k': 5}

In [13]:
################################################################################
# 평가할 RAG Chain
################################################################################

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser
from langchain_core.documents import Document
from langchain_openai import ChatOpenAI

prompt_txt = """<instruction>
당신은 정보제공을 목적으로하는 유능한 AI Assistant 입니다.
주어진 context의 내용을 기반으로 질문에 답변을 합니다.
Context에 질문에 대한 명확한 정보가 있는 경우 그것을 바탕으로 답변을 합니다.
Context에 질문에 대한 명확한 정보가 없는 경우 "정보가 부족해 답을 할 수없습니다." 라고 답합니다.
절대 추측이나 일반 상식을 바탕으로 답을 하거나 Context 없는 내용을 만들어서 답변해서는 안됩니다.
</instruction>
<context>
{context}
</context>
<question>
{query}
</question>
"""
prompt = ChatPromptTemplate.from_template(template=prompt_txt)

model = ChatOpenAI(model="gpt-5.4-mini")
parser = StrOutputParser()


def format_docs_for_prompt(documents: list[Document]) -> str:
    """LLM 프롬프트({context})용: 문서들을 하나의 문자열로 합침 (doc_name/page도 같이 표기)"""
    parts = []
    for doc in documents:
        meta = doc.metadata
        header = f"[{meta.get('doc_name', '')} p.{meta.get('page', '')}]"
        parts.append(f"{header}\n{doc.page_content}")
    return "\n\n---\n\n".join(parts)


def format_docs_for_ragas(documents: list[Document]) -> list[str]:
    """RAGAS 평가용: 검색된 문서 각각의 내용을 list[str]로 추출"""
    return [doc.page_content for doc in documents]


def build_prompt_input(state: dict) -> dict:
    """검색 결과({'documents':..., 'query':...})를 prompt 입력({'context':str, 'query':str})으로 변환"""
    return {
        "context": format_docs_for_prompt(state["documents"]),
        "query": state["query"],
    }


# 1단계: 질문으로 검색 → 원본 Document 리스트 + 질문 보존 (retriever는 여기서 1회만 호출됨)
retrieve_step = {
    "documents": retriever,
    "query": RunnablePassthrough(),
}

# RAG 체인 -> RAG 평가 데이터셋을 만드는 RAG Chain -> 최종응답: LLM 응답(str), 검색한 문서들(list[str]), 질문(str)
chain = (
    RunnablePassthrough()  # dict | dict 가 파이썬 dict 병합 연산으로 취급되는 것을 막기 위해 필요
    | retrieve_step
    | {
        "response": RunnableLambda(build_prompt_input) | prompt | model | parser,
        "retrieved_context": RunnableLambda(lambda state: format_docs_for_ragas(state["documents"])),
        "query": RunnableLambda(lambda state: state["query"]),
    }
)

In [14]:
res = chain.invoke("병장의 월급은?")

In [15]:
res["response"]

'병장의 월급은 **1,500,000원**입니다.'

In [16]:
res["retrieved_context"]

['Part 01 생활편의 분야\n6 2026 병 복지 길라잡이\n보 수\n봉 급\n • 계급별 지급액\n 단위 : 원\n \n이병\n일병\n상병\n병장\n750,000\n900,000\n1,200,000\n1,500,000\n • 병 봉급 인상\n 단위 : 원\n연도\n계급\n’21년\n’22년\n’23년\n’24년\n’25~’26년\n병 장 \n608,500\n676,100\n1,000,000\n1,250,000\n1,500,000\n상 병 \n549,200\n610,200\n800,000\n1,000,000\n1,200,000\n일 병\n496,900\n552,100\n680,000\n800,000\n900,000\n이 병\n459,100\n510,100\n600,000\n640,000\n750,000\n인상율(병장)\n12.5%\n11.1%\n47.9%\n25%\n20%\n* 병역의무 이행자의 보상과 예우를 위해 병 봉급과 자산형성프로그램을 결합하여\n’25년까지 병장 기준 200만원 이상으로 인상\n수 당\n단위 : 원\n \n구 분\n지급 기준\n금액\n특수지\n근 무\n수 당\n갑\n・비무장지대, 서해5도, 울릉도, 접적 해역 상주 근무자\n * 가산금 : 서해5도 40,000원, 비무장지대 및 \n북방한계선 인접해역 20,000원\n25,000 \n(가산금별도)\n을\n・GOP, 해안초소, 해발 800m 이상 고지대 상주 근무자\n * 가산금 : 10,000원(GOP / 해안초소)\n20,000\n(가산금별도)\n항 공\n수 당\n을\n・항공기 동승근무자\n40,000 \n함 정\n수 당\n을\n・전투함 및 지원함 승무원\n * 함정출동가산금 : 1일 4,000원\n32,700 \n(가산금별도)\n병\n・수륙양용궤도차량 승무원\n32,700 \npart 01\n생활편의 분야\n▶▶▶ 병 복지혜택 이렇게 다양합니다',
 '이 표는 **계급별 연도(’21~’26년) 급여 수준과 병장 급여 인상률**을 비교한 자료입니다. 행은 **병장·상병·일병·이병**의 월급이며, 열은 **’21년, ’22년, ’23년, ’24년, ’25~’26년**의 금액 변화를 보여줍니다. 주요 수치로 병장 급여는 **60.85만 원 → 67.61만 원 → 100만 원 → 125만 원 → 150만 원**, 상병은 **54.92만 원 → 61.02만 원 → 80만 원 → 100만 원 → 120만 원**, 일병은 **49.69만 원 → 55.21만 원 → 68만 원 → 80만 원 → 90만 원**, 이병은 **45.91만 원 → 51.01만 원 → 60만 원 → 64만 원 → 75만 원**으로 증가합니다. 또한 병장 인상률은 **12.5%, 11.1%, 47.9%, 25%, 20%**로 표시되어 있습니다.',
 '2026 병 복지 길라잡이 7\n수 당(계속)\n 단위 : 원 / 월\n \n구 분\n지급 기준\n금액\n위험\n근무\n수당\n갑\n・40m 이상 해난구조 및 특수잠수 작업\n240,240\n・고공 낙하산 강하자\n138,800\n・불발탄처리 및 탄약 기능 시험자, 지뢰제거 작전 투입\n118,800\n을\n・항공기/기구 강하자\n85,000 \n・헬기 레펠 및 F/R 강하자\n55,000\n・상륙 임무자(해병대)\n50,000\n병\n・특수전류분야 종사자, 탄약개수의 특수분야 종사자\n・월 1회 모형탑 낙하자, 컨테이너 크레인 운용자\n・유해발굴 / 감식업무자, 중장비 수송차량 운전자\n18,000\n위험근무수당 \n가산금\n・위험근무수당을 지급받는 특전사, 해병대, 해군(UDT/SSU)과 각 군의 \n폭발물처리반에 근무하는 군인이 특수임무를 위해 야외 출동 시 1일 \n3,000원 지급\n해파수당\n・해외파견근무수당 지급규정에 따라 임무・환경・등급・지역 등 고려 \n등급별 지급\n * 월 지급 기준액(미합중국 달러) : 1,474달러\n여 비\n • 정기휴가비(급지별) * ’25년 식비 : 7,000원 / 1식\n단위 : 원\n \n구 분\n휴가여비(왕복)\n전역귀가여비(편도)\n1 급지 (451Km 이상)\n152,200\n76,100\n2 급지 (450Km까지)\n138,400\n69,200\n3 급지 (400Km까지)\n110,600\n55,300\n4 급지 (350Km까지)\n96,800\n48,400\n5 급지 (300Km까지)\n83,000\n41,500\n6 급지 (250Km까지)\n69,200\n34,600\n7 급지 (200Km까지)\n46,800\n23,400\n8 급지 (150Km까지)\n33,000\n16,500\n9 급지 (100Km까지)\n22,000\n11,000\n10 급지 (50Km까지)\n13,800\n6,900\n도서가산금\n50해리 미만\n49,800\n24,900\n50해리 이상\n145,560\n89,280\n백령(울릉)도\n175,720\n111,360\n* 교통비 기준 단가 인상 : Km당 132원→138원, 식비 : 7,000원 / 1식 \n • 도서가산금 : (기존) 귀향지만 적용, (개선) 출발지까지 추가',
 'Part 01 생활편의 분야\n8 2026 병 복지 길라잡이\n병 급여(봉급/ 수당 등) 확인방법 안내\n • 급여 지급 일자별 지급항목\n - 매월 10일 : 봉급, 수당, 휴가ㆍ전역비, 병 일용품비\n - 매월 25일 : 신규 입대자 봉급, 수당, 휴가ㆍ전역비\n • 급여지급 확인방법 * 아래 2가지 사항 중 선택\n ①국군재정관리단 인트라넷 국방급여포털 접속 후 조회 \n ②국방급여포털(앱) 접속 / 로그인 후 급여명세서 확인\n • 급여 미지급 / 착오지급 발생 시 문의\n - 주요 착오 / 미지급 사례\n \n구 분\n내 용\n봉 급\n・진급을 하였으나 전 계급으로 급여가 지급된 경우\n ☞ 소속부대에서 진급명령 미발령·지연한 경우로서, 명령 발령 시 다음달 \n급여에 소급지급\n휴가 / \n전역비\n・진급월 휴가비 미지급된 사례\n ☞ 진급 당시 입실 중이거나, 군병원 퇴원 이후 퇴원명령 처리가 지연된 경우로서 \n명령발령, 급여지급 조치 후 당월 25일 또는 다음달 10일 급여 지급 시 소급지급\n ☞ 제주도, 연평도 등 도서지역 거주 또는 근무인원의 경우 소속부대 인사/\n 재정부서에서 항구설정 必, 항구 설정 및 휴가비 추가회수등록시 소급지급\n - 문의방법\n • 1차 : 인사 명령(입대ㆍ진급ㆍ전역) 발령, 급지 설정 여부 확인(소속부대 인사부서)\n • 2차 : 인사 명령 발령에 근거한 국방통합급여정보체계(DIPIS) 반영 여부 확인\n * 소속부대 인사 / 재정부서 확인(육군 : 재정, 해·공군·해병대 : 인사부서)\n •기타 안내사항\n - 급여계좌 변경\n • 변경 시기 : 훈련소 및 신병교육대 수료 후 소속부대(자대)에서 변경\n * 훈련소, 신병교육기관에서 임의 변경 불가: 소속 부대(자대)에서 변경\n • 변경방법: 매월 말일까지 개인이 급여포탈에서 직접신청 또는 소속\n부대 인사ㆍ재정부서 급여업무 담당자에게 변경 요청',
 '6 \n 기본급 및 각종 수당 인상 \n \n•(기본급) 초급간부 기본급 6.6% 인상(하사·중사·소위·중위)\n구 분\n소 위\n중 위\n하 사\n중 사\n’25년\n2,017,300원\n2,163,900원\n2,000,900원\n2,046,400원\n’26년\n2,150,400원\n2,306,700원\n2,133,000원\n2,181,500원\n* 기타 계급은 3.5% 인상\n \n•(특수/위험근무수당) 핵심전투인력 수당 신설 및 인상\n구 분\n특수근무수당\n위험근무수당\n신설\n· 간호조무부사관 장려수당\n· 국방대학교 특정직 교수 수당\n· 방사선 취급 근무자 위험근무수당\n· 운용시험평가관 위험근무수당\n· 조사본부 과학수사연구소 \n 위험근무수당\n인상/\n확대\n· 수상함 함정근무수당 10%\n· 중요직무급 위험·특수지근무수당과 병급\n·\x07 \x07장려수당 1호(특수무기), 5호(위성운용), \n8호(부사관) 지급대상 확대\n· 급유통제사 항공수당 급호 인상\n· 야간비행 출동가산금 확대\n· 민원업무수당 인상\n· 갑3호(대테러부대) 지급대상 확대\n \n•(시간외근무수당) 상한시간 예외직위 최신화\n - 의무후송항공대, 해상초계기 운용요원, 우도경비대 등\n * 시간외근무 상한 시간은 동일(GP 200시간, GOP·해강안·함정 등 150시간)\n \n•(비상근무수당) 일 8,000원, 월 120,000원→일 16,000원, 월 180,000원\n \n•(업무대행수당) 육아·질병휴직 → 대상 확대(모든 휴직 업무대행자)\n 당직근무비 인상\n \n•평일 : 2만원 → 3만원 / 휴일 4만원 → 10만원\n 장병e음 플랫폼 서비스 개시 : ’26. 2월\n \n•\x07인사, 행정, 복지 등 여러 서비스를 통합·연결하여 모바일 환경에서 일괄 \n제공하는 플랫폼 개시\n’26년도에는 이렇게 바뀝니다!\n2026 초급간부 길라잡이']

# 4. RAGAS 를 이용해 평가를 위한 합성 데이터 셋 만들기

- 평가 데이터셋 구성
  - `user_input`: 사용자 질문
  - `retrieved_contexts`: Vectorstore에서 검색한 context
  - `response`: LLM의 응답
  - `reference`: 정답

## 4.1 TestsetGenerator
- **문서(retrieved_contexts)를 기준**으로 **질문**, **정답** 을 생성한다.
- 평가할 LLM으로 생성된 질문을 넣어 답변을 추출하여 데이터셋을 구성한다.


> **주의**
> - TestsetGenerator import 시 `No Module named langchain_community.chat_models.vertexai` Error 발생 
> - RAGAS와 langchain-community의 버전 호환성 문제 때문에 발생한다.
> - 해결
>   1. langchain_google_vertexai 설치
>       - `!uv pip install langchain_google_vertexai`
>   2. `.venv\Lib\site-packages\langchain_community\chat_models` 디렉토리 아래 `vertexai.py` 파일을 만들고 아래 코드를 > 넣는다.
>    ```python
>       try:
>          from langchain_google_vertexai import ChatVertexAI
>       except ImportError:
>           class ChatVertexAI:
>               def __init__(self, *args, **kwargs):
>                   raise ImportError(
>                       "ChatVertexAI requires langchain-google-vertexai. "
>                       "Install with: pip install langchain-google-vertexai"
>                   )
>    ```

In [17]:
# !uv pip install langchain_google_vertexai

In [18]:
# 주피터노트북 환경에서 비동기적 처리 위해 
# script(.py) 로 작성할 경우는 필요 없다.

import nest_asyncio
nest_asyncio.apply()

In [19]:
from ragas.testset import TestsetGenerator

c:\Users\Playdata\SKN\SKN31-3rd-2Team\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [20]:
#
# testset -> Context들(문서들) - [질문 - 정답답변 + (Retriever가 찾은 문서 + LLM 응답: chain에서 생성)]
# 1. Context(문서들)을 추출 - TestsetGenerator -> 질문과 정답 답변 생성

import random

# 데이터셋을 생성할 때 사용할 Context를 추출
client = QdrantClient(url="http://localhost:6333")
COLLECTION_NAME = "guidance_vectordb"

info = client.get_collection(COLLECTION_NAME)
total_docs = info.points_count

results, _ = client.scroll(
    collection_name=COLLECTION_NAME,
    limit=total_docs,
)

# random하게 k(5)개를 sampling
sample_docs:"list[PointStruct]" =random.sample(results, 10) # 리스트에서 랜덤하게 k(5)개를 추출

# PointStruct - payload: page_content, metadata
# page_content만 추출해서 list[str]
docs = [point.payload['page_content'] for point in sample_docs]

In [21]:
total_docs

337

In [22]:
sample_docs

[Record(id='14772b0f-7db1-53dd-b194-a34c500ae6c1', payload={'page_content': 'MEMO', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 86, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='34629ca6-16f0-5946-8970-2eecdf7dd1ed', payload={'page_content': '이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 범부처 경진대회에 참가**하고 **12월에 시상식이 진행**됨을 보여줍니다. 표의 항목은 주로 **대회 참가 시기(9~12월)**와 **시상식 개최 시기(12월)**라는 주요 일정으로 구성되어 있습니다. 검색용으로는 **범부처 창업경진대회**, **참가 일정**, **시상식 일정**, **9~12월 참가**, **12월 시상식** 등의 키워드로 활용할 수 있습니다.', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 67, 'type': 'table', 'table_markdown': '| 범부처\n창업경진대회 참가 |\n| --- |\n| •범부처 경진대회 참가\n(9∼12월)\n•범부처 경진대회\n시상식(12월) |', 'summary': '이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 범부처 경진대회에 참가**하고 **12월에 시상식이 진행**됨을 보여줍니다. 표의 항목은 주로 **대회 참가 시기(9~12월)**와 **시상식 개최 시기(12월)**라는 주요 일정으로 구성되어 있습니다. 검색용으로는 **범부처 창업경진대회**, **참가 일정**, **시상식 일정**, **9~12월 참가**, **12월 시상식** 등의 키워드로 활용할 수 있습니다.'}}, vector=None, shard_key=None, order_value=None),
 Record(id='0e68413e-d289-5c5f-a212-712bdfaebcc5', payload={'page_content': '02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부 길라잡이\n-⑤ 간부 주거 지원제도\n 개 요 \n \x07 \x07군인이 안정된 주거생활을 함으로써 근무에 전념할 수 있도록 하기 위하여 \n주거시설을 제공하거나 민간주택 전·월세 지원\n 군 주거지원 종류\n구 분\n내 용\n군 주거시설\n공관, 지휘관관사, 일반관사, 간부숙소\n민간주택 전ㆍ월세\n (이자지원)\n협약은행에서 전ㆍ월세 자금을 지원하고 \n국가는 그 이자를 지원\n 지원대상\n구 분\n내 용\n군 주거\n시설\n관사\n부양가족이 있고 관리부대 근무지 내에\n자가주택을 보유하지 않은 군인\n간부\n숙소\n 미혼간부ㆍ가족과 별거하는 기혼간부\n민간주택 전ㆍ월세\n(이자지원)\n관리부대의 근무지 내에 관사가 부족하여 \n민간주택 전ㆍ월세 지원이 필요한 경우\n 신청방법 \n • “국방인사정보체계”를 통해 신청 \n 초급간부 주거여건 개선 지속 추진\n •전용면적 확대(미혼 간부숙소 18㎡→ 24㎡) \n •비품개선(실별 세탁기, 취사용 인덕션, 빌트인가구 설치)\n국방부 군 주거정책과 주거관리담당 | 900-5472\n담당부서', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 46, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='4a7947d7-3111-55ce-9106-804e8bf1a506', payload={'page_content': '이 표는 **“03 Part 자기개발 및 전직지원 분야”**에 포함된 지원 항목을 정리한 것으로, 군 구성원의 자기개발과 전역 후 진로 준비를 돕는 내용을 담고 있습니다. 주요 항목은 **국내·외 학위과정 및 국외군사교육 지원**, **학습콘텐츠(M-kiss, e-러닝 등) 지원**, **전역예정장병의 취업·창업 지원**, **예비군훈련 안내**, **상비예비군 제도** 등 총 **5개 세부 분야**입니다. 이 표는 교육·훈련·취업 연계와 예비군 제도 안내를 중심으로 한 전직지원 서비스를 요약한 것입니다.', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 56, 'type': 'table', 'table_markdown': '| 03\nPart\n자기개발 및 전직지원 분야 |\n| --- |\n| \ue426-① 국내·외 학위과정 및 국외군사교육 지원\n\ue426-② 학습콘텐츠(M-kiss, e-러닝 등) 지원\n\ue426-③ 전역예정장병 취업 및 창업 지원\n\ue426-④ 예비군훈련 안내\n\ue426-⑤ 상비예비군 제도 |', 'summary': '이 표는 **“03 Part 자기개발 및 전직지원 분야”**에 포함된 지원 항목을 정리한 것으로, 군 구성원의 자기개발과 전역 후 진로 준비를 돕는 내용을 담고 있습니다. 주요 항목은 **국내·외 학위과정 및 국외군사교육 지원**, **학습콘텐츠(M-kiss, e-러닝 등) 지원**, **전역예정장병의 취업·창업 지원**, **예비군훈련 안내**, **상비예비군 제도** 등 총 **5개 세부 분야**입니다. 이 표는 교육·훈련·취업 연계와 예비군 제도 안내를 중심으로 한 전직지원 서비스를 요약한 것입니다.'}}, vector=None, shard_key=None, order_value=None),
 Record(id='fb92901e-f75c-5b39-a5c5-55b696fc2ef5', payload={'page_content': '12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획 각 군 홈페이지 탑재 시기\n•육군 : 장교 전반기 전년도 12월, 후반기 8월 / 부사관 4월\n•해군 : 장교·부사관 전반기 1월 / 부사관 후반기 6월\n•공군 : 장교 전반기 2월 / 부사관 전반기 1월\n•해병 : 장교 전반기 2월, 후반기 9월 / 부사관 전반기 3월, 후반기 10월\n* 공군은 선발결과만 홈페이지 게시, 계획은 공문으로 전파\n* 각 군별 선발절차 및 추진일정, 선발방법 및 평가기준 등 탑재되어,매년 최신화되는 \n 세부평가 요소를 확인해서 준비 필요\n 책임감 있는 임무수행과 부대에 기여하는 자세가 중요\n•본인 소관 업무를 책임감 있게 수행하고, \n•\x07특히, 부대원(상급자, 하급자, 동료)과 원만한 관계를 유지하면서, \n 해당 특기/분야에서 인정하는 자격증 등을 취득하는 자기개발 활동 필요\n 장기(연장) 복무 관련 문의사항 : 각 부대 인사참모 소관\n 장기(연장) 복무 선발 담당 현황\n•육군 : 인사사령부 인력획득계획과 장기복무선발담당(960-7161~3)\n•해군 : 해군본부 장교인사과 장교복무/특기관리담당(910-1216)\n 부사관/병인사과 부사관/병인사담당(910-1221)\n•공군 : 공군본부 장교인사과 장교경력관리담당(920-1438)\n 부사관/병인사과 부사관/병인사운영담당(910-1147)\n•해병 : 해병대사 인사운영과 장교인사담당(928-3121)\n 인사운영과 부사관/병인사담당(928-3122)\nTip', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 13, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='b047a3c3-d0ab-5d35-9a7e-19cc8e3446e9', payload={'page_content': '포항역KTX 직원주차장 \n방면 계단 밑\n주말/공휴일08:00 ~ 18:00\n동대구\n972-4555\n972-7788\n053-750-4555\n평일/주말/\n공휴일\n07:00 ~ 20:00\n동대구역 6번 출구\n우측 2m 지점\n부산\n977-4090\n977-4091\n051-730-4090\n평일/주말/\n공휴일\n07:00 ~ 20:00 부산역 5번 출구 방향에서\n2m 지점\n천안 \n아산\n833-7788\n041-531-7213\n평일\n08:00 ~ 18:00\n천안 아산역 2층 \n매표소 뒤편 30m 지점\n금\n08:00 ~ 19:00\n주말/공휴일08:00 ~ 16:00', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 38, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='4de91d71-ea64-5d0f-a85c-d90c37eaba5c', payload={'page_content': '이 표는 해병대 인사평정에서 **장교와 부사관의 평가항목별 배점 비중**을 나타낸 것입니다. 열은 **계(총점 100점)**를 기준으로 **근무평정, 교육성적, 상훈, 부대평가, 체력검정, 잠재역량, 위원회평가**로 구성되어 있으며, 장교는 근무평정 70점·교육성적 10점·상훈 3점·체력검정 3점·잠재역량 4점·위원회평가 10점(부대평가는 없음)으로 배분됩니다. 부사관은 근무평정 45점·교육성적 10점·상훈 3점·부대평가 10점·체력검정 15점·잠재역량 7점·위원회평가 10점으로, 장교보다 체력검정과 부대평가 비중이 더 큽니다.', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 12, 'type': 'table', 'table_markdown': '| 구 분 |  | 계 | 근무\n평정 | 교육\n성적 | 상훈 | 부대\n평가 | 체력\n검정 | 잠재\n역량 | 위원회\n평가 |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| 해\n병\n대 | 장 교 | 100 | 70 | 10 | 3 | - | 3 | 4 | 10 |\n|  | 부사관 | 100 | 45 | 10 | 3 | 10 | 15 | 7 | 10 |', 'summary': '이 표는 해병대 인사평정에서 **장교와 부사관의 평가항목별 배점 비중**을 나타낸 것입니다. 열은 **계(총점 100점)**를 기준으로 **근무평정, 교육성적, 상훈, 부대평가, 체력검정, 잠재역량, 위원회평가**로 구성되어 있으며, 장교는 근무평정 70점·교육성적 10점·상훈 3점·체력검정 3점·잠재역량 4점·위원회평가 10점(부대평가는 없음)으로 배분됩니다. 부사관은 근무평정 45점·교육성적 10점·상훈 3점·부대평가 10점·체력검정 15점·잠재역량 7점·위원회평가 10점으로, 장교보다 체력검정과 부대평가 비중이 더 큽니다.'}}, vector=None, shard_key=None, order_value=None),
 Record(id='b253c705-e250-5dd2-9a8c-fa902d0f0980', payload={'page_content': '이 표는 **국방/병무 관련 통합 서비스의 1차·2차 서비스 구성을 기능 영역별로 정리한 목록**입니다. 컬럼은 각각 **구분(1차/2차 서비스와 시행 시점)**, **제공 서비스의 대분류(인사·소통·행정·복지·교육·의료)**, **세부 제공 항목**, **개수**를 의미합니다. 1차 서비스(’26.2월)는 인사 3개, 소통 4개, 행정 3개, 복지 13개, 교육 6개, 의료 3개로 구성되어 총 **32개** 서비스를 제공하며, 2차 서비스(’26.7월)는 인사 2개, 소통 2개, 행정 4개로 **8개** 서비스를 추가합니다. 주요 항목으로는 신분 인증/통합 로그인, 급여명세서 조회, 휴가·외박·출장 조회, 자녀 기숙사 신청, 군 인터넷 쇼핑몰 연계, 체력단련장·호텔콘도·항공·열차 예약, 군 병원 예약, 증명서 발급, 챗봇 연계, 입영 신청 및 병역판정검사 결과 조회 등이 포함됩니다.', 'metadata': {'doc_name': '사병_길라잡이.pdf', 'page': 27, 'type': 'table', 'table_markdown': '| 구구 분분 | 제제공공 서서비비스스 |  | 개개수수 |\n| --- | --- | --- | --- |\n| 11차차 서서비비스스\n((’’2266..22월월)) | 인인 사사\n((33)) | 신분 인증 및 확인(신분증), 통합 회원 관리(통합 로그인),\n급여명세서 조회 | 32개 |\n|  | 소소 통통\n((44)) | 알림톡 발송, 각 군 훈련소 연결, 소통과 공감앱 연결,\n헬프콜 연결 |  |\n|  | 행행 정정\n((33)) | 휴가/외박/출장 조회, 각군 모집안내 연결, 민방위훈련\n유예(면제) 신청 연결 |  |\n|  | 복복 지지\n((1133)) | 자녀 기숙사 신청, 군 인터넷 쇼핑몰(와몰)연결, 체력\n단련장 예약, 호텔콘도 예약, 웨딩/연회 예약, 항공\n예약, 해상 예약, 버스/열차 예매, 전세객차 예매,\n영화할인 신청, 군인공제회 예금조회, 맞춤형 e북\n지원, 내일준비적금 가입 |  |\n|  | 교교 육육\n((66)) | 국가기술자격검정 연결, 제대군인 취업센터 연결,\n일반강좌 신청, 대학 원격강좌 신청, 진로설계유형\n검사, 디지털 독서지원 신청 |  |\n|  | 의의 료료\n((33)) | 군 병원 예약, 민간병원 진료비 청구, 심리 검사 |  |\n| 22차차 서서비비스스\n((’’2266..77월월)) | 인인 사사\n((22)) | 증명서 신청‧발급, 증명서 전자지갑 저장 | 8개 |\n|  | 소소 통통\n((22)) | 지능형 챗봇 등, 공공마이데이터(신분 정보) 연계 |  |\n|  | 행행 정정\n((44)) | 입영 신청, 병역판정 검사 결과 조회, 동원훈련 연기\n신청, 예비군훈련 연기 신청 |  |', 'summary': '이 표는 **국방/병무 관련 통합 서비스의 1차·2차 서비스 구성을 기능 영역별로 정리한 목록**입니다. 컬럼은 각각 **구분(1차/2차 서비스와 시행 시점)**, **제공 서비스의 대분류(인사·소통·행정·복지·교육·의료)**, **세부 제공 항목**, **개수**를 의미합니다. 1차 서비스(’26.2월)는 인사 3개, 소통 4개, 행정 3개, 복지 13개, 교육 6개, 의료 3개로 구성되어 총 **32개** 서비스를 제공하며, 2차 서비스(’26.7월)는 인사 2개, 소통 2개, 행정 4개로 **8개** 서비스를 추가합니다. 주요 항목으로는 신분 인증/통합 로그인, 급여명세서 조회, 휴가·외박·출장 조회, 자녀 기숙사 신청, 군 인터넷 쇼핑몰 연계, 체력단련장·호텔콘도·항공·열차 예약, 군 병원 예약, 증명서 발급, 챗봇 연계, 입영 신청 및 병역판정검사 결과 조회 등이 포함됩니다.'}}, vector=None, shard_key=None, order_value=None),
 Record(id='cd332f67-775d-5242-9a86-b6fbc2f76cd5', payload={'page_content': '42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임 치료 시술(인공수정, 체외수정 등) 당일 휴가 2∼4일 부여\n* 여성 군인 : 2∼4일, 남성 군인 : 1일\n난임 휴직\n•\x07난임으로 장기간 치료가 필요한 군인 및 군무원 1년(불가피한 경우 1년 \n연장 가능) 휴직 허용\n* 휴직(질병휴직) 1년차 봉급의 70%, 2년차 봉급의 50% 지급\n임신검진휴가\n•임신기간 중 검진을 위해 10일 휴가 부여\n* (배우자) 임신기간 중 배우자 임신 검진에 동행하기 위해 10일 사용\n유·사산 휴가\n•유산 또는 사산 시 임신유지 기간에 따른 휴가 부여\n*\x07 15주 이내(10일), 16∼21주(30일), 22∼27주(60일), 28주 이상(90일)\n출산휴가\n•\x07(본인)출산 전후로 90일(미숙아 출산 시 100일, 한 번에 둘 이상 자녀를 임신\n시 120일)의 출산휴가를 허가하되, 출산 후 45일(한 번에 둘 이상 자녀를 \n임신 시 60일) 이상 활용\n* 유·사산 경험 및 위험자, 고령 산모(만 35세 이상)는 출산휴가 분할사용 가능\n•(배우자)20일 * \x07한 번에 둘 이상의 자녀를 출산한 경우 25일\n모성보호시간\n•휴식이나 병원진료 등을 위해 임신 여성에게 1일 2시간 휴식 허용\n출산축하금\n(군인공제회 가입자) •첫째 30만원, 둘째 60만원, 셋째 90만원, 넷째 이상 150만원\n가족수당\n•첫째 월 5만원, 둘째 월 8만원, 셋째 이상 1명당 월 12만원\n민간병원 산부인과 \n진료비 지원\n•연간 20만원 한도(급여항목)\n부인과·유방암 \n건강검진비 지원\n•연간 10만원 한도(비급여항목 포함)\n보직조정', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 43, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='e5258d93-e1f2-575c-889f-a88f51757d31', payload={'page_content': '02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n육아 휴직\n•\x07만 8세 이하 또는 초등학교 2학년 이하의 자녀를 양육하는 군인 및 군무\n원이 임신·출산으로 필요한 경우 자녀당 최대 3년 휴직 허용\n•30일 이상 휴직 시 휴직일로부터 최초 1년간 수당 지급\n* 부모 모두 3개월 이상 육아휴직, 한부모가족, 장애아동의 부모는 1년 6개월간\n 수당 지급, 확대기간(13~18개월) 지급액은 월봉급액의 80%(최대 160만원)\n•\x07육아휴직 6개월째까지 : 육아휴직 시작일을 기준으로 한 월봉급의 \n100% (1∼3개월 최대 250만원, 4∼6개월 최대 200만원)\n•\x07육아휴직 7개월째부터 12개월째까지 : 육아휴직 시작일을 기준으로 한\n 월봉급의 80% (최대 160만원)\n육아 시간\n•만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 군무원\n* 육아를 위해 필요한 경우 36개월 범위 내 1일 최대 2시간\n자녀돌봄\n휴가\n•\x07고등학생 이하 자녀 또는 손자녀를 양육중인 군인 및 군무원의 학교 공\n식행사 참여 및 병원진료 동행 등에 연간 10일 범위 휴가 부여(시간단위 \n활용 가능)\n* \x07유급휴가 : 자녀 수에 1을 더한 일수, 자녀가 장애인인 경우 또는 한부모가족지원\n법에 따른 모 또는 부에 해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n* 무급휴가 : 손자녀 돌봄, 유급휴가 초과 시\n탄력 근무\n•\x07만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 군인 및 군무원 출·퇴근 \n시간 조정\n* 1일 8시간 근무 유지(출근시간 기준 1~2시간 전후 범위내 30분 단위로 조정)\n비상시\n출·퇴근\n시간 조정\n•\x07부부 군인·군무원 중 1인 또는 한부모가정의 경우 비상 상황 발생 등으\n로 자녀를 양육(돌봄)함에 있어 공백이 생길 경우 출·퇴근 시간을 조정\n당직근무\n면제\n•3자녀 이상 여성 당직근무 면제\n* 셋째 임신 시 ∼ 마지막 자녀 초등학교 입학 전까지\n군 보육시설•어린이집 159개소, 공동육아나눔터 44개소 운영\n-③-Ⅳ\n육아 지원제도 세부사항\n국방부 양성평등정책팀 일-가정 양립지원담당 | 900-5173\n담당부서', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 44, 'type': 'text'}}, vector=None, shard_key=None, order_value=None)]

In [23]:
docs

['MEMO',
 '이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 범부처 경진대회에 참가**하고 **12월에 시상식이 진행**됨을 보여줍니다. 표의 항목은 주로 **대회 참가 시기(9~12월)**와 **시상식 개최 시기(12월)**라는 주요 일정으로 구성되어 있습니다. 검색용으로는 **범부처 창업경진대회**, **참가 일정**, **시상식 일정**, **9~12월 참가**, **12월 시상식** 등의 키워드로 활용할 수 있습니다.',
 '02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부 길라잡이\n-⑤ 간부 주거 지원제도\n 개 요 \n \x07 \x07군인이 안정된 주거생활을 함으로써 근무에 전념할 수 있도록 하기 위하여 \n주거시설을 제공하거나 민간주택 전·월세 지원\n 군 주거지원 종류\n구 분\n내 용\n군 주거시설\n공관, 지휘관관사, 일반관사, 간부숙소\n민간주택 전ㆍ월세\n (이자지원)\n협약은행에서 전ㆍ월세 자금을 지원하고 \n국가는 그 이자를 지원\n 지원대상\n구 분\n내 용\n군 주거\n시설\n관사\n부양가족이 있고 관리부대 근무지 내에\n자가주택을 보유하지 않은 군인\n간부\n숙소\n 미혼간부ㆍ가족과 별거하는 기혼간부\n민간주택 전ㆍ월세\n(이자지원)\n관리부대의 근무지 내에 관사가 부족하여 \n민간주택 전ㆍ월세 지원이 필요한 경우\n 신청방법 \n • “국방인사정보체계”를 통해 신청 \n 초급간부 주거여건 개선 지속 추진\n •전용면적 확대(미혼 간부숙소 18㎡→ 24㎡) \n •비품개선(실별 세탁기, 취사용 인덕션, 빌트인가구 설치)\n국방부 군 주거정책과 주거관리담당 | 900-5472\n담당부서',
 '이 표는 **“03 Part 자기개발 및 전직지원 분야”**에 포함된 지원 항목을 정리한 것으로, 군 구성원의 자기개발과 전역 후 진로 준비를 돕는 내용을 담고 있습니다. 주요 항목은 **국내·외 학위과정 및 국외군사교육 지원**, **학습콘텐츠(M-kiss, e-러닝 등) 지원**, **전역예정장병의 취업·창업 지원**, **예비군훈련 안내**, **상비예비군 제도** 등 총 **5개 세부 분야**입니다. 이 표는 교육·훈련·취업 연계와 예비군 제도 안내를 중심으로 한 전직지원 서비스를 요약한 것입니다.',
 '12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획 각 군 홈페이지 탑재 시기\n•육군 : 장교 전반기 전년도 12월, 후반기 8월 / 부사관 4월\n•해군 : 장교·부사관 전반기 1월 / 부사관 후반기 6월\n•공군 : 장교 전반기 2월 / 부사관 전반기 1월\n•해병 : 장교 전반기 2월, 후반기 9월 / 부사관 전반기 3월, 후반기 10월\n* 공군은 선발결과만 홈페이지 게시, 계획은 공문으로 전파\n* 각 군별 선발절차 및 추진일정, 선발방법 및 평가기준 등 탑재되어,매년 최신화되는 \n 세부평가 요소를 확인해서 준비 필요\n 책임감 있는 임무수행과 부대에 기여하는 자세가 중요\n•본인 소관 업무를 책임감 있게 수행하고, \n•\x07특히, 부대원(상급자, 하급자, 동료)과 원만한 관계를 유지하면서, \n 해당 특기/분야에서 인정하는 자격증 등을 취득하는 자기개발 활동 필요\n 장기(연장) 복무 관련 문의사항 : 각 부대 인사참모 소관\n 장기(연장) 복무 선발 담당 현황\n•육군 : 인사사령부 인력획득계획과 장기복무선발담당(960-7161~3)\n•해군 : 해군본부 장교인사과 장교복무/특기관리담당(910-1216)\n 부사관/병인사과 부사관/병인사담당(910-1221)\n•공군 : 공군본부 장교인사과 장교경력관리담당(920-1438)\n 부사관/병인사과 부사관/병인사운영담당(910-1147)\n•해병 : 해병대사 인사운영과 장교인사담당(928-3121)\n 인사운영과 부사관/병인사담당(928-3122)\nTip',
 '포항역KTX 직원주차장 \n방면 계단 밑\n주말/공휴일08:00 ~ 18:00\n동대구\n972-4555\n972-7788\n053-750-4555\n평일/주말/\n공휴일\n07:00 ~ 20:00\n동대구역 6번 출구\n우측 2m 지점\n부산\n977-4090\n977-4091\n051-730-4090\n평일/주말/\n공휴일\n07:00 ~ 20:00 부산역 5번 출구 방향에서\n2m 지점\n천안 \n아산\n833-7788\n041-531-7213\n평일\n08:00 ~ 18:00\n천안 아산역 2층 \n매표소 뒤편 30m 지점\n금\n08:00 ~ 19:00\n주말/공휴일08:00 ~ 16:00',
 '이 표는 해병대 인사평정에서 **장교와 부사관의 평가항목별 배점 비중**을 나타낸 것입니다. 열은 **계(총점 100점)**를 기준으로 **근무평정, 교육성적, 상훈, 부대평가, 체력검정, 잠재역량, 위원회평가**로 구성되어 있으며, 장교는 근무평정 70점·교육성적 10점·상훈 3점·체력검정 3점·잠재역량 4점·위원회평가 10점(부대평가는 없음)으로 배분됩니다. 부사관은 근무평정 45점·교육성적 10점·상훈 3점·부대평가 10점·체력검정 15점·잠재역량 7점·위원회평가 10점으로, 장교보다 체력검정과 부대평가 비중이 더 큽니다.',
 '이 표는 **국방/병무 관련 통합 서비스의 1차·2차 서비스 구성을 기능 영역별로 정리한 목록**입니다. 컬럼은 각각 **구분(1차/2차 서비스와 시행 시점)**, **제공 서비스의 대분류(인사·소통·행정·복지·교육·의료)**, **세부 제공 항목**, **개수**를 의미합니다. 1차 서비스(’26.2월)는 인사 3개, 소통 4개, 행정 3개, 복지 13개, 교육 6개, 의료 3개로 구성되어 총 **32개** 서비스를 제공하며, 2차 서비스(’26.7월)는 인사 2개, 소통 2개, 행정 4개로 **8개** 서비스를 추가합니다. 주요 항목으로는 신분 인증/통합 로그인, 급여명세서 조회, 휴가·외박·출장 조회, 자녀 기숙사 신청, 군 인터넷 쇼핑몰 연계, 체력단련장·호텔콘도·항공·열차 예약, 군 병원 예약, 증명서 발급, 챗봇 연계, 입영 신청 및 병역판정검사 결과 조회 등이 포함됩니다.',
 '42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임 치료 시술(인공수정, 체외수정 등) 당일 휴가 2∼4일 부여\n* 여성 군인 : 2∼4일, 남성 군인 : 1일\n난임 휴직\n•\x07난임으로 장기간 치료가 필요한 군인 및 군무원 1년(불가피한 경우 1년 \n연장 가능) 휴직 허용\n* 휴직(질병휴직) 1년차 봉급의 70%, 2년차 봉급의 50% 지급\n임신검진휴가\n•임신기간 중 검진을 위해 10일 휴가 부여\n* (배우자) 임신기간 중 배우자 임신 검진에 동행하기 위해 10일 사용\n유·사산 휴가\n•유산 또는 사산 시 임신유지 기간에 따른 휴가 부여\n*\x07 15주 이내(10일), 16∼21주(30일), 22∼27주(60일), 28주 이상(90일)\n출산휴가\n•\x07(본인)출산 전후로 90일(미숙아 출산 시 100일, 한 번에 둘 이상 자녀를 임신\n시 120일)의 출산휴가를 허가하되, 출산 후 45일(한 번에 둘 이상 자녀를 \n임신 시 60일) 이상 활용\n* 유·사산 경험 및 위험자, 고령 산모(만 35세 이상)는 출산휴가 분할사용 가능\n•(배우자)20일 * \x07한 번에 둘 이상의 자녀를 출산한 경우 25일\n모성보호시간\n•휴식이나 병원진료 등을 위해 임신 여성에게 1일 2시간 휴식 허용\n출산축하금\n(군인공제회 가입자) •첫째 30만원, 둘째 60만원, 셋째 90만원, 넷째 이상 150만원\n가족수당\n•첫째 월 5만원, 둘째 월 8만원, 셋째 이상 1명당 월 12만원\n민간병원 산부인과 \n진료비 지원\n•연간 20만원 한도(급여항목)\n부인과·유방암 \n건강검진비 지원\n•연간 10만원 한도(비급여항목 포함)\n보직조정',
 '02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n육아 휴직\n•\x07만 8세 이하 또는 초등학교 2학년 이하의 자녀를 양육하는 군인 및 군무\n원이 임신·출산으로 필요한 경우 자녀당 최대 3년 휴직 허용\n•30일 이상 휴직 시 휴직일로부터 최초 1년간 수당 지급\n* 부모 모두 3개월 이상 육아휴직, 한부모가족, 장애아동의 부모는 1년 6개월간\n 수당 지급, 확대기간(13~18개월) 지급액은 월봉급액의 80%(최대 160만원)\n•\x07육아휴직 6개월째까지 : 육아휴직 시작일을 기준으로 한 월봉급의 \n100% (1∼3개월 최대 250만원, 4∼6개월 최대 200만원)\n•\x07육아휴직 7개월째부터 12개월째까지 : 육아휴직 시작일을 기준으로 한\n 월봉급의 80% (최대 160만원)\n육아 시간\n•만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 군무원\n* 육아를 위해 필요한 경우 36개월 범위 내 1일 최대 2시간\n자녀돌봄\n휴가\n•\x07고등학생 이하 자녀 또는 손자녀를 양육중인 군인 및 군무원의 학교 공\n식행사 참여 및 병원진료 동행 등에 연간 10일 범위 휴가 부여(시간단위 \n활용 가능)\n* \x07유급휴가 : 자녀 수에 1을 더한 일수, 자녀가 장애인인 경우 또는 한부모가족지원\n법에 따른 모 또는 부에 해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n* 무급휴가 : 손자녀 돌봄, 유급휴가 초과 시\n탄력 근무\n•\x07만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 군인 및 군무원 출·퇴근 \n시간 조정\n* 1일 8시간 근무 유지(출근시간 기준 1~2시간 전후 범위내 30분 단위로 조정)\n비상시\n출·퇴근\n시간 조정\n•\x07부부 군인·군무원 중 1인 또는 한부모가정의 경우 비상 상황 발생 등으\n로 자녀를 양육(돌봄)함에 있어 공백이 생길 경우 출·퇴근 시간을 조정\n당직근무\n면제\n•3자녀 이상 여성 당직근무 면제\n* 셋째 임신 시 ∼ 마지막 자녀 초등학교 입학 전까지\n군 보육시설•어린이집 159개소, 공동육아나눔터 44개소 운영\n-③-Ⅳ\n육아 지원제도 세부사항\n국방부 양성평등정책팀 일-가정 양립지원담당 | 900-5173\n담당부서']

In [24]:
# testset 생성
from ragas.testset import TestsetGenerator
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
#testsetgenerator 는 gpt-5 이후 버전은 사용할 수 없다. 
## Langchain의 모델과 Embedding 모델 -> ragas에서 사용할 수 있도록 변환(wrapping)
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))
generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
    llm_context="""
- 사람들이 현역병 복지에 대해서 궁금해 할 만한 질문들을 생성한다.
- 데이터셋은 반드시 한국어로 작성한다.
- 데이터셋은 JSON 문법읋 지켜서 작성한다. 특히 구두점은 꼭 지켜야 한다.
- 생성된 내용이나 Document에 JSON문법에 맞지 않는 표현이 있으면 반드시 수정해서 처리한다.
""" 
# 질문/답변을 생성할 때 LLM에게 전달할 system Prompt를 설정
)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_33668\3702810314.py:8: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\Playdata\AppData\Local\Temp\ipykernel_33668\3702810314.py:9: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

In [25]:
testset = generator.generate_with_chunks(
    docs, testset_size=10, # Context 내용 테스트셋 개수(질문 답변 개수)
)

Applying SummaryExtractor: 100%|██████████| 10/10 [00:03<00:00,  2.55it/s]
Applying CustomNodeFilter:   0%|          | 0/10 [00:00<?, ?it/s]Node d5e1dd85-7612-4441-88a7-caaa8335270a does not have a summary. Skipping filtering.
Node 736d8e4b-2f38-401a-b718-50196f0ec0c8 does not have a summary. Skipping filtering.
Node 9f968296-58aa-4266-9524-9f11db5efc3c does not have a summary. Skipping filtering.
Node e4db4e82-bd1a-405c-81ee-cac199203e4e does not have a summary. Skipping filtering.
Node e7fd5d5d-26db-4342-8ac4-010f5cf01148 does not have a summary. Skipping filtering.
Node 042280f8-3787-4c2c-a252-0a0c6377b687 does not have a summary. Skipping filtering.
Node 97443fad-e33c-43c9-b4e2-33f808488583 does not have a summary. Skipping filtering.
Node 2f2f4c00-19ed-4797-85ac-36139a752a85 does not have a summary. Skipping filtering.
Node b65181ae-ac62-45d3-b4d7-f906b9294cfb does not have a summary. Skipping filtering.
Node 70cc3199-7fff-408e-bba1-de0f5eab68a2 does not have a summary. Skipping filtering.
Applying CustomNodeFilter: 100%|██████████| 10/10 [00:00<00:00, 2789.14it/s]
Applying EmbeddingExtractor: 100%|██████████| 10/10 [00:00<00:00, 14.00it/s]
Applying ThemesExtractor: 100%|██████████| 10/10 [00:01<00:00,  5.70it/s]
Applying NERExtractor: 100%|██████████| 10/10 [00:01<00:00,  8.23it/s]
Applying CosineSimilarityBuilder: 100%|██████████| 1/1 [00:00<00:00, 175.35it/s]
Applying OverlapScoreBuilder: 100%|██████████| 1/1 [00:00<00:00, 240.55it/s]
Generating personas: 100%|██████████| 3/3 [00:01<00:00,  2.40it/s]
Generating Scenarios: 100%|██████████| 3/3 [00:04<00:00,  1.48s/it]
Generating Samples: 100%|██████████| 12/12 [00:06<00:00,  1.85it/s]

In [26]:
testset

Testset(samples=[TestsetSample(eval_sample=SingleTurnSample(user_input='9~12월 언제 뭐해요?', retrieved_contexts=None, reference_contexts=['이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 범부처 경진대회에 참가**하고 **12월에 시상식이 진행**됨을 보여줍니다. 표의 항목은 주로 **대회 참가 시기(9~12월)**와 **시상식 개최 시기(12월)**라는 주요 일정으로 구성되어 있습니다. 검색용으로는 **범부처 창업경진대회**, **참가 일정**, **시상식 일정**, **9~12월 참가**, **12월 시상식** 등의 키워드로 활용할 수 있습니다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='9~12월에는 범부처 창업경진대회에 참가하고, 12월에 시상식이 진행됩니다.', rubrics=None, persona_name='Office Administrator', query_style='MISSPELLED', query_length='SHORT'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='군 주거 지원제도에서 국가가 민간주택 전ㆍ월세 지원 시 어떤 방식으로 지원을 제공하며, 지원 대상은 누구인지 자세히 설명해 주시겠습니까?', retrieved_contexts=None, reference_contexts=['02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부 길라잡이\n-⑤ 간부 주거 지원제도\n 개 요 \n \x07 \x07군인이 안정된 주거생활을 함으로써 근무에 전념할 수 있도록 하기 위하여 \n주거시설을 제공하거나 민간주택 전·월세 지원\n 군 주거지원 종류\n구 분\n내 용\n군 주거시설\n공관, 지휘관관사, 일반관사, 간부숙소\n민간주택 전ㆍ월세\n (이자지원)\n협약은행에서 전ㆍ월세 자금을 지원하고 \n국가는 그 이자를 지원\n 지원대상\n구 분\n내 용\n군 주거\n시설\n관사\n부양가족이 있고 관리부대 근무지 내에\n자가주택을 보유하지 않은 군인\n간부\n숙소\n 미혼간부ㆍ가족과 별거하는 기혼간부\n민간주택 전ㆍ월세\n(이자지원)\n관리부대의 근무지 내에 관사가 부족하여 \n민간주택 전ㆍ월세 지원이 필요한 경우\n 신청방법 \n • “국방인사정보체계”를 통해 신청 \n 초급간부 주거여건 개선 지속 추진\n •전용면적 확대(미혼 간부숙소 18㎡→ 24㎡) \n •비품개선(실별 세탁기, 취사용 인덕션, 빌트인가구 설치)\n국방부 군 주거정책과 주거관리담당 | 900-5472\n담당부서'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='군 주거 지원제도에서 민간주택 전ㆍ월세 지원은 협약은행에서 전ㆍ월세 자금을 지원하고, 국가는 그 이자를 지원하는 방식으로 제공됩니다. 지원 대상은 관리부대의 근무지 내에 관사가 부족하여 민간주택 전ㆍ월세 지원이 필요한 경우에 해당합니다.', rubrics=None, persona_name='Military Housing Coordinator', query_style='PERFECT_GRAMMAR', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='국내외 학위과정이 뭐에요? 혹시 군에서 지원해주는건가요? 그리고 이게 자기개발이나 전직지원에 어떻게 도움이 되는지 궁금합니다.', retrieved_contexts=None, reference_contexts=['이 표는 **“03 Part 자기개발 및 전직지원 분야”**에 포함된 지원 항목을 정리한 것으로, 군 구성원의 자기개발과 전역 후 진로 준비를 돕는 내용을 담고 있습니다. 주요 항목은 **국내·외 학위과정 및 국외군사교육 지원**, **학습콘텐츠(M-kiss, e-러닝 등) 지원**, **전역예정장병의 취업·창업 지원**, **예비군훈련 안내**, **상비예비군 제도** 등 총 **5개 세부 분야**입니다. 이 표는 교육·훈련·취업 연계와 예비군 제도 안내를 중심으로 한 전직지원 서비스를 요약한 것입니다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference="국내·외 학위과정은 군 구성원의 자기개발과 전역 후 진로 준비를 돕기 위해 지원되는 항목 중 하나입니다. 이 과정은 '03 Part 자기개발 및 전직지원 분야'에 포함되어 있으며, 군에서 국내·외 학위과정 및 국외군사교육 지원을 제공하고 있습니다. 이를 통해 군 구성원들은 교육·훈련·취업 연계와 예비군 제도 안내 등 전직지원 서비스를 받을 수 있습니다.", rubrics=None, persona_name='Office Administrator', query_style='MISSPELLED', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='육군 장기복무 선발계획은 언제 어디에 탑재되나요? 그리고 육군 장기복무 선발 담당 부서와 연락처가 어떻게 되나요?', retrieved_contexts=None, reference_contexts=['12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획 각 군 홈페이지 탑재 시기\n•육군 : 장교 전반기 전년도 12월, 후반기 8월 / 부사관 4월\n•해군 : 장교·부사관 전반기 1월 / 부사관 후반기 6월\n•공군 : 장교 전반기 2월 / 부사관 전반기 1월\n•해병 : 장교 전반기 2월, 후반기 9월 / 부사관 전반기 3월, 후반기 10월\n* 공군은 선발결과만 홈페이지 게시, 계획은 공문으로 전파\n* 각 군별 선발절차 및 추진일정, 선발방법 및 평가기준 등 탑재되어,매년 최신화되는 \n 세부평가 요소를 확인해서 준비 필요\n 책임감 있는 임무수행과 부대에 기여하는 자세가 중요\n•본인 소관 업무를 책임감 있게 수행하고, \n•\x07특히, 부대원(상급자, 하급자, 동료)과 원만한 관계를 유지하면서, \n 해당 특기/분야에서 인정하는 자격증 등을 취득하는 자기개발 활동 필요\n 장기(연장) 복무 관련 문의사항 : 각 부대 인사참모 소관\n 장기(연장) 복무 선발 담당 현황\n•육군 : 인사사령부 인력획득계획과 장기복무선발담당(960-7161~3)\n•해군 : 해군본부 장교인사과 장교복무/특기관리담당(910-1216)\n 부사관/병인사과 부사관/병인사담당(910-1221)\n•공군 : 공군본부 장교인사과 장교경력관리담당(920-1438)\n 부사관/병인사과 부사관/병인사운영담당(910-1147)\n•해병 : 해병대사 인사운영과 장교인사담당(928-3121)\n 인사운영과 부사관/병인사담당(928-3122)\nTip'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='육군 장기복무 선발계획은 장교의 경우 전반기는 전년도 12월, 후반기는 8월에 각 군 홈페이지에 탑재됩니다. 부사관의 경우 4월에 탑재됩니다. 육군 장기복무 선발 담당 부서는 인사사령부 인력획득계획과 장기복무선발담당이며, 연락처는 960-7161~3입니다.', rubrics=None, persona_name='Office Administrator', query_style='MISSPELLED', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='육아휴직 제도와 난임 휴가 및 휴직 제도는 각각 어떤 대상과 조건에 따라 적용되며, 지원 내용에는 어떤 차이가 있습니까?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n육아 휴직\n•\x07만 8세 이하 또는 초등학교 2학년 이하의 자녀를 양육하는 군인 및 군무\n원이 임신·출산으로 필요한 경우 자녀당 최대 3년 휴직 허용\n•30일 이상 휴직 시 휴직일로부터 최초 1년간 수당 지급\n* 부모 모두 3개월 이상 육아휴직, 한부모가족, 장애아동의 부모는 1년 6개월간\n 수당 지급, 확대기간(13~18개월) 지급액은 월봉급액의 80%(최대 160만원)\n•\x07육아휴직 6개월째까지 : 육아휴직 시작일을 기준으로 한 월봉급의 \n100% (1∼3개월 최대 250만원, 4∼6개월 최대 200만원)\n•\x07육아휴직 7개월째부터 12개월째까지 : 육아휴직 시작일을 기준으로 한\n 월봉급의 80% (최대 160만원)\n육아 시간\n•만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 군무원\n* 육아를 위해 필요한 경우 36개월 범위 내 1일 최대 2시간\n자녀돌봄\n휴가\n•\x07고등학생 이하 자녀 또는 손자녀를 양육중인 군인 및 군무원의 학교 공\n식행사 참여 및 병원진료 동행 등에 연간 10일 범위 휴가 부여(시간단위 \n활용 가능)\n* \x07유급휴가 : 자녀 수에 1을 더한 일수, 자녀가 장애인인 경우 또는 한부모가족지원\n법에 따른 모 또는 부에 해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n* 무급휴가 : 손자녀 돌봄, 유급휴가 초과 시\n탄력 근무\n•\x07만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 군인 및 군무원 출·퇴근 \n시간 조정\n* 1일 8시간 근무 유지(출근시간 기준 1~2시간 전후 범위내 30분 단위로 조정)\n비상시\n출·퇴근\n시간 조정\n•\x07부부 군인·군무원 중 1인 또는 한부모가정의 경우 비상 상황 발생 등으\n로 자녀를 양육(돌봄)함에 있어 공백이 생길 경우 출·퇴근 시간을 조정\n당직근무\n면제\n•3자녀 이상 여성 당직근무 면제\n* 셋째 임신 시 ∼ 마지막 자녀 초등학교 입학 전까지\n군 보육시설•어린이집 159개소, 공동육아나눔터 44개소 운영\n-③-Ⅳ\n육아 지원제도 세부사항\n국방부 양성평등정책팀 일-가정 양립지원담당 | 900-5173\n담당부서', '<2-hop>\n\n42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임 치료 시술(인공수정, 체외수정 등) 당일 휴가 2∼4일 부여\n* 여성 군인 : 2∼4일, 남성 군인 : 1일\n난임 휴직\n•\x07난임으로 장기간 치료가 필요한 군인 및 군무원 1년(불가피한 경우 1년 \n연장 가능) 휴직 허용\n* 휴직(질병휴직) 1년차 봉급의 70%, 2년차 봉급의 50% 지급\n임신검진휴가\n•임신기간 중 검진을 위해 10일 휴가 부여\n* (배우자) 임신기간 중 배우자 임신 검진에 동행하기 위해 10일 사용\n유·사산 휴가\n•유산 또는 사산 시 임신유지 기간에 따른 휴가 부여\n*\x07 15주 이내(10일), 16∼21주(30일), 22∼27주(60일), 28주 이상(90일)\n출산휴가\n•\x07(본인)출산 전후로 90일(미숙아 출산 시 100일, 한 번에 둘 이상 자녀를 임신\n시 120일)의 출산휴가를 허가하되, 출산 후 45일(한 번에 둘 이상 자녀를 \n임신 시 60일) 이상 활용\n* 유·사산 경험 및 위험자, 고령 산모(만 35세 이상)는 출산휴가 분할사용 가능\n•(배우자)20일 * \x07한 번에 둘 이상의 자녀를 출산한 경우 25일\n모성보호시간\n•휴식이나 병원진료 등을 위해 임신 여성에게 1일 2시간 휴식 허용\n출산축하금\n(군인공제회 가입자) •첫째 30만원, 둘째 60만원, 셋째 90만원, 넷째 이상 150만원\n가족수당\n•첫째 월 5만원, 둘째 월 8만원, 셋째 이상 1명당 월 12만원\n민간병원 산부인과 \n진료비 지원\n•연간 20만원 한도(급여항목)\n부인과·유방암 \n건강검진비 지원\n•연간 10만원 한도(비급여항목 포함)\n보직조정'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 군무원이 임신·출산 등으로 필요한 경우 자녀당 최대 3년까지 휴직이 허용되며, 최초 1년간 수당이 지급됩니다. 육아휴직 6개월째까지는 월봉급의 100%(1~3개월 최대 250만원, 4~6개월 최대 200만원), 7~12개월째까지는 월봉급의 80%(최대 160만원)가 지급됩니다. 반면, 난임 휴가 및 휴직 제도는 난임 치료 시술(인공수정, 체외수정 등) 당일에 여성 군인은 2~4일, 남성 군인은 1일의 휴가가 부여되고, 장기간 치료가 필요한 경우 1년(불가피한 경우 1년 연장 가능)까지 휴직이 허용되며, 1년차에는 봉급의 70%, 2년차에는 50%가 지급됩니다. 즉, 육아휴직은 자녀 양육을 위한 장기 휴직과 수당 지원이 중심이고, 난임 휴가 및 휴직은 난임 치료를 위한 단기 휴가와 장기 치료 휴직 및 봉급 일부 지급이 주요 지원 내용입니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_abstract_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='육아휴직 제도랑 난임 휴가 및 휴직 제도 차이 뭐에요?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n육아 휴직\n•\x07만 8세 이하 또는 초등학교 2학년 이하의 자녀를 양육하는 군인 및 군무\n원이 임신·출산으로 필요한 경우 자녀당 최대 3년 휴직 허용\n•30일 이상 휴직 시 휴직일로부터 최초 1년간 수당 지급\n* 부모 모두 3개월 이상 육아휴직, 한부모가족, 장애아동의 부모는 1년 6개월간\n 수당 지급, 확대기간(13~18개월) 지급액은 월봉급액의 80%(최대 160만원)\n•\x07육아휴직 6개월째까지 : 육아휴직 시작일을 기준으로 한 월봉급의 \n100% (1∼3개월 최대 250만원, 4∼6개월 최대 200만원)\n•\x07육아휴직 7개월째부터 12개월째까지 : 육아휴직 시작일을 기준으로 한\n 월봉급의 80% (최대 160만원)\n육아 시간\n•만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 군무원\n* 육아를 위해 필요한 경우 36개월 범위 내 1일 최대 2시간\n자녀돌봄\n휴가\n•\x07고등학생 이하 자녀 또는 손자녀를 양육중인 군인 및 군무원의 학교 공\n식행사 참여 및 병원진료 동행 등에 연간 10일 범위 휴가 부여(시간단위 \n활용 가능)\n* \x07유급휴가 : 자녀 수에 1을 더한 일수, 자녀가 장애인인 경우 또는 한부모가족지원\n법에 따른 모 또는 부에 해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n* 무급휴가 : 손자녀 돌봄, 유급휴가 초과 시\n탄력 근무\n•\x07만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 군인 및 군무원 출·퇴근 \n시간 조정\n* 1일 8시간 근무 유지(출근시간 기준 1~2시간 전후 범위내 30분 단위로 조정)\n비상시\n출·퇴근\n시간 조정\n•\x07부부 군인·군무원 중 1인 또는 한부모가정의 경우 비상 상황 발생 등으\n로 자녀를 양육(돌봄)함에 있어 공백이 생길 경우 출·퇴근 시간을 조정\n당직근무\n면제\n•3자녀 이상 여성 당직근무 면제\n* 셋째 임신 시 ∼ 마지막 자녀 초등학교 입학 전까지\n군 보육시설•어린이집 159개소, 공동육아나눔터 44개소 운영\n-③-Ⅳ\n육아 지원제도 세부사항\n국방부 양성평등정책팀 일-가정 양립지원담당 | 900-5173\n담당부서', '<2-hop>\n\n42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임 치료 시술(인공수정, 체외수정 등) 당일 휴가 2∼4일 부여\n* 여성 군인 : 2∼4일, 남성 군인 : 1일\n난임 휴직\n•\x07난임으로 장기간 치료가 필요한 군인 및 군무원 1년(불가피한 경우 1년 \n연장 가능) 휴직 허용\n* 휴직(질병휴직) 1년차 봉급의 70%, 2년차 봉급의 50% 지급\n임신검진휴가\n•임신기간 중 검진을 위해 10일 휴가 부여\n* (배우자) 임신기간 중 배우자 임신 검진에 동행하기 위해 10일 사용\n유·사산 휴가\n•유산 또는 사산 시 임신유지 기간에 따른 휴가 부여\n*\x07 15주 이내(10일), 16∼21주(30일), 22∼27주(60일), 28주 이상(90일)\n출산휴가\n•\x07(본인)출산 전후로 90일(미숙아 출산 시 100일, 한 번에 둘 이상 자녀를 임신\n시 120일)의 출산휴가를 허가하되, 출산 후 45일(한 번에 둘 이상 자녀를 \n임신 시 60일) 이상 활용\n* 유·사산 경험 및 위험자, 고령 산모(만 35세 이상)는 출산휴가 분할사용 가능\n•(배우자)20일 * \x07한 번에 둘 이상의 자녀를 출산한 경우 25일\n모성보호시간\n•휴식이나 병원진료 등을 위해 임신 여성에게 1일 2시간 휴식 허용\n출산축하금\n(군인공제회 가입자) •첫째 30만원, 둘째 60만원, 셋째 90만원, 넷째 이상 150만원\n가족수당\n•첫째 월 5만원, 둘째 월 8만원, 셋째 이상 1명당 월 12만원\n민간병원 산부인과 \n진료비 지원\n•연간 20만원 한도(급여항목)\n부인과·유방암 \n건강검진비 지원\n•연간 10만원 한도(비급여항목 포함)\n보직조정'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 군무원이 자녀당 최대 3년까지 휴직할 수 있고, 일정 기간 동안 수당이 지급됩니다. 반면, 난임 휴가 및 휴직 제도는 난임 치료 시술을 위한 휴가(여성 2~4일, 남성 1일)와 장기간 치료가 필요한 경우 1년(최대 2년)까지 휴직이 가능하며, 휴직 기간 동안 봉급의 일부가 지급됩니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_abstract_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='육아 시간제 근무와 모성보호시간 제공 제도는 각각 어떤 대상에게 적용되며, 근무시간 조정이나 휴식 제공 측면에서 어떤 차이가 있습니까?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n육아 휴직\n•\x07만 8세 이하 또는 초등학교 2학년 이하의 자녀를 양육하는 군인 및 군무\n원이 임신·출산으로 필요한 경우 자녀당 최대 3년 휴직 허용\n•30일 이상 휴직 시 휴직일로부터 최초 1년간 수당 지급\n* 부모 모두 3개월 이상 육아휴직, 한부모가족, 장애아동의 부모는 1년 6개월간\n 수당 지급, 확대기간(13~18개월) 지급액은 월봉급액의 80%(최대 160만원)\n•\x07육아휴직 6개월째까지 : 육아휴직 시작일을 기준으로 한 월봉급의 \n100% (1∼3개월 최대 250만원, 4∼6개월 최대 200만원)\n•\x07육아휴직 7개월째부터 12개월째까지 : 육아휴직 시작일을 기준으로 한\n 월봉급의 80% (최대 160만원)\n육아 시간\n•만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 군무원\n* 육아를 위해 필요한 경우 36개월 범위 내 1일 최대 2시간\n자녀돌봄\n휴가\n•\x07고등학생 이하 자녀 또는 손자녀를 양육중인 군인 및 군무원의 학교 공\n식행사 참여 및 병원진료 동행 등에 연간 10일 범위 휴가 부여(시간단위 \n활용 가능)\n* \x07유급휴가 : 자녀 수에 1을 더한 일수, 자녀가 장애인인 경우 또는 한부모가족지원\n법에 따른 모 또는 부에 해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n* 무급휴가 : 손자녀 돌봄, 유급휴가 초과 시\n탄력 근무\n•\x07만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 군인 및 군무원 출·퇴근 \n시간 조정\n* 1일 8시간 근무 유지(출근시간 기준 1~2시간 전후 범위내 30분 단위로 조정)\n비상시\n출·퇴근\n시간 조정\n•\x07부부 군인·군무원 중 1인 또는 한부모가정의 경우 비상 상황 발생 등으\n로 자녀를 양육(돌봄)함에 있어 공백이 생길 경우 출·퇴근 시간을 조정\n당직근무\n면제\n•3자녀 이상 여성 당직근무 면제\n* 셋째 임신 시 ∼ 마지막 자녀 초등학교 입학 전까지\n군 보육시설•어린이집 159개소, 공동육아나눔터 44개소 운영\n-③-Ⅳ\n육아 지원제도 세부사항\n국방부 양성평등정책팀 일-가정 양립지원담당 | 900-5173\n담당부서', '<2-hop>\n\n42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임 치료 시술(인공수정, 체외수정 등) 당일 휴가 2∼4일 부여\n* 여성 군인 : 2∼4일, 남성 군인 : 1일\n난임 휴직\n•\x07난임으로 장기간 치료가 필요한 군인 및 군무원 1년(불가피한 경우 1년 \n연장 가능) 휴직 허용\n* 휴직(질병휴직) 1년차 봉급의 70%, 2년차 봉급의 50% 지급\n임신검진휴가\n•임신기간 중 검진을 위해 10일 휴가 부여\n* (배우자) 임신기간 중 배우자 임신 검진에 동행하기 위해 10일 사용\n유·사산 휴가\n•유산 또는 사산 시 임신유지 기간에 따른 휴가 부여\n*\x07 15주 이내(10일), 16∼21주(30일), 22∼27주(60일), 28주 이상(90일)\n출산휴가\n•\x07(본인)출산 전후로 90일(미숙아 출산 시 100일, 한 번에 둘 이상 자녀를 임신\n시 120일)의 출산휴가를 허가하되, 출산 후 45일(한 번에 둘 이상 자녀를 \n임신 시 60일) 이상 활용\n* 유·사산 경험 및 위험자, 고령 산모(만 35세 이상)는 출산휴가 분할사용 가능\n•(배우자)20일 * \x07한 번에 둘 이상의 자녀를 출산한 경우 25일\n모성보호시간\n•휴식이나 병원진료 등을 위해 임신 여성에게 1일 2시간 휴식 허용\n출산축하금\n(군인공제회 가입자) •첫째 30만원, 둘째 60만원, 셋째 90만원, 넷째 이상 150만원\n가족수당\n•첫째 월 5만원, 둘째 월 8만원, 셋째 이상 1명당 월 12만원\n민간병원 산부인과 \n진료비 지원\n•연간 20만원 한도(급여항목)\n부인과·유방암 \n건강검진비 지원\n•연간 10만원 한도(비급여항목 포함)\n보직조정'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='육아 시간제 근무는 만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 군무원이 육아를 위해 필요한 경우 36개월 범위 내에서 1일 최대 2시간까지 근무시간을 단축할 수 있는 제도입니다. 반면, 모성보호시간 제공은 임신한 여성에게 적용되며, 휴식이나 병원진료 등을 위해 1일 2시간의 휴식이 허용됩니다. 즉, 육아 시간제 근무는 자녀 양육을 위한 근무시간 조정에 중점을 두고, 모성보호시간은 임신 여성의 건강 보호를 위한 휴식 제공에 중점을 둔다는 차이가 있습니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_abstract_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='일과 가정의 양립 지원과 가족수당 지원에 대해 궁금한데, 군인 및 군무원이 자녀를 양육할 때 받을 수 있는 육아휴직, 탄력 근무, 자녀돌봄휴가 등 일과 가정의 양립을 위한 제도들과, 자녀 수에 따라 지급되는 가족수당의 구체적인 지원 내용은 어떻게 되나요?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n육아 휴직\n•\x07만 8세 이하 또는 초등학교 2학년 이하의 자녀를 양육하는 군인 및 군무\n원이 임신·출산으로 필요한 경우 자녀당 최대 3년 휴직 허용\n•30일 이상 휴직 시 휴직일로부터 최초 1년간 수당 지급\n* 부모 모두 3개월 이상 육아휴직, 한부모가족, 장애아동의 부모는 1년 6개월간\n 수당 지급, 확대기간(13~18개월) 지급액은 월봉급액의 80%(최대 160만원)\n•\x07육아휴직 6개월째까지 : 육아휴직 시작일을 기준으로 한 월봉급의 \n100% (1∼3개월 최대 250만원, 4∼6개월 최대 200만원)\n•\x07육아휴직 7개월째부터 12개월째까지 : 육아휴직 시작일을 기준으로 한\n 월봉급의 80% (최대 160만원)\n육아 시간\n•만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 군무원\n* 육아를 위해 필요한 경우 36개월 범위 내 1일 최대 2시간\n자녀돌봄\n휴가\n•\x07고등학생 이하 자녀 또는 손자녀를 양육중인 군인 및 군무원의 학교 공\n식행사 참여 및 병원진료 동행 등에 연간 10일 범위 휴가 부여(시간단위 \n활용 가능)\n* \x07유급휴가 : 자녀 수에 1을 더한 일수, 자녀가 장애인인 경우 또는 한부모가족지원\n법에 따른 모 또는 부에 해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n* 무급휴가 : 손자녀 돌봄, 유급휴가 초과 시\n탄력 근무\n•\x07만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 군인 및 군무원 출·퇴근 \n시간 조정\n* 1일 8시간 근무 유지(출근시간 기준 1~2시간 전후 범위내 30분 단위로 조정)\n비상시\n출·퇴근\n시간 조정\n•\x07부부 군인·군무원 중 1인 또는 한부모가정의 경우 비상 상황 발생 등으\n로 자녀를 양육(돌봄)함에 있어 공백이 생길 경우 출·퇴근 시간을 조정\n당직근무\n면제\n•3자녀 이상 여성 당직근무 면제\n* 셋째 임신 시 ∼ 마지막 자녀 초등학교 입학 전까지\n군 보육시설•어린이집 159개소, 공동육아나눔터 44개소 운영\n-③-Ⅳ\n육아 지원제도 세부사항\n국방부 양성평등정책팀 일-가정 양립지원담당 | 900-5173\n담당부서', '<2-hop>\n\n42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임 치료 시술(인공수정, 체외수정 등) 당일 휴가 2∼4일 부여\n* 여성 군인 : 2∼4일, 남성 군인 : 1일\n난임 휴직\n•\x07난임으로 장기간 치료가 필요한 군인 및 군무원 1년(불가피한 경우 1년 \n연장 가능) 휴직 허용\n* 휴직(질병휴직) 1년차 봉급의 70%, 2년차 봉급의 50% 지급\n임신검진휴가\n•임신기간 중 검진을 위해 10일 휴가 부여\n* (배우자) 임신기간 중 배우자 임신 검진에 동행하기 위해 10일 사용\n유·사산 휴가\n•유산 또는 사산 시 임신유지 기간에 따른 휴가 부여\n*\x07 15주 이내(10일), 16∼21주(30일), 22∼27주(60일), 28주 이상(90일)\n출산휴가\n•\x07(본인)출산 전후로 90일(미숙아 출산 시 100일, 한 번에 둘 이상 자녀를 임신\n시 120일)의 출산휴가를 허가하되, 출산 후 45일(한 번에 둘 이상 자녀를 \n임신 시 60일) 이상 활용\n* 유·사산 경험 및 위험자, 고령 산모(만 35세 이상)는 출산휴가 분할사용 가능\n•(배우자)20일 * \x07한 번에 둘 이상의 자녀를 출산한 경우 25일\n모성보호시간\n•휴식이나 병원진료 등을 위해 임신 여성에게 1일 2시간 휴식 허용\n출산축하금\n(군인공제회 가입자) •첫째 30만원, 둘째 60만원, 셋째 90만원, 넷째 이상 150만원\n가족수당\n•첫째 월 5만원, 둘째 월 8만원, 셋째 이상 1명당 월 12만원\n민간병원 산부인과 \n진료비 지원\n•연간 20만원 한도(급여항목)\n부인과·유방암 \n건강검진비 지원\n•연간 10만원 한도(비급여항목 포함)\n보직조정'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='군인 및 군무원이 일과 가정의 양립을 지원받기 위해 활용할 수 있는 제도에는 육아휴직, 육아시간, 자녀돌봄휴가, 탄력 근무, 비상시 출퇴근 시간 조정, 당직근무 면제, 군 보육시설 운영 등이 있습니다. 육아휴직은 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 경우 자녀당 최대 3년까지 가능하며, 최초 1년간 수당이 지급됩니다. 육아휴직 6개월째까지는 월봉급의 100%(1~3개월 최대 250만원, 4~6개월 최대 200만원), 7~12개월째까지는 80%(최대 160만원)가 지급됩니다. 부모 모두 3개월 이상 육아휴직을 사용하거나 한부모가족, 장애아동의 부모인 경우 1년 6개월간 수당이 지급됩니다. 자녀돌봄휴가는 고등학생 이하 자녀 또는 손자녀를 양육 중인 경우 연간 10일 범위 내에서 사용할 수 있고, 유급휴가는 자녀 수에 1을 더한 일수, 장애인 자녀나 한부모가족의 경우 1일이 추가됩니다. 탄력 근무는 만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 경우 출퇴근 시간을 30분 단위로 조정할 수 있습니다. 가족수당 지원은 첫째 자녀 월 5만원, 둘째 월 8만원, 셋째 이상은 1명당 월 12만원이 지급됩니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_abstract_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='해병대사 장기복무 선발 일정이 언제고, 장기복무 관련 문의는 어디로 해야 되는지 알려줘.', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획 각 군 홈페이지 탑재 시기\n•육군 : 장교 전반기 전년도 12월, 후반기 8월 / 부사관 4월\n•해군 : 장교·부사관 전반기 1월 / 부사관 후반기 6월\n•공군 : 장교 전반기 2월 / 부사관 전반기 1월\n•해병 : 장교 전반기 2월, 후반기 9월 / 부사관 전반기 3월, 후반기 10월\n* 공군은 선발결과만 홈페이지 게시, 계획은 공문으로 전파\n* 각 군별 선발절차 및 추진일정, 선발방법 및 평가기준 등 탑재되어,매년 최신화되는 \n 세부평가 요소를 확인해서 준비 필요\n 책임감 있는 임무수행과 부대에 기여하는 자세가 중요\n•본인 소관 업무를 책임감 있게 수행하고, \n•\x07특히, 부대원(상급자, 하급자, 동료)과 원만한 관계를 유지하면서, \n 해당 특기/분야에서 인정하는 자격증 등을 취득하는 자기개발 활동 필요\n 장기(연장) 복무 관련 문의사항 : 각 부대 인사참모 소관\n 장기(연장) 복무 선발 담당 현황\n•육군 : 인사사령부 인력획득계획과 장기복무선발담당(960-7161~3)\n•해군 : 해군본부 장교인사과 장교복무/특기관리담당(910-1216)\n 부사관/병인사과 부사관/병인사담당(910-1221)\n•공군 : 공군본부 장교인사과 장교경력관리담당(920-1438)\n 부사관/병인사과 부사관/병인사운영담당(910-1147)\n•해병 : 해병대사 인사운영과 장교인사담당(928-3121)\n 인사운영과 부사관/병인사담당(928-3122)\nTip'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='해병대사 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반기 3월, 후반기 10월이야. 장기복무 관련 문의는 해병대사 인사운영과 장교인사담당(928-3121)이나 부사관/병인사담당(928-3122)로 하면 돼.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='해병 장기복무 선발 일정이랑 담당 부서 전화번호가 뭐였더라? 그리고 해병 부사관이 장기복무 준비할 때 자기개발 활동이나 자격증 취득이 왜 중요한지도 알려줘.', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획 각 군 홈페이지 탑재 시기\n•육군 : 장교 전반기 전년도 12월, 후반기 8월 / 부사관 4월\n•해군 : 장교·부사관 전반기 1월 / 부사관 후반기 6월\n•공군 : 장교 전반기 2월 / 부사관 전반기 1월\n•해병 : 장교 전반기 2월, 후반기 9월 / 부사관 전반기 3월, 후반기 10월\n* 공군은 선발결과만 홈페이지 게시, 계획은 공문으로 전파\n* 각 군별 선발절차 및 추진일정, 선발방법 및 평가기준 등 탑재되어,매년 최신화되는 \n 세부평가 요소를 확인해서 준비 필요\n 책임감 있는 임무수행과 부대에 기여하는 자세가 중요\n•본인 소관 업무를 책임감 있게 수행하고, \n•\x07특히, 부대원(상급자, 하급자, 동료)과 원만한 관계를 유지하면서, \n 해당 특기/분야에서 인정하는 자격증 등을 취득하는 자기개발 활동 필요\n 장기(연장) 복무 관련 문의사항 : 각 부대 인사참모 소관\n 장기(연장) 복무 선발 담당 현황\n•육군 : 인사사령부 인력획득계획과 장기복무선발담당(960-7161~3)\n•해군 : 해군본부 장교인사과 장교복무/특기관리담당(910-1216)\n 부사관/병인사과 부사관/병인사담당(910-1221)\n•공군 : 공군본부 장교인사과 장교경력관리담당(920-1438)\n 부사관/병인사과 부사관/병인사운영담당(910-1147)\n•해병 : 해병대사 인사운영과 장교인사담당(928-3121)\n 인사운영과 부사관/병인사담당(928-3122)\nTip'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='해병 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반기 3월, 후반기 10월에 각 군 홈페이지에 공지됩니다. 해병 장기복무 관련 담당 부서는 해병대사 인사운영과로, 장교인사담당 전화번호는 928-3121, 부사관/병인사담당 전화번호는 928-3122입니다. 해병 부사관이 장기복무를 준비할 때 자기개발 활동이나 해당 특기/분야에서 인정하는 자격증 취득이 중요한 이유는 책임감 있는 임무수행과 부대에 기여하는 자세가 중요하며, 본인 소관 업무를 책임감 있게 수행하고 부대원과 원만한 관계를 유지하는 것과 더불어 자기개발 활동이 평가 요소로 반영되기 때문입니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='군무원이 자녀를 양육하거나 임신, 출산, 난임 치료 등 가족 관련 상황에서 받을 수 있는 휴직, 휴가, 근무시간 조정, 수당 및 지원 제도에는 어떤 것들이 있으며, 각 제도의 주요 조건과 지원 내용은 무엇인가요?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n육아 휴직\n•\x07만 8세 이하 또는 초등학교 2학년 이하의 자녀를 양육하는 군인 및 군무\n원이 임신·출산으로 필요한 경우 자녀당 최대 3년 휴직 허용\n•30일 이상 휴직 시 휴직일로부터 최초 1년간 수당 지급\n* 부모 모두 3개월 이상 육아휴직, 한부모가족, 장애아동의 부모는 1년 6개월간\n 수당 지급, 확대기간(13~18개월) 지급액은 월봉급액의 80%(최대 160만원)\n•\x07육아휴직 6개월째까지 : 육아휴직 시작일을 기준으로 한 월봉급의 \n100% (1∼3개월 최대 250만원, 4∼6개월 최대 200만원)\n•\x07육아휴직 7개월째부터 12개월째까지 : 육아휴직 시작일을 기준으로 한\n 월봉급의 80% (최대 160만원)\n육아 시간\n•만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 군무원\n* 육아를 위해 필요한 경우 36개월 범위 내 1일 최대 2시간\n자녀돌봄\n휴가\n•\x07고등학생 이하 자녀 또는 손자녀를 양육중인 군인 및 군무원의 학교 공\n식행사 참여 및 병원진료 동행 등에 연간 10일 범위 휴가 부여(시간단위 \n활용 가능)\n* \x07유급휴가 : 자녀 수에 1을 더한 일수, 자녀가 장애인인 경우 또는 한부모가족지원\n법에 따른 모 또는 부에 해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n* 무급휴가 : 손자녀 돌봄, 유급휴가 초과 시\n탄력 근무\n•\x07만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 군인 및 군무원 출·퇴근 \n시간 조정\n* 1일 8시간 근무 유지(출근시간 기준 1~2시간 전후 범위내 30분 단위로 조정)\n비상시\n출·퇴근\n시간 조정\n•\x07부부 군인·군무원 중 1인 또는 한부모가정의 경우 비상 상황 발생 등으\n로 자녀를 양육(돌봄)함에 있어 공백이 생길 경우 출·퇴근 시간을 조정\n당직근무\n면제\n•3자녀 이상 여성 당직근무 면제\n* 셋째 임신 시 ∼ 마지막 자녀 초등학교 입학 전까지\n군 보육시설•어린이집 159개소, 공동육아나눔터 44개소 운영\n-③-Ⅳ\n육아 지원제도 세부사항\n국방부 양성평등정책팀 일-가정 양립지원담당 | 900-5173\n담당부서', '<2-hop>\n\n42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임 치료 시술(인공수정, 체외수정 등) 당일 휴가 2∼4일 부여\n* 여성 군인 : 2∼4일, 남성 군인 : 1일\n난임 휴직\n•\x07난임으로 장기간 치료가 필요한 군인 및 군무원 1년(불가피한 경우 1년 \n연장 가능) 휴직 허용\n* 휴직(질병휴직) 1년차 봉급의 70%, 2년차 봉급의 50% 지급\n임신검진휴가\n•임신기간 중 검진을 위해 10일 휴가 부여\n* (배우자) 임신기간 중 배우자 임신 검진에 동행하기 위해 10일 사용\n유·사산 휴가\n•유산 또는 사산 시 임신유지 기간에 따른 휴가 부여\n*\x07 15주 이내(10일), 16∼21주(30일), 22∼27주(60일), 28주 이상(90일)\n출산휴가\n•\x07(본인)출산 전후로 90일(미숙아 출산 시 100일, 한 번에 둘 이상 자녀를 임신\n시 120일)의 출산휴가를 허가하되, 출산 후 45일(한

In [27]:
sample1 = testset.samples[0].eval_sample
print("사용자질문:", sample1.user_input)
print("Context:", sample1.reference_contexts)
print("생성된 답변(정답):", sample1.reference)
print("평가대상 RAG의 답변:", sample1.response)
print("평가대상 RAG가 검색한 Context:", sample1.retrieved_contexts)

사용자질문: 9~12월 언제 뭐해요?
Context: ['이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 범부처 경진대회에 참가**하고 **12월에 시상식이 진행**됨을 보여줍니다. 표의 항목은 주로 **대회 참가 시기(9~12월)**와 **시상식 개최 시기(12월)**라는 주요 일정으로 구성되어 있습니다. 검색용으로는 **범부처 창업경진대회**, **참가 일정**, **시상식 일정**, **9~12월 참가**, **12월 시상식** 등의 키워드로 활용할 수 있습니다.']
생성된 답변(정답): 9~12월에는 범부처 창업경진대회에 참가하고, 12월에 시상식이 진행됩니다.
평가대상 RAG의 답변: None
평가대상 RAG가 검색한 Context: None

In [ ]:
# 생성된 Testset을 Pandas DataFrame으로 변환
eval_df = testset.to_pandas()

# import os

# SAVE_DIR = r"C:\Users\Playdata\SKN\SKN31-3rd-2Team\eval_results"
# os.makedirs(SAVE_DIR, exist_ok=True)

# eval_df["source"] = "qdrant"  # 나중에 출처별로 점수 나눠보기 위함
# eval_df.to_pickle(os.path.join(SAVE_DIR, "eval_testset_qdrant.pkl"))
# # CSV는 reference_contexts가 list라서 저장 시 깨짐 -> pickle 사용

In [29]:
eval_df.shape

(12, 7)

In [30]:
eval_df

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name
0,9~12월 언제 뭐해요?,"[이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 ...","9~12월에는 범부처 창업경진대회에 참가하고, 12월에 시상식이 진행됩니다.",Office Administrator,MISSPELLED,SHORT,single_hop_specific_query_synthesizer
1,군 주거 지원제도에서 국가가 민간주택 전ㆍ월세 지원 시 어떤 방식으로 지원을 제공하...,[02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부...,군 주거 지원제도에서 민간주택 전ㆍ월세 지원은 협약은행에서 전ㆍ월세 자금을 지원하고...,Military Housing Coordinator,PERFECT_GRAMMAR,LONG,single_hop_specific_query_synthesizer
2,국내외 학위과정이 뭐에요? 혹시 군에서 지원해주는건가요? 그리고 이게 자기개발이나 ...,[이 표는 **“03 Part 자기개발 및 전직지원 분야”**에 포함된 지원 항목을...,국내·외 학위과정은 군 구성원의 자기개발과 전역 후 진로 준비를 돕기 위해 지원되는...,Office Administrator,MISSPELLED,LONG,single_hop_specific_query_synthesizer
3,육군 장기복무 선발계획은 언제 어디에 탑재되나요? 그리고 육군 장기복무 선발 담당 ...,[12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획...,"육군 장기복무 선발계획은 장교의 경우 전반기는 전년도 12월, 후반기는 8월에 각 ...",Office Administrator,MISSPELLED,LONG,single_hop_specific_query_synthesizer
4,"육아휴직 제도와 난임 휴가 및 휴직 제도는 각각 어떤 대상과 조건에 따라 적용되며,...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
5,육아휴직 제도랑 난임 휴가 및 휴직 제도 차이 뭐에요?,[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
6,"육아 시간제 근무와 모성보호시간 제공 제도는 각각 어떤 대상에게 적용되며, 근무시간...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아 시간제 근무는 만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
7,"일과 가정의 양립 지원과 가족수당 지원에 대해 궁금한데, 군인 및 군무원이 자녀를 ...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,군인 및 군무원이 일과 가정의 양립을 지원받기 위해 활용할 수 있는 제도에는 육아휴...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
8,"해병대사 장기복무 선발 일정이 언제고, 장기복무 관련 문의는 어디로 해야 되는지 알려줘.",[<1-hop>\n\n12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\...,"해병대사 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer
9,해병 장기복무 선발 일정이랑 담당 부서 전화번호가 뭐였더라? 그리고 해병 부사관이 ...,[<1-hop>\n\n12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\...,"해병 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반기 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer
10,"군무원이 자녀를 양육하거나 임신, 출산, 난임 치료 등 가족 관련 상황에서 받을 수...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,"군무원은 자녀 양육, 임신, 출산, 난임 치료 등 다양한 가족 관련 상황에서 여러 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer
11,군무원 난임휴직이랑 육아휴직 차이 뭐에요?,[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,군무원 난임휴직은 난임으로 장기간 치료가 필요한 경우 1년(불가피한 경우 1년 연장...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer

In [31]:
row_idx = 0
q = eval_df.loc[row_idx, 'user_input']
resp = chain.invoke(q)

In [32]:
# resp
resp['response']

'범부처 창업경진대회는 **9~12월에 참가**하고, **12월에 시상식**이 진행됩니다.'

In [33]:
# resp
resp['retrieved_context']

['이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 범부처 경진대회에 참가**하고 **12월에 시상식이 진행**됨을 보여줍니다. 표의 항목은 주로 **대회 참가 시기(9~12월)**와 **시상식 개최 시기(12월)**라는 주요 일정으로 구성되어 있습니다. 검색용으로는 **범부처 창업경진대회**, **참가 일정**, **시상식 일정**, **9~12월 참가**, **12월 시상식** 등의 키워드로 활용할 수 있습니다.',
 '이 표는 어떤 자격시험의 **연간 일정**을 정리한 것으로, 각 컬럼은 **원서 접수**, **검정시험 시행**, **합격자 발표**, **등록/자격증 교부** 시점을 의미합니다. 일정은 **원서 접수 6~7월**, **시험 9~11월**, **합격자 발표 12월**, **등록 및 자격증 교부 12월~다음 해 1월(’26.1월까지)**로 구성되어 있습니다. 즉, 접수부터 자격증 발급까지의 전체 진행 흐름과 주요 월별 시기를 한눈에 보여주는 표입니다.',
 '이 표는 절차별 **시기(언제 시행하는지)**를 정리한 내용으로, 가운데 **시기** 컬럼에 각 절차의 수행 시점을 나열하고 있습니다. 주요 항목은 **1~8월 수시**, **9~10월 정기**, **10월 연 1회 정기**, **필요시 수시**, **일정 고려** 등으로, 특정 업무나 점검이 연중 수시 또는 정기적으로 이루어짐을 보여줍니다. **절 차**와 **기 타** 컬럼은 대부분 비어 있어, 실제 핵심 정보는 각 절차의 실행 시기 중심으로 구성된 표입니다.',
 '이 표는 **전반기와 후반기별 시험 일정**을 정리한 것으로, 각 구분에 따라 **원서접수, 필기시험, 실기시험** 시기가 제시되어 있습니다. 전반기는 **원서접수 1.19.~2.4., 필기시험 3.21., 실기시험 5.11.~6.8.**이며, 후반기는 **원서접수 6.15.~7.1., 필기시험 8.1., 실기시험 10.26.~11.20.**로 구성되어 있습니다. 즉, 이 표는 연간 시험 진행 일정과 단계별 접수·시험 날짜를 보여주는 일정표입니다.',
 '이 표는 **최종전 및 시상식 일정**을 정리한 것으로, **발표평가**를 거쳐 **26개 팀의 순위를 결정**한 뒤 **9월에 시상식**을 진행하는 흐름을 담고 있습니다. 표의 항목 중 **“최종전/시상식”**은 전체 단계의 큰 구분을 뜻하며, 아래에는 세부 진행 내용으로 **발표평가, 26팀 순위결정, 시상식(9월)**이 나열되어 있습니다. 마지막의 **“8∼9월”**은 이 과정이 진행되는 기간을 의미합니다.']

In [34]:
# 모든 testset의 데이터데 대한 llm 응답과 retriever의 검색 겷과를 추가
response_list = []
retrieved_context_list = []

for user_input in eval_df['user_input']:
    resp = chain.invoke(user_input)
    response_list.append(resp["response"])
    retrieved_context_list.append(resp["retrieved_context"])

In [35]:
print(len(response_list), len(retrieved_context_list))

12 12

In [36]:
response_list

['범부처 창업경진대회는 **9~12월에 참가**하고, **12월에 시상식**이 진행됩니다.',
 '군 주거 지원제도에서 **민간주택 전ㆍ월세 지원(이자지원)**은 **협약은행에서 전ㆍ월세 자금을 지원하고, 국가는 그 이자를 지원하는 방식**으로 제공됩니다.\n\n지원 대상은 **관리부대의 근무지 내에 관사가 부족하여 민간주택 전ㆍ월세 지원이 필요한 경우**입니다.',
 '국내·외 학위과정은 **국내 또는 국외의 대학/대학원에서 학위를 취득하는 과정**을 말합니다.  \n제공된 내용에 따르면, 군에서는 이를 **지원**하고 있습니다.\n\n지원 내용은 크게 다음과 같습니다.\n\n- **전문 학위교육**\n  - 국내·외 민간대학과 군사교육기관의 **석·박사 과정** 위탁교육 지원\n  - **지원자격:** 장기복무자\n- **능력개발교육**\n  - 국내 민간대학의 **야간·사이버 대학/대학원** 과정에 대한 등록금 지원\n  - **지원자격:** 장기복무자\n- **e-MU 학위취득**\n  - 인하공전 등 6개 대학 관련 학위취득 지원\n  - **지원자격:** 군특성화고 졸업자(일반부사관 일부 포함/각 군 추천 인원)\n\n이것이 **자기개발 및 전직지원**에 도움이 되는 이유는, 제공된 내용상 이 분야가 **군 구성원의 자기개발과 전역 후 진로 준비를 돕는 것**이고, 학위과정 지원은\n- **전문인력 양성**\n- **개인의 자질 향상**\n- **직무능력 배양**\n에 목적이 있기 때문입니다.\n\n즉, 군에서 학위 취득을 지원함으로써 현재는 역량을 키우고, 이후에는 전직이나 진로 준비에 필요한 학력을 갖추는 데 도움이 됩니다.\n\n원하시면 제가 이어서 **“국내·외 학위과정 지원”과 “국외군사교육 지원”의 차이**도 정리해드릴게요.',
 '육군 장기복무 선발계획은 **홈페이지에 탑재**되며, 시기는 다음과 같습니다.\n\n- **장교:** 전반기 **전년도 12월**, 후반기 **8월**\n- **부사관:** **4월**\n\n육군 장기복무 선발 담당 부서와 연락처는 다음과 같습니다.\n\n- **인사사령부 인력획득계획과 장기복무선발담당**\n- **연락처: 960-7161~3**',
 '육아휴직과 난임 휴가·휴직은 적용 대상과 조건, 지원 내용이 다릅니다.\n\n### 1) 육아휴직\n- **대상**: 만 8세 이하 또는 **초등학교 2학년 이하**의 자녀를 양육하는 군인 및 군무원\n- **조건**: 임신·출산으로 인해 필요한 경우\n- **지원 내용**:  \n  - **자녀당 최대 3년** 휴직 허용  \n  - **30일 이상 휴직 시** 휴직일로부터 최초 1년간 수당 지급  \n  - 육아휴직 6개월째까지: 월봉급의 **100%**  \n  - 7~12개월째: 월봉급의 **80%**\n\n### 2) 난임 휴가 및 휴직\n- **대상**: 난임 치료가 필요한 군인 및 군무원\n- **난임 휴가 조건 및 내용**:\n  - 난임 치료 시술(인공수정, 체외수정 등) **당일 휴가**\n  - **여성 군인: 2~4일**\n  - **남성 군인: 1일**\n- **난임 휴직 조건 및 내용**:\n  - 난임으로 **장기간 치료가 필요한 경우**\n  - **1년 휴직 허용**, 불가피한 경우 **1년 연장 가능**\n  - 휴직(질병휴직) 1년차 봉급의 **70%**, 2년차 봉급의 **50%** 지급\n\n### 차이점\n- **육아휴직**은 자녀 양육을 위한 제도로, 자녀 나이 기준이 있고 **장기간 휴직과 육아휴직 수당**이 핵심입니다.\n- **난임 휴가·휴직**은 난임 치료를 위한 제도로, **치료 시술 시 단기 휴가**와 **장기 치료 시 휴직**으로 나뉘며, 휴직 시에는 **질병휴직 기준의 봉급 일부**가 지급됩니다.',
 'Context 기준으로 보면 차이는 다음과 같습니다.\n\n- **난임 휴가 및 휴직 제도**\n  - **대상**: 난임 치료가 필요한 군인 및 군무원\n  - **난임 휴가**: 난임 치료 시술 당일 휴가\n    - 여성 군인: **총 2~4일**\n    - 남성 군인: **1일**\n  - **난임 휴직**: 난임으로 **장기간 치료가 필요한 경우** 허용\n    - **1년**, 불가피한 경우 **1년 연장 가능**\n\n- **육아휴직 제도**\n  - **대상**: **만 8세 이하 또는 초등학교 2학년 이하 자녀**를 양육하는 군인 및 군무원\n  - **내용**: 자녀 양육을 위해 휴직 허용\n    - **자녀당 최대 3년**\n\n즉, **난임 휴가/휴직은 임신을 위한 치료 지원**, **육아휴직은 이미 있는 자녀를 양육하기 위한 지원**입니다.',
 '정보가 부족해 답을 할 수없습니다.',
 '군인 및 군무원이 자녀를 양육할 때 받을 수 있는 **일·가정 양립 지원제도**와 **가족수당**은 다음과 같습니다.\n\n### 1) 일과 가정의 양립 지원제도\n- **육아휴직**: 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 경우, **자녀당 최대 3년** 휴직 가능합니다.  \n  - 30일 이상 휴직 시 **휴직일로부터 최초 1년간 수당 지급**\n- **육아시간**: 만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 경우, **36개월 범위 내 1일 최대 2시간** 사용 가능합니다.\n- **탄력근무**: 만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 경우, **출·퇴근 시간 조정**이 가능합니다.  \n  - **1일 8시간 근무는 유지**하며, 출근시간 기준 **1~2시간 전후 범위 내 30분 단위로 조정**합니다.\n- **비상시 출·퇴근시간 조정**: 부부 군인·군무원 중 1인 또는 한부모가정의 경우, 자녀 돌봄에 공백이 생기면 출·퇴근 시간을 조정할 수 있습니다.\n- **자녀돌봄휴가**: **고등학생 이하 자녀 또는 손자녀**를 양육하는 경우, 학교 공식행사 참여나 병원진료 동행 등을 위해 **연간 10일 범위**에서 휴가가 부여됩니다.  \n  - **시간단위 사용 가능**\n\n### 2) 가족수당\n- **첫째 자녀**: 월 **5만원**\n- **둘째 자녀**: 월 **8만원**\n- **셋째 이상 자녀**: **1명당 월 12만원**\n\n원하시면 제가 이 내용을 **표 형태로 보기 쉽게 정리**해드릴 수 있습니다.',
 '해병대 장기복무 선발 계획의 홈페이지 탑재 시기는 다음과 같습니다.\n\n- **장교**: 전반기 **2월**, 후반기 **9월**\n- **부사관**: 전반기 **3월**, 후반기 **10월**\n\n장기복무 관련 문의는 다음으로 하시면 됩니다.\n\n- **해병대사 인사운영과 장교인사담당**: **928-3121**\n- **해병대사 인사운영과 부사관/병인사담당**: **928-3122**',
 '해병 장기복무 관련 정보는 다음과 같습니다.\n\n- **선발계획 홈페이지 탑재 시기**\n  - **장교:** 전반기 2월, 후반기 9월\n  - **부사관:** 전반기 3월, 후반기 10월\n\n- **담당 부서 전화번호**\n  - **해병대사 인사운영과 장교인사담당:** **928-3121**\n  - **해병대사 인사운영과 부사관/병인사담당:** **928-3122**\n\n- **해병 부사관이 장기복무 준비 시 자기개발 활동과 자격증 취득이 중요한 이유**\n  - 문서에서는 **책임감 있는 임무수행과 부대에 기여하는 자세가 중요**하다고 안내합니다.\n  - 특히 **부대원(상급자, 하급자, 동료)과 원만한 관계를 유지**하면서,\n  - **해당 특기/분야에서 인정하는 자격증 등을 취득하는 자기개발 활동**이 필요하다고 설명합니다.\n\n즉, 해병 부사관은 장기복무 선발을 준비할 때 단순히 근무만 하는 것이 아니라, **책임감, 대인관계, 자기개발, 자격증 취득**이 함께 중요하다고 볼 수 있습니다.',
 'Context에 따르면 군무원이 임신·출산·육아 및 난임, 가족 돌봄과 관련하여 받을 수 있는 제도는 다음과 같습니다.\n\n- **난임치료 시술휴가**\n  - 여성: 시술 시마다 **2~4일**\n  - 남성: **1일**\n\n- **난임휴직**\n  - 난임으로 장기간 치료가 필요한 경우 **1년 휴직**\n  - **부득이한 경우 1년 연장 가능**\n\n- **임신검진휴가**\n  - 임신기간 중 검진을 위해 **10일**\n\n- **배우자 임신검진 동행휴가**\n  - 배우자 임신검진에 동행하기 위해 **10일**\n\n- **출산휴가**\n  - 본인: **90일**\n  - 한 번에 둘 이상 출생: **120일**\n  - 배우자: **20일**\n  - 한 번에 둘 이상 출생 시 배우자: **25일**\n\n- **유·사산 휴가**\n  - 임신유지 기간에 따라 휴가 부여\n  - 15주 이내: **10일**\n  - 16~21주: **30일**\n  - 22~27주: **60일**\n  - 28주 이상: **90일**\n  - 배우자: **3일**\n\n- **육아휴직**\n  - 만 8세 이하 또는 **초등학교 2학년 이하** 자녀를 양육하는 경우\n  - **자녀당 최대 3년**\n  - 30일 이상 휴직 시 휴직일로부터 최초 1년간 수당 지급\n  - 지급 기준:\n    - 1~3개월: 월봉급의 **100%**(최대 250만원)\n    - 4~6개월: 월봉급의 **100%**(최대 200만원)\n    - 7~12개월: 월봉급의 **80%**(최대 160만원)\n    - 부모 모두 3개월 이상 육아휴직, 한부모가족, 장애아동 부모는 **1년 6개월**까지 수당 지급 가능\n\n- **육아시간**\n  - 만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 경우\n  - **1일 최대 2시간**, **36개월 범위 내**\n\n- **모성보호시간**\n  - 임신 여성에게 **1일 2시간** 휴식 또는 병원진료 등을 위해 사용 가능\n\n- **자녀돌봄휴가**\n  - 고등학생 이하 자녀 또는 손자녀 양육 시\n  - 학교 공식행사 참여, 병원진료 동행 등에 대해 **연간 10일**\n  - 시간단위 사용 가능\n\n- **탄력근무**\n  - 만 15세 이하 또는 **중학교 3학년 이하** 자녀를 둔 경우\n  - 출·퇴근 시간 조정 가능\n  - 1일 8시간 근무는 유지\n  - 출근시간 기준 **1~2시간 전후 범위 내**, 30분 단위 조정\n\n- **비상시 출·퇴근시간 조정**\n  - 부부 군인·군무원 중 1인 또는 한부모가정의 경우\n  - 자녀 돌봄 공백이 생길 때 출·퇴근 시간 조정 가능\n\n- **야간 및 공휴일 등 근무 제한**\n  - 임신 중이거나 출산 후 1년이 지나지 않은 경우\n  - **21시~08시 야간근무**, **토요일 및 공휴일 근무 제한**\n  - 본인이 희망하거나 별도 규정이 있으면 예외\n\n- **당직근무 면제**\n  - 임신 확인 시부터 출산 후 1년까지 면제\n  - 유·사산의 경우 임신유지 기간에 따라 면제\n  - 난임 시술 중인 여성은 진단서에 명시된 시술기간 동안 면제\n  - **3자녀 이상 여성은 셋째 임신 시부터 마지막 자녀 초등학교 입학 전까지 면제**\n\n- **체력검정 보류**\n  - 임신 중이거나 출산 후 1년이 경과되지 않은 경우\n  - 당해 연도 체력검정 **일시보류(1급 부여)**\n\n- **보직조정**\n  - 임신여군이 희망할 경우 분만 가능한 산부인과 인근지역(30분 이내)으로 조정\n  - 분만취약지 근무 중인 임신여군은 본인 희망 시 보직조정 가능\n  - 유해·위험 가능 직위 배치 제한\n\n- **가족수당**\n  - 첫째: 월 **5만원**\n  - 둘째: 월 **8만원**\n  - 셋째 이상: 1명당 월 **12만원**\n\n- **민간병원 산부인과 진료비 지원**\n  - 연간 **20만원 한도**(급여항목)\n\n- **부인과·유방암 건강검진비 지원**\n  - 연간 **10만원 한도**(비급여항목 포함)\n\n- **출산축하금**\n  - 군인공제회 가입자 기준\n  - 첫째 **30만원**\n  - 둘째 **60만원**\n  - 셋째 **90만원**\n  - 넷째 이상 **150만원**\n\n- **군 보육시설**\n  - 어린이집 **159개소**, 공동육아나눔터 **44개소** 운영\n\n원하시면 제가 이 내용을 **“휴직/휴가”, “근무조정”, “수당·지원금”**으로 나눠서 더 보기 쉽게 정리해드릴 수 있습니다.',
 'Context에 따르면 차이는 다음과 같습니다.\n\n- **난임휴직**\n  - **난임으로 장기간 치료가 필요한 경우**에 허용\n  - 군인 및 군무원 대상\n  - **1년 휴직** 가능, **불가피한 경우 1년 연장 가능**\n  - 휴직(질병휴직) 기간 중 봉급은 **1년차 70%, 2년차 50%** 지급\n\n- **육아휴직**\n  - **만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육**하기 위한 경우\n  - 군인 및 군무원 대상\n  - **자녀당 최대 3년 휴직** 가능\n  - 휴직 30일 이상 시 **최초 1년간 수당 지급**  \n    - 6개월째까지, 7~12개월째까지 지급 기준이 따로 안내되어 있음\n\n즉, **난임휴직은 난임 치료를 위한 휴직**, **육아휴직은 자녀 양육을 위한 휴직**입니다.']

In [37]:
retrieved_context_list

[['이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 범부처 경진대회에 참가**하고 **12월에 시상식이 진행**됨을 보여줍니다. 표의 항목은 주로 **대회 참가 시기(9~12월)**와 **시상식 개최 시기(12월)**라는 주요 일정으로 구성되어 있습니다. 검색용으로는 **범부처 창업경진대회**, **참가 일정**, **시상식 일정**, **9~12월 참가**, **12월 시상식** 등의 키워드로 활용할 수 있습니다.',
  '이 표는 어떤 자격시험의 **연간 일정**을 정리한 것으로, 각 컬럼은 **원서 접수**, **검정시험 시행**, **합격자 발표**, **등록/자격증 교부** 시점을 의미합니다. 일정은 **원서 접수 6~7월**, **시험 9~11월**, **합격자 발표 12월**, **등록 및 자격증 교부 12월~다음 해 1월(’26.1월까지)**로 구성되어 있습니다. 즉, 접수부터 자격증 발급까지의 전체 진행 흐름과 주요 월별 시기를 한눈에 보여주는 표입니다.',
  '이 표는 절차별 **시기(언제 시행하는지)**를 정리한 내용으로, 가운데 **시기** 컬럼에 각 절차의 수행 시점을 나열하고 있습니다. 주요 항목은 **1~8월 수시**, **9~10월 정기**, **10월 연 1회 정기**, **필요시 수시**, **일정 고려** 등으로, 특정 업무나 점검이 연중 수시 또는 정기적으로 이루어짐을 보여줍니다. **절 차**와 **기 타** 컬럼은 대부분 비어 있어, 실제 핵심 정보는 각 절차의 실행 시기 중심으로 구성된 표입니다.',
  '이 표는 **전반기와 후반기별 시험 일정**을 정리한 것으로, 각 구분에 따라 **원서접수, 필기시험, 실기시험** 시기가 제시되어 있습니다. 전반기는 **원서접수 1.19.~2.4., 필기시험 3.21., 실기시험 5.11.~6.8.**이며, 후반기는 **원서접수 6.15.~7.1., 필기시험 8.1., 실기시험 10.26.~11.20.**로 구성되어 있습니다. 즉, 이 표는 연간 시험 진행 일정과 단계별 접수·시험 날짜를 보여주는 일정표입니다.',
  '이 표는 **최종전 및 시상식 일정**을 정리한 것으로, **발표평가**를 거쳐 **26개 팀의 순위를 결정**한 뒤 **9월에 시상식**을 진행하는 흐름을 담고 있습니다. 표의 항목 중 **“최종전/시상식”**은 전체 단계의 큰 구분을 뜻하며, 아래에는 세부 진행 내용으로 **발표평가, 26팀 순위결정, 시상식(9월)**이 나열되어 있습니다. 마지막의 **“8∼9월”**은 이 과정이 진행되는 기간을 의미합니다.'],
 ['02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부 길라잡이\n-⑤ 간부 주거 지원제도\n 개 요 \n \x07 \x07군인이 안정된 주거생활을 함으로써 근무에 전념할 수 있도록 하기 위하여 \n주거시설을 제공하거나 민간주택 전·월세 지원\n 군 주거지원 종류\n구 분\n내 용\n군 주거시설\n공관, 지휘관관사, 일반관사, 간부숙소\n민간주택 전ㆍ월세\n (이자지원)\n협약은행에서 전ㆍ월세 자금을 지원하고 \n국가는 그 이자를 지원\n 지원대상\n구 분\n내 용\n군 주거\n시설\n관사\n부양가족이 있고 관리부대 근무지 내에\n자가주택을 보유하지 않은 군인\n간부\n숙소\n 미혼간부ㆍ가족과 별거하는 기혼간부\n민간주택 전ㆍ월세\n(이자지원)\n관리부대의 근무지 내에 관사가 부족하여 \n민간주택 전ㆍ월세 지원이 필요한 경우\n 신청방법 \n • “국방인사정보체계”를 통해 신청 \n 초급간부 주거여건 개선 지속 추진\n •전용면적 확대(미혼 간부숙소 18㎡→ 24㎡) \n •비품개선(실별 세탁기, 취사용 인덕션, 빌트인가구 설치)\n국방부 군 주거정책과 주거관리담당 | 900-5472\n담당부서',
  '보수\n급식 및 물자\n병영생활관 개선\n현역병 학자금 대출이자 면제\n나라사랑카드 \n나라사랑포털 운영\n장병내일준비적금\n청년 주택드림 청약통장\n국외영주권자 등 병사 항공권 지원제도\n면세주류 구매\n군 마트 / Wa-Mall 이용\n문화, 스포츠 관련 할인혜택 제공\n휴양시설 이용\n체력단련장 이용\n군인공제회 저축제도\n장병e음 플랫폼 서비스\nPart 01\n생활편의 분야',
  '이 표는 **군인 가족수당·주거보조·육아휴직 급여**처럼 보이는 지급 항목을 정리한 것으로, **구분(지급 제도 종류), 대상, 지급액, 지급일**을 보여줍니다. 부양가족이 있는 군인은 배우자 **4만원**, 배우자·자녀 외 부양가족은 1명당 **2만원(최대 4명)**, 자녀는 첫째 **5만원(+2만원)**, 둘째 **8만원(+1만원)**, 셋째 이상은 1명당 **12만원(+1만원)**이 지급됩니다. 또한 하사~중령 복무자 중 군 관사·간부숙소 미거주자는 **16만원**을 받고, 만 8세 이하/초2 이하 자녀 양육 또는 임신·출산으로 30일 이상 휴직 시에는 **12개월 동안 월 봉급의 80%**를 지급하되 **최소 70만원, 최대 250만원**으로 제한됩니다.',
  '2026 병 복지 길라잡이 19\n국외영주권자 등 병사 항공권 지원제도\n개 요\n 시민권자, 국외영주권자, 재외국민 병사에게 정기휴가 및 전역 시\n항공권을 지원하는 제도\n주요내용\n□ (지원대상) 시민권자, 국외영주권자, 재외국민 병사\n□ (지원범위) 정기휴가 시 왕복항공권(최대 3회), 전역 시 편도항공권\n□ 국외여비 신청 문의 : 소속부대 인사부서\n□ 항공권 예약 여행사 : ㈜하나투어 \n (예약 이메일) air4@hanatour.com\n * 요청 시 기재사항 : 여권 사본 첨부(필수), 한글 이름, 영문 이름, 연락처,\n희망 여정(예: 1.10.인천-파리/1.20.파리-인천), 휴가(왕복) 또는 전역(편도)\n (전화 문의) 02-2127-0045 (평일 09:00~18:00)\n (카카오톡 문의) 플러스 친구 하나투어 법인영업\n항공권 지원 절차',
  '취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧\n국가보훈대상자 등록\n예비군훈련 안내\n상비예비군 제도\n예비역 병 ⇨ 부사관(하사) 임용\nPart 06\n사회적응 지원 분야'],
 ['-① 국내·외 학위과정 및 국외군사교육 지원\n-② 학습콘텐츠(M-kiss, e-러닝 등) 지원\n-③ 전역예정장병 취업 및 창업 지원\n-④ 예비군훈련 안내\n-⑤ 상비예비군 제도\n자기개발 및 전직지원 분야\n03\nPart',
  '56 \n2026 초급간부 길라잡이\n-①-Ⅰ\n국내·외 학위과정 지원\n 개 요 \n \x07전문인력 양성을 위한 국내·외 대학/대학원 학위과정 위탁교육과 개인의 \n자질향상 및 직무능력배양을 위한 국내 야간·사이버 대학/대학원 학위과정 \n등록금 지원\n 주요내용\n •전문 학위교육\n구 분\n내 용\n선발과정\n국내·외 민간대학과 군사교육기관 석·박사\n지원자격\n장기복무자\n선발시기\n매년 6~8월(당해 연도 세부선발계획에 따라 변동될 수 있음)\n비 고\n해당학교 학위과정 위탁교육 지원\n •능력개발교육\n구 분\n내 용\n선발과정\n국내 민간대학(야간, 사이버) 전문학사, 학사, 석사\n지원자격\n장기복무자\n선발시기\n매년 4~6월, 10~12월(당해 연도 세부선발계획에 따라 변동될 수 있음)\n비 고\n해당 학교 학위과정 등록금 지원\n •e-MU(electronic-Military University) 학위취득\n구 분\n내 용\n선발과정\n인하공전 등 6개 대학\n지원자격\n군특성화고 졸업자(일반부사관 일부 포함/각 군 추천 인원)\n선발시기\n매년 1~2월(당해 연도 세부선발계획에 따라 변동될 수 있음)\n수업방식\nOn Line(전공, 교양) + Off Line(전공실기, 방학 중 2주)\n비 고\n등록금 감면(국가장학금 추가 지급 시 개인부담 완화)\n-① 국내·외 학위과정 및 국외군사교육 지원',
  '01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n57 \n03\nPart\n2026 초급간부 길라잡이\n-①-Ⅱ\n국외군사교육 지원\n 개 요 \n \x07최신 군사지식 습득, 무관요원 및 권역별 지역전문가 양성을 위한 \n국외군사교육(병과교, 지참대 등) 추진\n 주요내용\n •국외군사교육\n구 분\n내 용\n선발과정\n국외 지휘참모대 과정, 병과교육 과정 등\n지원자격\n장기복무자\n선발시기\n매년 6~8월(당해 연도 세부선발계획에 따라 변동될 수 있음)\n비 고\n해당 교육과정 위탁교육 지원\n •국외연수\n구 분\n내 용\n선발과정\n국외 민간대학, 연구, 방산업체 등에서 무기운영이나 직무관련 과정 등\n지원자격\n장기복무자\n선발시기\n매년 6~8월(당해 연도 세부선발계획에 따라 변동될 수 있음)\n비 고\n해당 교육과정 위탁교육 지원\n국방부 인적자원개발과, 각 군 담당\n담당부서',
  '이 표는 **“03 Part 자기개발 및 전직지원 분야”**에 포함된 지원 항목을 정리한 것으로, 군 구성원의 자기개발과 전역 후 진로 준비를 돕는 내용을 담고 있습니다. 주요 항목은 **국내·외 학위과정 및 국외군사교육 지원**, **학습콘텐츠(M-kiss, e-러닝 등) 지원**, **전역예정장병의 취업·창업 지원**, **예비군훈련 안내**, **상비예비군 제도** 등 총 **5개 세부 분야**입니다. 이 표는 교육·훈련·취업 연계와 예비군 제도 안내를 중심으로 한 전직지원 서비스를 요약한 것입니다.',
  '01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n59 \n03\nPart\n2026 초급간부 길라잡이\n - 어학 학습 \n ① 한국외대 제2외국어 온라인 강좌 지원(과정비 무료) : 9개 국어\n ② YBM, 야나두, 시원스쿨 등 50% 이상 할인(’25년 기준)\n •한국사·한국어 능력시험 응시료 지원\n •독학사 취득을 위한 학습비 지원\n - 학사학위 미 취득인원을 위해 교재비 지원(최대 35만원)\n •학점은행/자격증 강좌 할인(아이비 김영)\n - 편입, 사회복지, 한국어교원자원증, 컴퓨터 개발 등(최대 65% 할인)\n •서울사이버대 심리상담과정 온라인 강좌 지원(과정비 무료)\n - 상담역량, 영유아발달지원 등 5개 과정\n •국가기술자격검정 응시료 면제(군내 응시)\n* \x07 \x07각 군별 제휴 회사 및 지원기간 상이에 따라 이용 전 확인 필요\n국방부 인적자원개발과, 각 군 담당\n담당부서'],
 ['01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n11 \n/\n2026 초급간부 길라잡이\n01\nPart\n장기복무 선발 길라잡이\n 장기복무 선발 혜택 \n• 소령(상사) 진출 기회 부여 → 직업안정성 보장 \n * 계급별 연령 정년 : 50세(소령), 53세(상사) \n• 군사교육(전문학위 위탁교육, 영어반 교육 등) 선발 조건 부여 \n• 국외연수, 국방무관, UN PKO 등 해외 근무 조건 부여\n 당해 연도 각 군별 장기복무 선발계획을 확인, 준비 필요\n•평가요소 및 배점\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n부대 \n평가\n부대\n추천\n면접\n평가\n체력 \n검정\n잠재 \n역량\n질적 \n평가\n육 \n군\n장 \n교\n2~3년100\n25\n5\n5\n10\n30\n10\n5\n-\n5\n5년차\n이상\n100\n40\n5\n5\n10\n25\n-\n5\n-\n-\n부\n사\n관\n3~4년100\n35\n5\n5\n10\n15\n10\n5\n5\n5\n5년차\n이상\n100\n50\n10\n0\n* 격오지 근무경력 가점 : 최대 1점 부여\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n부대 \n평가\n체력 \n검정\n인성\n평가\n기술\n자격\n해상/\n전방\n잠재 \n역량\n위원회\n평가\n해\n군\n장 교\n100\n45\n10\n5\n15\n5\n-\n-\n-\n10\n10\n부사관100\n30\n15\n5\n20\n5\n5\n5\n10\n20\n5\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n보직\n관리\n부대\n평가\n체력\n검정\n전문\n능력\n선발\n심사\n공 \n군\n장 교\n100\n25\n10\n3\n2\n20\n5\n5\n30\n부사관\n90\n20\n10\n5\n5\n15\n10\n5\n20\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n부대 \n평가\n체력 \n검정\n잠재 \n역량\n위원회\n평가\n해\n병\n대\n장 교\n100\n70\n10\n3\n-\n3\n4\n10\n부사관\n100\n45\n10\n3\n10\n15\n7\n10\n•\x07각 군 장교 및 부사관 장기복무 심사 담당부서에서 심의 2∼3개월 전 \n홈페이지 게시 및 각 부대(인사/행정참모)로 공문 발송\nTip',
  '12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획 각 군 홈페이지 탑재 시기\n•육군 : 장교 전반기 전년도 12월, 후반기 8월 / 부사관 4월\n•해군 : 장교·부사관 전반기 1월 / 부사관 후반기 6월\n•공군 : 장교 전반기 2월 / 부사관 전반기 1월\n•해병 : 장교 전반기 2월, 후반기 9월 / 부사관 전반기 3월, 후반기 10월\n* 공군은 선발결과만 홈페이지 게시, 계획은 공문으로 전파\n* 각 군별 선발절차 및 추진일정, 선발방법 및 평가기준 등 탑재되어,매년 최신화되는 \n 세부평가 요소를 확인해서 준비 필요\n 책임감 있는 임무수행과 부대에 기여하는 자세가 중요\n•본인 소관 업무를 책임감 있게 수행하고, \n•\x07특히, 부대원(상급자, 하급자, 동료)과 원만한 관계를 유지하면서, \n 해당 특기/분야에서 인정하는 자격증 등을 취득하는 자기개발 활동 필요\n 장기(연장) 복무 관련 문의사항 : 각 부대 인사참모 소관\n 장기(연장) 복무 선발 담당 현황\n•육군 : 인사사령부 인력획득계획과 장기복무선발담당(960-7161~3)\n•해군 : 해군본부 장교인사과 장교복무/특기관리담당(910-1216)\n 부사관/병인사과 부사관/병인사담당(910-1221)\n•공군 : 공군본부 장교인사과 장교경력관리담당(920-1438)\n 부사관/병인사과 부사관/병인사운영담당(910-1147)\n•해병 : 해병대사 인사운영과 장교인사담당(928-3121)\n 인사운영과 부사관/병인사담당(928-3122)\nTip',
  '이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 정리한 것으로, 장기복무 선발계획이 **홈페이지에 게시되는 시기**와 함께 선발 준비 시 확인해야 할 사항을 담고 있습니다. 컬럼은 문서 제목 아래에 각 군별 **장교/부사관 선발계획 탑재 시기**를 구분해 적고 있으며, 육군은 장교 전반기 전년도 12월·후반기 8월, 부사관 4월, 해군은 장교·부사관 전반기 1월, 부사관 후반기 6월, 공군은 장교 전반기 2월·부사관 전반기 1월, 해병은 장교 전반기 2월·후반기 9월, 부사관 전반기 3월·후반기 10월로 제시합니다. 또한 선발절차·추진일정·평가기준 등은 매년 최신화되며, 책임감 있는 임무수행과 대인관계, 관련 자격증 취득 같은 자기개발이 중요하다고 안내합니다. 마지막으로 장기복무 문의처와 각 군의 **선발 담당 부서/연',
  '10 \n2026 초급간부 길라잡이\n-①-Ⅰ\n장기복무 지원 및 선발과정\n 선발일정 : 신분별 연 1~2회 \n•육군 : 장교 전·후반기/부사관 전반기 •해군 : 전반기/부사관 전·후반기\n•공군 : 장교 전반기/부사관 전반기 •해병 : 장교 전·후반기/부사관 전·후반기\n* 각 군별 대상 및 기간 공문 확인 필요(인사참모)\n 지원대상\n구 분\n장 교\n부사관\n육 군\n(전반기)임관 5년차 이상 \n(후반기)임관 2∼3년차\n임관 3년차 ∼ 7년차\n해 군\n임관 3년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n공 군\n임관 3년차 ∼ 9년차\n임관 4년차 ∼ 7년차\n해 병\n임관 2년차 ∼ 4년차\n임관 3년차 ∼ 5년차\n 선발비율\n구 분\n장 교\n부사관\n육 군\n2년차 60%, 3년차 20%,\n5년차∼7년차 20%\n3년차 40%, 4년차 50% \n5년차∼7년차 10%\n해 군\n3년차 70%, 4년차 30%,\n이후 결원발생 시\n3년차 70%, 4년차 30%,\n이후 결원발생 시\n공 군\n3년차 70%, 4년차 30%,\n이후 결원발생 시\n4년차 60% 5년차 40%,\n이후 결원발생 시\n해 병\n2년차 30%, 3년차 40%,\n4년차 30%, 이후 결원발생 시\n3년차 40%, 4년차 30%,\n5년차 30%\n* 선발비율은 군 인력운영 수준을 고려 각 군별 조정 가능\n 선발절차\n①선발계획 공지 → ②지원서접수/신원조사 → (육군, AI 면접) → \n③부대추천 심의 → ④면접평가 → ⑤선발심의 → ⑥합격자 발표\n-① 장기/연장복무제도\n각 군별 담당\n담당부서',
  '01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n/\n2026 초급간부 길라잡이\n01\nPart\n복무연장 관련 알아두어야 할 사항\n \x07복무연장 지원기간은 임관일 기준으로 장교는 10년, 부사관은 \n7년을 넘지 않는 범위에서 복무연장 신청이 가능하며, 1회 신청시 \n4년 범위 내 연단위로 신청 가능(단, 공군은 1년 단위 지원) \n \x07당해 연도 선발계획을 확인하고 평가요소별 준비 필요\nTip\n 선발일정 : 연 1~2회 \n•육군 : 연 1∼2회(장교 전·후반기/부사관 4월) •해군 : 연 2회(전반기, 후반기)\n•공군 : 연 1회(장교 5월/부사관 4월) •해병 : 연 2회(전반기, 후반기)\n 지원대상\n구 분\n장 교\n부사관\n육 군\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n해 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 6년차\n공 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 5년차\n해 병\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n 선발비율\n•각 군별 중기인력 수준을 고려하여 병과별 적정 비율 산정\n 선발절차\n①선발계획 공지 → ②지원서접수 → ③부대추천 심사 → ④선발심의 → \n⑤합격자 발표\n-①-Ⅱ\n복무연장 지원 및 선발과정\n각 군별 담당\n담당부서'],
 ['이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~1년, 만5세, 초2, 초6, 중3, 고3)**로 적용되는 **복무·휴가·돌봄 지원 제도**를 정리한 것입니다. 주요 항목은 난임치료 시술휴가(여성 시술마다 2~4일, 남성 1일)와 난임휴직(1년+부득이한 경우 1년 연장), 임신검진휴가 10일·배우자 동행휴가 10일, 출산휴가 90일(다태아 120일, 배우자 20일/25일), 육아휴직 자녀당 최대 3년, 육아시간·모성보호시간(각 1일 최대 2시간), 자녀돌봄휴가 최대 10일, 가족수당(첫째 5만원·둘째 8만원·셋째 이상 12만원) 등입니다. 또한 야간·주말 근무 제한, 당직면제(3자녀 이상은 초등 입학 전까지), 체력검정 보류, 보육시설(어린이집 159개소), 출산축하금(첫째 30만원~넷',
  '42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임 치료 시술(인공수정, 체외수정 등) 당일 휴가 2∼4일 부여\n* 여성 군인 : 2∼4일, 남성 군인 : 1일\n난임 휴직\n•\x07난임으로 장기간 치료가 필요한 군인 및 군무원 1년(불가피한 경우 1년 \n연장 가능) 휴직 허용\n* 휴직(질병휴직) 1년차 봉급의 70%, 2년차 봉급의 50% 지급\n임신검진휴가\n•임신기간 중 검진을 위해 10일 휴가 부여\n* (배우자) 임신기간 중 배우자 임신 검진에 동행하기 위해 10일 사용\n유·사산 휴가\n•유산 또는 사산 시 임신유지 기간에 따른 휴가 부여\n*\x07 15주 이내(10일), 16∼21주(30일), 22∼27주(60일), 28주 이상(90일)\n출산휴가\n•\x07(본인)출산 전후로 90일(미숙아 출산 시 100일, 한 번에 둘 이상 자녀를 임신\n시 120일)의 출산휴가를 허가하되, 출산 후 45일(한 번에 둘 이상 자녀를 \n임신 시 60일) 이상 활용\n* 유·사산 경험 및 위험자, 고령 산모(만 35세 이상)는 출산휴가 분할사용 가능\n•(배우자)20일 * \x07한 번에 둘 이상의 자녀를 출산한 경우 25일\n모성보호시간\n•휴식이나 병원진료 등을 위해 임신 여성에게 1일 2시간 휴식 허용\n출산축하금\n(군인공제회 가입자) •첫째 30만원, 둘째 60만원, 셋째 90만원, 넷째 이상 150만원\n가족수당\n•첫째 월 5만원, 둘째 월 8만원, 셋째 이상 1명당 월 12만원\n민간병원 산부인과 \n진료비 지원\n•연간 20만원 한도(급여항목)\n부인과·유방암 \n건강검진비 지원\n•연간 10만원 한도(비급여항목 포함)\n보직조정',
  '02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n육아 휴직\n•\x07만 8세 이하 또는 초등학교 2학년 이하의 자녀를 양육하는 군인 및 군무\n원이 임신·출산으로 필요한 경우 자녀당 최대 3년 휴직 허용\n•30일 이상 휴직 시 휴직일로부터 최초 1년간 수당 지급\n* 부모 모두 3개월 이상 육아휴직, 한부모가족, 장애아동의 부모는 1년 6개월간\n 수당 지급, 확대기간(13~18개월) 지급액은 월봉급액의 80%(최대 160만원)\n•\x07육아휴직 6개월째까지 : 육아휴직 시작일을 기준으로 한 월봉급의 \n100% (1∼3개월 최대 250만원, 4∼6개월 최대 200만원)\n•\x07육아휴직 7개월째부터 12개월째까지 : 육아휴직 시작일을 기준으로 한\n 월봉급의 80% (최대 160만원)\n육아 시간\n•만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 군무원\n* 육아를 위해 필요한 경우 36개월 범위 내 1일 최대 2시간\n자녀돌봄\n휴가\n•\x07고등학생 이하 자녀 또는 손자녀를 양육중인 군인 및 군무원의 학교 공\n식행사 참여 및 병원진료 동행 등에 연간 10일 범위 휴가 부여(시간단위 \n활용 가능)\n* \x07유급휴가 : 자녀 수에 1을 더한 일수, 자녀가 장애인인 경우 또는 한부모가족지원\n법에 따른 모 또는 부에 해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n* 무급휴가 : 손자녀 돌봄, 유급휴가 초과 시\n탄력 근무\n•\x07만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 군인 및 군무원 출·퇴근 \n시간 조정\n* 1일 8시간 근무 유지(출근시간 기준 1~2시간 전후 범위내 30분 단위로 조정)\n비상시\n출·퇴근\n시간 조정\n•\x07부부 군인·군무원 중 1인 또는 한부모가정의 경우 비상 상황 발생 등으\n로 자녀를 양육(돌봄)함에 있어 공백이 생길 경우 출·퇴근 시간을 조정\n당직근무\n면제\n•3자녀 이상 여성 당직근무 면제\n* 셋째 임신 시 ∼ 마지막 자녀 초등학교 입학 전까지\n군 보육시설•어린이집 159개소, 공동육아나눔터 44개소 운영\n-③-Ⅳ\n육아 지원제도 세부사항\n국방부 양성평등정책팀 일-가정 양립지원담당 | 900-5173\n담당부서',
  '01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n19 \n/\n2026 초급간부 길라잡이\n01\nPart\n출산\n본인 90일\n(미숙아 출산 시 100일, 한번에 둘 이상 자녀를 출산시 120일)\n배우자 20일\n(한번에 둘 이상 자녀를 출산한 경우에는 25일)\n유·사산\n본인 유·사산 날부터 90일까지\n임신 기간\n휴가 시작일\n휴가 기간\n15주 이내\n유산 또는 사산한 날\n10일까지\n16주∼21주 \n30일까지\n22주∼27주 \n60일까지\n28주 이상\n90일까지\n배우자의 유·사산 3일\n육아시간\n8세 이하 또는 초등학교 2학년 이하의 자녀 육아\n1일 최대 2시간(36개월의 범위)\n자녀돌봄휴가\n손자녀 연 10일 범위(무급)\n자녀 연 10일 범위\n(자녀 수에 1을 더한 일수까지 유급, 나머지 일자는 무급)\n* 자녀가 장애인인 경우 또는 한부모가족지원법에 따른 모 또는 부에 \n해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n사망\n배우자 5일 이내\n본인·배우자의 부모 5일 이내\n본인·배우자의 (외)조부모 3일 이내\n자녀 및 자녀의 배우자 3일 이내\n본인·배우자의 형제자매 3일 이내\n구직휴가\n단기복무자(장교, 부사관)로서 전역예정일이 1년 이내 군인\n•복무기간이 2년 이상 3년 미만인 단기복무자 : 3일 이내\n•복무기간이 3년 이상 4년 미만인 단기복무자 : 4일 이내\n•복무기간이 4년 이상 5년 미만인 단기복무자 : 5일 이내\n의무복무기간의 2분의 1 이상을 마친 병 : 2일 이내\n재해구호휴가\n군인(배우자, 부모, 배우자의 부모, 자녀 포함)이 \n재난 및 안전관리 기본법에 따른 재난으로 \n피해를 입은 경우 5일 범위 \n* 대규모 재난 시 10일 범위\n국방부 병영문화혁신담당관 복무제도개선담당 | 900-5167\n담당부서',
  '18 \n2026 초급간부 길라잡이\n 공 가 \n구 분\n기 간\n공무상 질병이나 부상으로 직무 불가 시\n30일 이내\n공무관련 국회, 법원, 검찰, 경찰 또는 그 밖의 국가기관 소환 시\n직접\n필요한 기간\n법률에 따라 투표 참여 시\n외국유학·군사교육 또는 군 시설 외에서 위탁교육 시험 응시 \n올림픽·전국체육대회 등 국가적 행사 참가 시\n천재지변·교통차단 또는 그 밖의 사유로 출근이 불가할 때\n 산업안전보건법 제129조부터 제131조까지의 규정에 따른 \n건강진단, 국민건강보호법 제52조에 따른 건강검진 시\n군보건의료 관한 법률에 따른 예방접종(감염여부 검사) 시\n 청원휴가\n구 분\n기 간\n본인진료\n연간 30일 이내\n성폭력 피해 치료\n60일 이내\n가족 간호\n요양 중인 본인 가족(조부모, 부모, 배우자, 자녀, 손자녀) 및 \n배우자 부모 연간 30일 이내\n혼인\n본인 5일 이내\n자녀 1일 이내\n여성보건휴가\n생리기간 중 휴식 월 1일(무급)\n임신검진휴가\n임신 중인 여성 군인 10일 범위\n배우자 임신검진\n 동행휴가\n배우자 임신기간 중 배우자의 임신검진에 동행하기 위해 \n10일 범위\n모성보호시간\n임신 중인 여성 군인 1일 2시간 범위\n난임치료\n여성 군인 총 2일∼4일\n인공수정 시\n총 2일\n동결 보존된 배아를 이식하는 체외수정 시\n총 3일\n난자 채취 후 체외수정 시\n총 4일\n남성 군인 1일\n입양\n자녀 입양 시 20일 이내'],
 ['이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~1년, 만5세, 초2, 초6, 중3, 고3)**로 적용되는 **복무·휴가·돌봄 지원 제도**를 정리한 것입니다. 주요 항목은 난임치료 시술휴가(여성 시술마다 2~4일, 남성 1일)와 난임휴직(1년+부득이한 경우 1년 연장), 임신검진휴가 10일·배우자 동행휴가 10일, 출산휴가 90일(다태아 120일, 배우자 20일/25일), 육아휴직 자녀당 최대 3년, 육아시간·모성보호시간(각 1일 최대 2시간), 자녀돌봄휴가 최대 10일, 가족수당(첫째 5만원·둘째 8만원·셋째 이상 12만원) 등입니다. 또한 야간·주말 근무 제한, 당직면제(3자녀 이상은 초등 입학 전까지), 체력검정 보류, 보육시설(어린이집 159개소), 출산축하금(첫째 30만원~넷',
  '42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임 치료 시술(인공수정, 체외수정 등) 당일 휴가 2∼4일 부여\n* 여성 군인 : 2∼4일, 남성 군인 : 1일\n난임 휴직\n•\x07난임으로 장기간 치료가 필요한 군인 및 군무원 1년(불가피한 경우 1년 \n연장 가능) 휴직 허용\n* 휴직(질병휴직) 1년차 봉급의 70%, 2년차 봉급의 50% 지급\n임신검진휴가\n•임신기간 중 검진을 위해 10일 휴가 부여\n* (배우자) 임신기간 중 배우자 임신 검진에 동행하기 위해 10일 사용\n유·사산 휴가\n•유산 또는 사산 시 임신유지 기간에 따른 휴가 부여\n*\x07 15주 이내(10일), 16∼21주(30일), 22∼27주(60일), 28주 이상(90일)\n출산휴가\n•\x07(본인)출산 전후로 90일(미숙아 출산 시 100일, 한 번에 둘 이상 자녀를 임신\n시 120일)의 출산휴가를 허가하되, 출산 후 45일(한 번에 둘 이상 자녀를 \n임신 시 60일) 이상 활용\n* 유·사산 경험 및 위험자, 고령 산모(만 35세 이상)는 출산휴가 분할사용 가능\n•(배우자)20일 * \x07한 번에 둘 이상의 자녀를 출산한 경우 25일\n모성보호시간\n•휴식이나 병원진료 등을 위해 임신 여성에게 1일 2시간 휴식 허용\n출산축하금\n(군인공제회 가입자) •첫째 30만원, 둘째 60만원, 셋째 90만원, 넷째 이상 150만원\n가족수당\n•첫째 월 5만원, 둘째 월 8만원, 셋째 이상 1명당 월 12만원\n민간병원 산부인과 \n진료비 지원\n•연간 20만원 한도(급여항목)\n부인과·유방암 \n건강검진비 지원\n•연간 10만원 한도(비급여항목 포함)\n보직조정',
  '18 \n2026 초급간부 길라잡이\n 공 가 \n구 분\n기 간\n공무상 질병이나 부상으로 직무 불가 시\n30일 이내\n공무관련 국회, 법원, 검찰, 경찰 또는 그 밖의 국가기관 소환 시\n직접\n필요한 기간\n법률에 따라 투표 참여 시\n외국유학·군사교육 또는 군 시설 외에서 위탁교육 시험 응시 \n올림픽·전국체육대회 등 국가적 행사 참가 시\n천재지변·교통차단 또는 그 밖의 사유로 출근이 불가할 때\n 산업안전보건법 제129조부터 제131조까지의 규정에 따른 \n건강진단, 국민건강보호법 제52조에 따른 건강검진 시\n군보건의료 관한 법률에 따른 예방접종(감염여부 검사) 시\n 청원휴가\n구 분\n기 간\n본인진료\n연간 30일 이내\n성폭력 피해 치료\n60일 이내\n가족 간호\n요양 중인 본인 가족(조부모, 부모, 배우자, 자녀, 손자녀) 및 \n배우자 부모 연간 30일 이내\n혼인\n본인 5일 이내\n자녀 1일 이내\n여성보건휴가\n생리기간 중 휴식 월 1일(무급)\n임신검진휴가\n임신 중인 여성 군인 10일 범위\n배우자 임신검진\n 동행휴가\n배우자 임신기간 중 배우자의 임신검진에 동행하기 위해 \n10일 범위\n모성보호시간\n임신 중인 여성 군인 1일 2시간 범위\n난임치료\n여성 군인 총 2일∼4일\n인공수정 시\n총 2일\n동결 보존된 배아를 이식하는 체외수정 시\n총 3일\n난자 채취 후 체외수정 시\n총 4일\n남성 군인 1일\n입양\n자녀 입양 시 20일 이내',
  '01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n19 \n/\n2026 초급간부 길라잡이\n01\nPart\n출산\n본인 90일\n(미숙아 출산 시 100일, 한번에 둘 이상 자녀를 출산시 120일)\n배우자 20일\n(한번에 둘 이상 자녀를 출산한 경우에는 25일)\n유·사산\n본인 유·사산 날부터 90일까지\n임신 기간\n휴가 시작일\n휴가 기간\n15주 이내\n유산 또는 사산한 날\n10일까지\n16주∼21주 \n30일까지\n22주∼27주 \n60일까지\n28주 이상\n90일까지\n배우자의 유·사산 3일\n육아시간\n8세 이하 또는 초등학교 2학년 이하의 자녀 육아\n1일 최대 2시간(36개월의 범위)\n자녀돌봄휴가\n손자녀 연 10일 범위(무급)\n자녀 연 10일 범위\n(자녀 수에 1을 더한 일수까지 유급, 나머지 일자는 무급)\n* 자녀가 장애인인 경우 또는 한부모가족지원법에 따른 모 또는 부에 \n해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n사망\n배우자 5일 이내\n본인·배우자의 부모 5일 이내\n본인·배우자의 (외)조부모 3일 이내\n자녀 및 자녀의 배우자 3일 이내\n본인·배우자의 형제자매 3일 이내\n구직휴가\n단기복무자(장교, 부사관)로서 전역예정일이 1년 이내 군인\n•복무기간이 2년 이상 3년 미만인 단기복무자 : 3일 이내\n•복무기간이 3년 이상 4년 미만인 단기복무자 : 4일 이내\n•복무기간이 4년 이상 5년 미만인 단기복무자 : 5일 이내\n의무복무기간의 2분의 1 이상을 마친 병 : 2일 이내\n재해구호휴가\n군인(배우자, 부모, 배우자의 부모, 자녀 포함)이 \n재난 및 안전관리 기본법에 따른 재난으로 \n피해를 입은 경우 5일 범위 \n* 대규모 재난 시 10일 범위\n국방부 병영문화혁신담당관 복무제도개선담당 | 900-5167\n담당부서',
  '02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n육아 휴직\n•\x07만 8세 이하 또는 초등학교 2학년 이하의 자녀를 양육하는 군인 및 군무\n원이 임신·출산으로 필요한 경우 자녀당 최대 3년 휴직 허용\n•30일 이상 휴직 시 휴직일로부터 최초 1년간 수당 지급\n* 부모 모두 3개월 이상 육아휴직, 한부모가족, 장애아동의 부모는 1년 6개월간\n 수당 지급, 확대기간(13~18개월) 지급액은 월봉급액의 80%(최대 160만원)\n•\x07육아휴직 6개월째까지 : 육아휴직 시작일을 기준으로 한 월봉급의 \n100% (1∼3개월 최대 250만원, 4∼6개월 최대 200만원)\n•\x07육아휴직 7개월째부터 12개월째까지 : 육아휴직 시작일을 기준으로 한\n 월봉급의 80% (최대 160만원)\n육아 시간\n•만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 군무원\n* 육아를 위해 필요한 경우 36개월 범위 내 1일 최대 2시간\n자녀돌봄\n휴가\n•\x07고등학생 이하 자녀 또는 손자녀를 양육중인 군인 및 군무원의 학교 공\n식행사 참여 및 병원진료 동행 등에 연간 10일 범위 휴가 부여(시간단위 \n활용 가능)\n* \x07유급휴가 : 자녀 수에 1을 더한 일수, 자녀가 장애인인 경우 또는 한부모가족지원\n법에 따른 모 또는 부에 해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n* 무급휴가 : 손자녀 돌봄, 유급휴가 초과 시\n탄력 근무\n•\x07만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 군인 및 군무원 출·퇴근 \n시간 조정\n* 1일 8시간 근무 유지(출근시간 기준 1~2시간 전후 범위내 30분 단위로 조정)\n비상시\n출·퇴근\n시간 조정\n•\x07부부 군인·군무원 중 1인 또는 한부모가정의 경우 비상 상황 발생 등으\n로 자녀를 양육(돌봄)함에 있어 공백이 생길 경우 출·퇴근 시간을 조정\n당직근무\n면제\n•3자녀 이상 여성 당직근무 면제\n* 셋째 임신 시 ∼ 마지막 자녀 초등학교 입학 전까지\n군 보육시설•어린이집 159개소, 공동육아나눔터 44개소 운영\n-③-Ⅳ\n육아 지원제도 세부사항\n국방부 양성평등정책팀 일-가정 양립지원담당 | 900-5173\n담당부서'],
 ['이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~1년, 만5세, 초2, 초6, 중3, 고3)**로 적용되는 **복무·휴가·돌봄 지원 제도**를 정리한 것입니다. 주요 항목은 난임치료 시술휴가(여성 시술마다 2~4일, 남성 1일)와 난임휴직(1년+부득이한 경우 1년 연장), 임신검진휴가 10일·배우자 동행휴가 10일, 출산휴가 90일(다태아 120일, 배우자 20일/25일), 육아휴직 자녀당 최대 3년, 육아시간·모성보호시간(각 1일 최대 2시간), 자녀돌봄휴가 최대 10일, 가족수당(첫째 5만원·둘째 8만원·셋째 이상 12만원) 등입니다. 또한 야간·주말 근무 제한, 당직면제(3자녀 이상은 초등 입학 전까지), 체력검정 보류, 보육시설(어린이집 159개소), 출산축하금(첫째 30만원~넷',
  '02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n육아 휴직\n•\x07만 8세 이하 또는 초등학교 2학년 이하의 자녀를 양육하는 군인 및 군무\n원이 임신·출산으로 필요한 경우 자녀당 최대 3년 휴직 허용\n•30일 이상 휴직 시 휴직일로부터 최초 1년간 수당 지급\n* 부모 모두 3개월 이상 육아휴직, 한부모가족, 장애아동의 부모는 1년 6개월간\n 수당 지급, 확대기간(13~18개월) 지급액은 월봉급액의 80%(최대 160만원)\n•\x07육아휴직 6개월째까지 : 육아휴직 시작일을 기준으로 한 월봉급의 \n100% (1∼3개월 최대 250만원, 4∼6개월 최대 200만원)\n•\x07육아휴직 7개월째부터 12개월째까지 : 육아휴직 시작일을 기준으로 한\n 월봉급의 80% (최대 160만원)\n육아 시간\n•만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 군무원\n* 육아를 위해 필요한 경우 36개월 범위 내 1일 최대 2시간\n자녀돌봄\n휴가\n•\x07고등학생 이하 자녀 또는 손자녀를 양육중인 군인 및 군무원의 학교 공\n식행사 참여 및 병원진료 동행 등에 연간 10일 범위 휴가 부여(시간단위 \n활용 가능)\n* \x07유급휴가 : 자녀 수에 1을 더한 일수, 자녀가 장애인인 경우 또는 한부모가족지원\n법에 따른 모 또는 부에 해당하는 경우는 유급휴가 일수에 1일을 더한 일수\n* 무급휴가 : 손자녀 돌봄, 유급휴가 초과 시\n탄력 근무\n•\x07만 15세 이하 또는 중학교 3학년 이하 자녀를 둔 군인 및 군무원 출·퇴근 \n시간 조정\n* 1일 8시간 근무 유지(출근시간 기준 1~2시간 전후 범위내 30분 단위로 조정)\n비상시\n출·퇴근\n시간 조정\n•\x07부부 군인·군무원 중 1인 또는 한부모가정의 경우 비상 상황 발생 등으\n로 자녀를 양육(돌봄)함에 있어 공백이 생길 경우 출·퇴근 시간을 조정\n당직근무\n면제\n•3자녀 이상 여성 당직근무 면제\n* 셋째 임신 시 ∼ 마지막 자녀 초등학교 입학 전까지\n군 보육시설•어린이집 159개소, 공동육아나눔터 44개소 운영\n-③-Ⅳ\n육아 지원제도 세부사항\n국방부 양성평등정책팀 일-가정 양립지원담당 | 900-5173\n담당부서',
  '18 \n2026 초급간부 길라잡이\n 공 가 \n구 분\n기 간\n공무상 질병이나 부상으로 직무 불가 시\n30일 이내\n공무관련 국회, 법원, 검찰, 경찰 또는 그 밖의 국가기관 소환 시\n직접\n필요한 기간\n법률에 따라 투표 참여 시\n외국유학·군사교육 또는 군 시설 외에서 위탁교육 시험 응시 \n올림픽·전국체육대회 등 국가적 행사 참가 시\n천재지변·교통차단 또는 그 밖의 사유로 출근이 불가할 때\n 산업안전보건법 제129조부터 제131조까지의 규정에 따른 \n건강진단, 국민건강보호법 제52조에 따른 건강검진 시\n군보건의료 관한 법률에 따른 예방접종(감염여부 검사) 시\n 청원휴가\n구 분\n기 간\n본인진료\n연간 30일 이내\n성폭력 피해 치료\n60일 이내\n가족 간호\n요양 중인 본인 가족(조부모, 부모, 배우자, 자녀, 손자녀) 및 \n배우자 부모 연간 30일 이내\n혼인\n본인 5일 이내\n자녀 1일 이내\n여성보건휴가\n생리기간 중 휴식 월 1일(무급)\n임신검진휴가\n임신 중인 여성 군인 10일 범위\n배우자 임신검진\n 동행휴가\n배우자 임신기간 중 배우자의 임신검진에 동행하기 위해 \n10일 범위\n모성보호시간\n임신 중인 여성 군인 1일 2시간 범위\n난임치료\n여성 군인 총 2일∼4일\n인공수정 시\n총 2일\n동결 보존된 배아를 이식하는 체외수정 시\n총 3일\n난자 채취 후 체외수정 시\n총 4일\n남성 군인 1일\n입양\n자녀 입양 시 20일 이내',

In [38]:
#
# eval_df에 컬럼으로 추가
#
eval_df['response'] = response_list
eval_df['retrieved_contexts'] = retrieved_context_list
eval_df

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name,response,retrieved_contexts
0,9~12월 언제 뭐해요?,"[이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 ...","9~12월에는 범부처 창업경진대회에 참가하고, 12월에 시상식이 진행됩니다.",Office Administrator,MISSPELLED,SHORT,single_hop_specific_query_synthesizer,"범부처 창업경진대회는 **9~12월에 참가**하고, **12월에 시상식**이 진행됩니다.","[이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 ..."
1,군 주거 지원제도에서 국가가 민간주택 전ㆍ월세 지원 시 어떤 방식으로 지원을 제공하...,[02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부...,군 주거 지원제도에서 민간주택 전ㆍ월세 지원은 협약은행에서 전ㆍ월세 자금을 지원하고...,Military Housing Coordinator,PERFECT_GRAMMAR,LONG,single_hop_specific_query_synthesizer,군 주거 지원제도에서 **민간주택 전ㆍ월세 지원(이자지원)**은 **협약은행에서 전...,[02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부...
2,국내외 학위과정이 뭐에요? 혹시 군에서 지원해주는건가요? 그리고 이게 자기개발이나 ...,[이 표는 **“03 Part 자기개발 및 전직지원 분야”**에 포함된 지원 항목을...,국내·외 학위과정은 군 구성원의 자기개발과 전역 후 진로 준비를 돕기 위해 지원되는...,Office Administrator,MISSPELLED,LONG,single_hop_specific_query_synthesizer,국내·외 학위과정은 **국내 또는 국외의 대학/대학원에서 학위를 취득하는 과정**을...,"[-① 국내·외 학위과정 및 국외군사교육 지원\n-② 학습콘텐츠(M-kiss, e-..."
3,육군 장기복무 선발계획은 언제 어디에 탑재되나요? 그리고 육군 장기복무 선발 담당 ...,[12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획...,"육군 장기복무 선발계획은 장교의 경우 전반기는 전년도 12월, 후반기는 8월에 각 ...",Office Administrator,MISSPELLED,LONG,single_hop_specific_query_synthesizer,"육군 장기복무 선발계획은 **홈페이지에 탑재**되며, 시기는 다음과 같습니다.\n\...",[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n11 \n...
4,"육아휴직 제도와 난임 휴가 및 휴직 제도는 각각 어떤 대상과 조건에 따라 적용되며,...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,"육아휴직과 난임 휴가·휴직은 적용 대상과 조건, 지원 내용이 다릅니다.\n\n###...",[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...
5,육아휴직 제도랑 난임 휴가 및 휴직 제도 차이 뭐에요?,[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,Context 기준으로 보면 차이는 다음과 같습니다.\n\n- **난임 휴가 및 휴...,[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...
6,"육아 시간제 근무와 모성보호시간 제공 제도는 각각 어떤 대상에게 적용되며, 근무시간...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아 시간제 근무는 만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,정보가 부족해 답을 할 수없습니다.,[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...
7,"일과 가정의 양립 지원과 가족수당 지원에 대해 궁금한데, 군인 및 군무원이 자녀를 ...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,군인 및 군무원이 일과 가정의 양립을 지원받기 위해 활용할 수 있는 제도에는 육아휴...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,군인 및 군무원이 자녀를 양육할 때 받을 수 있는 **일·가정 양립 지원제도**와 ...,[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...
8,"해병대사 장기복무 선발 일정이 언제고, 장기복무 관련 문의는 어디로 해야 되는지 알려줘.",[<1-hop>\n\n12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\...,"해병대사 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,해병대 장기복무 선발 계획의 홈페이지 탑재 시기는 다음과 같습니다.\n\n- **장...,[12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획...
9,해병 장기복무 선발 일정이랑 담당 부서 전화번호가 뭐였더라? 그리고 해병 부사관이 ...,[<1-hop>\n\n12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\...,"해병 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반기 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,해병 장기복무 관련 정보는 다음과 같습니다.\n\n- **선발계획 홈페이지 탑재 시...,[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n11 \n...
10,"군무원이 자녀를 양육하거나 임신, 출산, 난임 치료 등 가족 관련 상황에서 받을 수...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,"군무원은 자녀 양육, 임신, 출산, 난임 치료 등 다양한 가족 관련 상황에서 여러 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,"Context에 따르면 군무원이 임신·출산·육아 및 난임, 가족 돌봄과 관련하여 받...",[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...
11,군무원 난임휴직이랑 육아휴직 차이 뭐에요?,[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,군무원 난임휴직은 난임으로 장기간 치료가 필요한 경우 1년(불가피한 경우 1년 연장...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,Context에 따르면 차이는 다음과 같습니다.\n\n- **난임휴직**\n - ...,[42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임...

In [39]:
# eval_df를 ragas의 평가데이터셋 타입으로 변환
from ragas import EvaluationDataset
eval_dataset = EvaluationDataset.from_pandas(
    eval_df[["user_input", "retrieved_contexts", "response", "reference"]]
)
eval_dataset

EvaluationDataset(features=['user_input', 'retrieved_contexts', 'response', 'reference'], len=12)

In [40]:
#
# 평가
#
from ragas.metrics import (
    LLMContextRecall,
    LLMContextPrecisionWithReference,
    Faithfulness,
    AnswerRelevancy,
)
from ragas import evaluate

C:\Users\Playdata\AppData\Local\Temp\ipykernel_33668\3378832119.py:4: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_33668\3378832119.py:4: DeprecationWarning: Importing LLMContextPrecisionWithReference from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextPrecisionWithReference
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_33668\3378832119.py:4: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_33668\3378832119.py:4: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import (

In [41]:
# 평가할 때 사용할 LLM embedding 모델
eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

metrics = [
    LLMContextRecall(llm=eval_llm),
    LLMContextPrecisionWithReference(llm=eval_llm),
    Faithfulness(llm=eval_llm),
    AnswerRelevancy(llm=eval_llm, embeddings=eval_embeddings)

]
eval_result = evaluate(dataset=eval_dataset, metrics=metrics)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_33668\384477035.py:2: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\Playdata\AppData\Local\Temp\ipykernel_33668\384477035.py:3: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))
Evaluating:  44%|████▍     | 21/48 [02:56<05:28, 12.17s/it]Exception raised in Job[6]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4.1 in organization org-YYuhur6XSTqIwPfGagtPXakj on tokens per min (TPM): Limit 30000, Used 30000, Requested 1919. Please try again in 3.838s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}})
Evaluating:  46%|████▌     | 22/48 [02:59<04:06,  9.49s/it]Exception raised in Job[10]: TimeoutError()
Evaluating:  48%|████▊     | 23/48 [03:00<02:51,  6.85s/it]Exception raised in Job[13]: TimeoutError()
Exception raised in Job[14]: TimeoutError()
Exception raised in Job[16]: TimeoutError()
Evaluating:  54%|█████▍    | 26/48 [03:02<01:16,  3.50s/it]Exception raised in Job[20]: TimeoutError()
Exception raised in Job[18]: TimeoutError()
Evaluating:  56%|█████▋    | 27/48 [03:05<01:10,  3.34s/it]Exception raised in Job[22]: TimeoutError()
Evaluating:  71%|███████   | 34/48 [03:20<00:42,  3.07s/it]Exception raised in Job[24]: TimeoutError()
Evaluating:  75%|███████▌  | 36/48 [03:47<01:31,  7.64s/it]Exception raised in Job[26]: TimeoutError()
Evaluating:  79%|███████▉  | 38/48 [04:09<01:31,  9.15s/it]Exception raised in Job[28]: TimeoutError()
Evaluating:  98%|█████████▊| 47/48 [05:26<00:11, 11.24s/it]Exception raised in Job[42]: TimeoutError()
Evaluating: 100%|██████████| 48/48 [06:05<00:00,  7.61s/it]

In [42]:
eval_result

{'context_recall': 1.0000, 'llm_context_precision_with_reference': 0.9020, 'faithfulness': 0.9818, 'answer_relevancy': 0.5549}

In [43]:
result_df = eval_result.to_pandas()
result_df

,user_input,retrieved_contexts,response,reference,context_recall,llm_context_precision_with_reference,faithfulness,answer_relevancy
0,9~12월 언제 뭐해요?,"[이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 ...","범부처 창업경진대회는 **9~12월에 참가**하고, **12월에 시상식**이 진행됩니다.","9~12월에는 범부처 창업경진대회에 참가하고, 12월에 시상식이 진행됩니다.",1.0,1.000000,1.000000,0.232617
1,군 주거 지원제도에서 국가가 민간주택 전ㆍ월세 지원 시 어떤 방식으로 지원을 제공하...,[02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부...,군 주거 지원제도에서 **민간주택 전ㆍ월세 지원(이자지원)**은 **협약은행에서 전...,군 주거 지원제도에서 민간주택 전ㆍ월세 지원은 협약은행에서 전ㆍ월세 자금을 지원하고...,1.0,1.000000,NaN,0.570793
2,국내외 학위과정이 뭐에요? 혹시 군에서 지원해주는건가요? 그리고 이게 자기개발이나 ...,"[-① 국내·외 학위과정 및 국외군사교육 지원\n-② 학습콘텐츠(M-kiss, e-...",국내·외 학위과정은 **국내 또는 국외의 대학/대학원에서 학위를 취득하는 과정**을...,국내·외 학위과정은 군 구성원의 자기개발과 전역 후 진로 준비를 돕기 위해 지원되는...,1.0,1.000000,NaN,0.655427
3,육군 장기복무 선발계획은 언제 어디에 탑재되나요? 그리고 육군 장기복무 선발 담당 ...,[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n11 \n...,"육군 장기복무 선발계획은 **홈페이지에 탑재**되며, 시기는 다음과 같습니다.\n\...","육군 장기복무 선발계획은 장교의 경우 전반기는 전년도 12월, 후반기는 8월에 각 ...",1.0,NaN,NaN,0.812678
4,"육아휴직 제도와 난임 휴가 및 휴직 제도는 각각 어떤 대상과 조건에 따라 적용되며,...",[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...,"육아휴직과 난임 휴가·휴직은 적용 대상과 조건, 지원 내용이 다릅니다.\n\n###...",육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,NaN,0.916667,NaN,0.560461
5,육아휴직 제도랑 난임 휴가 및 휴직 제도 차이 뭐에요?,[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...,Context 기준으로 보면 차이는 다음과 같습니다.\n\n- **난임 휴가 및 휴...,육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,NaN,1.000000,NaN,0.501525
6,"육아 시간제 근무와 모성보호시간 제공 제도는 각각 어떤 대상에게 적용되며, 근무시간...",[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...,정보가 부족해 답을 할 수없습니다.,육아 시간제 근무는 만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 ...,NaN,0.750000,NaN,0.000000
7,"일과 가정의 양립 지원과 가족수당 지원에 대해 궁금한데, 군인 및 군무원이 자녀를 ...",[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...,군인 및 군무원이 자녀를 양육할 때 받을 수 있는 **일·가정 양립 지원제도**와 ...,군인 및 군무원이 일과 가정의 양립을 지원받기 위해 활용할 수 있는 제도에는 육아휴...,NaN,1.000000,1.000000,0.851316
8,"해병대사 장기복무 선발 일정이 언제고, 장기복무 관련 문의는 어디로 해야 되는지 알려줘.",[12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획...,해병대 장기복무 선발 계획의 홈페이지 탑재 시기는 다음과 같습니다.\n\n- **장...,"해병대사 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반...",1.0,0.805556,1.000000,0.462306
9,해병 장기복무 선발 일정이랑 담당 부서 전화번호가 뭐였더라? 그리고 해병 부사관이 ...,[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n11 \n...,해병 장기복무 관련 정보는 다음과 같습니다.\n\n- **선발계획 홈페이지 탑재 시...,"해병 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반기 ...",1.0,0.950000,0.909091,0.555348
10,"군무원이 자녀를 양육하거나 임신, 출산, 난임 치료 등 가족 관련 상황에서 받을 수...",[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...,"Context에 따르면 군무원이 임신·출산·육아 및 난임, 가족 돌봄과 관련하여 받...","군무원은 자녀 양육, 임신, 출산, 난임 치료 등 다양한 가족 관련 상황에서 여러 ...",1.0,1.000000,NaN,0.773304
11,군무원 난임휴직이랑 육아휴직 차이 뭐에요?,[42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임...,Context에 따르면 차이는 다음과 같습니다.\n\n- **난임휴직**\n - ...,군무원 난임휴직은 난임으로 장기간 치료가 필요한 경우 1년(불가피한 경우 1년 연장...,1.0,0.500000,1.000000,0.683323