# 1. RAG 평가 개요
- RAG 평가란 RAG 시스템이 주어진 입력에 대해 얼마나 효과적으로 관련 정보를 검색하고, 이를 기반으로 정확하고 유의미한 응답을 생성하는지를 측정하는 과정이다. 
- **평가 요소**
    - **검색 단계 평가**
        - 입력 질문에 대해 검색된 문서나 정보의 관련성과 정확성을 평가.
    - **생성 단계 평가**
        - 검색된 정보를 기반으로 생성된 응답의 품질, 정확성등을 평가.
- **평가 방법**
    - **온/오프라인 평가**
        1. **오프라인 평가**
            - 미리 준비된 데이터셋을 활용하여 RAG 시스템의 성능을 측정한다.
        2. **온라인 평가**
            - 실제 사용자 트래픽과 피드백을 기반으로 시스템의 실시간 성능을 평가한다.
    - **정량적/정성적 평가**
        1. 정량적 평가
            - 자동화된 지표를 사용하여 생성된 텍스트의 품질을 평가한다.
        2. 정성적 평가
            - 전문가나 일반 사용자가 직접 생성된 응답의 품질을 평가하여 주관적인 지표를 평가한다.

# 2. [RAGAS](https://www.ragas.io/)
- RAGAS는 RAG 파이프라인을 **정량적으로 평가하는** 오픈소스 프레임 워크이다. 
- RAGAS 문서: https://docs.ragas.io/en/stable/
## 2.1 설치
- `pip install ragas rapidfuzz`

## 2.2 RAGAS 평가 지표 개요
![ragas_score](figures/ragas_score.png)
- **Generation**
    - llm 모델이 생성한 답변에 대한 평가 지표들.
    - **Faithfulness(신뢰성)**
        -  생성된 답변과 검색된 문서(context)간의 관련성을 평가하는 지표
        -  생성된 답변이 주어진 문맥(context)에 얼마나 충실한지를 평가하는 지표로 할루시네이션에 대한 평가로 볼 수있다.
    - **Answer relevancy(답변 적합성)**
        - 생성된 답변과 사용자의 질문간의 관련성을 평가하는 지표
        - 생성된 답변이 사용자의 질문과 얼마나 관련성이 있는지를 평가하는 지표.
- **Retrieval**
    -  질문에 대해 검색한 문서(context)들에 대한 평가
    -  **Context Precision(문맥 정밀도)**
        -  검색된 문서(context)들 중 질문과 관련 있는 것들이 **얼마나 상위 순위에 위치하는지** 평가하는 지표.
    -  **Context Recall(문맥 재현률)**
        -  검색된 문서(context)가 정답(ground-truth)의 정보를 얼마나 포함하고 있는지 평가하는 지표.
- 이러한 지표들은 RAG 파이프라인의 성능을 다각도로 평가하는 데 활용된다.
![RAGAS_score2](figures/RAGAS_score2.png)

## 2.3 주요 평가지표
### 2.3.1 Generation 평가
- LLM이 생성한 답변에 대한 평가
  
#### 2.3.1.1 Faithfulness (신뢰성)
- 생성된 답변이 얼마나 주어진 검색 문서들(context)를 잘 반영해서 생성되었는지 평가한다. 할루시네이션에 대한 평가라고 할 수 있다. 
- 점수범위: **0 ~ 1** (1에 가까울수록 좋음)
- 답변에 포함된 모든 주장이 context에서 얼마나 추출 가능한지를 확인한다.

##### 2.3.1.1.1평가 방법
1. Answer에서 주장 구문(claim statement)들을 생성(추출)한다. (주장이란, 질문(user input)과 관련된 내용)
    - 예) 
        - **질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요? 
        - **LLM 답변**: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 3000만명이다.
2. 각 주장들을 context로 부터 추론 가능한지 판단한다. 이를 바탕으로 faithfulness 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다. .... 한국의 인구는 5000만명이고 서울에 1000만이 살고 있다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 추론가능한 주장.
            - 한국의 인구는 3000만명이다. -> context에서 추론 불가능한 주장.
3. **Faithfulness score** 를 계산한다. 총 주장 수 중에서 context로 부터 추론가능한 주장의 개수.    
    - 예)
        - Faithfulness Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 유추할 수있다.)
    - LLM 답변에서 주장을 추출 하는 것과 각 주장이 context에서 추론 가능한 지를 판단하는 것은 LLM 을 활용한다.
- 공식
    $$
    \text{Faithfulness Score}\;=\;\cfrac{\text{주어진\;context\;에서\;추론할\;수\;있는\;주장의\;개수}}{\text{총\;주장\;개수}}
    $$

### 2.3.2 Answer relevancy (답변 적합성)
- 생성된 답변이 질문(user input)에 얼마나 잘 부합하는 지를 평가한다.
- 점수 범위: -1~1 (1에 가까울수록 좋음)
- LLM이 생성한 답변을 기반으로 질문들을 생성한다. 이렇게 생성한 질문들과 실제 질문(user input) 간의 유사도를 측정한다.

#### 2.3.2.1 평가방법
1. LLM이 생성한 답변을 기반으로 질문들을 생성한다.
    - 예) 
        - **LLM** 답변: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
2. 실제 질문과 생성한 질문간의 코사인 유사도를 측정한다. 그 평균이 최종 점수가 된다.
    - 예)
        - **실제 질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요?
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
- 공식
  $$
    \cfrac{1}{N} \sum_{i=1}^{N} \text{cosine\_similarity}(q_{\text{user}_{_i}}, q_{\text{generated}})
  $$

## 2.4 Retrieval 평가
Vector store에서 검색한 context에 대한 평가

### 2.4.1 Context Precision
- 검색된 문서(context)들 중 질문과 관련 있는 것들이 얼마나 **상위 순위**에 있는 지 평가.
- 점수 범위: 0~1 (1에 가까울수록 좋음)


#### 2.4.1.1평가방법

- 공식
$$
 \text{Context\;Precision@K} = \frac{\sum_{k=1}^{K} \left( \text{Precision@k} \times v_k \right)}{\ 상위\;K개\;결과에서의\;관련\;항목\;수}
$$
$$
 \text{Precision@k} = \frac{\text{True\;positive@k}}{(\text{True\;positive@k} + \text{False\;positive@k})} \\
$$
- $\text{Precision@k}$: 개별 문서에 대한 Precision
- K: context 의 개수(chuck 수)
- $v_k$: 관련성 여부로 0 또는 1. (0: 관련 없음, 1: 관련 있음)

#### 2.4.1.2 예시
- 질문과 context 관련성의 예
    - 질문: 한국의 수도는 어디이고 인구는 얼마나 되나요?
    - **높은 정밀도 context들**: 질문과 직접적인 관련이 있는 문서들
        - 한국의 수도는 서울이고 인구는 5000만명 입니다. 
        - 한국의 수도는 서울입니다.
        - 한국은 동아시아에 위치해 있는 국가로 수도는 서울입니다.
        - 한국의 인구는 5000만명 입니다.
    - **낮은 정밀도 context**: 한국과 관련있어 검색될 수 있지만 질문과 직접적 관련이 없다. 
        - 한국은 동아시아에 위치한 국가입니다.
        - 한국의 K-pop은 전 세계적으로 유명합니다.
        - 비빔밥, 불고기는 한국의 대표적인 음식입니다.
    - **높은 정밀도의 context이 상위 순위에 위치했으면 높은 점수를 받는다.**

- 점수 계산 예:
    - **상위 5개의 검색 결과 중 1번째, 3번째, 4번째 문서가 관련이 있다고 가정하자.**
    - **Precision@K 계산**
        ```bash
            Precision@1 = 1/1 = 1.0    # True positive@1/(True positive@1 + False positive@1).  1/1(1번 문서 계산 시에는 1개 문서만 있으므로 분모가 1이 된다.)
            Precision@2 = 1/2 = 0.5
            Precision@3 = 2/3 ≈ 0.67    
            Precision@4 = 3/4 = 0.75
            Precision@5 = 3/5 = 0.6
        ```
    - **vk의 값**
        - 1번째: $v_1 = 1$ - 관련있음
        - 2번째: $v_2 = 0$ - 관련없음
        - 3번째: $v_3 = 1$ - 관련있음
        - 4번째: $v_4 = 1$ - 관련있음
        - 5번째: $v_5 = 0$ - 관련없음

    - **Context Precision@5**
        $$
        \text{Context\;Precision@5} = \frac{(1.0 \times 1) + (0.5 \times 0) + (0.67 \times 1) + (0.75 \times 1) + (0.6 \times 0)}{3} = \frac{1.0 + 0 + 0.67 + 0.75 + 0}{3} ≈ 0.807
        $$

### 2.4.2 Context Recall (문맥 재현률)
- 검색된 문서(context)가 얼마나 정답(ground-truth)의 정보를 포함있는 지 평가하는 지표
- 점수 범위: 0~1 (1에 가까울수록 좋음)
- **정답(ground truth)의 각 주장(claim)이 검색된 context와 얼마나 일치**하는지 계산함.

#### 2.4.2.1 평가방법
1. 정답에서 주장(claim)들을 생성(추출)한다.
    - 예) 
        - **정답**: 한국의 수도는 서울이고 인구수는 5000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 5000만명이다.
2. 각 주장(claim)의 정보를 검색된 contexts에서 찾을 수 있는지 판별한다. 이를 바탕으로 context recall 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 찾을 수 있다.
            - 한국의 인구는 5000만명이다. -> context에서 찾을 수 없다.
3. **Context Recall Score** 를 계산한다. 총 주장 수 중에서 context로 부터 찾을 수 있는 주장의 개수.
    - 예)
        - Context Recall Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 찾을 수 있다.)

- 공식
    $$
    \text{Context Recall Score}\;=\;\cfrac{\text{GT의\;주장\;중\;주어진\;context\;에서\;찾을\;수\;있는\;주장의\;개수}}{\text{GT의\;총\;주장\;개수}}
    $$

# 3. RAGAS 평가 실습

In [19]:
# !uv pip install ragas rapidfuzz
# 설치 후 커널 재시작

In [20]:
# Neo4j를 로컬에서 띄우는 예시 (law_pdfs_to_neo4j_pipeline.ipynb 에서 이미 적재된 DB에 연결만 하면 되므로,
# Neo4j 컨테이너가 이미 떠 있다면 이 셀은 실행할 필요 없습니다)
# docker run -p 7474:7474 -p 7687:7687 -v neo4j_data:/data -e NEO4J_AUTH=neo4j/your_password neo4j:latest

## 3.1 Neo4j 연결 및 Retriever 생성
앞서 `law_pdfs_to_neo4j_pipeline.ipynb`로 적재해둔 Neo4j DB에 연결만 하고, text-to-Cypher + 벡터 폴백 방식의 retriever를 만듭니다.

In [21]:
##################################################
# Neo4j 연결 및 retriever 생성
##################################################
import os
import re
from openai import OpenAI
from neo4j import GraphDatabase
from dotenv import load_dotenv
from langchain_core.documents import Document
from langchain_core.runnables import RunnableLambda

load_dotenv()

NEO4J_URI = os.getenv("NEO4J_URI")
NEO4J_USERNAME = os.getenv("NEO4J_USERNAME")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD")
NEO4J_DATABASE = os.getenv("NEO4J_DATABASE", "lawdb")  # law_pdfs_to_neo4j_pipeline.ipynb 와 동일 기본값

CHAT_MODEL = "gpt-5.4-mini"
EMBEDDING_MODEL = "text-embedding-3-large"  # 적재 시 사용한 임베딩 모델과 반드시 동일해야 함

openai_client = OpenAI()
driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USERNAME, NEO4J_PASSWORD))

# 연결 및 적재 상태 확인
with driver.session(database=NEO4J_DATABASE) as session:
    article_count = session.run("MATCH (a:ARTICLE) RETURN count(a) AS c").single()["c"]
    print(f"현재 Neo4j에 적재된 ARTICLE 노드: {article_count}개")
    if article_count == 0:
        print("⚠️ 적재된 데이터가 없습니다. law_pdfs_to_neo4j_pipeline.ipynb를 먼저 실행해주세요.")

FORBIDDEN_KEYWORDS = {"CREATE", "DELETE", "SET", "MERGE", "REMOVE", "DROP", "DETACH"}

# [수정] 관계명 REFERENCE -> REFERENCES
# (law_pdfs_to_neo4j_pipeline.ipynb의 load_references()가 실제로 만드는 관계는
#  MERGE (src)-[:REFERENCES]->(tgt) 이므로 스키마 설명도 이와 일치시켜야 합니다.
#  불일치 시 LLM이 REFERENCE로 Cypher를 짜면 에러 없이 조용히 빈 결과만 나옵니다.)
SCHEMA_DESCRIPTION = """
그래프 DB 스키마:
1. 노드 라벨:
  - LAW (법률/법령 메타데이터)
    * 속성: id (string, 법령명), name (string), law_type (string), promulgation_date (string), effective_date (string)
  - ARTICLE (법령 조문)
    * 속성: id (string, 형식 "법령명::제N조"), name (string, 조문제목), description (string, 본문),
             original_id (string, 예: "제8조"), original_id_normalized (string, 예: "8", "5-2"), law_id (string)

2. 관계(Relationships):
  - (:LAW)-[:CONTAINS]->(:ARTICLE) : 법률이 특정 조문을 포함함.
  - (:ARTICLE)-[:REFERENCES]->(:ARTICLE) : 하나의 조문이 다른 조문을 참조/인용함.

벡터 인덱스: 'article_vector_index' (ARTICLE 노드의 embedding 속성 기준, 의미 검색용, dim=3072, cosine)
"""


class Neo4jRetriever:
    """사용자 질문을 받아 Neo4j(text-to-Cypher + 벡터 폴백)에서 참조 조문을 가져오는 retriever"""

    def __init__(self, client: OpenAI, driver, database: str):
        self.client = client
        self.driver = driver
        self.database = database

    def _is_safe_cypher(self, query: str) -> bool:
        upper = query.upper()
        return not any(re.search(rf"\b{kw}\b", upper) for kw in FORBIDDEN_KEYWORDS)

    def _generate_cypher(self, user_query: str) -> str:
        system_prompt = f"""
당신은 Neo4j Cypher 쿼리를 작성하는 전문가입니다.
아래 그래프 스키마만을 근거로, 사용자 질문에 답하기 위한 최적의 Cypher 쿼리를 작성하세요.

{SCHEMA_DESCRIPTION}

쿼리 작성 가이드라인:
1. 오직 읽기(MATCH) 쿼리만 작성하세요. (CUD 명령어 절대 금지)
2. [특정 조문 지정 질문]: 법령명/조번호가 명시된 경우, 해당 ARTICLE과 REFERENCES로 연결된 조문까지 함께 가져오세요.
3. [주제/의미 검색 질문]: 아래 벡터 검색 형태를 사용하세요:
   CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)
   YIELD node, score
   RETURN node.id AS id, node.name AS name, node.description AS description, score
   ORDER BY score DESC
4. RETURN문에는 반드시 'id', 'name', 'description', 'score' 별칭을 사용하세요.
5. 오직 Cypher 쿼리 텍스트만 출력하세요. 마크다운 코드블록이나 설명은 절대 포함하지 마세요.
"""
        response = self.client.chat.completions.create(
            model=CHAT_MODEL,
            temperature=0,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_query},
            ],
        )
        cypher = response.choices[0].message.content.strip()
        cypher = re.sub(r'^```(cypher)?\s*|\s*```$', '', cypher, flags=re.MULTILINE).strip()
        return cypher

    def _vector_fallback(self, user_query: str, top_k: int) -> list[dict]:
        embedding = self.client.embeddings.create(
            model=EMBEDDING_MODEL, input=[user_query]
        ).data[0].embedding

        cypher = """
        CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)
        YIELD node, score
        RETURN node.id AS id, node.name AS name, node.description AS description, score
        ORDER BY score DESC
        """
        with self.driver.session(database=self.database) as session:
            results = session.run(cypher, top_k=top_k, query_embedding=embedding)
            return [dict(r) for r in results]

    def retrieve(self, user_query: str, top_k: int = 5) -> list[dict]:
        cypher = self._generate_cypher(user_query)

        if not self._is_safe_cypher(cypher):
            return self._vector_fallback(user_query, top_k)

        params = {"top_k": top_k}
        if "query_embedding" in cypher:
            params["query_embedding"] = self.client.embeddings.create(
                model=EMBEDDING_MODEL, input=[user_query]
            ).data[0].embedding

        try:
            with self.driver.session(database=self.database) as session:
                results = session.run(cypher, **params)
                rows = [dict(r) for r in results]
        except Exception:
            return self._vector_fallback(user_query, top_k)

        if not rows:
            return self._vector_fallback(user_query, top_k)

        return rows


neo4j_retriever = Neo4jRetriever(client=openai_client, driver=driver, database=NEO4J_DATABASE)


def _rows_to_documents(rows: list[dict]) -> list[Document]:
    """Neo4jRetriever가 반환하는 list[dict]를 체인이 기대하는 list[Document]로 변환"""
    return [
        Document(
            page_content=row.get("description", ""),
            metadata={"id": row.get("id"), "name": row.get("name"), "score": row.get("score")},
        )
        for row in rows
    ]


# LCEL 체인에서 retriever 자리를 그대로 대체할 수 있도록 Runnable로 감쌈
retriever = RunnableLambda(lambda query: _rows_to_documents(neo4j_retriever.retrieve(query, top_k=5)))

현재 Neo4j에 적재된 ARTICLE 노드: 1697개

In [22]:
################################################################################
# 평가할 RAG Chain
################################################################################

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser
from langchain_core.documents import Document
from langchain_openai import ChatOpenAI

prompt_txt = """<instruction>
당신은 정보제공을 목적으로하는 유능한 AI Assistant 입니다.
주어진 context의 내용을 기반으로 질문에 답변을 합니다.
Context에 질문에 대한 명확한 정보가 있는 경우 그것을 바탕으로 답변을 합니다.
Context에 질문에 대한 명확한 정보가 없는 경우 "정보가 부족해 답을 할 수없습니다." 라고 답합니다.
절대 추측이나 일반 상식을 바탕으로 답을 하거나 Context 없는 내용을 만들어서 답변해서는 안됩니다.
</instruction>
<context>
{context}
</context>
<question>
{query}
</question>
"""
prompt = ChatPromptTemplate.from_template(template=prompt_txt)

model = ChatOpenAI(model="gpt-5.4-mini")
parser = StrOutputParser()


def format_docs_for_prompt(documents: list[Document]) -> str:
    """LLM 프롬프트({context})용: 조문 id/제목을 헤더로 표기해서 하나의 문자열로 합침"""
    parts = []
    for doc in documents:
        meta = doc.metadata
        header = f"[{meta.get('id', '')} {meta.get('name', '')}]"
        parts.append(f"{header}\n{doc.page_content}")
    return "\n\n---\n\n".join(parts)


def format_docs_for_ragas(documents: list[Document]) -> list[str]:
    """RAGAS 평가용: 검색된 문서 각각의 내용을 list[str]로 추출"""
    return [doc.page_content for doc in documents]


def build_prompt_input(state: dict) -> dict:
    """검색 결과({'documents':..., 'query':...})를 prompt 입력({'context':str, 'query':str})으로 변환"""
    return {
        "context": format_docs_for_prompt(state["documents"]),
        "query": state["query"],
    }


# 1단계: 질문으로 검색 → 원본 Document 리스트 + 질문 보존 (retriever는 여기서 1회만 호출됨)
retrieve_step = {
    "documents": retriever,
    "query": RunnablePassthrough(),
}

# RAG 체인 -> RAG 평가 데이터셋을 만드는 RAG Chain -> 최종응답: LLM 응답(str), 검색한 문서들(list[str]), 질문(str)
chain = (
    RunnablePassthrough()  # dict | dict 가 파이썬 dict 병합 연산으로 취급되는 것을 막기 위해 필요
    | retrieve_step
    | {
        "response": RunnableLambda(build_prompt_input) | prompt | model | parser,
        "retrieved_context": RunnableLambda(lambda state: format_docs_for_ragas(state["documents"])),
        "query": RunnableLambda(lambda state: state["query"]),
    }
)

In [23]:
res = chain.invoke("군인연금법 제8조는 무엇인가요?")

In [24]:
res["response"]

'군인연금법 제8조는 **“급여 사유의 확인 및 급여의 결정”**에 관한 조항입니다.  \n구체적으로는,\n\n- **제7조에 따른 급여**는\n- **그 급여를 받을 권리를 가진 사람의 청구에 따라**\n- **국방부장관이 결정하여 지급한다**고 규정하고 있습니다.'

In [25]:
res["retrieved_context"]

['제7조에 따른 급여는 그 급여를 받을 권리를 가진 사람의 청구에 따라 국방부\n장관이 결정하여 지급한다.\n\n법제처                                                            4                                                       국가법령정보센터\n군인연금법',
 '이 법에 따른 급여의 종류는 다음 각 호와 같다.\n1. 퇴직급여\n가. 퇴역연금\n나. 퇴역연금일시금\n다. 퇴역연금공제일시금\n라. 퇴직일시금\n2. 퇴직유족급여\n가. 퇴역유족연금\n나. 퇴역유족연금부가금\n다. 퇴역유족연금특별부가금\n라. 퇴역유족연금일시금\n마. 퇴직유족일시금\n3. 퇴직수당']

# 4. RAGAS 를 이용해 평가를 위한 합성 데이터 셋 만들기

- 평가 데이터셋 구성
  - `user_input`: 사용자 질문
  - `retrieved_contexts`: Vectorstore에서 검색한 context
  - `response`: LLM의 응답
  - `reference`: 정답

## 4.1 TestsetGenerator
- **문서(retrieved_contexts)를 기준**으로 **질문**, **정답** 을 생성한다.
- 평가할 LLM으로 생성된 질문을 넣어 답변을 추출하여 데이터셋을 구성한다.


> **주의**
> - TestsetGenerator import 시 `No Module named langchain_community.chat_models.vertexai` Error 발생 
> - RAGAS와 langchain-community의 버전 호환성 문제 때문에 발생한다.
> - 해결
>   1. langchain_google_vertexai 설치
>       - `!uv pip install langchain_google_vertexai`
>   2. `.venv\Lib\site-packages\langchain_community\chat_models` 디렉토리 아래 `vertexai.py` 파일을 만들고 아래 코드를 > 넣는다.
>    ```python
>       try:
>          from langchain_google_vertexai import ChatVertexAI
>       except ImportError:
>           class ChatVertexAI:
>               def __init__(self, *args, **kwargs):
>                   raise ImportError(
>                       "ChatVertexAI requires langchain-google-vertexai. "
>                       "Install with: pip install langchain-google-vertexai"
>                   )
>    ```

In [26]:
# !uv pip install langchain_google_vertexai

In [27]:
# 주피터노트북 환경에서 비동기적 처리 위해 
# script(.py) 로 작성할 경우는 필요 없다.

import nest_asyncio
nest_asyncio.apply()

In [28]:
from ragas.testset import TestsetGenerator

In [29]:
#
# testset -> Context들(문서들) - [질문 - 정답답변 + (Retriever가 찾은 문서 + LLM 응답: chain에서 생성)]
# 1. Context(문서들)을 추출 - Neo4j에서 ARTICLE 노드를 랜덤 샘플링 -> TestsetGenerator -> 질문과 정답 답변 생성

with driver.session(database=NEO4J_DATABASE) as session:
    total_docs = session.run("MATCH (a:ARTICLE) RETURN count(a) AS c").single()["c"]

    # rand() 정렬로 랜덤 k(5)개 샘플링 (APOC 없이도 동작)
    results = session.run(
        """
        MATCH (a:ARTICLE)
        RETURN a.id AS id, a.name AS name, a.description AS description
        ORDER BY rand()
        LIMIT $k
        """,
        k=10,
    )
    sample_docs = [dict(r) for r in results]

# description(조문 본문)만 추출해서 list[str]
docs = [d["description"] for d in sample_docs]

In [30]:
total_docs

1697

In [31]:
sample_docs

[{'id': '병역법::제29조',
  'name': '사회복무요원의 소집 등',
  'description': '① 지방병무청장은 사회복무요원 소집 순서가 결정된 사람을 대상으로 복무기관을 정\n하여 사회복무요원을 소집한다. 다만, 제26조제4항에 따라 선발한 사회복무요원은 복무기관과 복무분야를 정하여\n따로 소집할 수 있다. <개정 2013. 6. 4.>\n② 병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령으로 정하는 사람에 대\n하여는 제1항에도 불구하고 지방병무청장으로 하여금 따로 사회복무요원 소집을 하게 할 수 있다.<개정 2013. 6.\n4.>\n③ 제1항과 제2항에 따라 사회복무요원으로 소집된 사람에 대하여는 제55조에 따른 군사교육소집을 하며, 그 군사\n교육소집 기간은 복무기간에 산입한다.<개정 2013. 6. 4., 2016. 5. 29.>\n④ 지방병무청장은 복무기관의 장이 사회복무요원의 임무 부여에 활용할 수 있도록 사회복무요원이 다음 각 호의\n범죄로 인하여 형의 선고를 받은 경우 관련된 정보를 그 사회복무요원이 복무할 복무기관의 장에게 제공할 수 있으\n며, 정보 제공 절차 및 제공되는 정보의 범위는 병무청장이 정한다.<신설 2020. 12. 22., 2024. 1. 9.>\n1. 「아동ㆍ청소년의 성보호에 관한 법률」 제2조제2호, 제3호 및 제3호의2에 따른 범죄\n2. 「개인정보 보호법」 제70조부터 제73조까지에 따른 범죄\n3. 「특정강력범죄의 처벌에 관한 특례법」 제2조의 특정강력범죄\n4. 「형법」 제257조, 제258조, 제258조의2, 제259조부터 제265조까지에 따른 상해와 폭행의 죄, 제283조부터 제\n286조까지에 따른 협박의 죄\n5. 「마약류 관리에 관한 법률」 제58조, 제58조의2, 제59조부터 제64조까지, 제65조의2에 따른 범죄\n[전문개정 2009. 6. 9.]\n[제목개정 2013. 6. 4., 2020. 12. 22.]'},
 {'id': '병역법 시행령::제121조',
  'name': '의무ㆍ법무ㆍ군종ㆍ수의장교 등의 입영',
  'description': '① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 현역장교(의무ㆍ법무ㆍ군종ㆍ수의사관후보생을 포함하며, 이하 “의무ㆍ법무ㆍ군종ㆍ수의장교”라 한다)\n및 기본병과 분야의 현역장교(이하 “기본병과장교”라 한다)의 병적에 편입할 사람의 입영기본 계획서를 입영일 40일\n전까지 병무청장 및 해당 군 참모총장에게 송부하여야 하며, 이를 받은 병무청장은 입영 계획서를 작성하여 지방병\n무청장에게, 해당 군 참모총장은 교육 계획서를 작성하여 입영부대의 장에게 각각 송부하여야 한다. <개정 2016. 11.\n29.>\n② 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입을 지원한 사람에 대해서는 국방부장관이 병무청장\n으로부터 그 명단을 받아 현역장교 병적 편입 대상자로 입영할 사람의 명단을 입영일 20일 전까지 병무청장을 거쳐\n지방병무청장에게 송부하여야 한다.<개정 2016. 11. 29.>\n\n법제처                                                            69                                                       국가법령정보센터\n병역법 시행령\n③ 지방병무청장은 제1항에 따른 입영 계획서에 의하여 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과현역장교의 병적\n편입 대상자의 현역입영 통지서를 본인에게 입영일 7일 전까지 송달하여 개별입영하게 하고 입영자 명부와 병적기\n록표를 입영부대의 장에게 송부하여야 한다. 다만, 「의료법」 제77조 및 「전문의의 수련 및 자격 인정 등에 관한 규\n정」 제18조에 따라 보건복지부장관이 실시하는 전문의 자격시험의 합격 여부를 확인할 수 없는 의무ㆍ수의장교 편\n입 대상자에게는 현역입영 통지서를 입영일 전날까지 송달할 수 있다.<개정 2018. 5. 28.>\n④ 입영부대의 장은 제3항에 따라 입영한 사람에 대하여 정해진 군사교육을 실시하고 교육수료 10일 전까지 그 명\n단을 소속 군 참모총장을 거쳐 국방부장관에게 보고하여야 한다.\n⑤ 국방부장관은 제4항에 따른 보고를 받은 경우에는 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적에 편입\n될 사람이 군사교육을 마치는 날의 다음날에 현역장교 병적에 편입하여야 한다.\n[전문개정 2009. 12. 7.]'},
 {'id': '부대관리훈령::제260조',
  'name': '보고사고',
  'description': '① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각 호와 같다. 다만 성희롱ㆍ성폭력\n은 각 군 본부 성고충예방대응센터장(국방부 성폭력예방대응담당관)에게 보고하여야 하며, 각 군 본부 성고충예\n방대응센터장은 국방부 성폭력예방대응담당관에게 보고하여야 한다.\n1. 지휘보고 : 국방부 직할부대장ㆍ기관장 및 각 군 참모총장은 별표 3의 ‘극히 중한 사고’에 해당되는 사고가 있\n을 때에는 인지 즉시 장관에게 지휘보고 하여야 하며, 참모계통(군인권개선추진단, 관련부서)으로도 보고하여\n야 한다. 다만 성폭력의 경우 영관급 이상(4급 이상 군무원)ㆍ군 수사기관ㆍ미성년자가 연루되거나 언론보도\n(예상) 성폭력 발생 시에는 각 군 참모총장이(국방부 직할부대ㆍ기관은 국방부 성폭력예방대응담당관이) 장관\n에게 보고하여야 한다.\n2. 참모보고 : 지휘보고 대상인 극히 중한 사고나 참모보고 대상인 별표 3의 ‘중한 사고’ 발생시, 언론보도 사고 발\n생시에는 국방부 직할부대(기관) 인사처와 각 군 인사참모부는 제반사고에 대한 사항을 최초ㆍ중간ㆍ최종보고\n로 구분하여 국방부 차관실(군인권개선추진단)과 관련부서에 참모계통으로 보고하여야 한다.\n3. 참고보고 :「지휘보고」및「참모보고」에 포함되지 않는 기타 경미한 사고에 대해서는 국방부 차관실(군인권개선\n추진단)과 관련부서 계통으로 보고하여야 한다.\n4. 상황보고 : 군사지휘본부 지휘통제실장은 사고발생 상황을 접수한때에는 차관실(군인권개선추진단)과 제2항\n에 규정된 관련부서의 장에게 보고하여야 한다.\n5. 사고속보 : 사고속보는 제262조에 따라 군사경찰계통으로 보고한다.\n② 사고처리 주관부서는 별표 4와 같으며, 사고발생시 보고 및 처리는 사안에 따라 참모기능별로 유관부서와 협\n조하여 조치하고, 사고 발생시 당사자 또는 당사자로부터 보고를 받은 사람은 관할 군사경찰부대에 인지 즉시 신\n고하여야 한다.'},
 {'id': '부대관리훈령::제15조',
  'name': '군진수칙',
  'description': '군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세하고, 사명에 입\n각하여 전투 중 또는 포로가 되었을 경우에도 이를 지켜야한다.\n1. 나는 대한민국 군인(군무원)이다. 국가와 민족을 위하여 신명을 바치겠다.\n2. 나는 죽어도 항복하지 않겠다. 나는 전력을 다하여 끝까지 싸우겠다.\n3. 나는 만약에 포로가 되더라도 계속 항거하고 전력을 다하여 탈출하며, 전우의 탈출을 돕겠다.\n4. 나는 만약에 포로가 되더라도 아국이나 우방에 불리한 여하한 적의 권고나 우대도 거절하며, 추호도 적을 돕지\n않겠다.\n5. 나는 만약에 포로가 되더라도 기밀을 엄수하고, 전우를 보호하고, 선임자면 후임자를 통솔하고, 후임자면 선임\n자의 명령에 복종하겠다.\n6. 나는 만약 포로가 되어 심문 받더라도 계급, 성명, 군번, 연령을 제외하고는 진술을 회피하며, 아국과 우방에 불\n리한 성명, 그 밖에 여하한 요구에도 응하지 않겠다.\n7. 나는 조국에 신명을 바친 대한민국 군인임을 명심하고 나의 행동에 대한 책임을 지겠다. 나는 조국을 사랑하며\n조국은 나를 보호하고 있음을 확신한다.\n \n\n법제처                                                            4                                                   국가법령정보센터\n부대관리훈령\n 제2장 병영생활\n 제1절 책무'},
 {'id': '부대관리훈령::제89조',
  'name': '불침번의 근무요령',
  'description': '① 불침번은 건물 내ㆍ외를 완벽히 경계하여야 하며, 근무 중 지정된 위치를 떠나거나\n앉거나 담배를 피워서는 아니 된다.\n② 불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, 당직계통의 상관에게 보고하여야 한다.\n③ 불침번은 타인의 취침에 방해가 되지 아니하도록 근무하여야 한다.\n④ 불침번은 근무교대시 인원ㆍ장비 및 상관의 지시사항을 정확하게 인계ㆍ인수하여야 한다.'},
 {'id': '군인사법 시행령::제41조',
  'name': '증편',
  'description': '① 법 제33조에 따른 “증편(增編)”은 해당 군의 총병력이 증가되고 부대가 증설 또는 확장되어 각 계급에\n심한 불균형이 발생한 경우로 한다.\n② 제1항의 경우에 임시계급을 부여할 수 있는 인원은 해당 증편으로 인하여 증가된 인원 범위 내로 한다.\n[전문개정 2012. 1. 31.]'},
 {'id': '병역법 시행령::제28조',
  'name': '현역병모집 계획서의 작성 및 송부 등',
  'description': '① 각 군 참모총장은 법 제20조에 따른 현역병의 모집을 위하여 매년\n9월 30일까지 그 다음 해의 현역병 복무를 지원하는 사람(이하 “현역병복무지원자”라 한다)을 모집하기 위한 모집\n분야별ㆍ날짜별 인원 등이 포함된 현역병모집 계획서를 작성하고 병무청장에게 송부하여야 한다. 이 경우 각 군 참\n모총장이 그 송부한 내용을 변경하려는 경우에는 모집일 60일 전까지 병무청장에게 그 변경된 내용을 통보하여야\n\n법제처                                                            14                                                       국가법령정보센터\n병역법 시행령\n한다.\n② 병무청장은 제1항에 따라 현역병모집 계획서를 송부받은 경우에는 현역병복무지원자의 전형 및 선발을 위한 모\n집 분야별 지원자격 및 모집일정 등이 포함된 현역병모집 계획서를 작성하고 지방병무청장에게 송부하여야 한다.\n③ 지방병무청장은 제2항에 따라 현역병모집 계획서를 송부받은 경우에는 모집 홍보와 신체검사ㆍ체력검사ㆍ면접\nㆍ필기ㆍ실기 등의 전형 등을 위한 현역병모집 세부계획을 수립하여 시행하여야 한다.\n④ 병무청장 또는 지방병무청장은 현역병복무지원자의 전형을 위하여 해당 분야의 전문지식 및 능력이 있는 사람\n중에서 전형위원을 임명하거나 위촉할 수 있으며, 전형위원에게 예산의 범위에서 수당을 지급할 수 있다.<신설\n2011. 11. 23.>\n⑤ 현역병복무지원자 선발의 기준 및 절차 등에 관하여 필요한 사항은 병무청장이 선발하는 경우에는 병무청장이\n정하여 고시하고, 각 군 참모총장이 선발하는 경우에는 각 군 참모총장이 정하여 고시하여야 한다.<개정 2011. 11.\n23.>\n[전문개정 2009. 12. 7.]'},
 {'id': '공무원수당 등에 관한 규정::제2조',
  'name': '적용 범위',
  'description': '국가공무원(이하 “공무원”이라 한다)에게 지급하는 수당과 실비변상 등(이하 “수당등”이라 한다)의 종\n류, 지급범위, 지급액 및 지급방법에 관한 사항은 다른 법령에 특별한 규정이 있는 경우 외에는 이 영에서 정하는 바\n에 따른다.\n[전문개정 2008. 12. 31.]'},
 {'id': '공무원보수규정::제19조의2',
  'name': '원천징수 등의 금지',
  'description': '① 보수지급기관은 다음 각 호의 어느 하나에 해당하는 경우를 제외하고는 보수에서\n일정 금액을 정기적으로 원천징수, 특별징수 또는 공제(이하 이 조에서 “원천징수등”이라 한다)할 수 없다. <개정\n2013. 1. 9., 2016. 1. 8., 2019. 1. 8., 2020. 3. 10.>\n1. 법령에 따라 원천징수등을 하여야 하는 경우\n2. 「고용보험 및 산업재해보상보험의 보험료징수 등에 관한 법률」 제16조에 따른 고용보험료에 대하여 원천징수등\n을 하는 경우\n3. 법률에 따라 설립된 공제회의 부담금 등에 대하여 원천징수등을 하는 경우\n4. 법원의 재판에 따라 원천징수등을 하여야 하는 경우\n5. 본인이 선택한 기간의 범위에서 서면 제출 또는 전자인사관리시스템(공무원의 인사기록을 데이터베이스화하여\n관리하고 인사 업무를 전자적으로 처리할 수 있는 시스템을 말한다)을 통하여 「회계관계 직원 등의 책임에 관한\n법률」 제2조제1호가목에 따른 지출관(대리지출관, 분임지출관 및 대리분임지출관은 제외한다) 또는 같은 조 제\n2호가목에 따른 지출원(대리지출원, 분임지출원 및 대리분임지출원은 제외한다)에게 동의한 사항에 대하여 원천\n징수등을 하는 경우\n② 제1항에 따른 원천징수등의 방법, 운영 및 그 밖에 필요한 사항은 인사혁신처장이 정한다.<개정 2013. 3. 23.,\n2014. 11. 19.>\n[본조신설 2009. 12. 7.]'},
 {'id': '군인 재해보상법::제51조',
  'name': '조사ㆍ보고 등',
  'description': '국방부장관은 이 법에 따른 급여와 그 밖에 재해보상제도를 적정하게 운영하기 위하여 필요하\n다고 인정할 때에는 각 군 참모총장, 국방부 직할부대장 또는 직할기관장 및 요양기관의 장, 그 밖의 관계자에게 다\n음 각 호의 사항을 요구할 수 있으며, 소속 공무원 또는 기관으로 하여금 장부, 서류 또는 그 밖의 물건을 검사하게\n할 수 있다.\n1. 필요한 보고ㆍ통보\n2. 장부, 서류, 그 밖의 물건의 제시ㆍ제출\n3. 일정한 장소에의 출석과 의견의 진술 또는 설명'}]

In [32]:
docs

['① 지방병무청장은 사회복무요원 소집 순서가 결정된 사람을 대상으로 복무기관을 정\n하여 사회복무요원을 소집한다. 다만, 제26조제4항에 따라 선발한 사회복무요원은 복무기관과 복무분야를 정하여\n따로 소집할 수 있다. <개정 2013. 6. 4.>\n② 병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령으로 정하는 사람에 대\n하여는 제1항에도 불구하고 지방병무청장으로 하여금 따로 사회복무요원 소집을 하게 할 수 있다.<개정 2013. 6.\n4.>\n③ 제1항과 제2항에 따라 사회복무요원으로 소집된 사람에 대하여는 제55조에 따른 군사교육소집을 하며, 그 군사\n교육소집 기간은 복무기간에 산입한다.<개정 2013. 6. 4., 2016. 5. 29.>\n④ 지방병무청장은 복무기관의 장이 사회복무요원의 임무 부여에 활용할 수 있도록 사회복무요원이 다음 각 호의\n범죄로 인하여 형의 선고를 받은 경우 관련된 정보를 그 사회복무요원이 복무할 복무기관의 장에게 제공할 수 있으\n며, 정보 제공 절차 및 제공되는 정보의 범위는 병무청장이 정한다.<신설 2020. 12. 22., 2024. 1. 9.>\n1. 「아동ㆍ청소년의 성보호에 관한 법률」 제2조제2호, 제3호 및 제3호의2에 따른 범죄\n2. 「개인정보 보호법」 제70조부터 제73조까지에 따른 범죄\n3. 「특정강력범죄의 처벌에 관한 특례법」 제2조의 특정강력범죄\n4. 「형법」 제257조, 제258조, 제258조의2, 제259조부터 제265조까지에 따른 상해와 폭행의 죄, 제283조부터 제\n286조까지에 따른 협박의 죄\n5. 「마약류 관리에 관한 법률」 제58조, 제58조의2, 제59조부터 제64조까지, 제65조의2에 따른 범죄\n[전문개정 2009. 6. 9.]\n[제목개정 2013. 6. 4., 2020. 12. 22.]',
 '① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 현역장교(의무ㆍ법무ㆍ군종ㆍ수의사관후보생을 포함하며, 이하 “의무ㆍ법무ㆍ군종ㆍ수의장교”라 한다)\n및 기본병과 분야의 현역장교(이하 “기본병과장교”라 한다)의 병적에 편입할 사람의 입영기본 계획서를 입영일 40일\n전까지 병무청장 및 해당 군 참모총장에게 송부하여야 하며, 이를 받은 병무청장은 입영 계획서를 작성하여 지방병\n무청장에게, 해당 군 참모총장은 교육 계획서를 작성하여 입영부대의 장에게 각각 송부하여야 한다. <개정 2016. 11.\n29.>\n② 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입을 지원한 사람에 대해서는 국방부장관이 병무청장\n으로부터 그 명단을 받아 현역장교 병적 편입 대상자로 입영할 사람의 명단을 입영일 20일 전까지 병무청장을 거쳐\n지방병무청장에게 송부하여야 한다.<개정 2016. 11. 29.>\n\n법제처                                                            69                                                       국가법령정보센터\n병역법 시행령\n③ 지방병무청장은 제1항에 따른 입영 계획서에 의하여 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과현역장교의 병적\n편입 대상자의 현역입영 통지서를 본인에게 입영일 7일 전까지 송달하여 개별입영하게 하고 입영자 명부와 병적기\n록표를 입영부대의 장에게 송부하여야 한다. 다만, 「의료법」 제77조 및 「전문의의 수련 및 자격 인정 등에 관한 규\n정」 제18조에 따라 보건복지부장관이 실시하는 전문의 자격시험의 합격 여부를 확인할 수 없는 의무ㆍ수의장교 편\n입 대상자에게는 현역입영 통지서를 입영일 전날까지 송달할 수 있다.<개정 2018. 5. 28.>\n④ 입영부대의 장은 제3항에 따라 입영한 사람에 대하여 정해진 군사교육을 실시하고 교육수료 10일 전까지 그 명\n단을 소속 군 참모총장을 거쳐 국방부장관에게 보고하여야 한다.\n⑤ 국방부장관은 제4항에 따른 보고를 받은 경우에는 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적에 편입\n될 사람이 군사교육을 마치는 날의 다음날에 현역장교 병적에 편입하여야 한다.\n[전문개정 2009. 12. 7.]',
 '① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각 호와 같다. 다만 성희롱ㆍ성폭력\n은 각 군 본부 성고충예방대응센터장(국방부 성폭력예방대응담당관)에게 보고하여야 하며, 각 군 본부 성고충예\n방대응센터장은 국방부 성폭력예방대응담당관에게 보고하여야 한다.\n1. 지휘보고 : 국방부 직할부대장ㆍ기관장 및 각 군 참모총장은 별표 3의 ‘극히 중한 사고’에 해당되는 사고가 있\n을 때에는 인지 즉시 장관에게 지휘보고 하여야 하며, 참모계통(군인권개선추진단, 관련부서)으로도 보고하여\n야 한다. 다만 성폭력의 경우 영관급 이상(4급 이상 군무원)ㆍ군 수사기관ㆍ미성년자가 연루되거나 언론보도\n(예상) 성폭력 발생 시에는 각 군 참모총장이(국방부 직할부대ㆍ기관은 국방부 성폭력예방대응담당관이) 장관\n에게 보고하여야 한다.\n2. 참모보고 : 지휘보고 대상인 극히 중한 사고나 참모보고 대상인 별표 3의 ‘중한 사고’ 발생시, 언론보도 사고 발\n생시에는 국방부 직할부대(기관) 인사처와 각 군 인사참모부는 제반사고에 대한 사항을 최초ㆍ중간ㆍ최종보고\n로 구분하여 국방부 차관실(군인권개선추진단)과 관련부서에 참모계통으로 보고하여야 한다.\n3. 참고보고 :「지휘보고」및「참모보고」에 포함되지 않는 기타 경미한 사고에 대해서는 국방부 차관실(군인권개선\n추진단)과 관련부서 계통으로 보고하여야 한다.\n4. 상황보고 : 군사지휘본부 지휘통제실장은 사고발생 상황을 접수한때에는 차관실(군인권개선추진단)과 제2항\n에 규정된 관련부서의 장에게 보고하여야 한다.\n5. 사고속보 : 사고속보는 제262조에 따라 군사경찰계통으로 보고한다.\n② 사고처리 주관부서는 별표 4와 같으며, 사고발생시 보고 및 처리는 사안에 따라 참모기능별로 유관부서와 협\n조하여 조치하고, 사고 발생시 당사자 또는 당사자로부터 보고를 받은 사람은 관할 군사경찰부대에 인지 즉시 신\n고하여야 한다.',
 '군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세하고, 사명에 입\n각하여 전투 중 또는 포로가 되었을 경우에도 이를 지켜야한다.\n1. 나는 대한민국 군인(군무원)이다. 국가와 민족을 위하여 신명을 바치겠다.\n2. 나는 죽어도 항복하지 않겠다. 나는 전력을 다하여 끝까지 싸우겠다.\n3. 나는 만약에 포로가 되더라도 계속 항거하고 전력을 다하여 탈출하며, 전우의 탈출을 돕겠다.\n4. 나는 만약에 포로가 되더라도 아국이나 우방에 불리한 여하한 적의 권고나 우대도 거절하며, 추호도 적을 돕지\n않겠다.\n5. 나는 만약에 포로가 되더라도 기밀을 엄수하고, 전우를 보호하고, 선임자면 후임자를 통솔하고, 후임자면 선임\n자의 명령에 복종하겠다.\n6. 나는 만약 포로가 되어 심문 받더라도 계급, 성명, 군번, 연령을 제외하고는 진술을 회피하며, 아국과 우방에 불\n리한 성명, 그 밖에 여하한 요구에도 응하지 않겠다.\n7. 나는 조국에 신명을 바친 대한민국 군인임을 명심하고 나의 행동에 대한 책임을 지겠다. 나는 조국을 사랑하며\n조국은 나를 보호하고 있음을 확신한다.\n \n\n법제처                                                            4                                                   국가법령정보센터\n부대관리훈령\n 제2장 병영생활\n 제1절 책무',
 '① 불침번은 건물 내ㆍ외를 완벽히 경계하여야 하며, 근무 중 지정된 위치를 떠나거나\n앉거나 담배를 피워서는 아니 된다.\n② 불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, 당직계통의 상관에게 보고하여야 한다.\n③ 불침번은 타인의 취침에 방해가 되지 아니하도록 근무하여야 한다.\n④ 불침번은 근무교대시 인원ㆍ장비 및 상관의 지시사항을 정확하게 인계ㆍ인수하여야 한다.',
 '① 법 제33조에 따른 “증편(增編)”은 해당 군의 총병력이 증가되고 부대가 증설 또는 확장되어 각 계급에\n심한 불균형이 발생한 경우로 한다.\n② 제1항의 경우에 임시계급을 부여할 수 있는 인원은 해당 증편으로 인하여 증가된 인원 범위 내로 한다.\n[전문개정 2012. 1. 31.]',
 '① 각 군 참모총장은 법 제20조에 따른 현역병의 모집을 위하여 매년\n9월 30일까지 그 다음 해의 현역병 복무를 지원하는 사람(이하 “현역병복무지원자”라 한다)을 모집하기 위한 모집\n분야별ㆍ날짜별 인원 등이 포함된 현역병모집 계획서를 작성하고 병무청장에게 송부하여야 한다. 이 경우 각 군 참\n모총장이 그 송부한 내용을 변경하려는 경우에는 모집일 60일 전까지 병무청장에게 그 변경된 내용을 통보하여야\n\n법제처                                                            14                                                       국가법령정보센터\n병역법 시행령\n한다.\n② 병무청장은 제1항에 따라 현역병모집 계획서를 송부받은 경우에는 현역병복무지원자의 전형 및 선발을 위한 모\n집 분야별 지원자격 및 모집일정 등이 포함된 현역병모집 계획서를 작성하고 지방병무청장에게 송부하여야 한다.\n③ 지방병무청장은 제2항에 따라 현역병모집 계획서를 송부받은 경우에는 모집 홍보와 신체검사ㆍ체력검사ㆍ면접\nㆍ필기ㆍ실기 등의 전형 등을 위한 현역병모집 세부계획을 수립하여 시행하여야 한다.\n④ 병무청장 또는 지방병무청장은 현역병복무지원자의 전형을 위하여 해당 분야의 전문지식 및 능력이 있는 사람\n중에서 전형위원을 임명하거나 위촉할 수 있으며, 전형위원에게 예산의 범위에서 수당을 지급할 수 있다.<신설\n2011. 11. 23.>\n⑤ 현역병복무지원자 선발의 기준 및 절차 등에 관하여 필요한 사항은 병무청장이 선발하는 경우에는 병무청장이\n정하여 고시하고, 각 군 참모총장이 선발하는 경우에는 각 군 참모총장이 정하여 고시하여야 한다.<개정 2011. 11.\n23.>\n[전문개정 2009. 12. 7.]',
 '국가공무원(이하 “공무원”이라 한다)에게 지급하는 수당과 실비변상 등(이하 “수당등”이라 한다)의 종\n류, 지급범위, 지급액 및 지급방법에 관한 사항은 다른 법령에 특별한 규정이 있는 경우 외에는 이 영에서 정하는 바\n에 따른다.\n[전문개정 2008. 12. 31.]',
 '① 보수지급기관은 다음 각 호의 어느 하나에 해당하는 경우를 제외하고는 보수에서\n일정 금액을 정기적으로 원천징수, 특별징수 또는 공제(이하 이 조에서 “원천징수등”이라 한다)할 수 없다. <개정\n2013. 1. 9., 2016. 1. 8., 2019. 1. 8., 2020. 3. 10.>\n1. 법령에 따라 원천징수등을 하여야 하는 경우\n2. 「고용보험 및 산업재해보상보험의 보험료징수 등에 관한 법률」 제16조에 따른 고용보험료에 대하여 원천징수등\n을 하는 경우\n3. 법률에 따라 설립된 공제회의 부담금 등에 대하여 원천징수등을 하는 경우\n4. 법원의 재판에 따라 원천징수등을 하여야 하는 경우\n5. 본인이 선택한 기간의 범위에서 서면 제출 또는 전자인사관리시스템(공무원의 인사기록을 데이터베이스화하여\n관리하고 인사 업무를 전자적으로 처리할 수 있는 시스템을 말한다)을 통하여 「회계관계 직원 등의 책임에 관한\n법률」 제2조제1호가목에 따른 지출관(대리지출관, 분임지출관 및 대리분임지출관은 제외한다) 또는 같은 조 제\n2호가목에 따른 지출원(대리지출원, 분임지출원 및 대리분임지출원은 제외한다)에게 동의한 사항에 대하여 원천\n징수등을 하는 경우\n② 제1항에 따른 원천징수등의 방법, 운영 및 그 밖에 필요한 사항은 인사혁신처장이 정한다.<개정 2013. 3. 23.,\n2014. 11. 19.>\n[본조신설 2009. 12. 7.]',
 '국방부장관은 이 법에 따른 급여와 그 밖에 재해보상제도를 적정하게 운영하기 위하여 필요하\n다고 인정할 때에는 각 군 참모총장, 국방부 직할부대장 또는 직할기관장 및 요양기관의 장, 그 밖의 관계자에게 다\n음 각 호의 사항을 요구할 수 있으며, 소속 공무원 또는 기관으로 하여금 장부, 서류 또는 그 밖의 물건을 검사하게\n할 수 있다.\n1. 필요한 보고ㆍ통보\n2. 장부, 서류, 그 밖의 물건의 제시ㆍ제출\n3. 일정한 장소에의 출석과 의견의 진술 또는 설명']

In [33]:
# testset 생성
from ragas.testset import TestsetGenerator
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
# testsetgenerator 는 gpt-5 이후 버전은 사용할 수 없다.
## Langchain의 모델과 Embedding 모델 -> ragas에서 사용할 수 있도록 변환(wrapping)
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))
generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
    llm_context="""
- 군 관련 법령(공무원보수규정, 군인사법, 병역법, 군인연금법 등)에 대해 사람들이 궁금해 할 만한 질문들을 생성한다.
- 특정 조문 번호나 법령명을 명시한 질문과, 주제/상황 기반 질문을 골고루 섞는다.
- 데이터셋은 반드시 한국어로 작성한다.
- 데이터셋은 JSON 문법을 지켜서 작성한다. 특히 구두점은 꼭 지켜야 한다.
- 생성된 내용이나 Document에 JSON문법에 맞지 않는 표현이 있으면 반드시 수정해서 처리한다.
"""
    # 질문/답변을 생성할 때 LLM에게 전달할 system Prompt를 설정
)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_30664\1892202356.py:8: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\Playdata\AppData\Local\Temp\ipykernel_30664\1892202356.py:9: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

In [34]:
testset = generator.generate_with_chunks(
    docs, testset_size=10, # Context 내용 테스트셋 개수(질문 답변 개수)
)

Applying SummaryExtractor: 100%|██████████| 10/10 [00:01<00:00,  5.02it/s]
Applying CustomNodeFilter:   0%|          | 0/10 [00:00<?, ?it/s]Node ecee4a6d-8822-4178-8595-aa7d908c48da does not have a summary. Skipping filtering.
Node 3115e51f-b2a1-4e8e-bc86-9dc0eee29d75 does not have a summary. Skipping filtering.
Node dbd4c96a-06cf-41a3-82da-10868e9ff4a2 does not have a summary. Skipping filtering.
Node 7104e305-0022-4907-bc6b-75f231713c7a does not have a summary. Skipping filtering.
Node 6955aba5-b804-4196-983c-c8ebbb57c6af does not have a summary. Skipping filtering.
Node ae63e9cd-b0ea-4417-9b12-91a17f0fb63f does not have a summary. Skipping filtering.
Node 843d63c4-e67f-431f-aa90-6baafacab13f does not have a summary. Skipping filtering.
Node d282f520-48ff-4e7c-a159-fde1fac2c4de does not have a summary. Skipping filtering.
Node 530b6432-4ae3-4aaa-b113-13eaeefaba9f does not have a summary. Skipping filtering.
Node a4485e34-14f3-437a-ae7b-a068bdafea49 does not have a summary. Skipping filtering.
Applying CustomNodeFilter: 100%|██████████| 10/10 [00:00<00:00, 1626.64it/s]
Applying EmbeddingExtractor: 100%|██████████| 10/10 [00:00<00:00, 12.51it/s]
Applying ThemesExtractor: 100%|██████████| 10/10 [00:15<00:00,  1.60s/it]
Applying NERExtractor: 100%|██████████| 10/10 [00:02<00:00,  3.74it/s]
Applying CosineSimilarityBuilder: 100%|██████████| 1/1 [00:00<00:00, 392.76it/s]
Applying OverlapScoreBuilder: 100%|██████████| 1/1 [00:00<00:00, 664.71it/s]
Skipping multi_hop_abstract_query_synthesizer due to unexpected error: No relationships match the provided condition. Cannot form clusters.
Generating personas: 100%|██████████| 3/3 [00:01<00:00,  2.36it/s]
Generating Scenarios: 100%|██████████| 2/2 [00:09<00:00,  4.68s/it]
Generating Samples: 100%|██████████| 11/11 [00:05<00:00,  2.08it/s]

In [35]:
testset

Testset(samples=[TestsetSample(eval_sample=SingleTurnSample(user_input='대통령령에 따라 사회복무요원 소집이 연기된 사람이 다시 소집될 수 있는 경우는 무엇인가요?', retrieved_contexts=None, reference_contexts=['① 지방병무청장은 사회복무요원 소집 순서가 결정된 사람을 대상으로 복무기관을 정\n하여 사회복무요원을 소집한다. 다만, 제26조제4항에 따라 선발한 사회복무요원은 복무기관과 복무분야를 정하여\n따로 소집할 수 있다. <개정 2013. 6. 4.>\n② 병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령으로 정하는 사람에 대\n하여는 제1항에도 불구하고 지방병무청장으로 하여금 따로 사회복무요원 소집을 하게 할 수 있다.<개정 2013. 6.\n4.>\n③ 제1항과 제2항에 따라 사회복무요원으로 소집된 사람에 대하여는 제55조에 따른 군사교육소집을 하며, 그 군사\n교육소집 기간은 복무기간에 산입한다.<개정 2013. 6. 4., 2016. 5. 29.>\n④ 지방병무청장은 복무기관의 장이 사회복무요원의 임무 부여에 활용할 수 있도록 사회복무요원이 다음 각 호의\n범죄로 인하여 형의 선고를 받은 경우 관련된 정보를 그 사회복무요원이 복무할 복무기관의 장에게 제공할 수 있으\n며, 정보 제공 절차 및 제공되는 정보의 범위는 병무청장이 정한다.<신설 2020. 12. 22., 2024. 1. 9.>\n1. 「아동ㆍ청소년의 성보호에 관한 법률」 제2조제2호, 제3호 및 제3호의2에 따른 범죄\n2. 「개인정보 보호법」 제70조부터 제73조까지에 따른 범죄\n3. 「특정강력범죄의 처벌에 관한 특례법」 제2조의 특정강력범죄\n4. 「형법」 제257조, 제258조, 제258조의2, 제259조부터 제265조까지에 따른 상해와 폭행의 죄, 제283조부터 제\n286조까지에 따른 협박의 죄\n5. 「마약류 관리에 관한 법률」 제58조, 제58조의2, 제59조부터 제64조까지, 제65조의2에 따른 범죄\n[전문개정 2009. 6. 9.]\n[제목개정 2013. 6. 4., 2020. 12. 22.]'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령으로 정하는 사람에 대하여는 제1항에도 불구하고 지방병무청장으로 하여금 따로 사회복무요원 소집을 하게 할 수 있습니다.', rubrics=None, persona_name='Military Incident Reporting Officer', query_style='MISSPELLED', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='지방병무청장의 역할은 무엇인가요?', retrieved_contexts=None, reference_contexts=['① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 현역장교(의무ㆍ법무ㆍ군종ㆍ수의사관후보생을 포함하며, 이하 “의무ㆍ법무ㆍ군종ㆍ수의장교”라 한다)\n및 기본병과 분야의 현역장교(이하 “기본병과장교”라 한다)의 병적에 편입할 사람의 입영기본 계획서를 입영일 40일\n전까지 병무청장 및 해당 군 참모총장에게 송부하여야 하며, 이를 받은 병무청장은 입영 계획서를 작성하여 지방병\n무청장에게, 해당 군 참모총장은 교육 계획서를 작성하여 입영부대의 장에게 각각 송부하여야 한다. <개정 2016. 11.\n29.>\n② 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입을 지원한 사람에 대해서는 국방부장관이 병무청장\n으로부터 그 명단을 받아 현역장교 병적 편입 대상자로 입영할 사람의 명단을 입영일 20일 전까지 병무청장을 거쳐\n지방병무청장에게 송부하여야 한다.<개정 2016. 11. 29.>\n\n법제처                                                            69                                                       국가법령정보센터\n병역법 시행령\n③ 지방병무청장은 제1항에 따른 입영 계획서에 의하여 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과현역장교의 병적\n편입 대상자의 현역입영 통지서를 본인에게 입영일 7일 전까지 송달하여 개별입영하게 하고 입영자 명부와 병적기\n록표를 입영부대의 장에게 송부하여야 한다. 다만, 「의료법」 제77조 및 「전문의의 수련 및 자격 인정 등에 관한 규\n정」 제18조에 따라 보건복지부장관이 실시하는 전문의 자격시험의 합격 여부를 확인할 수 없는 의무ㆍ수의장교 편\n입 대상자에게는 현역입영 통지서를 입영일 전날까지 송달할 수 있다.<개정 2018. 5. 28.>\n④ 입영부대의 장은 제3항에 따라 입영한 사람에 대하여 정해진 군사교육을 실시하고 교육수료 10일 전까지 그 명\n단을 소속 군 참모총장을 거쳐 국방부장관에게 보고하여야 한다.\n⑤ 국방부장관은 제4항에 따른 보고를 받은 경우에는 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적에 편입\n될 사람이 군사교육을 마치는 날의 다음날에 현역장교 병적에 편입하여야 한다.\n[전문개정 2009. 12. 7.]'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='지방병무청장은 입영 계획서에 따라 현역입영 통지서를 입영일 7일 전까지 대상자에게 송달하고, 입영자 명부와 병적기록표를 입영부대의 장에게 송부해야 합니다. 다만, 전문의 자격시험 합격 여부를 확인할 수 없는 경우에는 입영일 전날까지 통지서를 송달할 수 있습니다.', rubrics=None, persona_name='Military Incident Reporting Officer', query_style='WEB_SEARCH_LIKE', query_length='SHORT'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='군사경찰부대 뭐하는데, 사고나면 군사경찰부대가 어떻게 해야돼요, 그리고 사고속보는 군사경찰계통으로 보고한다는데 그거 무슨 뜻인지 설명해줘요.', retrieved_contexts=None, reference_contexts=['① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각 호와 같다. 다만 성희롱ㆍ성폭력\n은 각 군 본부 성고충예방대응센터장(국방부 성폭력예방대응담당관)에게 보고하여야 하며, 각 군 본부 성고충예\n방대응센터장은 국방부 성폭력예방대응담당관에게 보고하여야 한다.\n1. 지휘보고 : 국방부 직할부대장ㆍ기관장 및 각 군 참모총장은 별표 3의 ‘극히 중한 사고’에 해당되는 사고가 있\n을 때에는 인지 즉시 장관에게 지휘보고 하여야 하며, 참모계통(군인권개선추진단, 관련부서)으로도 보고하여\n야 한다. 다만 성폭력의 경우 영관급 이상(4급 이상 군무원)ㆍ군 수사기관ㆍ미성년자가 연루되거나 언론보도\n(예상) 성폭력 발생 시에는 각 군 참모총장이(국방부 직할부대ㆍ기관은 국방부 성폭력예방대응담당관이) 장관\n에게 보고하여야 한다.\n2. 참모보고 : 지휘보고 대상인 극히 중한 사고나 참모보고 대상인 별표 3의 ‘중한 사고’ 발생시, 언론보도 사고 발\n생시에는 국방부 직할부대(기관) 인사처와 각 군 인사참모부는 제반사고에 대한 사항을 최초ㆍ중간ㆍ최종보고\n로 구분하여 국방부 차관실(군인권개선추진단)과 관련부서에 참모계통으로 보고하여야 한다.\n3. 참고보고 :「지휘보고」및「참모보고」에 포함되지 않는 기타 경미한 사고에 대해서는 국방부 차관실(군인권개선\n추진단)과 관련부서 계통으로 보고하여야 한다.\n4. 상황보고 : 군사지휘본부 지휘통제실장은 사고발생 상황을 접수한때에는 차관실(군인권개선추진단)과 제2항\n에 규정된 관련부서의 장에게 보고하여야 한다.\n5. 사고속보 : 사고속보는 제262조에 따라 군사경찰계통으로 보고한다.\n② 사고처리 주관부서는 별표 4와 같으며, 사고발생시 보고 및 처리는 사안에 따라 참모기능별로 유관부서와 협\n조하여 조치하고, 사고 발생시 당사자 또는 당사자로부터 보고를 받은 사람은 관할 군사경찰부대에 인지 즉시 신\n고하여야 한다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='사고가 발생하면 사고속보는 제262조에 따라 군사경찰계통으로 보고해야 하고, 사고 발생시 당사자나 보고받은 사람은 관할 군사경찰부대에 인지 즉시 신고해야 한다고 나와 있습니다.', rubrics=None, persona_name='Military Personnel Administrator', query_style='POOR_GRAMMAR', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='국가법령정보센터에서 군 복무 중인 군인과 군무원이 반드시 지켜야 하는 맹세와 관련된 법령이나 규정을 어떻게 확인할 수 있나요?', retrieved_contexts=None, reference_contexts=['군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세하고, 사명에 입\n각하여 전투 중 또는 포로가 되었을 경우에도 이를 지켜야한다.\n1. 나는 대한민국 군인(군무원)이다. 국가와 민족을 위하여 신명을 바치겠다.\n2. 나는 죽어도 항복하지 않겠다. 나는 전력을 다하여 끝까지 싸우겠다.\n3. 나는 만약에 포로가 되더라도 계속 항거하고 전력을 다하여 탈출하며, 전우의 탈출을 돕겠다.\n4. 나는 만약에 포로가 되더라도 아국이나 우방에 불리한 여하한 적의 권고나 우대도 거절하며, 추호도 적을 돕지\n않겠다.\n5. 나는 만약에 포로가 되더라도 기밀을 엄수하고, 전우를 보호하고, 선임자면 후임자를 통솔하고, 후임자면 선임\n자의 명령에 복종하겠다.\n6. 나는 만약 포로가 되어 심문 받더라도 계급, 성명, 군번, 연령을 제외하고는 진술을 회피하며, 아국과 우방에 불\n리한 성명, 그 밖에 여하한 요구에도 응하지 않겠다.\n7. 나는 조국에 신명을 바친 대한민국 군인임을 명심하고 나의 행동에 대한 책임을 지겠다. 나는 조국을 사랑하며\n조국은 나를 보호하고 있음을 확신한다.\n \n\n법제처                                                            4                                                   국가법령정보센터\n부대관리훈령\n 제2장 병영생활\n 제1절 책무'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='국가법령정보센터에서는 군에 복무 중인 군인과 근무 중인 군무원이 국가에 대하여 맹세해야 하는 내용과, 전투 중 또는 포로가 되었을 경우에도 이를 지켜야 한다는 규정, 그리고 부대관리훈령 등 관련 법령 및 규정을 확인할 수 있습니다.', rubrics=None, persona_name='Military Incident Reporting Officer', query_style='WEB_SEARCH_LIKE', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='불침번이 근무 중 이상이 있을 때 당직계통에 어떻게 보고해야 합니까?', retrieved_contexts=None, reference_contexts=['① 불침번은 건물 내ㆍ외를 완벽히 경계하여야 하며, 근무 중 지정된 위치를 떠나거나\n앉거나 담배를 피워서는 아니 된다.\n② 불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, 당직계통의 상관에게 보고하여야 한다.\n③ 불침번은 타인의 취침에 방해가 되지 아니하도록 근무하여야 한다.\n④ 불침번은 근무교대시 인원ㆍ장비 및 상관의 지시사항을 정확하게 인계ㆍ인수하여야 한다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, 당직계통의 상관에게 보고하여야 합니다.', rubrics=None, persona_name='Military Personnel Administrator', query_style='PERFECT_GRAMMAR', query_length='SHORT'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='국방부장관 입영계획서 언제 보내야되? 그리고 급여나 재해보상 관련해서 국방부장관이 할 수 있는 일은 뭐야?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 현역장교(의무ㆍ법무ㆍ군종ㆍ수의사관후보생을 포함하며, 이하 “의무ㆍ법무ㆍ군종ㆍ수의장교”라 한다)\n및 기본병과 분야의 현역장교(이하 “기본병과장교”라 한다)의 병적에 편입할 사람의 입영기본 계획서를 입영일 40일\n전까지 병무청장 및 해당 군 참모총장에게 송부하여야 하며, 이를 받은 병무청장은 입영 계획서를 작성하여 지방병\n무청장에게, 해당 군 참모총장은 교육 계획서를 작성하여 입영부대의 장에게 각각 송부하여야 한다. <개정 2016. 11.\n29.>\n② 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입을 지원한 사람에 대해서는 국방부장관이 병무청장\n으로부터 그 명단을 받아 현역장교 병적 편입 대상자로 입영할 사람의 명단을 입영일 20일 전까지 병무청장을 거쳐\n지방병무청장에게 송부하여야 한다.<개정 2016. 11. 29.>\n\n법제처                                                            69                                                       국가법령정보센터\n병역법 시행령\n③ 지방병무청장은 제1항에 따른 입영 계획서에 의하여 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과현역장교의 병적\n편입 대상자의 현역입영 통지서를 본인에게 입영일 7일 전까지 송달하여 개별입영하게 하고 입영자 명부와 병적기\n록표를 입영부대의 장에게 송부하여야 한다. 다만, 「의료법」 제77조 및 「전문의의 수련 및 자격 인정 등에 관한 규\n정」 제18조에 따라 보건복지부장관이 실시하는 전문의 자격시험의 합격 여부를 확인할 수 없는 의무ㆍ수의장교 편\n입 대상자에게는 현역입영 통지서를 입영일 전날까지 송달할 수 있다.<개정 2018. 5. 28.>\n④ 입영부대의 장은 제3항에 따라 입영한 사람에 대하여 정해진 군사교육을 실시하고 교육수료 10일 전까지 그 명\n단을 소속 군 참모총장을 거쳐 국방부장관에게 보고하여야 한다.\n⑤ 국방부장관은 제4항에 따른 보고를 받은 경우에는 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적에 편입\n될 사람이 군사교육을 마치는 날의 다음날에 현역장교 병적에 편입하여야 한다.\n[전문개정 2009. 12. 7.]', '<2-hop>\n\n국방부장관은 이 법에 따른 급여와 그 밖에 재해보상제도를 적정하게 운영하기 위하여 필요하\n다고 인정할 때에는 각 군 참모총장, 국방부 직할부대장 또는 직할기관장 및 요양기관의 장, 그 밖의 관계자에게 다\n음 각 호의 사항을 요구할 수 있으며, 소속 공무원 또는 기관으로 하여금 장부, 서류 또는 그 밖의 물건을 검사하게\n할 수 있다.\n1. 필요한 보고ㆍ통보\n2. 장부, 서류, 그 밖의 물건의 제시ㆍ제출\n3. 일정한 장소에의 출석과 의견의 진술 또는 설명'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='국방부장관은 입영기본 계획서를 입영일 40일 전까지 병무청장 및 해당 군 참모총장에게 송부해야 합니다. 그리고 급여나 재해보상제도 운영을 위해 필요하다고 인정할 때에는 각 군 참모총장 등에게 필요한 보고나 통보, 장부나 서류의 제출, 일정한 장소에의 출석과 의견 진술 등을 요구할 수 있습니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='국방부장관이 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여 입영 및 군사교육 과정에서 수행해야 하는 주요 역할과, 급여 및 재해보상제도 운영을 위해 각 군 참모총장 등에게 요구할 수 있는 사항은 무엇인가?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 현역장교(의무ㆍ법무ㆍ군종ㆍ수의사관후보생을 포함하며, 이하 “의무ㆍ법무ㆍ군종ㆍ수의장교”라 한다)\n및 기본병과 분야의 현역장교(이하 “기본병과장교”라 한다)의 병적에 편입할 사람의 입영기본 계획서를 입영일 40일\n전까지 병무청장 및 해당 군 참모총장에게 송부하여야 하며, 이를 받은 병무청장은 입영 계획서를 작성하여 지방병\n무청장에게, 해당 군 참모총장은 교육 계획서를 작성하여 입영부대의 장에게 각각 송부하여야 한다. <개정 2016. 11.\n29.>\n② 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입을 지원한 사람에 대해서는 국방부장관이 병무청장\n으로부터 그 명단을 받아 현역장교 병적 편입 대상자로 입영할 사람의 명단을 입영일 20일 전까지 병무청장을 거쳐\n지방병무청장에게 송부하여야 한다.<개정 2016. 11. 29.>\n\n법제처                                                            69                                                       국가법령정보센터\n병역법 시행령\n③ 지방병무청장은 제1항에 따른 입영 계획서에 의하여 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과현역장교의 병적\n편입 대상자의 현역입영 통지서를 본인에게 입영일 7일 전까지 송달하여 개별입영하게 하고 입영자 명부와 병적기\n록표를 입영부대의 장에게 송부하여야 한다. 다만, 「의료법」 제77조 및 「전문의의 수련 및 자격 인정 등에 관한 규\n정」 제18조에 따라 보건복지부장관이 실시하는 전문의 자격시험의 합격 여부를 확인할 수 없는 의무ㆍ수의장교 편\n입 대상자에게는 현역입영 통지서를 입영일 전날까지 송달할 수 있다.<개정 2018. 5. 28.>\n④ 입영부대의 장은 제3항에 따라 입영한 사람에 대하여 정해진 군사교육을 실시하고 교육수료 10일 전까지 그 명\n단을 소속 군 참모총장을 거쳐 국방부장관에게 보고하여야 한다.\n⑤ 국방부장관은 제4항에 따른 보고를 받은 경우에는 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적에 편입\n될 사람이 군사교육을 마치는 날의 다음날에 현역장교 병적에 편입하여야 한다.\n[전문개정 2009. 12. 7.]', '<2-hop>\n\n국방부장관은 이 법에 따른 급여와 그 밖에 재해보상제도를 적정하게 운영하기 위하여 필요하\n다고 인정할 때에는 각 군 참모총장, 국방부 직할부대장 또는 직할기관장 및 요양기관의 장, 그 밖의 관계자에게 다\n음 각 호의 사항을 요구할 수 있으며, 소속 공무원 또는 기관으로 하여금 장부, 서류 또는 그 밖의 물건을 검사하게\n할 수 있다.\n1. 필요한 보고ㆍ통보\n2. 장부, 서류, 그 밖의 물건의 제시ㆍ제출\n3. 일정한 장소에의 출석과 의견의 진술 또는 설명'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='국방부장관은 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여, 입영기본 계획서를 입영일 40일 전까지 병무청장 및 해당 군 참모총장에게 송부하고, 입영 대상자 명단을 입영일 20일 전까지 병무청장을 거쳐 지방병무청장에게 송부해야 합니다. 또한, 군사교육을 마친 사람을 현역장교 병적에 편입하는 역할도 수행합니다. 한편, 국방부장관은 급여와 재해보상제도 운영을 위해 필요하다고 인정할 때 각 군 참모총장, 국방부 직할부대장 등에게 필요한 보고ㆍ통보, 장부 및 서류의 제출, 일정한 장소 출석과 의견 진술 등을 요구할 수 있습니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='국방부 관련 규정에 따라 성희롱 또는 성폭력 사고가 발생했을 때, 보고의 유형과 보고계통은 어떻게 다르며, 각 군 본부 성고충예방대응센터장과 국방부 성폭력예방대응담당관의 역할은 무엇인가요? 또한, 극히 중한 사고와 언론보도(예상) 성폭력 사고의 경우에는 어떤 절차로 국방부 장관에게 보고가 이루어지나요?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각 호와 같다. 다만 성희롱ㆍ성폭력\n은 각 군 본부 성고충예방대응센터장(국방부 성폭력예방대응담당관)에게 보고하여야 하며, 각 군 본부 성고충예\n방대응센터장은 국방부 성폭력예방대응담당관에게 보고하여야 한다.\n1. 지휘보고 : 국방부 직할부대장ㆍ기관장 및 각 군 참모총장은 별표 3의 ‘극히 중한 사고’에 해당되는 사고가 있\n을 때에는 인지 즉시 장관에게 지휘보고 하여야 하며, 참모계통(군인권개선추진단, 관련부서)으로도 보고하여\n야 한다. 다만 성폭력의 경우 영관급 이상(4급 이상 군무원)ㆍ군 수사기관ㆍ미성년자가 연루되거나 언론보도\n(예상) 성폭력 발생 시에는 각 군 참모총장이(국방부 직할부대ㆍ기관은 국방부 성폭력예방대응담당관이) 장관\n에게 보고하여야 한다.\n2. 참모보고 : 지휘보고 대상인 극히 중한 사고나 참모보고 대상인 별표 3의 ‘중한 사고’ 발생시, 언론보도 사고 발\n생시에는 국방부 직할부대(기관) 인사처와 각 군 인사참모부는 제반사고에 대한 사항을 최초ㆍ중간ㆍ최종보고\n로 구분하여 국방부 차관실(군인권개선추진단)과 관련부서에 참모계통으로 보고하여야 한다.\n3. 참고보고 :「지휘보고」및「참모보고」에 포함되지 않는 기타 경미한 사고에 대해서는 국방부 차관실(군인권개선\n추진단)과 관련부서 계통으로 보고하여야 한다.\n4. 상황보고 : 군사지휘본부 지휘통제실장은 사고발생 상황을 접수한때에는 차관실(군인권개선추진단)과 제2항\n에 규정된 관련부서의 장에게 보고하여야 한다.\n5. 사고속보 : 사고속보는 제262조에 따라 군사경찰계통으로 보고한다.\n② 사고처리 주관부서는 별표 4와 같으며, 사고발생시 보고 및 처리는 사안에 따라 참모기능별로 유관부서와 협\n조하여 조치하고, 사고 발생시 당사자 또는 당사자로부터 보고를 받은 사람은 관할 군사경찰부대에 인지 즉시 신\n고하여야 한다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방대응센터장(국방부 성폭력예방대응담당관)에게 보고해야 하며, 각 군 본부 성고충예방대응센터장은 국방부 성폭력예방대응담당관에게 보고해야 합니다. 극히 중한 사고가 발생하면 국방부 직할부대장, 기관장 및 각 군 참모총장은 인지 즉시 장관에게 지휘보고를 해야 하며, 참모계통(군인권개선추진단, 관련부서)으로도 보고해야 합니다. 특히 성폭력의 경우 영관급 이상, 군 수사기관, 미성년자 연루, 언론보도(예상) 성폭력 발생 시에는 각 군 참모총장이(국방부 직할부대ㆍ기관은 국방부 성폭력예방대응담당관이) 장관에게 보고해야 합니다. 이처럼 성희롱ㆍ성폭력 사고는 일반 사고와 달리 별도의 보고계통과 담당자가 지정되어 있으며, 중대한 사고나 언론보도 예상 시에는 신속하게 국방부 장관에게 보고가 이루어집니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='국방부와 각 군 본부에서 성희롱 또는 성폭력 사고가 발생했을 때, 사고 보고의 유형과 보고 계통은 어떻게 다르며, 국방부 성폭력예방대응담당관의 역할은 무엇인가?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각 호와 같다. 다만 성희롱ㆍ성폭력\n은 각 군 본부 성고충예방대응센터장(국방부 성폭력예방대응담당관)에게 보고하여야 하며, 각 군 본부 성고충예\n방대응센터장은 국방부 성폭력예방대응담당관에게 보고하여야 한다.\n1. 지휘보고 : 국방부 직할부대장ㆍ기관장 및 각 군 참모총장은 별표 3의 ‘극히 중한 사고’에 해당되는 사고가 있\n을 때에는 인지 즉시 장관에게 지휘보고 하여야 하며, 참모계통(군인권개선추진단, 관련부서)으로도 보고하여\n야 한다. 다만 성폭력의 경우 영관급 이상(4급 이상 군무원)ㆍ군 수사기관ㆍ미성년자가 연루되거나 언론보도\n(예상) 성폭력 발생 시에는 각 군 참모총장이(국방부 직할부대ㆍ기관은 국방부 성폭력예방대응담당관이) 장관\n에게 보고하여야 한다.\n2. 참모보고 : 지휘보고 대상인 극히 중한 사고나 참모보고 대상인 별표 3의 ‘중한 사고’ 발생시, 언론보도 사고 발\n생시에는 국방부 직할부대(기관) 인사처와 각 군 인사참모부는 제반사고에 대한 사항을 최초ㆍ중간ㆍ최종보고\n로 구분하여 국방부 차관실(군인권개선추진단)과 관련부서에 참모계통으로 보고하여야 한다.\n3. 참고보고 :「지휘보고」및「참모보고」에 포함되지 않는 기타 경미한 사고에 대해서는 국방부 차관실(군인권개선\n추진단)과 관련부서 계통으로 보고하여야 한다.\n4. 상황보고 : 군사지휘본부 지휘통제실장은 사고발생 상황을 접수한때에는 차관실(군인권개선추진단)과 제2항\n에 규정된 관련부서의 장에게 보고하여야 한다.\n5. 사고속보 : 사고속보는 제262조에 따라 군사경찰계통으로 보고한다.\n② 사고처리 주관부서는 별표 4와 같으며, 사고발생시 보고 및 처리는 사안에 따라 참모기능별로 유관부서와 협\n조하여 조치하고, 사고 발생시 당사자 또는 당사자로부터 보고를 받은 사람은 관할 군사경찰부대에 인지 즉시 신\n고하여야 한다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방대응센터장(국방부 성폭력예방대응담당관)에게 반드시 보고해야 하며, 각 군 본부 성고충예방대응센터장은 다시 국방부 성폭력예방대응담당관에게 보고해야 합니다. 일반적인 사고의 경우, 극히 중한 사고는 국방부 직할부대장ㆍ기관장 및 각 군 참모총장이 장관에게 지휘보고를 하고, 참모계통(군인권개선추진단, 관련부서)으로도 보고합니다. 그러나 성폭력의 경우에는 영관급 이상, 군 수사기관, 미성년자 연루, 언론보도(예상) 등 특수 상황에서는 각 군 참모총장(국방부 직할부대ㆍ기관은 국방부 성폭력예방대응담당관)이 장관에게 보고해야 합니다. 이처럼 성희롱ㆍ성폭력 사고는 국방부 성폭력예방대응담당관이 보고 체계의 중심 역할을 하며, 사고 발생 시 신속하고 체계적으로 상급 기관에 보고가 이루어지도록 담당합니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='법제처에서 정한 규정에 따라 군인이나 군무원이 포로가 되었을 때 지켜야 하는 맹세 내용하고, 현역병 모집 계획서 작성 및 전형 절차가 어떻게 진행되는지 설명해줘. 그리고 이 과정에서 법제처가 어떤 역할을 하는지도 같이 말해줘.', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세하고, 사명에 입\n각하여 전투 중 또는 포로가 되었을 경우에도 이를 지켜야한다.\n1. 나는 대한민국 군인(군무원)이다. 국가와 민족을 위하여 신명을 바치겠다.\n2. 나는 죽어도 항복하지 않겠다. 나는 전력을 다하여 끝까지 싸우겠다.\n3. 나는 만약에 포로가 되더라도 계속 항거하고 전력을 다하여 탈출하며, 전우의 탈출을 돕겠다.\n4. 나는 만약에 포로가 되더라도 아국이나 우방에 불리한 여하한 적의 권고나 우대도 거절하며, 추호도 적을 돕지\n않겠다.\n5. 나는 만약에 포로가 되더라도 기밀을 엄수하고, 전우를 보호하고, 선임자면 후임자를 통솔하고, 후임자면 선임\n자의 명령에 복종하겠다.\n6. 나는 만약 포로가 되어 심문 받더라도 계급, 성명, 군번, 연령을 제외하고는 진술을 회피하며, 아국과 우방에 불\n리한 성명, 그 밖에 여하한 요구에도 응하지 않겠다.\n7. 나는 조국에 신명을 바친 대한민국 군인임을 명심하고 나의 행동에 대한 책임을 지겠다. 나는 조국을 사랑하며\n조국은 나를 보호하고 있음을 확신한다.\n \n\n법제처                                                            4                                                   국가법령정보센터\n부대관리훈령\n 제2장 병영생활\n 제1절 책무', '<2-hop>\n\n① 각 군 참모총장은 법 제20조에 따른 현역병의 모집을 위하여 매년\n9월 30일까지 그 다음 해의 현역병 복무를 지원하는 사람(이하 “현역병복무지원자”라 한다)을 모집하기 위한 모집\n분야별ㆍ날짜별 인원 등이 포함된 현역병모집 계획서를 작성하고 병무청장에게 송부하여야 한다. 이 경우 각 군 참\n모총장이 그 송부한 내용을 변경하려는 경우에는 모집일 60일 전까지 병무청장에게 그 변경된 내용을 통보하여야\n\n법제처                                                            14                                                       국가법령정보센터\n병역법 시행령\n한다.\n② 병무청장은 제1항에 따라 현역병모집 계획서를 송부받은 경우에는 현역병복무지원자의 전형 및 선발을 위한 모\n집 분야별 지원자격 및 모집일정 등이 포함된 현역병모집 계획서를 작성하고 지방병무청장에게 송부하여야 한다.\n③ 지방병무청장은 제2항에 따라 현역병모집 계획서를 송부받은 경우에는 모집 홍보와 신체검사ㆍ체력검사ㆍ면접\nㆍ필기ㆍ실기 등의 전형 등을 위한 현역병모집 세부계획을 수립하여 시행하여야 한다.\n④ 병무청장 또는 지방병무청장은 현역병복무지원자의 전형을 위하여 해당 분야의 전문지식 및 능력이 있는 사람\n중에서 전형위원을 임명하거나 위촉할 수 있으며, 전형위원에게 예산의 범위에서 수당을 지급할 수 있다.<신설\n2011. 11. 23.>\n⑤ 현역병복무지원자 선발의 기준 및 절차 등에 관하여 필요한 사항은 병무청장이 선발하는 경우에는 병무청장이\n정하여 고시하고, 각 군 참모총장이 선발하는 경우에는 각 군 참모총장이 정하여 고시하여야 한다.<개정 2011. 11.\n23.>\n[전문개정 2009. 12. 7.]'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='군에 복무 중인 군인이나 근무 중인 군무원은 법제처에서 정한 규정에 따라 국가와 민족을 위해 신명을 바치겠다고 맹세하고, 전투 중이나 포로가 되었을 때에도 죽어도 항복하지 않겠다고 다짐해야 해. 포로가 되더라도 계속 항거하고 탈출을 시도하며, 적의 권고나 우대도 거절하고, 기밀을 엄수하고 전우를 보호해야 해. 그리고 심문을 받더라도 계급, 성명, 군번, 연령 외에는 진술을 회피해야 하고, 조국에 신명을 바친 군인임을 명심해야 해. 현역병 모집과 관련해서는 각 군 참모총장이 매년 9월 30일까지 다음 해 현역병 복무 지원자를 모집하기 위한 계획서를 작성해서 병무청장에게 송부해야 하고, 병무청장은 이 계획서를 받아서 전형 및 선발을 위한 모집 분야별 지원자격과 모집일정 등이 포함된 계획서를 작성해서 지방병무청장에게 보내. 지방병무청장은 모집 홍보, 신체검사, 체력검사, 면접, 필기, 실기 등 전형을 위한 세부계획을 수립해서 시행해야 해. 전형위원도 임명할 수 있고, 선발 기준과 절차는 병무청장이나 각 군 참모총장이 정해서 고시해야 해. 이 모든 과정과 규정은 법제처에서 정한 법령과 시행령에 따라 이루어지기 때문에, 법제처는 군인의 맹세와 현역병 모집 절차의 근거가 되는 법적 기준을 제공하는 중요한 역할을 해.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='국가법령정보센터에 따르면, 군 복무 중 포로가 되었을 때 군인이 지켜야 할 행동 원칙과, 현역병 모집 및 선발 절차에 관한 법적 근거는 각각 무엇이며, 이 두 가지가 군인의 책무와 병역법 시행령에서 어떻게 규정되어 있는지 설명하시오.', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세하고, 사명에 입\n각하여 전투 중 또는 포로가 되었을 경우에도 이를 지켜야한다.\n1. 나는 대한민국 군인(군무원)이다. 국가와 민족을 위하여 신명을 바치겠다.\n2. 나는 죽어도 항복하지 않겠다. 나는 전력을 다하여 끝까지 싸우겠다.\n3. 나는 만약에 포로가 되더라도 계속 항거하고 전력을 다하여 탈출하며, 전우의 탈출을 돕겠다.\n4. 나는 만약에 포로가 되더라도 아국이나 우방에 불리한 여하한 적의 권고나 우대도 거절하며, 추호도 적을 돕지\n않겠다.\n5. 나는 만약에 포로가 되더라도 기밀을 엄수하고, 전우를 보호하고, 선임자면 후임자를 통솔하고, 후임자면 선임\n자의 명령에 복종하겠다.\n6. 나는 만약 포로가 되어 심문 받더라도 계급, 성명, 군번, 연령을 제외하고는 진술을 회피하며, 아국과 우방에 불\n리한 성명, 그 밖에 여하한 요구에도 응하지 않겠다.\n7. 나는 조국에 신명을 바친 대한민국 군인임을 명심하고 나의 행동에 대한 책임을 지겠다. 나는 조국을 사랑하며\n조국은 나를 보호하고 있음을 확신한다.\n \n\n법제처                                                            4                                                   국가법령정보센터\n부대관리훈령\n 제2장 병영생활\n 제1절 책무', '<2-hop>\n\n① 각 군 참모총장은 법 제20조에 따른 현역병의 모집을 위하여 매년\n9월 30일까지 그 다음 해의 현역병 복무를 지원하는 사람(이하 “현역병복무지원자”라 한다)을 모집하기 위한 모집\n분야별ㆍ날짜별 인원 등이 포함된 현역병모집 계획서를 작성하고 병무청장에게 송부하여야 한다. 이 경우 각 군 참\n모총장이 그 송부한 내용을 변경하려는 경우에는 모집일 60일 전까지 병무청장에게 그 변경된 내용을 통보하여야\n\n법제처                                                            14                                                       국가법령정보센터\n병역법 시행령\n한다.\n② 병무청장은 제1항에 따라 현역병모집 계획서를 송부받은 경우에는 현역병복무지원자의 전형 및 선발을 위한 모\n집 분야별 지원자격 및 모집일정 등이 포함된 현역병모집 계획서를 작성하고 지방병무청장에게 송부하여야 한다.\n③ 지방병무청장은 제2항에 따라 현역병모집 계획서를 송부받은 경우에는 모집 홍보와 신체검사ㆍ체력검사ㆍ면접\nㆍ필기ㆍ실기 등의 전형 등을 위한 현역병모집 세부계획을 수립하여 시행하여야 한다.\n④ 병무청장 또는 지방병무청장은 현역병복무지원자의 전형을 위하여 해당 분야의 전문지식 및 능력이 있는 사람\n중에서 전형위원을 임명하거나 위촉할 수 있으며, 전형위원에게 예산의 범위에서 수당을 지급할 수 있다.<신설\n2011. 11. 23.>\n⑤ 현역병복무지원자 선발의 기준 및 절차 등에 관하여 필요한 사항은 병무청장이 선발하는 경우에는 병무청장이\n정하여 고시하고, 각 군 참모총장이 선발하는 경우에는 각 군 참모총장이 정하여 고시하여야 한다.<개정 2011. 11.\n23.>\n[전문개정 2009. 12. 7.]'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='<1-hop>에 따르면, 군 복무 중인 군인이나 군무원은 국가에 대한 맹세에 따라 포로가 되었을 경우에도 계속 항거하고 탈출을 시도하며, 적의 권고나 우대를 거절하고, 기밀을 엄수하며, 전우를 보호하고, 계급, 성명, 군번, 연령 외에는 진술을 회피해야 하는 등 엄격한 행동 원칙을 지켜야 합니다. <2-hop>에서는 병역법 시행령에 따라 각 군 참모총장이 매년 현역병 모집 계획서를 작성하여 병무청장에게 송부하고, 병무청장은 이를 바탕으로 전형 및 선발을 위한 계획을 수립하며, 지방병무청장은 세부계획을 시행하도록 규정하고 있습니다. 이처럼 국가법령정보센터에 명시된 군인의 책무와 병역법 시행령은 각각 군 복무 중 행동 원칙과 현역병 모집 및 선발 절차에 대한 법적 근거를 제공하고 있습니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer')])

In [36]:
sample1 = testset.samples[0].eval_sample
print("사용자질문:", sample1.user_input)
print("Context:", sample1.reference_contexts)
print("생성된 답변(정답):", sample1.reference)
print("평가대상 RAG의 답변:", sample1.response)
print("평가대상 RAG가 검색한 Context:", sample1.retrieved_contexts)

사용자질문: 대통령령에 따라 사회복무요원 소집이 연기된 사람이 다시 소집될 수 있는 경우는 무엇인가요?
Context: ['① 지방병무청장은 사회복무요원 소집 순서가 결정된 사람을 대상으로 복무기관을 정\n하여 사회복무요원을 소집한다. 다만, 제26조제4항에 따라 선발한 사회복무요원은 복무기관과 복무분야를 정하여\n따로 소집할 수 있다. <개정 2013. 6. 4.>\n② 병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령으로 정하는 사람에 대\n하여는 제1항에도 불구하고 지방병무청장으로 하여금 따로 사회복무요원 소집을 하게 할 수 있다.<개정 2013. 6.\n4.>\n③ 제1항과 제2항에 따라 사회복무요원으로 소집된 사람에 대하여는 제55조에 따른 군사교육소집을 하며, 그 군사\n교육소집 기간은 복무기간에 산입한다.<개정 2013. 6. 4., 2016. 5. 29.>\n④ 지방병무청장은 복무기관의 장이 사회복무요원의 임무 부여에 활용할 수 있도록 사회복무요원이 다음 각 호의\n범죄로 인하여 형의 선고를 받은 경우 관련된 정보를 그 사회복무요원이 복무할 복무기관의 장에게 제공할 수 있으\n며, 정보 제공 절차 및 제공되는 정보의 범위는 병무청장이 정한다.<신설 2020. 12. 22., 2024. 1. 9.>\n1. 「아동ㆍ청소년의 성보호에 관한 법률」 제2조제2호, 제3호 및 제3호의2에 따른 범죄\n2. 「개인정보 보호법」 제70조부터 제73조까지에 따른 범죄\n3. 「특정강력범죄의 처벌에 관한 특례법」 제2조의 특정강력범죄\n4. 「형법」 제257조, 제258조, 제258조의2, 제259조부터 제265조까지에 따른 상해와 폭행의 죄, 제283조부터 제\n286조까지에 따른 협박의 죄\n5. 「마약류 관리에 관한 법률」 제58조, 제58조의2, 제59조부터 제64조까지, 제65조의2에 따른 범죄\n[전문개정 2009. 6. 9.]\n[제목개정 2013. 6. 4., 2020. 12. 22.]']
생성된 답변(정답): 병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령으로 정하는 사람에 대하여는 제1항에도 불구하고 지방병무청장으로 하여금 따로 사회복무요원 소집을 하게 할 수 있습니다.
평가대상 RAG의 답변: None
평가대상 RAG가 검색한 Context: None

In [ ]:
# 생성된 Testset을 Pandas DataFrame으로 변환
eval_df = testset.to_pandas()

# import os

# SAVE_DIR = r"C:\Users\Playdata\SKN\SKN31-3rd-2Team\eval_results"
# os.makedirs(SAVE_DIR, exist_ok=True)

# eval_df["source"] = "neo4j"  # 나중에 출처별로 점수 나눠보기 위함
# eval_df.to_pickle(os.path.join(SAVE_DIR, "eval_testset_neo4j.pkl"))
# # CSV는 reference_contexts가 list라서 저장 시 깨짐 -> pickle 사용

In [38]:
eval_df.shape

(11, 8)

In [39]:
eval_df

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name,source
0,대통령령에 따라 사회복무요원 소집이 연기된 사람이 다시 소집될 수 있는 경우는 무엇...,[① 지방병무청장은 사회복무요원 소집 순서가 결정된 사람을 대상으로 복무기관을 정\...,병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령...,Military Incident Reporting Officer,MISSPELLED,LONG,single_hop_specific_query_synthesizer,qdrant
1,지방병무청장의 역할은 무엇인가요?,[① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 ...,지방병무청장은 입영 계획서에 따라 현역입영 통지서를 입영일 7일 전까지 대상자에게 ...,Military Incident Reporting Officer,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer,qdrant
2,"군사경찰부대 뭐하는데, 사고나면 군사경찰부대가 어떻게 해야돼요, 그리고 사고속보는 ...",[① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각 호와 같다. 다만 ...,"사고가 발생하면 사고속보는 제262조에 따라 군사경찰계통으로 보고해야 하고, 사고 ...",Military Personnel Administrator,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer,qdrant
3,국가법령정보센터에서 군 복무 중인 군인과 군무원이 반드시 지켜야 하는 맹세와 관련된...,"[군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세...",국가법령정보센터에서는 군에 복무 중인 군인과 근무 중인 군무원이 국가에 대하여 맹세...,Military Incident Reporting Officer,WEB_SEARCH_LIKE,LONG,single_hop_specific_query_synthesizer,qdrant
4,불침번이 근무 중 이상이 있을 때 당직계통에 어떻게 보고해야 합니까?,"[① 불침번은 건물 내ㆍ외를 완벽히 경계하여야 하며, 근무 중 지정된 위치를 떠나거...","불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, 당직계통의 상관에게 보고하...",Military Personnel Administrator,PERFECT_GRAMMAR,SHORT,single_hop_specific_query_synthesizer,qdrant
5,국방부장관 입영계획서 언제 보내야되? 그리고 급여나 재해보상 관련해서 국방부장관이 ...,[<1-hop>\n\n① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군...,국방부장관은 입영기본 계획서를 입영일 40일 전까지 병무청장 및 해당 군 참모총장에...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant
6,국방부장관이 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여 입영 ...,[<1-hop>\n\n① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군...,"국방부장관은 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여, 입영...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant
7,"국방부 관련 규정에 따라 성희롱 또는 성폭력 사고가 발생했을 때, 보고의 유형과 보...",[<1-hop>\n\n① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각...,성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant
8,"국방부와 각 군 본부에서 성희롱 또는 성폭력 사고가 발생했을 때, 사고 보고의 유형...",[<1-hop>\n\n① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각...,성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant
9,법제처에서 정한 규정에 따라 군인이나 군무원이 포로가 되었을 때 지켜야 하는 맹세 ...,"[<1-hop>\n\n군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음...",군에 복무 중인 군인이나 근무 중인 군무원은 법제처에서 정한 규정에 따라 국가와 민...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant
10,"국가법령정보센터에 따르면, 군 복무 중 포로가 되었을 때 군인이 지켜야 할 행동 원...","[<1-hop>\n\n군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음...","<1-hop>에 따르면, 군 복무 중인 군인이나 군무원은 국가에 대한 맹세에 따라 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant

In [40]:
row_idx = 0
q = eval_df.loc[row_idx, 'user_input']
resp = chain.invoke(q)

Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"

In [41]:
# resp
resp['response']

'사회복무요원 소집이 연기된 사람은 **그 연기 사유가 없어진 경우** 다시 별도로 소집될 수 있습니다.  \n\n근거: **병역법 시행령 제52조 제3호**  \n- “사회복무요원 소집이 연기된 사람으로서 **그 사유가 없어진 사람**”'

In [42]:
# resp
resp['retrieved_context']

['법 제29조제2항에 따라 사회복무요원 소집 순서에 따르지 않고 따로 사회복무\n요원 소집을 할 수 있는 사람은 다음 각 호와 같다. <개정 2010. 7. 21., 2011. 7. 14., 2013. 12. 4., 2016. 6. 14., 2016.\n11. 29., 2017. 9. 22., 2020. 6. 30., 2021. 10. 14.>\n1. 병역판정검사를 받고 그 해 소집을 희망하는 사람\n2. 학군 군간부후보생 또는 의무ㆍ법무ㆍ군종ㆍ수의사관후보생으로서 해당 병적에서 제적되어 소집할 사람\n3. 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람\n4. 국외에서 귀국한 사람으로서 소집할 사람\n5. 사회복무요원 소집 기피의 죄를 범한 사람으로서 형사처분이 종료된 사람 및 공소시효가 완성된 사람\n6. 예술ㆍ체육요원, 공중보건의사, 병역판정전담의사, 공익법무관, 공중방역수의사, 전문연구요원 또는 산업기능요\n원으로의 편입이 취소되어 소집할 사람\n7. 제137조제7항에 따라 보충역으로 편입된 사람\n8. 대체역법 제25조제2항에 따라 대체역의 편입이 취소되어 소집할 사람\n9. 그 밖에 병무청장이 필요하다고 인정하는 사람\n[전문개정 2009. 12. 7.]\n[제목개정 2013. 12. 4.]',
 '① 법 제65조제11항 본문에 따라 사회복무요원으\n로 계속 복무하는 것이 적합하지 아니한 사람은 다음 각 호와 같다. <개정 2017. 5. 29.>\n1. 같은 질병이나 심신장애로 6개월 이상 지속적인 치료에도 불구하고 치유되지 아니하여 정상적인 직무 수행이 곤\n란한 사람\n2. 「정신건강증진 및 정신질환자 복지서비스 지원에 관한 법률」 제3조제1호의 정신질환자로서 근무시간 중 다른\n사람의 생명 또는 신체에 중대한 위해(危害)를 입힐 우려가 있는 사람\n3. 지능 정도가 현저히 낮거나 발달장애 등으로 다른 사람의 도움 없이는 단순한 직무 수행도 곤란한 사람\n4. 마약ㆍ대마ㆍ향정신성의약품 또는 알코올에 중독되어 치료 등을 받았으나 치유되지 아니하여 지속적인 치료가\n필요하다고 인정되는 사람으로서 정상적인 직무 수행이 곤란한 사람\n5. 그 밖의 중대한 질병 또는 심신장애로 정상적인 직무 수행이 곤란하다고 인정되는 사람\n② 복무기관의 장은 사회복무요원이 제1항 각 호의 어느 하나에 해당하는 사람으로 판단되는 경우에는 사회복무요\n원 소집해제 신청서를 지방병무청장에게 제출하여야 한다.\n③ 지방병무청장은 제2항에 따라 사회복무요원 소집해제 신청서를 받은 경우에는 그 사실 여부를 확인하기 위한 조\n사를 실시하여야 한다.\n④ 제3항에 따른 조사의 방법 및 절차 등에 필요한 사항은 병무청장이 정한다.\n⑤ 지방병무청장은 제3항에 따른 사실조사 결과 제1항 각 호의 어느 하나에 해당하는 사람에 대해서는 국방부령으\n로 정하는 심사를 거쳐 전시근로역에 편입할 수 있다.\n⑥ 지방병무청장은 제2항에도 불구하고 법 제31조의2제2항에 따른 복무관리ㆍ감독이나 법 제43조제2항에 따른 실\n태조사 과정에서 제1항 각 호에 해당하는 사람을 확인한 경우에는 제5항의 심사를 거쳐 전시근로역에 편입할 수 있\n다.<개정 2021. 10. 14.>\n⑦ 지방병무청장은 제5항 및 제6항에 따라 병역처분을 변경한 경우에는 그 사실을 기재한 병역증을 복무기관의 장\n을 통하여 본인에게 교부하여야 한다.\n[본조신설 2016. 11. 29.]',
 '① 지방병무청장은 사회복무요원 소집 대상자에 대하여 지역별로 소집순서를\n결정한다. <개정 2013. 6. 4.>\n② 제1항에 따른 지역별 범위 및 소집순서의 결정기준은 신체등급ㆍ학력ㆍ연령 등의 자질을 고려하여 병무청장이\n정한다.<개정 2016. 5. 29.>\n[전문개정 2009. 6. 9.]\n[제목개정 2013. 6. 4.]',
 '① 「국가유공자 등 예우 및 지원에 관한 법률」 제30조에 따른 취업지원 실시기관의 장\n은 소집 등에 의한 승선근무예비역, 보충역(사회복무요원은 제외한다. 이하 이 조에서 같다) 또는 대체복무요원 복무\n를 마친 사람이 채용시험에 응시하는 경우에는 대통령령으로 정하는 바에 따라 3세의 범위에서 응시상한연령을 연\n장하여야 한다. <개정 2010. 1. 25., 2011. 5. 24., 2013. 6. 4., 2016. 1. 19., 2016. 5. 29., 2019. 12. 31.>\n② 승선근무예비역, 보충역 또는 대체복무요원 복무 중인 사람이 복무 만료 예정일 전 6개월 이내에 채용시험에 응\n시하는 경우에는 복무를 마친 사람으로 본다.<개정 2010. 1. 25., 2019. 12. 31.>\n[전문개정 2009. 6. 9.]',
 '① 지방병무청장이 법 제28조제1항에 따라 사회복무요원 소집 순서를 결정한 경우에\n는 시ㆍ군ㆍ구별 사회복무요원 소집 순서 명부를 작성하여야 한다. <개정 2013. 12. 4.>\n② 사회복무요원의 소집은 사회복무요원 소집 순서가 결정된 사람에 대하여 복무기관을 정하여 실시한다. 다만, 법']

In [43]:
# 모든 testset의 데이터데 대한 llm 응답과 retriever의 검색 겷과를 추가
response_list = []
retrieved_context_list = []

for user_input in eval_df['user_input']:
    resp = chain.invoke(user_input)
    response_list.append(resp["response"])
    retrieved_context_list.append(resp["retrieved_context"])

Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', 5, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nWITH node, score\nWHERE node.description CONTAINS '성희롱' OR node.description CONTAINS '성폭력' OR node.name CONTAINS '성희롱' OR node.name CONTAINS '성폭력'\nOPTIONAL MATCH (law:LAW)-[:CONTAINS]->(node)\nOPTIONAL MATCH (node)-[:REFERENCES]->(ref:ARTICLE)\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=2, column=9, offset=9>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 9, 'line': 2, 'column': 9}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "\n        CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\n        YIELD node, score\n        RETURN node.id AS id, node.name AS name, node.description AS description, score\n        ORDER BY score DESC\n        "

In [44]:
print(len(response_list), len(retrieved_context_list))

11 11

In [45]:
response_list

['사회복무요원 소집이 연기된 사람은 **그 연기 사유가 없어졌을 때** 다시 소집될 수 있습니다.  \n근거: 병역법 시행령 제52조 제3호.',
 '정보가 부족해 답을 할 수없습니다.',
 '주어진 Context 기준으로만 답변드리면 다음과 같습니다.\n\n### 1) 군사경찰부대는 뭐 하는 곳인가요?\nContext에는 **군사경찰부대의 일반적인 업무 전체**가 자세히 나오지는 않습니다. 다만 사고와 관련해서는 다음 역할이 확인됩니다.\n\n- **사고 발생 시 인지 즉시 신고를 받는 대상**\n- **사고속보를 군사경찰계통으로 보고하는 체계의 일부**\n- **국방부조사본부가 관할 변경되거나 수사 조정·통제를 할 때 수사인력 지원에 협조하는 대상**\n\n즉, Context상으로는 **사고 신고 접수, 사고속보 보고, 수사 지원과 관련된 역할**이 확인됩니다.\n\n### 2) 사고가 나면 군사경찰부대가 어떻게 해야 하나요?\nContext에 따르면:\n\n- **사고 발생 시 당사자 또는 당사자로부터 보고를 받은 사람은 관할 군사경찰부대에 인지 즉시 신고해야 합니다.**\n- **사고속보는 제262조에 따라 군사경찰계통으로 보고합니다.**\n- 또한 **중대 사건·사고의 관할이 국방부조사본부로 변경되는 경우**, 국방부조사본부장은 수사인력 지원을 요청할 수 있고 **각 군 군사경찰실(단)장은 특별한 사유가 없는 한 이를 지원해야 합니다.**\n\n즉, 사고가 나면 군사경찰부대는 **신고를 받고, 사고속보를 처리하며, 필요시 수사 지원에 협조**해야 합니다.\n\n### 3) “사고속보는 군사경찰계통으로 보고한다”는 뜻은 무엇인가요?\nContext에 따르면 **사고속보는 제262조에 따라 군사경찰계통으로 보고**한다고 되어 있습니다.\n\n이 뜻은:\n- 사고와 관련한 **긴급한 초기 정보**를\n- **군사경찰의 보고 라인(계통)**을 통해\n- 정해진 절차에 따라 전달한다는 의미입니다.\n\n즉, 일반 행정라인이 아니라 **군사경찰 조직을 통한 보고체계**로 사고의 초기 상황을 신속히 올리는 것입니다.\n\n### 정리\n- 군사경찰부대는 Context상 **사고 신고 접수, 사고속보 보고, 수사 지원**과 관련된 역할을 합니다.\n- 사고가 나면 **즉시 관할 군사경찰부대에 신고**해야 합니다.\n- **사고속보를 군사경찰계통으로 보고**한다는 것은 **군사경찰의 보고 체계를 통해 사고 초기 정보를 신속히 전달한다**는 뜻입니다.\n\n원하시면 제가 이 내용을 **아주 쉽게 한 줄 요약**으로도 바꿔드릴게요.',
 '정보가 부족해 답을 할 수없습니다.',
 '불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, **당직계통의 상관에게 보고하여야 합니다.**',
 '정보가 부족해 답을 할 수없습니다.',
 '국방부장관의 주요 역할은 다음과 같습니다.\n\n1. **입영기본 계획서 송부**\n   - 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적에 편입할 사람의 **입영기본 계획서**를 **입영일 40일 전까지** 병무청장 및 해당 군 참모총장에게 송부해야 합니다.\n\n2. **지원자 명단 송부**\n   - 병적 편입을 지원한 사람의 명단을 병무청장으로부터 받아,\n   - **현역장교 병적 편입 대상자로 입영할 사람의 명단**을 **입영일 20일 전까지** 병무청장을 거쳐 지방병무청장에게 송부해야 합니다.\n\n3. **군사교육 후 병적 편입**\n   - 입영부대의 장으로부터 교육수료자 명단 보고를 받은 경우,\n   - 해당 사람이 **군사교육을 마치는 날의 다음날에 현역장교 병적에 편입**해야 합니다.\n\n또한, **군인 재해보상법 제51조**에 따라 국방부장관은 재해보상제도를 적정하게 운영하기 위해 필요하다고 인정하면, 각 군 참모총장, 국방부 직할부대장 또는 직할기관장, 요양기관의 장, 그 밖의 관계자에게 다음 사항을 요구할 수 있습니다.\n\n- **필요한 보고ㆍ통보**\n- **장부, 서류, 그 밖의 물건의 제시ㆍ제출**\n- **일정한 장소에의 출석과 의견의 진술 또는 설명**\n\n',
 '부대관리훈령 제260조에 따르면, **성희롱ㆍ성폭력 사고**는 원칙적으로 **각 군 본부 성고충예방대응센터장(국방부 성폭력예방대응담당관)에게 보고**하여야 하며, **각 군 본부 성고충예방대응센터장은 이를 국방부 성폭력예방대응담당관에게 보고**하여야 합니다.\n\n### 보고의 유형과 보고계통\n제260조제1항에 따른 사고 보고의 유형은 다음과 같습니다.\n\n1. **지휘보고**  \n   - 국방부 직할부대장ㆍ기관장 및 각 군 참모총장은  \n     **별표 3의 ‘극히 중한 사고’**가 발생한 경우 인지 즉시 장관에게 지휘보고하여야 하며, 참모계통(군인권개선추진단, 관련부서)으로도 보고합니다.\n\n2. **참모보고**  \n   - 지휘보고 대상인 극히 중한 사고 또는 별표 3의 ‘중한 사고’, 언론보도 사고 발생 시  \n     국방부 직할부대(기관) 인사처와 각 군 인사참모부는 최초ㆍ중간ㆍ최종보고로 구분하여  \n     국방부 차관실(군인권개선추진단)과 관련부서에 참모계통으로 보고합니다.\n\n3. **참고보고**  \n   - 지휘보고 및 참모보고에 포함되지 않는 기타 경미한 사고는  \n     국방부 차관실(군인권개선추진단)과 관련부서 계통으로 보고합니다.\n\n4. **상황보고**  \n   - 군사지휘본부 지휘통제실장은 사고 발생 상황을 접수하면  \n     차관실(군인권개선추진단)과 관련부서 장에게 보고합니다.\n\n5. **사고속보**  \n   - 제262조에 따라 군사경찰계통으로 보고합니다.\n\n### 각 군 본부 성고충예방대응센터장과 국방부 성폭력예방대응담당관의 역할\n제260조와 제248조, 제249조의 내용을 종합하면:\n\n- **각 군 본부 성고충예방대응센터장**은 성희롱ㆍ성폭력 관련 사실을 접수하면  \n  **국방부 성폭력예방대응담당관에게 보고**해야 합니다.\n- **국방부 성폭력예방대응담당관**은 각 군 본부 및 해병대사령부 성고충예방대응센터 운영실태를 점검하며,  \n  성희롱ㆍ성폭력 관련 사항을 상위로 보고·관리하는 역할을 합니다.\n\n### 극히 중한 사고 및 언론보도(예상) 성폭력 사고의 국방부 장관 보고 절차\n제260조제1항제1호에 따르면, **성폭력의 경우 영관급 이상, 4급 이상 군무원, 군 수사기관, 미성년자 연루, 또는 언론보도(예상) 성폭력 발생 시**에는  \n**각 군 참모총장**이 보고하며, **국방부 직할부대ㆍ기관의 경우에는 국방부 성폭력예방대응담당관이** 장관에게 보고합니다.\n\n즉,\n- **각 군 소속 사건**: 각 군 참모총장이 국방부 장관에게 보고\n- **국방부 직할부대ㆍ기관 사건**: 국방부 성폭력예방대응담당관이 국방부 장관에게 보고\n\n정보가 부족해 답을 할 수없습니다.',
 '부대관리훈령 제260조에 따르면, **성희롱ㆍ성폭력은 각 군 본부 성고충예방대응센터장(국방부 성폭력예방대응담당관)에게 보고**하여야 하며, **각 군 본부 성고충예방대응센터장은 국방부 성폭력예방대응담당관에게 보고**하여야 합니다.\n\n또한 제248조에 따르면, **국방부의 성희롱ㆍ성폭력 고충처리부서는 군인권개선추진단 성폭력예방대응담당관실**입니다.  \n그리고 제248조 제3항에 따라 **국방부 성폭력예방대응담당관은 각 군 본부 및 해병대사령부 성고충예방대응센터의 운영실태를 주기적으로 점검**합니다.\n\n다만, 질문하신 **국방부와 각 군 본부에서 성희롱 또는 성폭력 사고가 발생했을 때의 사고 보고 “유형”과 “보고 계통”이 어떻게 다른지**에 대해서는, 제공된 context에는 국방부와 각 군 본부를 직접 비교해 구분한 명시적 내용이 없습니다.  \n따라서 **정보가 부족해 답을 할 수없습니다.**',
 '정보가 부족해 답을 할 수없습니다.',
 '정보가 부족해 답을 할 수없습니다.']

In [46]:
retrieved_context_list

[['법 제29조제2항에 따라 사회복무요원 소집 순서에 따르지 않고 따로 사회복무\n요원 소집을 할 수 있는 사람은 다음 각 호와 같다. <개정 2010. 7. 21., 2011. 7. 14., 2013. 12. 4., 2016. 6. 14., 2016.\n11. 29., 2017. 9. 22., 2020. 6. 30., 2021. 10. 14.>\n1. 병역판정검사를 받고 그 해 소집을 희망하는 사람\n2. 학군 군간부후보생 또는 의무ㆍ법무ㆍ군종ㆍ수의사관후보생으로서 해당 병적에서 제적되어 소집할 사람\n3. 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람\n4. 국외에서 귀국한 사람으로서 소집할 사람\n5. 사회복무요원 소집 기피의 죄를 범한 사람으로서 형사처분이 종료된 사람 및 공소시효가 완성된 사람\n6. 예술ㆍ체육요원, 공중보건의사, 병역판정전담의사, 공익법무관, 공중방역수의사, 전문연구요원 또는 산업기능요\n원으로의 편입이 취소되어 소집할 사람\n7. 제137조제7항에 따라 보충역으로 편입된 사람\n8. 대체역법 제25조제2항에 따라 대체역의 편입이 취소되어 소집할 사람\n9. 그 밖에 병무청장이 필요하다고 인정하는 사람\n[전문개정 2009. 12. 7.]\n[제목개정 2013. 12. 4.]',
  '① 법 제65조제11항 본문에 따라 사회복무요원으\n로 계속 복무하는 것이 적합하지 아니한 사람은 다음 각 호와 같다. <개정 2017. 5. 29.>\n1. 같은 질병이나 심신장애로 6개월 이상 지속적인 치료에도 불구하고 치유되지 아니하여 정상적인 직무 수행이 곤\n란한 사람\n2. 「정신건강증진 및 정신질환자 복지서비스 지원에 관한 법률」 제3조제1호의 정신질환자로서 근무시간 중 다른\n사람의 생명 또는 신체에 중대한 위해(危害)를 입힐 우려가 있는 사람\n3. 지능 정도가 현저히 낮거나 발달장애 등으로 다른 사람의 도움 없이는 단순한 직무 수행도 곤란한 사람\n4. 마약ㆍ대마ㆍ향정신성의약품 또는 알코올에 중독되어 치료 등을 받았으나 치유되지 아니하여 지속적인 치료가\n필요하다고 인정되는 사람으로서 정상적인 직무 수행이 곤란한 사람\n5. 그 밖의 중대한 질병 또는 심신장애로 정상적인 직무 수행이 곤란하다고 인정되는 사람\n② 복무기관의 장은 사회복무요원이 제1항 각 호의 어느 하나에 해당하는 사람으로 판단되는 경우에는 사회복무요\n원 소집해제 신청서를 지방병무청장에게 제출하여야 한다.\n③ 지방병무청장은 제2항에 따라 사회복무요원 소집해제 신청서를 받은 경우에는 그 사실 여부를 확인하기 위한 조\n사를 실시하여야 한다.\n④ 제3항에 따른 조사의 방법 및 절차 등에 필요한 사항은 병무청장이 정한다.\n⑤ 지방병무청장은 제3항에 따른 사실조사 결과 제1항 각 호의 어느 하나에 해당하는 사람에 대해서는 국방부령으\n로 정하는 심사를 거쳐 전시근로역에 편입할 수 있다.\n⑥ 지방병무청장은 제2항에도 불구하고 법 제31조의2제2항에 따른 복무관리ㆍ감독이나 법 제43조제2항에 따른 실\n태조사 과정에서 제1항 각 호에 해당하는 사람을 확인한 경우에는 제5항의 심사를 거쳐 전시근로역에 편입할 수 있\n다.<개정 2021. 10. 14.>\n⑦ 지방병무청장은 제5항 및 제6항에 따라 병역처분을 변경한 경우에는 그 사실을 기재한 병역증을 복무기관의 장\n을 통하여 본인에게 교부하여야 한다.\n[본조신설 2016. 11. 29.]',
  '① 지방병무청장은 사회복무요원 소집 대상자에 대하여 지역별로 소집순서를\n결정한다. <개정 2013. 6. 4.>\n② 제1항에 따른 지역별 범위 및 소집순서의 결정기준은 신체등급ㆍ학력ㆍ연령 등의 자질을 고려하여 병무청장이\n정한다.<개정 2016. 5. 29.>\n[전문개정 2009. 6. 9.]\n[제목개정 2013. 6. 4.]',
  '① 지방병무청장이 법 제28조제1항에 따라 사회복무요원 소집 순서를 결정한 경우에\n는 시ㆍ군ㆍ구별 사회복무요원 소집 순서 명부를 작성하여야 한다. <개정 2013. 12. 4.>\n② 사회복무요원의 소집은 사회복무요원 소집 순서가 결정된 사람에 대하여 복무기관을 정하여 실시한다. 다만, 법',
  '① 「국가유공자 등 예우 및 지원에 관한 법률」 제30조에 따른 취업지원 실시기관의 장\n은 소집 등에 의한 승선근무예비역, 보충역(사회복무요원은 제외한다. 이하 이 조에서 같다) 또는 대체복무요원 복무\n를 마친 사람이 채용시험에 응시하는 경우에는 대통령령으로 정하는 바에 따라 3세의 범위에서 응시상한연령을 연\n장하여야 한다. <개정 2010. 1. 25., 2011. 5. 24., 2013. 6. 4., 2016. 1. 19., 2016. 5. 29., 2019. 12. 31.>\n② 승선근무예비역, 보충역 또는 대체복무요원 복무 중인 사람이 복무 만료 예정일 전 6개월 이내에 채용시험에 응\n시하는 경우에는 복무를 마친 사람으로 본다.<개정 2010. 1. 25., 2019. 12. 31.>\n[전문개정 2009. 6. 9.]'],
 ['지방병무청장은 병무지청장, 병역판정전담의사 또는 군의관이 법 또는 이 영에 따라 행한 통지ㆍ\n처분이 위법하거나 부당하다고 인정하는 경우에는 이를 중지시키거나 취소 또는 변경할 수 있다. <개정 2016. 11.\n29.>\n[전문개정 2009. 12. 7.]',
  '① 지방병무청장(병무지청장을 포함한다. 이하 이 조에서 같다)은 다음 각 호의 어느 하나\n에 해당하는 사람이 병역의무를 감면받을 목적으로 속임수를 썼다고 인정할 만한 사유 등 대통령령으로 정하는 사\n유가 있는 경우에는 진료기록이나 치료내역 등 사실관계를 조사하고 확인신체검사를 할 수 있다. <개정 2016. 5.\n29., 2019. 12. 31.>\n1. 제12조제1항에 따른 신체등급 판정에서 질병 또는 심신장애로 4급부터 7급까지로 판정되어 병역처분을 받은 사\n람\n2. 제65조제1항제1호, 같은 조 제4항 및 제65조의2제1항에 따라 병역처분이 변경되거나 병역면제 처분을 받은 사람\n② 지방병무청장은 제1항에 따른 확인신체검사와 관련하여 질병이나 심신장애의 확인을 위하여 필요하다고 인정하\n는 경우 「의료법」에 따른 의료기관의 장, 「국민건강보험법」에 따른 국민건강보험공단의 장 또는 건강보험심사평가\n원의 장, 「초ㆍ중등교육법」에 따른 학교의 장 및 각 군 참모총장 등에 대하여 확인신체검사 대상자의 진료기록, 치\n료 관련 기록 내역, 학교생활기록부 및 학생건강기록부, 병역처분 변경 등 관련 자료 등의 제출을 요구할 수 있다.\n이 경우 자료 제출을 요구받은 자는 특별한 사유가 없으면 요구에 따라야 한다.<신설 2026. 6. 9.>\n③ 누구든지 제2항에 따라 취득한 확인신체검사 대상자에 대한 정보ㆍ자료를 공개 또는 누설하거나 다른 사람에게\n제공하는 등 확인신체검사 외의 목적으로 사용하여서는 아니 된다.<신설 2026. 6. 9.>\n④ 지방병무청장은 제1항에 따른 확인신체검사 결과 병역처분이 잘못되었다고 판단하면 대통령령으로 정하는 바에\n따라 병역처분을 변경하여야 한다.<개정 2026. 6. 9.>\n⑤ 제1항에 따른 확인신체검사의 방법 및 절차 등에 관하여 필요한 사항과 제2항에 따라 자료를 요구할 수 있는 사\n유 및 범위에 관한 구체적 사항은 대통령령으로 정한다.<개정 2026. 6. 9.>\n[본조신설 2011. 5. 24.]\n[시행일: 2026. 12. 10.] 제77조의2',
  '지방병무청장은 법 제21조제2항에 따라 상근예비역소집 대상자를\n선발하거나 같은 조 제4항에 따라 상근예비역소집 대상자의 선발을 취소한 경우에는 본인에게 지체 없이 그 사실을\n통지하여야 한다.\n[전문개정 2009. 12. 7.]',
  '① 지방병무청장은 병역판정전담의사가 법 제34조의2제4항을 위반하\n여 근무지를 이탈하거나 병역판정검사업무 외의 업무에 종사한 경우에는 그 사실을 병무청장에게 보고하여야 한다.\n<개정 2016. 11. 29.>\n② 지방병무청장은 병역판정전담의사가 장기입원 또는 요양 등 직무 외의 사유로 1개월 이상 근무하지 못한 경우에\n는 그 사유를 명시하여 병무청장에게 보고하여야 한다.<개정 2016. 11. 29.>\n[전문개정 2009. 12. 7.]\n[제목개정 2016. 11. 29.]',
  '지방병무청장, 병무지청장 또는 신체등급판정 사무를 담당하는 병무청 소속기관의 장은\n법 제79조제3항에 따라 환수할 비용이 발생하면 그 대상자에게 환수사유, 발생사실, 환수금액, 반납기한, 반납기관\n및 이의신청방법 등을 서면으로 통지하여야 한다. 이 경우 반납기한은 통지일부터 30일 이상으로 한다.\n[본조신설 2016. 11. 29.]\n[제158조의3에서 이동 <2021. 10. 14.>]'],
 ['국방부 사고대책반의 임무는 다음 각 호와 같다.\n1. 사고발생 초기 상황유지 및 보고, 분야별 대책 강구\n2. 사고자, 피해자, 관련자, 책임소재 규명 등 사고처리에 관한 사항 조치\n3. 사고수습 및 보상 등 유가족과의 협의시 지침 제공\n4. 언론 및 대외기관 대응, 대외 발표에 관한 사항 협의\n5. 사안 발생원인 분석, 재발방지 대책 등 후속조치 강구\n6. 담당부서별 소관사항 신속 파악 및 제출\n7. 사고 유형 및 경중에 따라 사고종합대책본부 설치 건의\n \n 제3절 사고종합대책 본부 운영',
  '① 국방부장관은 사고종합대책본부 설치 이전에 군내 주요사고에 대한 신속한\n보고, 대응 및 처리를 위하여 국방부 사고대책반을 운영한다.\n② 사건ㆍ사고 발생시 그 유형에 따른 별표 4의 사고처리 주관부서의 장(국장급)은 인사복지실, 군인권개선추진\n단, 전력자원관리실, 국방정책실 등 관련 부서의 의견을 수렴하여 최초 상황평가를 실시, 사고대책반 운영여부를\n판단하여야 한다. 이때 사건ㆍ사고의 경중 등에 따라 필요하다고 판단되는 경우 별표 8의 최초 상황평가 구성인\n원을 소집하여 운영할 수 있다.\n③ 최초 상황평가에 따라 사고대책반을 운영하는 경우 국방부 사고대책반장은 사고처리 주관부서의 장(국장급\n)으로 하며, 반원은 관련 과장(실무자)으로 한다. 사고대책반 세부 구성인원은 별표 8과 같다.\n④ 각급 부대 및 기관은 국방부 사고종합대책본부 및 사고대책반 운영기준을 참고하여 운영하되, 제대별 임무와\n조직규모 등 특성에 따라 운영형태와 방식 등을 달리 정할 수 있다.',
  '① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각 호와 같다. 다만 성희롱ㆍ성폭력\n은 각 군 본부 성고충예방대응센터장(국방부 성폭력예방대응담당관)에게 보고하여야 하며, 각 군 본부 성고충예\n방대응센터장은 국방부 성폭력예방대응담당관에게 보고하여야 한다.\n1. 지휘보고 : 국방부 직할부대장ㆍ기관장 및 각 군 참모총장은 별표 3의 ‘극히 중한 사고’에 해당되는 사고가 있\n을 때에는 인지 즉시 장관에게 지휘보고 하여야 하며, 참모계통(군인권개선추진단, 관련부서)으로도 보고하여\n야 한다. 다만 성폭력의 경우 영관급 이상(4급 이상 군무원)ㆍ군 수사기관ㆍ미성년자가 연루되거나 언론보도\n(예상) 성폭력 발생 시에는 각 군 참모총장이(국방부 직할부대ㆍ기관은 국방부 성폭력예방대응담당관이) 장관\n에게 보고하여야 한다.\n2. 참모보고 : 지휘보고 대상인 극히 중한 사고나 참모보고 대상인 별표 3의 ‘중한 사고’ 발생시, 언론보도 사고 발\n생시에는 국방부 직할부대(기관) 인사처와 각 군 인사참모부는 제반사고에 대한 사항을 최초ㆍ중간ㆍ최종보고\n로 구분하여 국방부 차관실(군인권개선추진단)과 관련부서에 참모계통으로 보고하여야 한다.\n3. 참고보고 :「지휘보고」및「참모보고」에 포함되지 않는 기타 경미한 사고에 대해서는 국방부 차관실(군인권개선\n추진단)과 관련부서 계통으로 보고하여야 한다.\n4. 상황보고 : 군사지휘본부 지휘통제실장은 사고발생 상황을 접수한때에는 차관실(군인권개선추진단)과 제2항\n에 규정된 관련부서의 장에게 보고하여야 한다.\n5. 사고속보 : 사고속보는 제262조에 따라 군사경찰계통으로 보고한다.\n② 사고처리 주관부서는 별표 4와 같으며, 사고발생시 보고 및 처리는 사안에 따라 참모기능별로 유관부서와 협\n조하여 조치하고, 사고 발생시 당사자 또는 당사자로부터 보고를 받은 사람은 관할 군사경찰부대에 인지 즉시 신\n고하여야 한다.',
  '① 국방부 차원의 대응이 필요한 중대 사건ㆍ사고\n발생시에 국방부조사본부장은 국방부장관의 승인을 받아 국방부조사본부에서 관할할 수 있다.\n② 국방부조사본부장은 각 군과 국직부대에서 제262조(사고속보)에 규정된 사건ㆍ사고가 발생한 경우와 그 밖에\n국방부장관이 지시한 사건ㆍ사고에 대한 수사ㆍ조사를 조정ㆍ통제할 수 있으며, 필요한 지원을 할 수 있다.\n③ 중대 사건ㆍ사고의 관할권 변경시에 국방부조사본부장은 수사에 필요한 수사인력 지원을 요청할 수 있으며\n각 군 군사경찰실(단)장은 특별한 사유가 없는 한 이를 지원하여야 한다.\n④ 국방부조사본부장은 군사경찰수사관이 편성된 국직 군사경찰부대에 대하여 정기적인 수사업무 지도방문을\n시행하고 수사 역량향상을 위한 교육 및 자원을 지원한다.',
  '① 국방부 및 각 군의 사고예방 및 군기강 확립 업무를 수행하는 국군방첩사령부, 군사\n경찰, 검찰(법무), 감사(감찰), 인사 기능별 주무부서(기관)의 장은 상호 수집된 첩보를 교환ㆍ공유하고, 유기적인\n협조체계를 유지한다.\n② 제190조에 따라 국방부에 적용하는 첩보교류 기관 및 부서는 다음 각 호와 같다.\n\n법제처                                                            38                                                   국가법령정보센터\n부대관리훈령\n1. 국군방첩사령부\n2. 국방부조사본부\n3. 국방부검찰단\n4. 국방부감사관실\n5. 국방부인사복지실\n6. 그 밖에 필요한 경우 관련부서 또는 기관\n③ 제190조에 따라 각 군에 적용하는 첩보교류 대상기관 및 부서는 장성급 장교가 지휘하는 제대별 여건을 고려\n하여 지휘관이 정한다.'],
 ['군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세하고, 사명에 입\n각하여 전투 중 또는 포로가 되었을 경우에도 이를 지켜야한다.\n1. 나는 대한민국 군인(군무원)이다. 국가와 민족을 위하여 신명을 바치겠다.\n2. 나는 죽어도 항복하지 않겠다. 나는 전력을 다하여 끝까지 싸우겠다.\n3. 나는 만약에 포로가 되더라도 계속 항거하고 전력을 다하여 탈출하며, 전우의 탈출을 돕겠다.\n4. 나는 만약에 포로가 되더라도 아국이나 우방에 불리한 여하한 적의 권고나 우대도 거절하며, 추호도 적을 돕지\n않겠다.\n5. 나는 만약에 포로가 되더라도 기밀을 엄수하고, 전우를 보호하고, 선임자면 후임자를 통솔하고, 후임자면 선임\n자의 명령에 복종하겠다.\n6. 나는 만약 포로가 되어 심문 받더라도 계급, 성명, 군번, 연령을 제외하고는 진술을 회피하며, 아국과 우방에 불\n리한 성명, 그 밖에 여하한 요구에도 응하지 않겠다.\n7. 나는 조국에 신명을 바친 대한민국 군인임을 명심하고 나의 행동에 대한 책임을 지겠다. 나는 조국을 사랑하며\n조국은 나를 보호하고 있음을 확신한다.\n \n\n법제처                                                            4                                                   국가법령정보센터\n부대관리훈령\n 제2장 병영생활\n 제1절 책무',
  '① 「군인의 지위 및 복무에 관한 기본법」제3조에 의한 군인, 사관생도ㆍ사관후보생\nㆍ준사관후보생 및 부사관후보생, 소집되어 군에 복무하는 예비역 및 보충역, 군무원, 국방부와 소속기관 공무원\n은「국가공무원법」제65조, 「공직선거법」 제57조의2, 제57조의6, 제60조, 제85조, 제86조, 제112조, 제238조,「군\n형법」제94조,「공익신고자 보호법」제25조의2, 「군인의 지위 및 복무에 관한 기본법」제33조,「정당법」제22조, 제\n53조,「정치자금법」제8조에서 규정한 정치적 중립의 의무를 준수하여야 한다.\n② 정치적 중립과 의무를 준수하기 위한「행동수칙」 및「세부행동기준」은 별표 1의3과 같다.',
  '① 군인은 다음 각 호의 행위를 하여서는 아니 된다.\n1. 성희롱ㆍ성추행 및 성폭력 등의 행위\n2. 상급자ㆍ하급자나 동료를 음해(陰害)하거나 유언비어를 유포하는 행위\n3. 의견 건의 또는 고충처리 등을 고의로 방해하거나 부당한 영향을 주는 행위\n4. 그 밖에 군기를 문란하게 하는 행위\n② 제1항에 따른 금지행위에 관한 세부기준은 국방부령으로 정한다.\n\n법제처                                                            5                                                       국가법령정보센터\n군인의 지위 및 복무에 관한 기본법',
  '① 군인은 제복을 입어야 한다. 다만, 근무의 특수성으로 인하여 국방부장관이 허가하는 경우\n에는 그러하지 아니하다.\n② 군인은 국가에 충성하고 굳게 단결하며 엄정한 군기(軍紀)를 유지하기 위하여 군예식(軍禮式)을 거행한다.\n③ 제1항 및 제2항에 따른 군인의 복제(服制) 및 예식에 관하여 필요한 사항은 대통령령으로 정한다.\n[전문개정 2011. 5. 24.]',
  '① 군인은 「대한민국헌법」과 법령을 준수하며 직무를 수행하여야 한다.\n② 국방부장관은 대통령령으로 정하는 바에 따라 군인에게 「대한민국헌법」 및 국방 관계 법령에 대한 교육을 실시\n하여야 한다.\n[본조신설 2026. 6. 9.]\n[종전 제34조는 제34조의2로 이동 <2026. 6. 9.>]\n[시행일: 2026. 12. 10.] 제34조\n \n\n법제처                                                            6                                                       국가법령정보센터\n군인의 지위 및 복무에 관한 기본법'],
 ['불침번은 통상 저녁점호 직후부터 다음날 기상시까지 생활관 또는 건물단위로\n지휘관이 정하는 곳에서 근무한다.',
  '① 불침번은 건물 내ㆍ외를 완벽히 경계하여야 하며, 근무 중 지정된 위치를 떠나거나\n앉거나 담배를 피워서는 아니 된다.\n② 불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, 당직계통의 상관에게 보고하여야 한다.\n③ 불침번은 타인의 취침에 방해가 되지 아니하도록 근무하여야 한다.\n④ 불침번은 근무교대시 인원ㆍ장비 및 상관의 지시사항을 정확하게 인계ㆍ인수하여야 한다.',
  '불침번은 당직사관의 지시를 받아 근무하며, 생활관 출입자 감시, 화재ㆍ도난의 예방 및\n위생관찰을 그 목적으로 한다.',
  '① 불침번은 통상 2인 1조로 편성함을 원칙으로 한다. 다만, 건물구조 또는 생활관 취침병력\n에 따라 이를 조정할 수 있다.\n② 불침번의 근무시간은 1시간 이상 2시간 이하로 함을 원칙으로 한다.',
  '점검 중 발견된 가벼운 결함사항은 그 자리에서 시정하도록 하고, 상급지휘관의 조치가 필요\n한 사항은 지휘계통에 따라 보고하여야 한다.'],
 ['① 국방부장관은 제8조제1항에 따른 급여의 결정 및 지급에 관한 권한을\n대통령령으로 정하는 바에 따라 각 군 참모총장, 국방부 직할부대장 또는 직할기관장에게 위임할 수 있다.\n② 국방부장관(제1항에 따라 위임받은 사람을 포함한다)은 급여에 관한 업무를 대통령령으로 정하는 바에 따라 다\n음 각 호의 구분에 따른 기관의 장에게 위탁할 수 있다.<개정 2023. 3. 4.>\n1. 사망보상금의 지급 및 환수에 관한 업무: 국가보훈부\n2. 공무상요양비 지급에 관한 업무: 국민건강보험공단\n3. 그 밖의 급여의 지급에 관한 업무: 체신관서(遞信官署) 또는 금융회사등',
  '① 제7조에 따른 급여를 받으려면 그 급여를 받을 권리를 가진 사람이 국방부\n장관에게 지급청구를 하여야 한다.\n② 국방부장관은 제1항에 따른 급여의 청구를 받으면 급여의 요건을 확인한 후 급여를 결정하고 지급한다. 다만, 제\n20조에 따른 공무상요양비(제5조제2항에 해당하는 경우는 제외한다), 제26조에 따른 상이연금 및 제35조에 따른 순\n직유족연금을 결정할 때에는 심의회의 심의를 거쳐야 한다.<개정 2024. 1. 16.>',
  '① 국방부장관은 제8조에 따른 급여의 결정과 지급에 관한 권한의 일부를\n대통령령으로 정하는 바에 따라 국방부 직할부대장에게 위임할 수 있다.\n② 국방부장관(제1항에 따라 위임받은 사람을 포함한다)은 급여의 지급에 관한 업무를 대통령령으로 정하는 바에\n따라 체신관서(遞信官署) 또는 금융회사등의 장에게 위탁할 수 있다.',
  '국방부장관은 이 법에 따른 급여와 그 밖에 재해보상제도를 적정하게 운영하기 위하여 필요하\n다고 인정할 때에는 각 군 참모총장, 국방부 직할부대장 또는 직할기관장 및 요양기관의 장, 그 밖의 관계자에게 다\n음 각 호의 사항을 요구할 수 있으며, 소속 공무원 또는 기관으로 하여금 장부, 서류 또는 그 밖의 물건을 검사하게\n할 수 있다.\n1. 필요한 보고ㆍ통보\n2. 장부, 서류, 그 밖의 물건의 제시ㆍ제출\n3. 일정한 장소에의 출석과 의견의 진술 또는 설명',
  '① 국방부장관은 이 법에 따른 급여를 지급받을 권리가 있는 사람에게 신분상의 이동,\n장해 정도, 그 밖에 급여에 관하여 필요한 서류 또는 물건의 제출을 요구할 수 있다.\n② 국방부장관은 이 법에 따른 급여와 그 밖에 군인재해보상제도의 적정한 운영을 위하여 필요하다고 인정할 때에\n는 국가기관, 지방자치단체, 요양기관, 그 밖에 대통령령으로 정하는 단체나 기관에 「군인연금법」 제27조제3항에\n따른 소득 등의 조사나 그 밖에 군인재해보상업무에 필요한 주민등록ㆍ가족관계등록ㆍ국세ㆍ지방세ㆍ토지ㆍ건물\nㆍ건강보험ㆍ장애인등록 등 대통령령으로 정하는 자료를 요청할 수 있다. 이 경우 자료의 제공 등을 요청받은 단체\n나 기관은 특별한 사유가 없으면 그 요청에 따라야 한다.<개정 2023. 10. 31.>\n③ 제2항에 따라 제공되는 자료에 대해서는 사용료ㆍ수수료 등을 면제한다.\n④ 제1항의 경우에 급여를 받을 권리가 있는 사람이 정당한 사유 없이 그 요구에 따르지 아니하면 이에 따를 때까\n지 그 사람에 대한 급여의 지급을 중지할 수 있다.'],
 ['① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 현역장교(의무ㆍ법무ㆍ군종ㆍ수의사관후보생을 포함하며, 이하 “의무ㆍ법무ㆍ군종ㆍ수의장교”라 한다)\n및 기본병과 분야의 현역장교(이하 “기본병과장교”라 한다)의 병적에 편입할 사람의 입영기본 계획서를 입영일 40일\n전까지 병무청장 및 해당 군 참모총장에게 송부하여야 하며, 이를 받은 병무청장은 입영 계획서를 작성하여 지방병\n무청장에게, 해당 군 참모총장은 교육 계획서를 작성하여 입영부대의 장에게 각각 송부하여야 한다. <개정 2016. 11.\n29.>\n② 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입을 지원한 사람에 대해서는 국방부장관이 병무청장\n으로부터 그 명단을 받아 현역장교 병적 편입 대상자로 입영할 사람의 명단을 입영일 20일 전까지 병무청장을 거쳐\n지방병무청장에게 송부하여야 한다.<개정 2016. 11. 29.>\n\n법제처                                                            69                                                       국가법령정보센터\n병역법 시행령\n③ 지방병무청장은 제1항에 따른 입영 계획서에 의하여 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과현역장교의 병적\n편입 대상자의 현역입영 통지서를 본인에게 입영일 7일 전까지 송달하여 개별입영하게 하고 입영자 명부와 병적기\n록표를 입영부대의 장에게 송부하여야 한다. 다만, 「의료법」 제77조 및 「전문의의 수련 및 자격 인정 등에 관한 규\n정」 제18조에 따라 보건복지부장관이 실시하는 전문의 자격시험의 합격 여부를 확인할 수 없는 의무ㆍ수의장교 편\n입 대상자에게는 현역입영 통지서를 입영일 전날까지 송달할 수 있다.<개정 2018. 5. 28.>\n④ 입영부대의 장은 제3항에 따라 입영한 사람에 대하여 정해진 군사교육을 실시하고 교육수료 10일 전까지 그 명\n단을 소속 군 참모총장을 거쳐 국방부장관에게 보고하여야 한다.\n⑤ 국방부장관은 제4항에 따른 보고를 받은 경우에는 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적에 편입\n될 사람이 군사교육을 마치는 날의 다음날에 현역장교 병적에 편입하여야 한다.\n[전문개정 2009. 12. 7.]',
  '① 다음 각 호의 어느 하나에 해당하는 직위의 보직은 해당 군의 장성급 장교 중에서\n참모총장이 추천심의위원회의 심의를 거쳐 국방부장관에게 추천하고, 국방부장관은 제청심의위원회의 심의를 거쳐\n제청하며, 대통령이 임명한다. <개정 2017. 3. 21.>\n1. 각군 참모차장\n2. 전투를 주된 임무로 하는 부대의 장\n3. 그 밖에 법령으로 정하는 중요 부서의 장\n② 참모총장은 해당 군의 장성급 장교 중에서 합동참모본부의 장성급 장교의 보직과 「국군조직법」 제9조제3항에\n따른 작전부대 및 합동부대의 장(長)의 보직을 국방부장관에게 추천할 때에는 미리 합참의장과 협의하여야 한다.\n<개정 2017. 3. 21.>\n③ 중장 이상으로서 제1항 각 호의 어느 하나에 해당하는 직위에 있는 사람은 그 직위에서 해임 또는 면직되거나\n그 보임기간이 끝난 후 다른 직위로 전직되지 아니하면 현역에서 전역된다. 다만, 제17조의2제1항제2호 및 제3호에\n해당하여 보직해임된 경우에는 전역되지 아니한다.<개정 2026. 2. 3.>\n④ 제1항에 따른 추천심의위원회 및 제청심의위원회의 구성과 운영에 관한 사항은 대통령령으로 정한다.\n[전문개정 2011. 5. 24.]\n[시행일: 2026. 8. 4.] 제20조',
  '국방부장관은 이 법에 따른 급여와 그 밖에 재해보상제도를 적정하게 운영하기 위하여 필요하\n다고 인정할 때에는 각 군 참모총장, 국방부 직할부대장 또는 직할기관장 및 요양기관의 장, 그 밖의 관계자에게 다\n음 각 호의 사항을 요구할 수 있으며, 소속 공무원 또는 기관으로 하여금 장부, 서류 또는 그 밖의 물건을 검사하게\n할 수 있다.\n1. 필요한 보고ㆍ통보\n2. 장부, 서류, 그 밖의 물건의 제시ㆍ제출\n3. 일정한 장소에의 출석과 의견의 진술 또는 설명',
  '① 현역병입영 대상자로서 다음 각 호의 어느 하나에 해당하는\n사람은 원할 경우 의무ㆍ법무ㆍ군종 또는 수의(獸醫) 분야의 현역장교 병적에 편입할 수 있다. 이 경우 제3호에 따른\n군종(軍宗) 분야의 병적편입 대상 종교의 선정기준과 군종 분야의 현역장교 선발 기준 및 절차 등에 필요한 사항은\n대통령령으로 정한다. <개정 2013. 6. 4.>\n1. 의사ㆍ치과의사 또는 한의사 자격이 있는 사람\n2. 판사ㆍ검사 또는 변호사 자격이 있는 사람\n3. 학사 이상의 학위를 가진 목사ㆍ신부ㆍ승려 또는 그 밖에 이와 동등한 직무를 수행하는 사람으로서 각 소속 종교\n단체에서 자격을 인정한 사람\n4. 수의사 자격이 있는 사람\n② 다음 각 호의 어느 하나에 해당하는 사람 중 의무ㆍ법무ㆍ군종ㆍ수의사관후보생을 지원한 사람은 의무ㆍ법무ㆍ\n군종ㆍ수의사관후보생의 병적에 편입할 수 있으며, 그 편입 대상, 제한연령, 선발 기준 및 절차 등에 필요한 사항은\n대통령령으로 정한다.<개정 2013. 6. 4.>\n1. 의사ㆍ치과의사 또는 한의사 자격이 있는 사람으로서 군전공의수련기관에서 정하여진 과정을 이수하고 있는 사\n람\n2. 판사ㆍ검사 또는 변호사 자격을 얻기 위하여 해당 연수기관이나 법학전문대학원에서 정하여진 과정을 이수하고\n있는 사람\n3. 목사ㆍ신부ㆍ승려 또는 그 밖에 이와 동등한 직무를 수행하는 사람의 자격을 얻기 위하여 신학대학ㆍ불교대학\n또는 그 밖에 성직자의 양성을 목적으로 하는 대학에 다니고 있는 사람\n4. 수의사 자격을 얻기 위하여 수의과대학(수의학과가 설치된 대학의 수의학과를 포함한다)에 다니고 있는 사람\n③ 제2항에 따라 의무ㆍ법무ㆍ군종ㆍ수의사관후보생의 병적에 편입된 사람은 35세까지 특수병과(特殊兵科)의 현역\n장교 병적에 편입할 수 있으며, 의무ㆍ법무ㆍ군종ㆍ수의사관후보생의 병적에서 제적된 사람은 그 신체등급에 따라\n현역병으로 입영하게 하거나 사회복무요원으로 소집할 수 있다.<개정 2013. 6. 4., 2016. 5. 29.>\n④ 제1항ㆍ제3항 및 제59조에 따라 현역장교의 병적에 편입할 사람에 대하여는 군부대에 입영시켜 군사교육을 받\n게 할 수 있다.\n\n법제처                                                            35                                                       국가법령정보센터\n병역법\n⑤ 입영부대의 장은 제4항에 따른 사람이 군부대에 입영한 경우에는 입영한 날부터 7일(토요일 및 공휴일을 포함한\n다) 이내에 신체검사를 하여야 하며, 신체검사의 결과 질병 또는 심신장애로 인하여 현역 복무에 적합하지 아니하거\n나 15일 이상의 치유기간이 필요하다고 인정되는 사람에 대하여는 그 질병 또는 심신장애의 정도와 치유기간(치유\n기간을 알 수 있는 경우만 해당한다)을 명시하여 귀가시켜야 한다. 군사교육 중 질병 또는 심신장애로 15일 이상의\n치유기간이 필요하다고 인정되는 사람에 대하여도 또한 같다.<개정 2016. 1. 19.>\n⑥ 병무청장은 제5항에 따라 귀가한 사람에 대하여는 대통령령으로 정하는 바에 따라 재신체검사를 한 후 신체등급\n에 따라 병역처분을 변경하거나 다시 입영시켜야 한다. 다만, 치유기간이 3개월 미만으로 명시되어 귀가한 사람에\n대하여는 재신체검사를 하지 아니하고 다시 입영시킬 수 있다.<개정 2016. 5. 29.>\n⑦ 제1항에 따른 군종 분야 병적편입 대상 종교의 선정 및 군종 분야 현역장교의 선발 등에 관한 사항을 심의하기\n위하여 국방부에 군종장교운영심사위원회를 두며, 그 구성 및 운영 등에 필요한 사항은 대통령령으로 정한다.\n⑧ 제2항에 따라 의무ㆍ법무ㆍ수의사관후보생의 병적에 편입된 사람에 대한 의무ㆍ법무ㆍ수의 분야의 현역장교 선\n발 기준 및 절차 등에 필요한 사항은 대통령령으로 정한다.<개정 2013. 6. 4.>\n[전문개정 2009. 6. 9.]',
  '① 참모총장은 법 제21조제3항에 따른 전직(轉職)을 위하여 전직 인원 등이 포함된 전직계획을 수\n립하여야 한다.\n② 법 제21조제3항에 따른 전직은 제22조제2항에 따라 승인된 진급 예정 인원의 범위에서 제1항의 전직계획에 따\n라 한다.\n③ 법 제21조제3항에 따른 전직은 1회로 한정하며, 같은 항 단서에 따라 병과장이 유사한 직위에 전직되는 경우에\n는 현재 직위보다 낮은 직위에 보직될 수 없다.\n④ 법 제21조제3항 본문에 따른 “유사한 계통의 직위”는 해당 병과장의 전공 분야와 같은 계통의 직무 분야로 한다.\n[전문개정 2012. 1. 31.]'],
 ['① 모든 군인 및 군무원은 성희롱ㆍ성폭력 관련 사실을 직접 목격하거나 타인에게 듣는 등 인지하였\n을 경우 지체없이 제242조제5호에 따른 양성평등계선으로 보고하여야 한다. 이때 양성평등계선 보고 외에 상급\n자(상급부대) 보고 또는 수사기관 등 신고는 피해자 의사에 반하여 할 수 없다.\n② 지휘계통에 따르지 아니하고 양성평등계선에 보고 등을 하였다는 이유로 어떠한 불이익한 조치를 할 수 없다.\n③ 성폭력 신고를 받은 수사기관은 피해자에게 양성평등계선에서 상담을 받을 수 있다는 사실을 알려야 하며, 피\n해자 의사에 따라 각 군 본부 및 해병대사령부 성고충예방대응센터(국방부 직할부대 및 합참은 국방부 성폭력예\n방대응담당관실)에 통보할 수 있다.\n\n법제처                                                            53                                                   국가법령정보센터\n부대관리훈령\n④ 각 군 본부 및 해병대사령부 성고충예방대응센터장은 성희롱ㆍ성폭력 관련 사실을 접수하였을 경우 국방부\n성폭력예방대응담당관에게 보고하여야 한다.\n⑤ 국방부 소속기관장 및 직할부대장, 합동참모의장 및 각 군 참모총장, 해병대사령관은 성희롱ㆍ성폭력 사건 발\n생 시 피해자의 명시적인 반대의견이 없으면 지체 없이 그 사실을 국방부장관에게 보고하고 성평등가족부장관에\n게 통보하여야 한다.',
  '① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각 호와 같다. 다만 성희롱ㆍ성폭력\n은 각 군 본부 성고충예방대응센터장(국방부 성폭력예방대응담당관)에게 보고하여야 하며, 각 군 본부 성고충예\n방대응센터장은 국방부 성폭력예방대응담당관에게 보고하여야 한다.\n1. 지휘보고 : 국방부 직할부대장ㆍ기관장 및 각 군 참모총장은 별표 3의 ‘극히 중한 사고’에 해당되는 사고가 있\n을 때에는 인지 즉시 장관에게 지휘보고 하여야 하며, 참모계통(군인권개선추진단, 관련부서)으로도 보고하여\n야 한다. 다만 성폭력의 경우 영관급 이상(4급 이상 군무원)ㆍ군 수사기관ㆍ미성년자가 연루되거나 언론보도\n(예상) 성폭력 발생 시에는 각 군 참모총장이(국방부 직할부대ㆍ기관은 국방부 성폭력예방대응담당관이) 장관\n에게 보고하여야 한다.\n2. 참모보고 : 지휘보고 대상인 극히 중한 사고나 참모보고 대상인 별표 3의 ‘중한 사고’ 발생시, 언론보도 사고 발\n생시에는 국방부 직할부대(기관) 인사처와 각 군 인사참모부는 제반사고에 대한 사항을 최초ㆍ중간ㆍ최종보고\n로 구분하여 국방부 차관실(군인권개선추진단)과 관련부서에 참모계통으로 보고하여야 한다.\n3. 참고보고 :「지휘보고」및「참모보고」에 포함되지 않는 기타 경미한 사고에 대해서는 국방부 차관실(군인권개선\n추진단)과 관련부서 계통으로 보고하여야 한다.\n4. 상황보고 : 군사지휘본부 지휘통제실장은 사고발생 상황을 접수한때에는 차관실(군인권개선추진단)과 제2항\n에 규정된 관련부서의 장에게 보고하여야 한다.\n5. 사고속보 : 사고속보는 제262조에 따라 군사경찰계통으로 보고한다.\n② 사고처리 주관부서는 별표 4와 같으며, 사고발생시 보고 및 처리는 사안에 따라 참모기능별로 유관부서와 협\n조하여 조치하고, 사고 발생시 당사자 또는 당사자로부터 보고를 받은 사람은 관할 군사경찰부대에 인지 즉시 신\n고하여야 한다.',
  '① 성희롱ㆍ성폭력 예방업무와 고충 상담 및 처리를 위하여 다\n음 각 호와 같이 성희롱ㆍ성폭력 고충처리부서(이하 "성고충처리부서"라 한다)를 지정ㆍ운용한다.\n1. 국방부 : 군인권개선추진단 성폭력예방대응담당관실\n2. 각 군 본부 및 해병대사령부 : 성고충예방대응센터\n3. 각 급 부대 : 인사부서 등\n② 성고충처리부서의 업무는 다음 각 호와 같다.\n1. 성희롱ㆍ성폭력 피해자의 고충에 대한 상담ㆍ조언 및 접수\n2. 피해자 보호 및 권리구제와 관련한 사항\n3. 성희롱ㆍ성폭력 사건의 처리\n4. 성희롱ㆍ성폭력 사건의 처리 관련 부서 간 협조ㆍ조정에 관한 사항\n5. 성희롱ㆍ성폭력 재발방지대책의 수립과 이행에 관한 사항\n6. 성희롱ㆍ성폭력 예방을 위한 교육ㆍ홍보 등\n\n법제처                                                            52                                                   국가법령정보센터\n부대관리훈령\n③ 국방부 성폭력예방대응담당관은 각 군 본부 및 해병대사령부 성고충예방대응센터 운영실태를 주기적으로 점\n검한다.\n④ 각 군 본부 및 해병대사령부 성고충예방대응센터장은 예하 부대 성고충처리부서 운영실태를 주기적으로 점검\n한다.\n⑤ 각 급 부대의 장은 성희롱ㆍ성폭력 예방 및 고충처리 업무담당자(양성평등담당관 등)를 지정하며, 절차를 확\n립하고, 그 실태를 점검하여 문제점을 보완한다.',
  '① 국방부장관 및 소속기관장, 국방부 직할부대장, 합동참모의장 및 각 군 참모총장ㆍ해병대사령관\n은 성희롱 및 성폭력을 예방하기 위하여 자체 계획을 수립하고 그 시행을 지도ㆍ감독하여야 한다.\n② 각 급 부대의 장은 부대를 지휘ㆍ감독함에 있어서 건강한 근무분위기를 조성하고 주기적인 진단평가를 실시\n하여 성희롱 및 성폭력을 예방할 책임이 있다.\n③ 각 급 부대의 성희롱ㆍ성폭력 예방ㆍ대응업무를 담당하는 참모 등은 성희롱ㆍ성폭력 예방대책을 수립ㆍ시행\n하고 수시로 부대의 장에게 보고하여 이를 예방할 책임이 있다.\n④ 모든 군인 및 군무원은 성적 언행ㆍ요구에 대한 불응이나 성별 차이를 이유로 복무ㆍ근무평가ㆍ근무조건, 사\n기ㆍ복지 등에서 불이익과 불공정한 환경을 조성하는 행위를 하여서는 아니 된다.\n⑤ 성희롱 및 성폭력에 관한 고충을 접수한 자는 제249조 및 제249조의2에 따른 조치를 하여야 하고, 이를 묵인\n하거나 은폐ㆍ조작하여서는 아니 된다.\n⑥ 국방부 군인권개선추진단(양성평등정책팀장)은 양성평등의식 확산을 위해 성인지 교육을 주기적으로 계획하\n고 시행한다.',
  '① 국방부장관 및 소속기관장, 국방부 직할부대장, 합동참모의장 및 각 군 참모총장ㆍ해병대사령관\n은 성희롱 및 성폭력을 예방하기 위하여 자체 계획을 수립하고 그 시행을 지도ㆍ감독하여야 한다.\n② 각 급 부대의 장은 부대를 지휘ㆍ감독함에 있어서 건강한 근무분위기를 조성하고 주기적인 진단평가를 실시\n하여 성희롱 및 성폭력을 예방할 책임이 있다.\n③ 각 급 부대의 성희롱ㆍ성폭력 예방ㆍ대응업무를 담당하는 참모 등은 성희롱ㆍ성폭력 예방대책을 수립ㆍ시행\n하고 수시로 부대의 장에게 보고하여 이를 예방할 책임이 있다.\n④ 모든 군인 및 군무원은 성적 언행ㆍ요구에 대한 불응이나 성별 차이를 이유로 복무ㆍ근무평가ㆍ근무조건, 사\n기ㆍ복지 등에서 불이익과 불공정한 환경을 조성하는 행위를 하여서는 아니 된다.\n⑤ 성희롱 및 성폭력에 관한 고충을 접수한 자는 제249조 및 제249조의2에 따른 조치를 하여야 하고, 이를 묵인\n하거나 은폐ㆍ조작하여서는 아니 된다.\n⑥ 국방부 군인권개선추진단(양성평등정책팀장)은 양성평등의식 확산을 위해 성인지 교육을 주기적으로 계획하\n고 시행한다.',
  '국방부장관 및 소속기관장, 국방부 직할부대장, 합동참모의장 및 각 군 참모총장ㆍ\n해병대사령관은 성희롱ㆍ성폭력을 예방하기 위하여 다음 각 호의 임무를 수행하며, 국방부장관(군인권개선추진\n단 성폭력예방대응담당관)은 이를 확인ㆍ감독ㆍ통제한다.\n1. 예방교육\n가. 각 급 부대(기관) : 4대 폭력(성희롱, 성폭력, 가정폭력, 성매매) 예방 및 성인지 교육\n나. 성폭력예방 전담교관 운영(세부 운영계획은 각 군 위임)\n다. 주기적인 성과분석 및 평가\n2. 현장중심의 성희롱ㆍ성폭력 예방활동\n가. 주기적인(특별/연말연시 등) 현장중심 성희롱ㆍ성폭력 예방활동 강화\n나. 성희롱ㆍ성폭력 사건 발생부대에 대한 재발방지대책 확인/점검\n다. 기타 조직문화개선을 위해 필요하다고 판단 시 현장 활동 강화'],
 ['① 모든 군인 및 군무원은 성희롱ㆍ성폭력 관련 사실을 직접 목격하거나 타인에게 듣는 등 인지하였\n을 경우 지체없이 제242조제5호에 따른 양성평등계선으로 보고하여야 한다. 이때 양성평등계선 보고 외에 상급\n자(상급부대) 보고 또는 수사기관 등 신고는 피해자 의사에 반하여 할 수 없다.\n② 지휘계통에 따르지 아니하고 양성평등계선에 보고 등을 하였다는 이유로 어떠한 불이익한 조치를 할 수 없다.\n③ 성폭력 신고를 받은 수사기관은 피해자에게 양성평등계선에서 상담을 받을 수 있다는 사실을 알려야 하며, 피\n해자 의사에 따라 각 군 본부 및 해병대사령부 성고충예방대응센터(국방부 직할부대 및 합참은 국방부 성폭력예\n방대응담당관실)에 통보할 수 있다.\n\n법제처                                                            53                                                   국가법령정보센터\n부대관리훈령\n④ 각 군 본부 및 해병대사령부 성고충예방대응센터장은 성희롱ㆍ성폭력 관련 사실을 접수하였을 경우 국방부\n성폭력예방대응담당관에게 보고하여야 한다.\n⑤ 국방부 소속기관장 및 직할부대장, 합동참모의장 및 각 군 참모총장, 해병대사령관은 성희롱ㆍ성폭력 사건 발\n생 시 피해자의 명시적인 반대의견이 없으면 지체 없이 그 사실을 국방부장관에게 보고하고 성평등가족부장관에\n게 통보하여야 한다.',

In [47]:
#
# eval_df에 컬럼으로 추가
#
eval_df['response'] = response_list
eval_df['retrieved_contexts'] = retrieved_context_list
eval_df

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name,source,response,retrieved_contexts
0,대통령령에 따라 사회복무요원 소집이 연기된 사람이 다시 소집될 수 있는 경우는 무엇...,[① 지방병무청장은 사회복무요원 소집 순서가 결정된 사람을 대상으로 복무기관을 정\...,병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령...,Military Incident Reporting Officer,MISSPELLED,LONG,single_hop_specific_query_synthesizer,qdrant,사회복무요원 소집이 연기된 사람은 **그 연기 사유가 없어졌을 때** 다시 소집될 ...,[법 제29조제2항에 따라 사회복무요원 소집 순서에 따르지 않고 따로 사회복무\n요...
1,지방병무청장의 역할은 무엇인가요?,[① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 ...,지방병무청장은 입영 계획서에 따라 현역입영 통지서를 입영일 7일 전까지 대상자에게 ...,Military Incident Reporting Officer,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer,qdrant,정보가 부족해 답을 할 수없습니다.,"[지방병무청장은 병무지청장, 병역판정전담의사 또는 군의관이 법 또는 이 영에 따라 ..."
2,"군사경찰부대 뭐하는데, 사고나면 군사경찰부대가 어떻게 해야돼요, 그리고 사고속보는 ...",[① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각 호와 같다. 다만 ...,"사고가 발생하면 사고속보는 제262조에 따라 군사경찰계통으로 보고해야 하고, 사고 ...",Military Personnel Administrator,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer,qdrant,주어진 Context 기준으로만 답변드리면 다음과 같습니다.\n\n### 1) 군사...,[국방부 사고대책반의 임무는 다음 각 호와 같다.\n1. 사고발생 초기 상황유지 및...
3,국가법령정보센터에서 군 복무 중인 군인과 군무원이 반드시 지켜야 하는 맹세와 관련된...,"[군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세...",국가법령정보센터에서는 군에 복무 중인 군인과 근무 중인 군무원이 국가에 대하여 맹세...,Military Incident Reporting Officer,WEB_SEARCH_LIKE,LONG,single_hop_specific_query_synthesizer,qdrant,정보가 부족해 답을 할 수없습니다.,"[군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세..."
4,불침번이 근무 중 이상이 있을 때 당직계통에 어떻게 보고해야 합니까?,"[① 불침번은 건물 내ㆍ외를 완벽히 경계하여야 하며, 근무 중 지정된 위치를 떠나거...","불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, 당직계통의 상관에게 보고하...",Military Personnel Administrator,PERFECT_GRAMMAR,SHORT,single_hop_specific_query_synthesizer,qdrant,"불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, **당직계통의 상관에게 보...",[불침번은 통상 저녁점호 직후부터 다음날 기상시까지 생활관 또는 건물단위로\n지휘관...
5,국방부장관 입영계획서 언제 보내야되? 그리고 급여나 재해보상 관련해서 국방부장관이 ...,[<1-hop>\n\n① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군...,국방부장관은 입영기본 계획서를 입영일 40일 전까지 병무청장 및 해당 군 참모총장에...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant,정보가 부족해 답을 할 수없습니다.,[① 국방부장관은 제8조제1항에 따른 급여의 결정 및 지급에 관한 권한을\n대통령령...
6,국방부장관이 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여 입영 ...,[<1-hop>\n\n① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군...,"국방부장관은 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여, 입영...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant,국방부장관의 주요 역할은 다음과 같습니다.\n\n1. **입영기본 계획서 송부**\...,[① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 ...
7,"국방부 관련 규정에 따라 성희롱 또는 성폭력 사고가 발생했을 때, 보고의 유형과 보...",[<1-hop>\n\n① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각...,성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant,"부대관리훈령 제260조에 따르면, **성희롱ㆍ성폭력 사고**는 원칙적으로 **각 군...",[① 모든 군인 및 군무원은 성희롱ㆍ성폭력 관련 사실을 직접 목격하거나 타인에게 듣...
8,"국방부와 각 군 본부에서 성희롱 또는 성폭력 사고가 발생했을 때, 사고 보고의 유형...",[<1-hop>\n\n① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각...,성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant,"부대관리훈령 제260조에 따르면, **성희롱ㆍ성폭력은 각 군 본부 성고충예방대응센터...",[① 모든 군인 및 군무원은 성희롱ㆍ성폭력 관련 사실을 직접 목격하거나 타인에게 듣...
9,법제처에서 정한 규정에 따라 군인이나 군무원이 포로가 되었을 때 지켜야 하는 맹세 ...,"[<1-hop>\n\n군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음...",군에 복무 중인 군인이나 근무 중인 군무원은 법제처에서 정한 규정에 따라 국가와 민...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant,정보가 부족해 답을 할 수없습니다.,"[① 국가기관, 지방자치단체의 장 또는 고용주는 소속 공무원이나 임직원이 징집ㆍ소집..."
10,"국가법령정보센터에 따르면, 군 복무 중 포로가 되었을 때 군인이 지켜야 할 행동 원...","[<1-hop>\n\n군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음...","<1-hop>에 따르면, 군 복무 중인 군인이나 군무원은 국가에 대한 맹세에 따라 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant,정보가 부족해 답을 할 수없습니다.,"[① 군인은 법률에서 정하는 바에 따라 신분이 보장되며, 그 계급에 걸맞은 예우를 ..."

In [48]:
# eval_df를 ragas의 평가데이터셋 타입으로 변환
from ragas import EvaluationDataset
eval_dataset = EvaluationDataset.from_pandas(
    eval_df[["user_input", "retrieved_contexts", "response", "reference"]]
)
eval_dataset

EvaluationDataset(features=['user_input', 'retrieved_contexts', 'response', 'reference'], len=11)

In [49]:
#
# 평가
#
from ragas.metrics import (
    LLMContextRecall,
    LLMContextPrecisionWithReference,
    Faithfulness,
    AnswerRelevancy,
)
from ragas import evaluate

C:\Users\Playdata\AppData\Local\Temp\ipykernel_30664\3378832119.py:4: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_30664\3378832119.py:4: DeprecationWarning: Importing LLMContextPrecisionWithReference from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextPrecisionWithReference
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_30664\3378832119.py:4: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_30664\3378832119.py:4: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import (

In [50]:
# 평가할 때 사용할 LLM embedding 모델
eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

metrics = [
    LLMContextRecall(llm=eval_llm),
    LLMContextPrecisionWithReference(llm=eval_llm),
    Faithfulness(llm=eval_llm),
    AnswerRelevancy(llm=eval_llm, embeddings=eval_embeddings)

]
eval_result = evaluate(dataset=eval_dataset, metrics=metrics)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_30664\384477035.py:2: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\Playdata\AppData\Local\Temp\ipykernel_30664\384477035.py:3: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))
Evaluating:  14%|█▎        | 6/44 [00:05<00:24,  1.54it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  41%|████      | 18/44 [00:43<01:49,  4.20s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  73%|███████▎  | 32/44 [02:57<02:28, 12.39s/it]Exception raised in Job[10]: TimeoutError()
Evaluating:  75%|███████▌  | 33/44 [03:00<01:42,  9.32s/it]Exception raised in Job[26]: TimeoutError()
Evaluating:  77%|███████▋  | 34/44 [03:08<01:29,  8.97s/it]Exception raised in Job[28]: TimeoutError()
Exception raised in Job[30]: TimeoutError()
Evaluating:  86%|████████▋ | 38/44 [03:28<00:40,  6.71s/it]Exception raised in Job[32]: TimeoutError()
Evaluating:  93%|█████████▎| 41/44 [03:48<00:19,  6.63s/it]Exception raised in Job[34]: TimeoutError()
Evaluating: 100%|██████████| 44/44 [04:02<00:00,  5.50s/it]

In [51]:
eval_result

{'context_recall': 0.6640, 'llm_context_precision_with_reference': 0.5667, 'faithfulness': 0.2143, 'answer_relevancy': 0.2296}

In [52]:
result_df = eval_result.to_pandas()
result_df

,user_input,retrieved_contexts,response,reference,context_recall,llm_context_precision_with_reference,faithfulness,answer_relevancy
0,대통령령에 따라 사회복무요원 소집이 연기된 사람이 다시 소집될 수 있는 경우는 무엇...,[법 제29조제2항에 따라 사회복무요원 소집 순서에 따르지 않고 따로 사회복무\n요...,사회복무요원 소집이 연기된 사람은 **그 연기 사유가 없어졌을 때** 다시 소집될 ...,병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령...,1.000000,1.000000,0.5,0.539641
1,지방병무청장의 역할은 무엇인가요?,"[지방병무청장은 병무지청장, 병역판정전담의사 또는 군의관이 법 또는 이 영에 따라 ...",정보가 부족해 답을 할 수없습니다.,지방병무청장은 입영 계획서에 따라 현역입영 통지서를 입영일 7일 전까지 대상자에게 ...,0.000000,0.000000,0.0,0.000000
2,"군사경찰부대 뭐하는데, 사고나면 군사경찰부대가 어떻게 해야돼요, 그리고 사고속보는 ...",[국방부 사고대책반의 임무는 다음 각 호와 같다.\n1. 사고발생 초기 상황유지 및...,주어진 Context 기준으로만 답변드리면 다음과 같습니다.\n\n### 1) 군사...,"사고가 발생하면 사고속보는 제262조에 따라 군사경찰계통으로 보고해야 하고, 사고 ...",1.000000,0.416667,NaN,0.843799
3,국가법령정보센터에서 군 복무 중인 군인과 군무원이 반드시 지켜야 하는 맹세와 관련된...,"[군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세...",정보가 부족해 답을 할 수없습니다.,국가법령정보센터에서는 군에 복무 중인 군인과 근무 중인 군무원이 국가에 대하여 맹세...,1.000000,1.000000,0.0,0.000000
4,불침번이 근무 중 이상이 있을 때 당직계통에 어떻게 보고해야 합니까?,[불침번은 통상 저녁점호 직후부터 다음날 기상시까지 생활관 또는 건물단위로\n지휘관...,"불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, **당직계통의 상관에게 보...","불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, 당직계통의 상관에게 보고하...",1.000000,0.450000,1.0,0.810833
5,국방부장관 입영계획서 언제 보내야되? 그리고 급여나 재해보상 관련해서 국방부장관이 ...,[① 국방부장관은 제8조제1항에 따른 급여의 결정 및 지급에 관한 권한을\n대통령령...,정보가 부족해 답을 할 수없습니다.,국방부장관은 입영기본 계획서를 입영일 40일 전까지 병무청장 및 해당 군 참모총장에...,0.500000,0.250000,0.0,0.000000
6,국방부장관이 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여 입영 ...,[① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 ...,국방부장관의 주요 역할은 다음과 같습니다.\n\n1. **입영기본 계획서 송부**\...,"국방부장관은 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여, 입영...",1.000000,0.833333,NaN,0.330904
7,"국방부 관련 규정에 따라 성희롱 또는 성폭력 사고가 발생했을 때, 보고의 유형과 보...",[① 모든 군인 및 군무원은 성희롱ㆍ성폭력 관련 사실을 직접 목격하거나 타인에게 듣...,"부대관리훈령 제260조에 따르면, **성희롱ㆍ성폭력 사고**는 원칙적으로 **각 군...",성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,1.000000,NaN,0.000000
8,"국방부와 각 군 본부에서 성희롱 또는 성폭력 사고가 발생했을 때, 사고 보고의 유형...",[① 모든 군인 및 군무원은 성희롱ㆍ성폭력 관련 사실을 직접 목격하거나 타인에게 듣...,"부대관리훈령 제260조에 따르면, **성희롱ㆍ성폭력은 각 군 본부 성고충예방대응센터...",성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,0.950000,NaN,0.000000
9,법제처에서 정한 규정에 따라 군인이나 군무원이 포로가 되었을 때 지켜야 하는 맹세 ...,"[① 국가기관, 지방자치단체의 장 또는 고용주는 소속 공무원이나 임직원이 징집ㆍ소집...",정보가 부족해 답을 할 수없습니다.,군에 복무 중인 군인이나 근무 중인 군무원은 법제처에서 정한 규정에 따라 국가와 민...,0.142857,0.333333,0.0,0.000000
10,"국가법령정보센터에 따르면, 군 복무 중 포로가 되었을 때 군인이 지켜야 할 행동 원...","[① 군인은 법률에서 정하는 바에 따라 신분이 보장되며, 그 계급에 걸맞은 예우를 ...",정보가 부족해 답을 할 수없습니다.,"<1-hop>에 따르면, 군 복무 중인 군인이나 군무원은 국가에 대한 맹세에 따라 ...",0.333333,0.000000,0.0,0.000000

In [53]:
driver.close()