# 1. RAG 평가 개요
- RAG 평가란 RAG 시스템이 주어진 입력에 대해 얼마나 효과적으로 관련 정보를 검색하고, 이를 기반으로 정확하고 유의미한 응답을 생성하는지를 측정하는 과정이다. 
- **평가 요소**
    - **검색 단계 평가**
        - 입력 질문에 대해 검색된 문서나 정보의 관련성과 정확성을 평가.
    - **생성 단계 평가**
        - 검색된 정보를 기반으로 생성된 응답의 품질, 정확성등을 평가.
- **평가 방법**
    - **온/오프라인 평가**
        1. **오프라인 평가**
            - 미리 준비된 데이터셋을 활용하여 RAG 시스템의 성능을 측정한다.
        2. **온라인 평가**
            - 실제 사용자 트래픽과 피드백을 기반으로 시스템의 실시간 성능을 평가한다.
    - **정량적/정성적 평가**
        1. 정량적 평가
            - 자동화된 지표를 사용하여 생성된 텍스트의 품질을 평가한다.
        2. 정성적 평가
            - 전문가나 일반 사용자가 직접 생성된 응답의 품질을 평가하여 주관적인 지표를 평가한다.

# 2. [RAGAS](https://www.ragas.io/)
- RAGAS는 RAG 파이프라인을 **정량적으로 평가하는** 오픈소스 프레임 워크이다. 
- RAGAS 문서: https://docs.ragas.io/en/stable/
## 2.1 설치
- `pip install ragas rapidfuzz`

## 2.2 RAGAS 평가 지표 개요
![ragas_score](figures/ragas_score.png)
- **Generation**
    - llm 모델이 생성한 답변에 대한 평가 지표들.
    - **Faithfulness(신뢰성)**
        -  생성된 답변과 검색된 문서(context)간의 관련성을 평가하는 지표
        -  생성된 답변이 주어진 문맥(context)에 얼마나 충실한지를 평가하는 지표로 할루시네이션에 대한 평가로 볼 수있다.
    - **Answer relevancy(답변 적합성)**
        - 생성된 답변과 사용자의 질문간의 관련성을 평가하는 지표
        - 생성된 답변이 사용자의 질문과 얼마나 관련성이 있는지를 평가하는 지표.
- **Retrieval**
    -  질문에 대해 검색한 문서(context)들에 대한 평가
    -  **Context Precision(문맥 정밀도)**
        -  검색된 문서(context)들 중 질문과 관련 있는 것들이 **얼마나 상위 순위에 위치하는지** 평가하는 지표.
    -  **Context Recall(문맥 재현률)**
        -  검색된 문서(context)가 정답(ground-truth)의 정보를 얼마나 포함하고 있는지 평가하는 지표.
- 이러한 지표들은 RAG 파이프라인의 성능을 다각도로 평가하는 데 활용된다.
![RAGAS_score2](figures/RAGAS_score2.png)

## 2.3 주요 평가지표
### 2.3.1 Generation 평가
- LLM이 생성한 답변에 대한 평가
  
#### 2.3.1.1 Faithfulness (신뢰성)
- 생성된 답변이 얼마나 주어진 검색 문서들(context)를 잘 반영해서 생성되었는지 평가한다. 할루시네이션에 대한 평가라고 할 수 있다. 
- 점수범위: **0 ~ 1** (1에 가까울수록 좋음)
- 답변에 포함된 모든 주장이 context에서 얼마나 추출 가능한지를 확인한다.

##### 2.3.1.1.1평가 방법
1. Answer에서 주장 구문(claim statement)들을 생성(추출)한다. (주장이란, 질문(user input)과 관련된 내용)
    - 예) 
        - **질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요? 
        - **LLM 답변**: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 3000만명이다.
2. 각 주장들을 context로 부터 추론 가능한지 판단한다. 이를 바탕으로 faithfulness 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다. .... 한국의 인구는 5000만명이고 서울에 1000만이 살고 있다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 추론가능한 주장.
            - 한국의 인구는 3000만명이다. -> context에서 추론 불가능한 주장.
3. **Faithfulness score** 를 계산한다. 총 주장 수 중에서 context로 부터 추론가능한 주장의 개수.    
    - 예)
        - Faithfulness Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 유추할 수있다.)
    - LLM 답변에서 주장을 추출 하는 것과 각 주장이 context에서 추론 가능한 지를 판단하는 것은 LLM 을 활용한다.
- 공식
    $$
    \text{Faithfulness Score}\;=\;\cfrac{\text{주어진\;context\;에서\;추론할\;수\;있는\;주장의\;개수}}{\text{총\;주장\;개수}}
    $$

### 2.3.2 Answer relevancy (답변 적합성)
- 생성된 답변이 질문(user input)에 얼마나 잘 부합하는 지를 평가한다.
- 점수 범위: -1~1 (1에 가까울수록 좋음)
- LLM이 생성한 답변을 기반으로 질문들을 생성한다. 이렇게 생성한 질문들과 실제 질문(user input) 간의 유사도를 측정한다.

#### 2.3.2.1 평가방법
1. LLM이 생성한 답변을 기반으로 질문들을 생성한다.
    - 예) 
        - **LLM** 답변: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
2. 실제 질문과 생성한 질문간의 코사인 유사도를 측정한다. 그 평균이 최종 점수가 된다.
    - 예)
        - **실제 질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요?
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
- 공식
  $$
    \cfrac{1}{N} \sum_{i=1}^{N} \text{cosine\_similarity}(q_{\text{user}_{_i}}, q_{\text{generated}})
  $$

## 2.4 Retrieval 평가
Vector store에서 검색한 context에 대한 평가

### 2.4.1 Context Precision
- 검색된 문서(context)들 중 질문과 관련 있는 것들이 얼마나 **상위 순위**에 있는 지 평가.
- 점수 범위: 0~1 (1에 가까울수록 좋음)


#### 2.4.1.1평가방법

- 공식
$$
 \text{Context\;Precision@K} = \frac{\sum_{k=1}^{K} \left( \text{Precision@k} \times v_k \right)}{\ 상위\;K개\;결과에서의\;관련\;항목\;수}
$$
$$
 \text{Precision@k} = \frac{\text{True\;positive@k}}{(\text{True\;positive@k} + \text{False\;positive@k})} \\
$$
- $\text{Precision@k}$: 개별 문서에 대한 Precision
- K: context 의 개수(chuck 수)
- $v_k$: 관련성 여부로 0 또는 1. (0: 관련 없음, 1: 관련 있음)

#### 2.4.1.2 예시
- 질문과 context 관련성의 예
    - 질문: 한국의 수도는 어디이고 인구는 얼마나 되나요?
    - **높은 정밀도 context들**: 질문과 직접적인 관련이 있는 문서들
        - 한국의 수도는 서울이고 인구는 5000만명 입니다. 
        - 한국의 수도는 서울입니다.
        - 한국은 동아시아에 위치해 있는 국가로 수도는 서울입니다.
        - 한국의 인구는 5000만명 입니다.
    - **낮은 정밀도 context**: 한국과 관련있어 검색될 수 있지만 질문과 직접적 관련이 없다. 
        - 한국은 동아시아에 위치한 국가입니다.
        - 한국의 K-pop은 전 세계적으로 유명합니다.
        - 비빔밥, 불고기는 한국의 대표적인 음식입니다.
    - **높은 정밀도의 context이 상위 순위에 위치했으면 높은 점수를 받는다.**

- 점수 계산 예:
    - **상위 5개의 검색 결과 중 1번째, 3번째, 4번째 문서가 관련이 있다고 가정하자.**
    - **Precision@K 계산**
        ```bash
            Precision@1 = 1/1 = 1.0    # True positive@1/(True positive@1 + False positive@1).  1/1(1번 문서 계산 시에는 1개 문서만 있으므로 분모가 1이 된다.)
            Precision@2 = 1/2 = 0.5
            Precision@3 = 2/3 ≈ 0.67    
            Precision@4 = 3/4 = 0.75
            Precision@5 = 3/5 = 0.6
        ```
    - **vk의 값**
        - 1번째: $v_1 = 1$ - 관련있음
        - 2번째: $v_2 = 0$ - 관련없음
        - 3번째: $v_3 = 1$ - 관련있음
        - 4번째: $v_4 = 1$ - 관련있음
        - 5번째: $v_5 = 0$ - 관련없음

    - **Context Precision@5**
        $$
        \text{Context\;Precision@5} = \frac{(1.0 \times 1) + (0.5 \times 0) + (0.67 \times 1) + (0.75 \times 1) + (0.6 \times 0)}{3} = \frac{1.0 + 0 + 0.67 + 0.75 + 0}{3} ≈ 0.807
        $$

### 2.4.2 Context Recall (문맥 재현률)
- 검색된 문서(context)가 얼마나 정답(ground-truth)의 정보를 포함있는 지 평가하는 지표
- 점수 범위: 0~1 (1에 가까울수록 좋음)
- **정답(ground truth)의 각 주장(claim)이 검색된 context와 얼마나 일치**하는지 계산함.

#### 2.4.2.1 평가방법
1. 정답에서 주장(claim)들을 생성(추출)한다.
    - 예) 
        - **정답**: 한국의 수도는 서울이고 인구수는 5000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 5000만명이다.
2. 각 주장(claim)의 정보를 검색된 contexts에서 찾을 수 있는지 판별한다. 이를 바탕으로 context recall 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 찾을 수 있다.
            - 한국의 인구는 5000만명이다. -> context에서 찾을 수 없다.
3. **Context Recall Score** 를 계산한다. 총 주장 수 중에서 context로 부터 찾을 수 있는 주장의 개수.
    - 예)
        - Context Recall Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 찾을 수 있다.)

- 공식
    $$
    \text{Context Recall Score}\;=\;\cfrac{\text{GT의\;주장\;중\;주어진\;context\;에서\;찾을\;수\;있는\;주장의\;개수}}{\text{GT의\;총\;주장\;개수}}
    $$

# 3. RAGAS 평가 실습

In [5]:
# !uv pip install ragas rapidfuzz
# 설치 후 커널 재시작

In [6]:
# docker run -p 6333:6333 -p 6334:6334   -v qdrant_storage:/qdrant/storage   qdrant/qdrant
# termianal에서 실행

## 0. 패키지 설치

In [7]:
# 필요한 library: pymupdf pdfplumber pillow openai qdrant-client langchain-core langchain-openai langchain-qdrant langchain-text-splitters python-dotenv

## 1. 설정 및 클라이언트 준비

In [8]:
import os
import re
import glob
import uuid
from pathlib import Path

import fitz  # PyMuPDF
import pdfplumber
from PIL import Image
from openai import OpenAI
from dotenv import load_dotenv

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, Filter, FieldCondition, MatchValue

from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings
from langchain_qdrant import QdrantVectorStore
from langchain_text_splitters import RecursiveCharacterTextSplitter

load_dotenv()

# ----- 설정값 -----
GUIDANCE_DIR = "./길라잡이"          # 이 폴더 안의 모든 PDF를 찾아서 적재

QDRANT_URL = os.getenv("QDRANT_URL", "http://localhost:6333")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY") or None
COLLECTION_NAME = "guidance_vectordb"

CHAT_MODEL = "gpt-5.4-mini"                          # 표 요약 / 이미지 캐법션용
EMBED_MODEL = "text-embedding-3-large"         # large 임베딩 모델
EMBED_DIM = 3072

CHUNK_SIZE = 800       # 텍스트 청크 최대 글자 수 (splitter 기준)
CHUNK_OVERLAP = 150    # 청크 간 격치는 글자 수 (문맥 끓김 방지)

openai_client = OpenAI()
qdrant_client = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)
embeddings = OpenAIEmbeddings(model=EMBED_MODEL)


def ensure_collection() -> bool:
    """collection이 이미 있으면 True(기존 데이터 존재), 없으면 새로 만들고 False를 반환"""
    existing = [c.name for c in qdrant_client.get_collections().collections]
    if COLLECTION_NAME in existing:
        print(f"'{COLLECTION_NAME}' collection이 이미 존재합니다.")
        return True
    qdrant_client.create_collection(
        collection_name=COLLECTION_NAME,
        vectors_config=VectorParams(size=EMBED_DIM, distance=Distance.COSINE),
    )
    print(f"'{COLLECTION_NAME}' collection 생성 완료 (dim={EMBED_DIM})")
    return False


collection_already_existed = ensure_collection()

vectorstore = QdrantVectorStore(
    client=qdrant_client,
    collection_name=COLLECTION_NAME,
    embedding=embeddings,
)

pdf_paths = sorted(glob.glob(str(Path(GUIDANCE_DIR) / "*.pdf")))
print(f"'{GUIDANCE_DIR}' 안에서 발견된 PDF {len(pdf_paths)}개")
for p in pdf_paths:
    print(" -", p)

'guidance_vectordb' collection이 이미 존재합니다.
'./길라잡이' 안에서 발견된 PDF 2개
 - 길라잡이\사병_길라잡이.pdf
 - 길라잡이\초급간부_길라잡이.pdf

## 2. 텍스트 정제

In [9]:
def clean_text(text: str) -> str:
    # Private Use Area (U+E000–U+F8FF) 문자 제거
    text = re.sub(r'[\ue000-\uf8ff]', '', text)
    # 과도한 공백/빈 줄 정리
    text = re.sub(r'[ \t]+', ' ', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

## 3. 표 추출 → 마크다운 → 요약

In [10]:
def table_to_markdown(table_rows):
    rows = [[cell if cell is not None else "" for cell in row] for row in table_rows]
    if not rows:
        return ""
    header = rows[0]
    body = rows[1:]
    md_lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(["---"] * len(header)) + " |"]
    for row in body:
        md_lines.append("| " + " | ".join(row) + " |")
    return "\n".join(md_lines)


def extract_tables(pdf_path: str):
    tables_out = []
    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, start=1):
            for table in page.extract_tables():
                if not table or len(table) < 2:
                    continue
                md_table = table_to_markdown(table)
                tables_out.append({"page": page_num, "markdown": md_table})
    return tables_out


def summarize_table(table_markdown: str) -> str:
    response = openai_client.chat.completions.create(
        model=CHAT_MODEL,
        max_completion_tokens=300,
        messages=[{
            "role": "user",
            "content": (
                "다음은 문서에서 추출한 표입니다. 이 표가 어떤 내용을 담고 있는지 "
                "검색에 활용할 수 있도록 2~4문장의 한국어로 요약해줘. "
                "컬럼이 의미하는 바와 주요 수치/항목을 포함해줘.\n\n"
                f"{table_markdown}"
            ),
        }],
    )
    return response.choices[0].message.content.strip()

## 4. 텍스트 청킹 (페이지 단위)

In [11]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    separators=["\n\n", "\n", ". ", " ", ""],
)

# 이 길이를 넘는 페이지만 splitter로 추가 분할 (그 외엔 페이지 통째로 한 청크)
PAGE_OVERFLOW_THRESHOLD = 1200


def chunk_text_by_page(pdf_path: str) -> list[dict]:
    """페이지 단위로 청크를 만든다. 페이지가 너무 길 때만 그 페이지 안에서 추가로 나눈다."""
    doc = fitz.open(pdf_path)
    results = []

    for page_num, page in enumerate(doc, start=1):
        page_text = clean_text(page.get_text("text"))

        if not page_text:
            continue  # 텍스트 없는 페이지(이미지만 있는 페이지 등)는 건너뜀

        if len(page_text) <= PAGE_OVERFLOW_THRESHOLD:
            results.append({"page": page_num, "text": page_text})
        else:
            # 이 페이지만 너무 길어서 임베딩이 흐려질 수 있는 경우 -> 페이지 내부에서만 분할
            sub_chunks = text_splitter.split_text(page_text)
            for sub in sub_chunks:
                results.append({"page": page_num, "text": sub})

    doc.close()
    return results

## 5. PDF 1개 → LangChain `Document` 리스트로 통합

In [12]:
ID_NAMESPACE = uuid.NAMESPACE_URL


def make_id(doc_name: str, chunk_type: str, index: int) -> str:
    """같은 PDF를 다시 적재해도 같은 ID가 나오도록 결정론적으로 생성 (재실행 시 upsert로 덮어씀)"""
    return str(uuid.uuid5(ID_NAMESPACE, f"{doc_name}::{chunk_type}::{index}"))


def build_documents_for_pdf(pdf_path: str) -> tuple[list[Document], list[str]]:
    doc_name = Path(pdf_path).name
    documents = []
    ids = []
    counter = 0

    # 1) 텍스트 청크
    text_chunks = chunk_text_by_page(pdf_path)
    for c in text_chunks:
        documents.append(Document(
            page_content=c["text"],
            metadata={"doc_name": doc_name, "page": c["page"], "type": "text"},
        ))
        ids.append(make_id(doc_name, "text", counter))
        counter += 1

    # 2) 표
    tables = extract_tables(pdf_path)
    for t in tables:
        summary = summarize_table(t["markdown"])
        documents.append(Document(
            page_content=summary,
            metadata={
                "doc_name": doc_name, "page": t["page"], "type": "table",
                "table_markdown": t["markdown"], "summary": summary,
            },
        ))
        ids.append(make_id(doc_name, "table", counter))
        counter += 1

    print(f"[{doc_name}] 텍스트 {len(text_chunks)} / 표 {len(tables)} → 총 {len(documents)}개")
    return documents, ids

## 6. 디렉토리 전체 적재 (upsert)

In [13]:
def upsert_documents(documents: list[Document], ids: list[str], batch_size: int = 100):
    for i in range(0, len(documents), batch_size):
        batch_docs = documents[i:i + batch_size]
        batch_ids = ids[i:i + batch_size]
        vectorstore.add_documents(documents=batch_docs, ids=batch_ids)
        print(f"  upsert 진행: {min(i + batch_size, len(documents))}/{len(documents)}")


def run_pipeline(directory: str = GUIDANCE_DIR):
    paths = sorted(glob.glob(str(Path(directory) / "*.pdf")))
    print(f"'{directory}'에서 PDF {len(paths)}개 발견, 적재 시작\n")

    total_chunks = 0
    for pdf_path in paths:
        documents, ids = build_documents_for_pdf(pdf_path)
        upsert_documents(documents, ids)
        total_chunks += len(documents)
        print()

    print(f"완료: PDF {len(paths)}개 / 총 {total_chunks}개 청크 적재")


# collection이 이미 있었다면 재적재를 건너뜀 (PDF 파싱/표 요약/임베딩 API 재호출 비용 방지)
if not collection_already_existed:
    run_pipeline(GUIDANCE_DIR)
else:
    print(f"'{COLLECTION_NAME}' 컴렉션에 이미 데이터가 있어 적재를 건너뜁니다. (재적재하려면 run_pipeline(GUIDANCE_DIR)를 직접 호출하세요)")

'guidance_vectordb' 컴렉션에 이미 데이터가 있어 적재를 건너뜁니다. (재적재하려면 run_pipeline(GUIDANCE_DIR)를 직접 호출하세요)

## 7. 검색 예시

In [14]:
def search(query: str, k: int = 5, type_filter: str = None):
    qfilter = None
    if type_filter:
        qfilter = Filter(must=[FieldCondition(key="metadata.type", match=MatchValue(value=type_filter))])

    results = vectorstore.similarity_search_with_score(query, k=k, filter=qfilter)

    for doc, score in results:
        print(f"[score={score:.3f}] doc={doc.metadata.get('doc_name')} page={doc.metadata.get('page')} type={doc.metadata.get('type')}")
        print(doc.page_content[:200])
        print("-" * 40)

    return results


# 사용 예시:
search("군인 해택 휴양시설알려줘")
# search("휴가 관련 표", type_filter="table")
# search("기차 할인 안내 이미지", type_filter="image")

[score=0.585] doc=사병_길라잡이.pdf page=23 type=text
2026 병 복지 길라잡이 23
 • 국군복지단 휴양시설 현황
구분
시 설 명
위 치
전화번호(군)
전화번호(일반)
직영
서귀포 호텔
제주 서귀포시
960-7703
064-738-0123
화진포 콘도
강원 고성군
960-7706
033-682-0500
청간정 콘도
강원 고성군
822-6470
033-631-9331
송 정 콘도
강원 강릉시
940-38
----------------------------------------
[score=0.549] doc=사병_길라잡이.pdf page=22 type=text
Part 01 생활편의 분야
22 2026 병 복지 길라잡이
휴양시설 이용
이용대상 / 방법 및 혜택
 • 이용대상 : 현역병, 배우자 및 그 직계 존·비속
 * 가족의 경우 가족관계 증빙서류, 신분증 또는 국방가족 모바일증명 제시
 * 국방가족 모바일증명은 국군복지포털 홈페이지를 이용하여 등록
 • 국군복지단 휴양시설 이용방법
 - 국군복지포털 홈페이지
----------------------------------------
[score=0.543] doc=초급간부_길라잡이.pdf page=35 type=text
34
2026 초급간부 길라잡이
•국군복지단 휴양시설 현황
구분
시 설 명
위 치
전화번호(군)
전화번호(일반)
직영
서귀포 호텔
제주 서귀포시
960-7703
064-738-0123
화진포 콘도
강원 고성군
960-7706
033-682-0500
청간정 콘도
강원 고성군
988-7873
033-631-9331
송정 콘도
강원 강릉시
940-3881
----------------------------------------
[score=0.525] doc=초급간부_길라잡이.pdf page=34 type=text
02
Part
생
활
편
의

분
야
33
2026 초급간부 길라잡이
•국군복지단 초급간부전용 객실예약 이용방법
- 국군복지포털 호텔/콘도/컨벤션-객실예약-‘초급간부전용 객실예약’ 활용
- 국군복지단 휴양시설 세부 이용절차
신청/접수
•인터넷 : 국군복지단 홈페이지(www.welfare.mil.kr)
 * 스마트폰 : 국군복지포털 앱 ⇨ 호텔/콘도
----------------------------------------
[score=0.507] doc=초급간부_길라잡이.pdf page=35 type=table
이 표는 국군복지단에서 이용 가능한 숙박·콘도 시설 목록으로, **시설명**, **위치**, **군 전화번호**, **일반 전화번호**를 정리한 자료입니다. 서귀포 호텔, 화진포 콘도, 청간정 콘도, 송정 콘도, 대천 콘도 등 개별 시설과 함께 한화·금호·소노·켄싱턴 같은 제휴 리조트 브랜드별 이용 가능 지역도 포함되어 있습니다. 대표 연락처로는 서귀포 호
----------------------------------------

[(Document(metadata={'doc_name': '사병_길라잡이.pdf', 'page': 23, 'type': 'text', '_id': 'fb4aa98d-c931-5260-82b6-e1fa8da946b5', '_collection_name': 'guidance_vectordb'}, page_content='2026 병 복지 길라잡이 23\n • 국군복지단 휴양시설 현황\n구분\n시 설 명\n위 치\n전화번호(군)\n전화번호(일반)\n직영\n서귀포 호텔\n제주 서귀포시\n960-7703\n064-738-0123\n화진포 콘도\n강원 고성군 \n960-7706\n033-682-0500\n청간정 콘도\n강원 고성군 \n822-6470\n033-631-9331\n송 정 콘도\n강원 강릉시 \n940-3881\n033-652-7573\n대 천 콘도\n충남 보령시 \n960-7705\n041-932-6305\n민영\n한 화\n설악, 용인, 대천, 산정호수, \n해운대, 경주, 제주, 평창, 거제\n국군복지단\n예약실\n984-6584\n국군복지단\n예약실\n1577-9800\n내선 “1번”\n금 호\n통영, 화순, 설악, 제주, 아산\n소 노\n설악, 경주, 단양, 홍천, 양양, \n변산, 거제, 삼척, 진도, 여수, \n고양(호텔), 양평\n켄싱턴\n남원, 설악비치, 충주, 경주,\n가평, 설악밸리, 하동, 서귀포\n무 주\n전북무주\n리 솜\n안면도\n엘도라도\n전남신안\n샤인빌(소노캄)\n제주\n보 광\n제주\n웰리힐리\n강원횡성\n영랑호\n강원 속초\n현대수\n강원 속초\n • 각 군 휴양시설 이용방법 : 각 군 홈페이지 참조\n구분\n시 설 명\n홈페이지 주소\n국방부\n국방컨벤션(웨딩)\nwww.mndconvention.co.kr\n육군\n로카우스 호텔, 계룡스파텔\nwelfare.army.mil.kr\n해군\n해군호텔(서울, 평택, 제주), \n해군회관(진해)\nwelfare.navy.mil.kr\n공군\n공군호텔\nwww.airforcehotel.co.kr\n그린나래호텔\nwww.guerinnarae.com\n해병대\n밀리토피아호텔 바이마린(해병대호텔)\nwww.militopiahotelbymarine.com'),
  0.5851183),
 (Document(metadata={'doc_name': '사병_길라잡이.pdf', 'page': 22, 'type': 'text', '_id': '40497236-80dc-5f46-b78d-a7b918de24d9', '_collection_name': 'guidance_vectordb'}, page_content='Part 01 생활편의 분야\n22 2026 병 복지 길라잡이\n휴양시설 이용\n이용대상 / 방법 및 혜택\n • 이용대상 : 현역병, 배우자 및 그 직계 존·비속\n * 가족의 경우 가족관계 증빙서류, 신분증 또는 국방가족 모바일증명 제시\n * 국방가족 모바일증명은 국군복지포털 홈페이지를 이용하여 등록\n • 국군복지단 휴양시설 이용방법\n - 국군복지포털 홈페이지 메인화면에 ‘병사전용 회원가입 메뉴’ 활용\n * 최소한의 정보(군번, 군구분, 성명 입력 → ID / PW 생성)로 가입 가능\n - 국군복지단 휴양시설 세부 이용절차\n신청/\n접수\n∙ 인터넷 : 국군복지포털 홈페이지(http://www.welfare.mil.kr)\n* 스마트폰 : 국군복지포털 앱 ⇨ 호텔/콘도 ⇨ 현역병 전용 예약\n∙ 예약/회원가입 : 군 984-6584, 일반 1577-9800 내선 1번\n신청시기\n예약확정\n∙ 직영 시설 이용일 기준 30일 전 00시~8일 전 23:59까지 신청\n 민영 시설 이용일 기준 30일 전 00시∼22일 전 23:59\n예약자 \n통보\n∙ 예약확정 시 이용 안내문자 발송\n1회 숙박\n가능기간\n∙ 성수기/ 비수기 주말(금, 토) : 2박 3일(제주지역: 3박 4일)\n∙ 비수기 평일(일 ~ 목) : 4박 5일\n * 여름⋅겨울 성수기(스키장운영 민영콘도만 해당) 기간 중\n 시설 이용은 1인 1회 / 기타 기간은 월 2회\n \n • 혜 택\n - 국군복지단 휴양시설(민영, 직영) 병사(가족) 대상 객실 우선 할당\n * 현역 이용 객실의 20%\n * 예약방법: 국군복지포털 홈페이지 내 ‘현역병 전용 객실예약’ 활용\n - 국군복지단 직영 휴양시설 성수기를 제외한 기간 중 평일 객실 30% 할인 \n * 현역병 본인 투숙 시\n * 직영콘도별 성수기 기간 : (제주) 매년 12월 1일 ∼ 2월 29일 /\n (제주 외) 매년 7월 1일 ~ 8월 31일'),
  0.5488748),
 (Document(metadata={'doc_name': '초급간부_길라잡이.pdf', 'page': 35, 'type': 'text', '_id': '1ae0cc80-62b3-5c57-9da7-42a7b205c3cf', '_collection_name': 'guidance_vectordb'}, page_content='34 \n2026 초급간부 길라잡이\n•국군복지단 휴양시설 현황\n구분\n시 설 명\n위 치\n전화번호(군)\n전화번호(일반)\n직영\n서귀포 호텔\n제주 서귀포시\n960-7703\n064-738-0123\n화진포 콘도\n강원 고성군 \n960-7706\n033-682-0500\n청간정 콘도\n강원 고성군 \n988-7873\n033-631-9331\n송정 콘도\n강원 강릉시 \n940-3881\n033-652-7573\n대천 콘도\n충남 보령시 \n960-7705\n041-932-6305\n민영\n한 화\n 거제, 경주, 대천, \n산정호수, 설악, 용인, \n제주, 평창, 해운대\n국군복지단\n예약실\n984-6499\n국군복지단\n예약실\n1577-9800\n금 호\n 통영, 화순, 설악, 제주, 아산\n소 노\n 경주, 거제, 고양, 단양,\n변산, 삼척, 설악, 진도,\n양양, 양평, 여수, 홍천\n켄싱턴\n남원, 설악비치, 충주, \n경주, 가평, 설악밸리, \n하동, 서귀포\n무 주\n전북 무주\n리 솜\n안면도\n엘도라도\n전남 신안\n샤인빌\n제주\n보 광\n제주\n웰리힐리\n강원 횡성\n영랑호\n강원 속초\n현대수\n강원 속초\n국방부 복지정책과 복지운영담당 | 900-6617\n담당부서'),
  0.54266524),
 (Document(metadata={'doc_name': '초급간부_길라잡이.pdf', 'page': 34, 'type': 'text', '_id': '58b67cb3-15b4-5cad-9036-b93e98e25e44', '_collection_name': 'guidance_vectordb'}, page_content='02\nPart\n생\n활\n편\n의\n \n분\n야\n33 \n2026 초급간부 길라잡이\n•국군복지단 초급간부전용 객실예약 이용방법\n- \x07국군복지포털 호텔/콘도/컨벤션-객실예약-‘초급간부전용 객실예약’ 활용\n- 국군복지단 휴양시설 세부 이용절차\n신청/접수\n•\x07인터넷 : 국군복지단 홈페이지(www.welfare.mil.kr)\n * 스마트폰 : 국군복지포털 앱 ⇨ 호텔/콘도 ⇨ 초급간부 전용 예약\n•\x07예약/회원가입 : 군 984-6499, 일반 1577-9800 내선 1번\n신청시기/ \n예약확정\n•\x07기간 : 이용일 기준 50일 전일 00:00 ∼ 30일 전일 23:59\n•\x07예약확정 확인 : 이용일 기준 29일 전일 10:00 확정(복지포털 확인)\n * 추첨제 탈락 시 : 일반 예약신청(점수제) 자동 전환 / 자동 전환 취소 가능\n예약자 통보\n•\x07예약확정 시 이용 안내문자 발송\n1회 숙박\n가능기간\n•\x07성수기/비수기 주말(금, 토) : 2박 3일(제주지역: 3박 4일)\n•\x07비수기 평일(일 ~ 목) : 4박 5일\n * \x07여름·겨울 성수기(스키장운영 민영콘도만 해당) 기간 중 시설 이용은 1인 1회 / \n기타 기간은 월 2회 \n•비수기 잔여객실 회원초대제도\n- 현역간부, 가족(직계존비속) 외 비회원을 초대하여 단독 이용기회 \n* \x07예약기간 : 내륙-이용일 기준 10일 전 ~ 4일 전, 제주-이용일 기준 25일 전 ~ 4일 전 \n* 요금적용 : 회원요금과 동일(직영시설의 경우 부가가치세 10% 추가)\n* 예약방법 : 잔여객실 예약에서 ‘초대함’ 선택 및 실제 이용자 입력\n* 초대한도 : 연 5회\n•각 군 휴양시설 이용방법 : 각 군 홈페이지 참조\n구분\n시 설 명\n홈페이지\n국방부\n국방컨벤션\nwww.mndconvention.co.kr\n육군\n계룡스파텔, ROKAUS호텔\nwelfare.army.mil.kr\n해군\n해군호텔(서울, 평택, 제주), \n해군회관(진해)\nwelfare.navy.mil.kr\n공군\n공군호텔\nwww.airforcehotel.co.kr\n그린나래호텔\nwww.guerinnarae.com\n해병대\n밀리토피아 호텔 바이마린\nwww.militopiahotelbymarine.com\n* 현역 결혼, 가족 행사시 컨벤션 할인 혜택 : 각 기관 홈페이지 확인'),
  0.5252058),
 (Document(metadata={'doc_name': '초급간부_길라잡이.pdf', 'page': 35, 'type': 'table', 'table_markdown': '| 구분 | 시 설 명 | 위 치 | 전화번호(군) | 전화번호(일반) |\n| --- | --- | --- | --- | --- |\n|  | 서귀포 호텔 | 제주 서귀포시 | 960-7703 |  |\n|  | 화진포 콘도 | 강원 고성군 | 960-7706 |  |\n|  | 청간정 콘도 | 강원 고성군 | 988-7873 |  |\n|  | 송정 콘도 | 강원 강릉시 | 940-3881 |  |\n|  | 대천 콘도 | 충남 보령시 | 960-7705 |  |\n|  | 한 화 | 거제, 경주, 대천,\n산정호수, 설악, 용인,\n제주, 평창, 해운대 | 국군복지단\n예약실\n984-6499 |  |\n|  | 금 호 | 통영, 화순, 설악, 제주, 아산 |  |  |\n|  | 소 노 | 경주, 거제, 고양, 단양,\n변산, 삼척, 설악, 진도,\n양양, 양평, 여수, 홍천 |  |  |\n|  | 켄싱턴 | 남원, 설악비치, 충주,\n경주, 가평, 설악밸리,\n하동, 서귀포 |  |  |\n|  | 무 주 | 전북 무주 |  |  |\n|  | 리 솜 | 안면도 |  |  |\n|  | 엘도라도 | 전남 신안 |  |  |\n|  | 샤인빌 | 제주 |  |  |\n|  | 보 광 | 제주 |  |  |\n|  | 웰리힐리 | 강원 횡성 |  |  |\n|  | 영랑호 | 강원 속초 |  |  |\n|  | 현대수 | 강원 속초 |  |  |', 'summary': '이 표는 국군복지단에서 이용 가능한 숙박·콘도 시설 목록으로, **시설명**, **위치**, **군 전화번호**, **일반 전화번호**를 정리한 자료입니다. 서귀포 호텔, 화진포 콘도, 청간정 콘도, 송정 콘도, 대천 콘도 등 개별 시설과 함께 한화·금호·소노·켄싱턴 같은 제휴 리조트 브랜드별 이용 가능 지역도 포함되어 있습니다. 대표 연락처로는 서귀포 호텔 960-7703, 화진포 콘도 960-7706, 청간정 콘도 988-7873, 송정 콘도 940-3881, 대천 콘도 960-7705가 기재되어 있으며, 한화 예약실은 984-6499로 표시되어 있습니다.', '_id': '7f46223c-b7fa-5103-9b15-f793fae79e32', '_collection_name': 'guidance_vectordb'}, page_content='이 표는 국군복지단에서 이용 가능한 숙박·콘도 시설 목록으로, **시설명**, **위치**, **군 전화번호**, **일반 전화번호**를 정리한 자료입니다. 서귀포 호텔, 화진포 콘도, 청간정 콘도, 송정 콘도, 대천 콘도 등 개별 시설과 함께 한화·금호·소노·켄싱턴 같은 제휴 리조트 브랜드별 이용 가능 지역도 포함되어 있습니다. 대표 연락처로는 서귀포 호텔 960-7703, 화진포 콘도 960-7706, 청간정 콘도 988-7873, 송정 콘도 940-3881, 대천 콘도 960-7705가 기재되어 있으며, 한화 예약실은 984-6499로 표시되어 있습니다.'),
  0.50705904)]

## 8. Retriever 생성

In [15]:
##################################################
# retriever 생성
##################################################

def get_retriever(vectorstore, k: int = 5):
    retriever = vectorstore.as_retriever(
        search_kwargs={"k": k}
    )
    return retriever


retriever = get_retriever(vectorstore)
print(retriever)

tags=['QdrantVectorStore', 'OpenAIEmbeddings'] vectorstore=<langchain_qdrant.qdrant.QdrantVectorStore object at 0x000002911D0A8590> search_kwargs={'k': 5}

In [16]:
################################################################################
# 평가할 RAG Chain
################################################################################

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser
from langchain_core.documents import Document
from langchain_openai import ChatOpenAI

prompt_txt = """<instruction>
당신은 정보제공을 목적으로하는 유능한 AI Assistant 입니다.
주어진 context의 내용을 기반으로 질문에 답변을 합니다.
Context에 질문에 대한 명확한 정보가 있는 경우 그것을 바탕으로 답변을 합니다.
Context에 질문에 대한 명확한 정보가 없는 경우 "정보가 부족해 답을 할 수없습니다." 라고 답합니다.
절대 추측이나 일반 상식을 바탕으로 답을 하거나 Context 없는 내용을 만들어서 답변해서는 안됩니다.
</instruction>
<context>
{context}
</context>
<question>
{query}
</question>
"""
prompt = ChatPromptTemplate.from_template(template=prompt_txt)

model = ChatOpenAI(model="gpt-5.4-mini")
parser = StrOutputParser()


def format_docs_for_prompt(documents: list[Document]) -> str:
    """LLM 프롬프트({context})용: 문서들을 하나의 문자열로 합침 (doc_name/page도 같이 표기)"""
    parts = []
    for doc in documents:
        meta = doc.metadata
        header = f"[{meta.get('doc_name', '')} p.{meta.get('page', '')}]"
        parts.append(f"{header}\n{doc.page_content}")
    return "\n\n---\n\n".join(parts)


def format_docs_for_ragas(documents: list[Document]) -> list[str]:
    """RAGAS 평가용: 검색된 문서 각각의 내용을 list[str]로 추출"""
    return [doc.page_content for doc in documents]


def build_prompt_input(state: dict) -> dict:
    """검색 결과({'documents':..., 'query':...})를 prompt 입력({'context':str, 'query':str})으로 변환"""
    return {
        "context": format_docs_for_prompt(state["documents"]),
        "query": state["query"],
    }


# 1단계: 질문으로 검색 → 원본 Document 리스트 + 질문 보존 (retriever는 여기서 1회만 호출됨)
retrieve_step = {
    "documents": retriever,
    "query": RunnablePassthrough(),
}

# RAG 체인 -> RAG 평가 데이터셋을 만드는 RAG Chain -> 최종응답: LLM 응답(str), 검색한 문서들(list[str]), 질문(str)
chain = (
    RunnablePassthrough()  # dict | dict 가 파이썬 dict 병합 연산으로 취급되는 것을 막기 위해 필요
    | retrieve_step
    | {
        "response": RunnableLambda(build_prompt_input) | prompt | model | parser,
        "retrieved_context": RunnableLambda(lambda state: format_docs_for_ragas(state["documents"])),
        "query": RunnableLambda(lambda state: state["query"]),
    }
)

In [17]:
res = chain.invoke("병장의 월급은?")

In [18]:
res["response"]

'병장의 월급은 **1,500,000원**입니다.'

In [19]:
res["retrieved_context"]

['Part 01 생활편의 분야\n6 2026 병 복지 길라잡이\n보 수\n봉 급\n • 계급별 지급액\n 단위 : 원\n \n이병\n일병\n상병\n병장\n750,000\n900,000\n1,200,000\n1,500,000\n • 병 봉급 인상\n 단위 : 원\n연도\n계급\n’21년\n’22년\n’23년\n’24년\n’25~’26년\n병 장 \n608,500\n676,100\n1,000,000\n1,250,000\n1,500,000\n상 병 \n549,200\n610,200\n800,000\n1,000,000\n1,200,000\n일 병\n496,900\n552,100\n680,000\n800,000\n900,000\n이 병\n459,100\n510,100\n600,000\n640,000\n750,000\n인상율(병장)\n12.5%\n11.1%\n47.9%\n25%\n20%\n* 병역의무 이행자의 보상과 예우를 위해 병 봉급과 자산형성프로그램을 결합하여\n’25년까지 병장 기준 200만원 이상으로 인상\n수 당\n단위 : 원\n \n구 분\n지급 기준\n금액\n특수지\n근 무\n수 당\n갑\n・비무장지대, 서해5도, 울릉도, 접적 해역 상주 근무자\n * 가산금 : 서해5도 40,000원, 비무장지대 및 \n북방한계선 인접해역 20,000원\n25,000 \n(가산금별도)\n을\n・GOP, 해안초소, 해발 800m 이상 고지대 상주 근무자\n * 가산금 : 10,000원(GOP / 해안초소)\n20,000\n(가산금별도)\n항 공\n수 당\n을\n・항공기 동승근무자\n40,000 \n함 정\n수 당\n을\n・전투함 및 지원함 승무원\n * 함정출동가산금 : 1일 4,000원\n32,700 \n(가산금별도)\n병\n・수륙양용궤도차량 승무원\n32,700 \npart 01\n생활편의 분야\n▶▶▶ 병 복지혜택 이렇게 다양합니다',
 '이 표는 **계급별 연도(’21~’26년) 급여 수준과 병장 급여 인상률**을 비교한 자료입니다. 행은 **병장·상병·일병·이병**의 월급이며, 열은 **’21년, ’22년, ’23년, ’24년, ’25~’26년**의 금액 변화를 보여줍니다. 주요 수치로 병장 급여는 **60.85만 원 → 67.61만 원 → 100만 원 → 125만 원 → 150만 원**, 상병은 **54.92만 원 → 61.02만 원 → 80만 원 → 100만 원 → 120만 원**, 일병은 **49.69만 원 → 55.21만 원 → 68만 원 → 80만 원 → 90만 원**, 이병은 **45.91만 원 → 51.01만 원 → 60만 원 → 64만 원 → 75만 원**으로 증가합니다. 또한 병장 인상률은 **12.5%, 11.1%, 47.9%, 25%, 20%**로 표시되어 있습니다.',
 '2026 병 복지 길라잡이 7\n수 당(계속)\n 단위 : 원 / 월\n \n구 분\n지급 기준\n금액\n위험\n근무\n수당\n갑\n・40m 이상 해난구조 및 특수잠수 작업\n240,240\n・고공 낙하산 강하자\n138,800\n・불발탄처리 및 탄약 기능 시험자, 지뢰제거 작전 투입\n118,800\n을\n・항공기/기구 강하자\n85,000 \n・헬기 레펠 및 F/R 강하자\n55,000\n・상륙 임무자(해병대)\n50,000\n병\n・특수전류분야 종사자, 탄약개수의 특수분야 종사자\n・월 1회 모형탑 낙하자, 컨테이너 크레인 운용자\n・유해발굴 / 감식업무자, 중장비 수송차량 운전자\n18,000\n위험근무수당 \n가산금\n・위험근무수당을 지급받는 특전사, 해병대, 해군(UDT/SSU)과 각 군의 \n폭발물처리반에 근무하는 군인이 특수임무를 위해 야외 출동 시 1일 \n3,000원 지급\n해파수당\n・해외파견근무수당 지급규정에 따라 임무・환경・등급・지역 등 고려 \n등급별 지급\n * 월 지급 기준액(미합중국 달러) : 1,474달러\n여 비\n • 정기휴가비(급지별) * ’25년 식비 : 7,000원 / 1식\n단위 : 원\n \n구 분\n휴가여비(왕복)\n전역귀가여비(편도)\n1 급지 (451Km 이상)\n152,200\n76,100\n2 급지 (450Km까지)\n138,400\n69,200\n3 급지 (400Km까지)\n110,600\n55,300\n4 급지 (350Km까지)\n96,800\n48,400\n5 급지 (300Km까지)\n83,000\n41,500\n6 급지 (250Km까지)\n69,200\n34,600\n7 급지 (200Km까지)\n46,800\n23,400\n8 급지 (150Km까지)\n33,000\n16,500\n9 급지 (100Km까지)\n22,000\n11,000\n10 급지 (50Km까지)\n13,800\n6,900\n도서가산금\n50해리 미만\n49,800\n24,900\n50해리 이상\n145,560\n89,280\n백령(울릉)도\n175,720\n111,360\n* 교통비 기준 단가 인상 : Km당 132원→138원, 식비 : 7,000원 / 1식 \n • 도서가산금 : (기존) 귀향지만 적용, (개선) 출발지까지 추가',
 'Part 01 생활편의 분야\n8 2026 병 복지 길라잡이\n병 급여(봉급/ 수당 등) 확인방법 안내\n • 급여 지급 일자별 지급항목\n - 매월 10일 : 봉급, 수당, 휴가ㆍ전역비, 병 일용품비\n - 매월 25일 : 신규 입대자 봉급, 수당, 휴가ㆍ전역비\n • 급여지급 확인방법 * 아래 2가지 사항 중 선택\n ①국군재정관리단 인트라넷 국방급여포털 접속 후 조회 \n ②국방급여포털(앱) 접속 / 로그인 후 급여명세서 확인\n • 급여 미지급 / 착오지급 발생 시 문의\n - 주요 착오 / 미지급 사례\n \n구 분\n내 용\n봉 급\n・진급을 하였으나 전 계급으로 급여가 지급된 경우\n ☞ 소속부대에서 진급명령 미발령·지연한 경우로서, 명령 발령 시 다음달 \n급여에 소급지급\n휴가 / \n전역비\n・진급월 휴가비 미지급된 사례\n ☞ 진급 당시 입실 중이거나, 군병원 퇴원 이후 퇴원명령 처리가 지연된 경우로서 \n명령발령, 급여지급 조치 후 당월 25일 또는 다음달 10일 급여 지급 시 소급지급\n ☞ 제주도, 연평도 등 도서지역 거주 또는 근무인원의 경우 소속부대 인사/\n 재정부서에서 항구설정 必, 항구 설정 및 휴가비 추가회수등록시 소급지급\n - 문의방법\n • 1차 : 인사 명령(입대ㆍ진급ㆍ전역) 발령, 급지 설정 여부 확인(소속부대 인사부서)\n • 2차 : 인사 명령 발령에 근거한 국방통합급여정보체계(DIPIS) 반영 여부 확인\n * 소속부대 인사 / 재정부서 확인(육군 : 재정, 해·공군·해병대 : 인사부서)\n •기타 안내사항\n - 급여계좌 변경\n • 변경 시기 : 훈련소 및 신병교육대 수료 후 소속부대(자대)에서 변경\n * 훈련소, 신병교육기관에서 임의 변경 불가: 소속 부대(자대)에서 변경\n • 변경방법: 매월 말일까지 개인이 급여포탈에서 직접신청 또는 소속\n부대 인사ㆍ재정부서 급여업무 담당자에게 변경 요청',
 '6 \n 기본급 및 각종 수당 인상 \n \n•(기본급) 초급간부 기본급 6.6% 인상(하사·중사·소위·중위)\n구 분\n소 위\n중 위\n하 사\n중 사\n’25년\n2,017,300원\n2,163,900원\n2,000,900원\n2,046,400원\n’26년\n2,150,400원\n2,306,700원\n2,133,000원\n2,181,500원\n* 기타 계급은 3.5% 인상\n \n•(특수/위험근무수당) 핵심전투인력 수당 신설 및 인상\n구 분\n특수근무수당\n위험근무수당\n신설\n· 간호조무부사관 장려수당\n· 국방대학교 특정직 교수 수당\n· 방사선 취급 근무자 위험근무수당\n· 운용시험평가관 위험근무수당\n· 조사본부 과학수사연구소 \n 위험근무수당\n인상/\n확대\n· 수상함 함정근무수당 10%\n· 중요직무급 위험·특수지근무수당과 병급\n·\x07 \x07장려수당 1호(특수무기), 5호(위성운용), \n8호(부사관) 지급대상 확대\n· 급유통제사 항공수당 급호 인상\n· 야간비행 출동가산금 확대\n· 민원업무수당 인상\n· 갑3호(대테러부대) 지급대상 확대\n \n•(시간외근무수당) 상한시간 예외직위 최신화\n - 의무후송항공대, 해상초계기 운용요원, 우도경비대 등\n * 시간외근무 상한 시간은 동일(GP 200시간, GOP·해강안·함정 등 150시간)\n \n•(비상근무수당) 일 8,000원, 월 120,000원→일 16,000원, 월 180,000원\n \n•(업무대행수당) 육아·질병휴직 → 대상 확대(모든 휴직 업무대행자)\n 당직근무비 인상\n \n•평일 : 2만원 → 3만원 / 휴일 4만원 → 10만원\n 장병e음 플랫폼 서비스 개시 : ’26. 2월\n \n•\x07인사, 행정, 복지 등 여러 서비스를 통합·연결하여 모바일 환경에서 일괄 \n제공하는 플랫폼 개시\n’26년도에는 이렇게 바뀝니다!\n2026 초급간부 길라잡이']

# 4. RAGAS 를 이용해 평가를 위한 합성 데이터 셋 만들기

- 평가 데이터셋 구성
  - `user_input`: 사용자 질문
  - `retrieved_contexts`: Vectorstore에서 검색한 context
  - `response`: LLM의 응답
  - `reference`: 정답

## 4.1 TestsetGenerator
- **문서(retrieved_contexts)를 기준**으로 **질문**, **정답** 을 생성한다.
- 평가할 LLM으로 생성된 질문을 넣어 답변을 추출하여 데이터셋을 구성한다.


> **주의**
> - TestsetGenerator import 시 `No Module named langchain_community.chat_models.vertexai` Error 발생 
> - RAGAS와 langchain-community의 버전 호환성 문제 때문에 발생한다.
> - 해결
>   1. langchain_google_vertexai 설치
>       - `!uv pip install langchain_google_vertexai`
>   2. `.venv\Lib\site-packages\langchain_community\chat_models` 디렉토리 아래 `vertexai.py` 파일을 만들고 아래 코드를 > 넣는다.
>    ```python
>       try:
>          from langchain_google_vertexai import ChatVertexAI
>       except ImportError:
>           class ChatVertexAI:
>               def __init__(self, *args, **kwargs):
>                   raise ImportError(
>                       "ChatVertexAI requires langchain-google-vertexai. "
>                       "Install with: pip install langchain-google-vertexai"
>                   )
>    ```

In [20]:
# !uv pip install langchain_google_vertexai

In [21]:
# 주피터노트북 환경에서 비동기적 처리 위해 
# script(.py) 로 작성할 경우는 필요 없다.

import nest_asyncio
nest_asyncio.apply()

In [22]:
from ragas.testset import TestsetGenerator

In [23]:
#
# testset -> Context들(문서들) - [질문 - 정답답변 + (Retriever가 찾은 문서 + LLM 응답: chain에서 생성)]
# 1. Context(문서들)을 추출 - TestsetGenerator -> 질문과 정답 답변 생성

import random

# 데이터셋을 생성할 때 사용할 Context를 추출
client = QdrantClient(url="http://localhost:6333")
COLLECTION_NAME = "guidance_vectordb"

info = client.get_collection(COLLECTION_NAME)
total_docs = info.points_count

results, _ = client.scroll(
    collection_name=COLLECTION_NAME,
    limit=total_docs,
)

# random하게 k(5)개를 sampling
sample_docs:"list[PointStruct]" =random.sample(results, 10) # 리스트에서 랜덤하게 k(5)개를 추출

# PointStruct - payload: page_content, metadata
# page_content만 추출해서 list[str]
docs = [point.payload['page_content'] for point in sample_docs]

In [24]:
total_docs

337

In [25]:
sample_docs

[Record(id='037f8624-432a-566d-ac6b-f517ddc3e748', payload={'page_content': '이 표는 **구분별로 장교와 부사관의 승진·보직 또는 충원 비율**을 연차 기준으로 나눈 내용으로 보입니다. 컬럼은 **‘구분’**(항목/기준), **‘장교’**(장교 대상 적용 비율), **‘부사관’**(부사관 대상 적용 비율)을 의미하며, 표에 제시된 수치로는 장교의 경우 **2년차 60%, 3년차 20%, 5~7년차 20%**, **3년차 70%, 4년차 30%**, **2년차 30%, 3년차 40%, 4년차 30%** 등 연차별 비율이 나타납니다. 또한 일부 항목은 **‘이후 결원 발생 시’**라고 되어 있어, 정해진 연차 비율 적용 후에는 결원 발생 시 추가 충원하는 방식임을 보여줍니다.', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 11, 'type': 'table', 'table_markdown': '| 구 분 | 장 교 | 부사관 |\n| --- | --- | --- |\n|  | 2년차 60%, 3년차 20%,\n5년차∼7년차 20% |  |\n|  | 3년차 70%, 4년차 30%,\n이후 결원발생 시 |  |\n|  | 3년차 70%, 4년차 30%,\n이후 결원발생 시 |  |\n|  | 2년차 30%, 3년차 40%,\n4년차 30%, 이후 결원발생 시 |  |', 'summary': '이 표는 **구분별로 장교와 부사관의 승진·보직 또는 충원 비율**을 연차 기준으로 나눈 내용으로 보입니다. 컬럼은 **‘구분’**(항목/기준), **‘장교’**(장교 대상 적용 비율), **‘부사관’**(부사관 대상 적용 비율)을 의미하며, 표에 제시된 수치로는 장교의 경우 **2년차 60%, 3년차 20%, 5~7년차 20%**, **3년차 70%, 4년차 30%**, **2년차 30%, 3년차 40%, 4년차 30%** 등 연차별 비율이 나타납니다. 또한 일부 항목은 **‘이후 결원 발생 시’**라고 되어 있어, 정해진 연차 비율 적용 후에는 결원 발생 시 추가 충원하는 방식임을 보여줍니다.'}}, vector=None, shard_key=None, order_value=None),
 Record(id='56fbbc36-3aff-5b6b-a6c5-d706c14092e0', payload={'page_content': '46 \n2026 초급간부 길라잡이\n 개 념 \n\x07하사 이상 현역간부, 군무원 및 공무원 등 개인에게 배정된 복지예산 한도 내에서 \n개인의 욕구와 필요에 따라 복지항목 및 수혜수준을 선택할 수 있는 제도\n* \x07맞춤형복지 예산은 기본항목(단체보험)을 선 계약 후 남은 금액을 개인별 복지점수에 따라 \n자율항목(복지포인트)으로 분기마다 지급\n* \x07맞춤형복지(단체보험, 복지포인트) 관련 자세한 내용은 “IMND 복지포털(웹/APP)”에서 확인 \n가능\n 맞춤형복지 구성 항목\n구분\n기본항목 (단체보험)\n자율항목 (복지포인트)\n내용\n•생명/상해 보험 \n•입·통원 의료비 보장 보험\n•매분기별 복지포인트 지급\n•개인별 자율적 선택사용\n기타\n•’26년 단체보험 계약현황\n - 주 계약 보험사 : 한화손해보험\n - 공동 서비스제공 : \x07삼성화재, 롯데손해보험, \n농협손해보험(자녀)\n•매년 11월 30일까지만 \n 사용 가능 \n (미사용 잔액은 불용처리)\n 이용방법 \n*\x07 \x07주의사항 : 복지포인트 미사용(불용)액 최소화를 위해 신규 임관자 대상 카드 발급 및 11월 말 \n까지 사용토록 관심 필요\n*\x07 \x07단체보험 중 생명·상해 보험은 의무가입 사항이며, 실손보험의 경우 개인실손 가입자에 한해 중복\n가입 제외 신청 시(매년 11월 ~ 익년 1월 中) 적용대상에서 제외 가능(차액은 복지포인트로 지급)\n-⑥ 맞춤형복지제도', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 47, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='ce359a7f-7e42-5d0c-8033-93f8690bcb0b', payload={'page_content': '02\nPart\n생\n활\n편\n의\n \n분\n야\n47 \n2026 초급간부 길라잡이\n 복지포인트 지급 기준 \n구분\n점 수\n비 고\n공통점수\n400점\n대상자 전원 지급\n근속점수\n300점\n근속 1년당 10점, 최대 30년\n가족점수\n배우자 150점, 부양가족 50점/1명당\n (가족점수는 “급여상 가족수당”을 받는 인원만 인정됨)\n* \x07분기 지급금액 = 개인점수 × 1점당 기준금액\n* 1점당 기준금액 = 분기 자율항목 가용예산 ÷ 개인점수의 합\n 복지포인트 사용 시 유의사항 \n •사용 가능한 분야 : 건강관리, 자기계발, 여가활동, 가정친화 등\n •사용 불가항목\n - 철도/항공, 인터넷 쇼핑몰 및 인터넷 결제(웹 및 App)\n - \x07세금공과금, 주류판매(유통), 전자상거래(다품목취급), 결제대행(PG), \n상품권판매\n - \x07복권판매, 농협(상품권), 룸살롱, 칵테일/스탠드바, 나이트클럽, 카바레, \n단란주점\n - \x07맥주홀, 유흥주점, 카지노, 비디오/전화방, 총포류판매, 성인용품판매점, \n안마시술소\n - \x07스포츠마사지, 종교단체, 무속/철학관, 귀금속, 금은방, 오락실/PC방\n - \x07각종회비\n •\x07복지포인트는 반드시 일시불 결제를 원칙으로 하며, 할부 결제 시 \n개인카드로 결제 처리됨\n국방부 복지정책과 복지정책협력 | 900-6625\n담당부서', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 48, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='3d29cde7-fa42-5ac2-8e20-aadf893895ef', payload={'page_content': '이 표는 국방 관련 복지·숙박 시설 목록을 정리한 것으로 보이며, 컬럼은 각각 **구분**, **시설명**, **홈페이지**를 의미합니다. 포함된 주요 시설은 **국방컨벤션**, **계룡스파텔·ROKAUS호텔**, **해군호텔(서울·평택·제주) 및 해군회관(진해)**, **공군호텔**, **그린나래호텔**, **밀리토피아 호텔 바이마린** 등입니다. 홈페이지 항목은 모두 비어 있어, 표는 시설명 중심의 안내 목록이며 총 **6개 항목(복수 지점 포함)**이 제시되어 있습니다.', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 34, 'type': 'table', 'table_markdown': '| 구분 | 시 설 명 | 홈페이지 |\n| --- | --- | --- |\n|  | 국방컨벤션 |  |\n|  | 계룡스파텔, ROKAUS호텔 |  |\n|  | 해군호텔(서울, 평택, 제주),\n해군회관(진해) |  |\n|  | 공군호텔 |  |\n|  | 그린나래호텔 |  |\n|  | 밀리토피아 호텔 바이마린 |  |', 'summary': '이 표는 국방 관련 복지·숙박 시설 목록을 정리한 것으로 보이며, 컬럼은 각각 **구분**, **시설명**, **홈페이지**를 의미합니다. 포함된 주요 시설은 **국방컨벤션**, **계룡스파텔·ROKAUS호텔**, **해군호텔(서울·평택·제주) 및 해군회관(진해)**, **공군호텔**, **그린나래호텔**, **밀리토피아 호텔 바이마린** 등입니다. 홈페이지 항목은 모두 비어 있어, 표는 시설명 중심의 안내 목록이며 총 **6개 항목(복수 지점 포함)**이 제시되어 있습니다.'}}, vector=None, shard_key=None, order_value=None),
 Record(id='0271a073-45c6-5d3c-9c63-7f50ee7076df', payload={'page_content': '장갑차야전정비병, 전차야전정비병, 조리병, 중형차량운전병, 지게차운전병, \n차량야전정비병\n종합행정학교\n군사경찰특기병, 군종특기병, 재정회계병\n포병학교\n자주포정비병\n항공학교\n운항관제반\n특수전학교\n공수기본, 낙하산포장정비\n해군\n기술행정학교\n공병병, 대형수송병, 일반수송병, 중장비수송병, 공병장비운용병, 수송병, \n전기병, 조리병, 추진기관병\n전투병과학교\n갑판병, 전탐병, 정보병, 조타병\n정보통신학교\n전산병 2과정, 전자전병, 정보통신병, 통신병 1과정, 통신병 2과정, \n전자기전병\n특수전전단\n특수전초급(병)\n해난구조교육훈련대대\n해난구조기본과정\n공군\n교육사령부 군수1학교\n항공기기관정비병, 항공기무기정비병, 항공기부속정비병, 항공기제작정비병, \n항공기지상장비정비병, 항공전자장비정비병, 항공탄약정비병, \n항공기기체정비병, 항공장구정비병\n교육사령부 군수2학교\n공병장비운전병(기지건설장비운전병), 급양병, 기계설비병(항공설비병), \n방공포차량운전병, 소방병(항공소방병), 일반차량운전병, 장갑차운전병, \n특수차량운전병, 항공기초과저지병, 항공운수병(항공운수 및 의장병), \n화생방병, 화생방차량운전병, 환경병(환경관리병), 전력설비병, 토목건축병\n방공포병학교\n단거리대공무기운용병, 단거리유도무기운용병, 장거리유도무기발사운용병, \n중거리유도무기발사운용병\n정보통신학교\n지상레이더체계정비병, 보안체계관리병, 전술항공통신체계정비병\n항공우주통제학교\n기상관측병\n* 국가평생교육진흥원의 평가인정 결과에 따라 학점인정 과정이 조정될 수 있으므로, 상세 내용은 \n‘학점은행제’ 홈페이지 확인', 'metadata': {'doc_name': '사병_길라잡이.pdf', 'page': 33, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='63e2ee03-5dc9-5868-a7b3-0bebb24bc486', payload={'page_content': '이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프로그램 목록**을 정리한 것입니다. 컬럼은 각각 **사업명**, **대상**, **주요 내용**을 의미하며, 사이버교육(사이버아카데미), 취업박람회, 청년장병 뉴스타트 Ⅰ·Ⅱ·Ⅲ(2박3일 소집교육 포함), 창업인식개선교육, 창업멘토링, 국방창업경진대회, 취업컨설팅 등이 포함됩니다. 대상은 주로 **군 복무 중인 전 장병**, **청년장병**, **창업 관심 장병**, **창업희망팀/경진대회 진출팀**, **구직등록 장병** 등으로 구분되며, 맞춤형 컨설팅·면접·취업매칭·설명회·멘토링 같은 실질적 지원이 핵심입니다.', 'metadata': {'doc_name': '사병_길라잡이.pdf', 'page': 66, 'type': 'table', 'table_markdown': '| 사사업업명명 | 대대상상 | 내내용용 |\n| --- | --- | --- |\n| 사이버아카데미 | 군 복무 중인 全 장병 | ◦전직준비 및 생애설계 역량 강화를 위한\n사이버교육 |\n| 국군장병\n취업박람회 | 군 복무 중인 全 장병 | ◦취업정보제공, 맞춤형 컨설팅, 구인기업\n현장면접 등 |\n| 청년장병 뉴스타트(Ⅰ)\n(취업역량 기본과정) | 청년장병 | ◦취업준비 분야별 맞춤형 취업역량\n집중교육(2박3일 소집교육) |\n| 청년장병 뉴스타트(Ⅱ)\n(취업준비 심화과정) | 청년장병 | ◦기업별 맞춤형교육 및 개인별 취업매칭\n및 컨설팅(2박3일 소집교육) |\n| 청년장병 뉴스타트(Ⅲ)\n(채용 설명회) | 청년장병 | ◦기업, 공직, 업종별 취ㆍ창업\n설명회 개최 |\n| 창업인식개선교육 | 창업 관심 장병 | ◦창업 인식개선 및 예비참여 준비과정 등 |\n| 창업멘토링 | 창업희망팀 및\n국방창업경진대회진출팀 | ◦전문 멘토링 집중 지원 |\n| 국방창업경진대회\n(군-국방부) | 창업 관심\n전역예정장병 | ◦장병들의 창업 아이디어 발굴 및 육성,\n범부처 창업경진대회와 연계·추진 |\n| 취업컨설팅 | 국방전직교육원\n구직등록 全 장병 | ◦맞춤형 1:1 상담 지원 |', 'summary': '이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프로그램 목록**을 정리한 것입니다. 컬럼은 각각 **사업명**, **대상**, **주요 내용**을 의미하며, 사이버교육(사이버아카데미), 취업박람회, 청년장병 뉴스타트 Ⅰ·Ⅱ·Ⅲ(2박3일 소집교육 포함), 창업인식개선교육, 창업멘토링, 국방창업경진대회, 취업컨설팅 등이 포함됩니다. 대상은 주로 **군 복무 중인 전 장병**, **청년장병**, **창업 관심 장병**, **창업희망팀/경진대회 진출팀**, **구직등록 장병** 등으로 구분되며, 맞춤형 컨설팅·면접·취업매칭·설명회·멘토링 같은 실질적 지원이 핵심입니다.'}}, vector=None, shard_key=None, order_value=None),
 Record(id='1ae66fec-26ab-5e9d-a3f7-4b719a83dea6', payload={'page_content': '48 \n2026 초급간부 길라잡이\n 초급간부 희망플러스 프로젝트 \n \n\x07초급간부의 ‘재정안정’을 돕기 위해 군인공제회에서 시행하는 재무설계 \n컨설팅, 개인회생비용지원, 생활보조 대출지원 제도\n 주요내용\n구 분\n 지 원 내 용\n재무설계\n컨설팅\n - 대상 : 군인공제회 현직 회원\n* 회원퇴직급여 10구좌(5만원) 이상 가입자\n (수혜인원은 1년간 회원퇴직급여 유지)\n - 인원 : 연 2,000명(비대면 3회 또는 대면 1회)\n - 개인별 자산/부채를 고려한 맞춤형 재무설계 서비스 제공\n* 목표금액 달성, 저축/부채관리, 은퇴설계 등\n - 비용 : 무료\n - 문의 : 02-6956-0790 (한국재무설계 주식회사)\n희망\n플러스론\n - 대상 : 저신용자 10년 이하 초급 간부 (중사, 대위, 7급 이하)\n* 회원퇴직급여 10구좌(5만원) 이상 가입자\n (수혜인원은 대출기간 동안 유지)\n* 신용점수 700점 이상\n (‘나이스 지킴이’에서 무료확인 가능)\n - 인원 : 연 250명\n - 지원내용 : 1인 최대 1,000만원 대출\n * 4.9% 금리(1년 단위 변동) 5년 만기/월 원리금 상환\n - 개인별 신청 (한국캐피탈 홈페이지)\n - 문의 : 02-522-2299 (한국캐피탈)\n개인회생 \n비용지원\n - 대상 : 금융취약자(신용불량자)\n* \x07회원퇴직급여 10구좌(5만원) 이상 가입자\n (수혜인원은 1년간 회원퇴직급여 유지)\n - 인원 : 연 250명\n - 지원내용 : 1인 220만원(부가세 포함) 이상 비용 지원\n - 문의 : 02-6953-3091(법무법인 승앤파트너스)\n-⑦ 초급간부 재정안정지원\n국방부 복지정책과 복지기금결산 | 900-6619\n담당부서', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 49, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='fde7b953-d2cb-543e-a326-e709036201e0', payload={'page_content': '취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧\n국가보훈대상자 등록\n예비군훈련 안내\n상비예비군 제도\n예비역 병 ⇨ 부사관(하사) 임용\nPart 06\n사회적응 지원 분야', 'metadata': {'doc_name': '사병_길라잡이.pdf', 'page': 65, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='4f78162f-58c7-5a01-b581-6b8f409b666e', payload={'page_content': '01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n17 \n/\n2026 초급간부 길라잡이\n01\nPart\n 개 요\n •관련 법령 : 군인복무기본법 시행령(제9조∼제13조)\n •휴가의 종류 : 연가, 특별휴가, 공가, 청원휴가\n •휴가일수 산정방법 : 토요일·공휴일은 휴가 일수에 미산입\n* \x07동일 사유로 실시한 휴가(공가·청원휴가·특별휴가)의 합산 기간이 30일 이상인 경우는 산입\n 연 가\n •연가 일수 : 연 21일 이내로 한 차례 또는 여러 차례로 나누어 사용 가능\n* \x07실제 복무 기간(개월)에 비례하여 산출\n* \x07근무시간 중 개인용무 외출 필요시 1분 단위 사용 가능, 누계 8시간을 (저축)연가 1일로 계산 \n •\x07연가 저축 : 연가보상비를 지급받고 남은 연가 일수 중 국방부장관이 \n정하는 범위의 연가를 이월·저축 가능\n 특별휴가 \n구 분\n기 간\n위로휴가\n훈련·검열, 특별한 근무로 피로가 심한 군인\n7일 범위\n포상휴가\n모범이 되는 공적이 있는 군인\n10일 범위\n대간첩 작전 유공자 등\n별도 지정\n보상휴가\n전방 경계업무 등 1주일 40시간을 초과하여 \n근무하는 군인\n1개월 3일 범위\n전역 전 휴가\n명예전역·정년전역하는 군인\n3개월 이내\n근속휴가\n각 근속연수에 따라 휴가부여\n•5년 이상 10년 미만\n•10년 이상 20년 미만\n•20년 이상\n3일∼7일 범위\n-⑤ 휴 가', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 18, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='d31c6e41-128b-5376-983e-954cad462b01', payload={'page_content': '01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n/\n2026 초급간부 길라잡이\n01\nPart\n복무연장 관련 알아두어야 할 사항\n \x07복무연장 지원기간은 임관일 기준으로 장교는 10년, 부사관은 \n7년을 넘지 않는 범위에서 복무연장 신청이 가능하며, 1회 신청시 \n4년 범위 내 연단위로 신청 가능(단, 공군은 1년 단위 지원) \n \x07당해 연도 선발계획을 확인하고 평가요소별 준비 필요\nTip\n 선발일정 : 연 1~2회 \n•육군 : 연 1∼2회(장교 전·후반기/부사관 4월) •해군 : 연 2회(전반기, 후반기)\n•공군 : 연 1회(장교 5월/부사관 4월) •해병 : 연 2회(전반기, 후반기)\n 지원대상\n구 분\n장 교\n부사관\n육 군\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n해 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 6년차\n공 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 5년차\n해 병\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n 선발비율\n•각 군별 중기인력 수준을 고려하여 병과별 적정 비율 산정\n 선발절차\n①선발계획 공지 → ②지원서접수 → ③부대추천 심사 → ④선발심의 → \n⑤합격자 발표\n-①-Ⅱ\n복무연장 지원 및 선발과정\n각 군별 담당\n담당부서', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 14, 'type': 'text'}}, vector=None, shard_key=None, order_value=None)]

In [26]:
docs

['이 표는 **구분별로 장교와 부사관의 승진·보직 또는 충원 비율**을 연차 기준으로 나눈 내용으로 보입니다. 컬럼은 **‘구분’**(항목/기준), **‘장교’**(장교 대상 적용 비율), **‘부사관’**(부사관 대상 적용 비율)을 의미하며, 표에 제시된 수치로는 장교의 경우 **2년차 60%, 3년차 20%, 5~7년차 20%**, **3년차 70%, 4년차 30%**, **2년차 30%, 3년차 40%, 4년차 30%** 등 연차별 비율이 나타납니다. 또한 일부 항목은 **‘이후 결원 발생 시’**라고 되어 있어, 정해진 연차 비율 적용 후에는 결원 발생 시 추가 충원하는 방식임을 보여줍니다.',
 '46 \n2026 초급간부 길라잡이\n 개 념 \n\x07하사 이상 현역간부, 군무원 및 공무원 등 개인에게 배정된 복지예산 한도 내에서 \n개인의 욕구와 필요에 따라 복지항목 및 수혜수준을 선택할 수 있는 제도\n* \x07맞춤형복지 예산은 기본항목(단체보험)을 선 계약 후 남은 금액을 개인별 복지점수에 따라 \n자율항목(복지포인트)으로 분기마다 지급\n* \x07맞춤형복지(단체보험, 복지포인트) 관련 자세한 내용은 “IMND 복지포털(웹/APP)”에서 확인 \n가능\n 맞춤형복지 구성 항목\n구분\n기본항목 (단체보험)\n자율항목 (복지포인트)\n내용\n•생명/상해 보험 \n•입·통원 의료비 보장 보험\n•매분기별 복지포인트 지급\n•개인별 자율적 선택사용\n기타\n•’26년 단체보험 계약현황\n - 주 계약 보험사 : 한화손해보험\n - 공동 서비스제공 : \x07삼성화재, 롯데손해보험, \n농협손해보험(자녀)\n•매년 11월 30일까지만 \n 사용 가능 \n (미사용 잔액은 불용처리)\n 이용방법 \n*\x07 \x07주의사항 : 복지포인트 미사용(불용)액 최소화를 위해 신규 임관자 대상 카드 발급 및 11월 말 \n까지 사용토록 관심 필요\n*\x07 \x07단체보험 중 생명·상해 보험은 의무가입 사항이며, 실손보험의 경우 개인실손 가입자에 한해 중복\n가입 제외 신청 시(매년 11월 ~ 익년 1월 中) 적용대상에서 제외 가능(차액은 복지포인트로 지급)\n-⑥ 맞춤형복지제도',
 '02\nPart\n생\n활\n편\n의\n \n분\n야\n47 \n2026 초급간부 길라잡이\n 복지포인트 지급 기준 \n구분\n점 수\n비 고\n공통점수\n400점\n대상자 전원 지급\n근속점수\n300점\n근속 1년당 10점, 최대 30년\n가족점수\n배우자 150점, 부양가족 50점/1명당\n (가족점수는 “급여상 가족수당”을 받는 인원만 인정됨)\n* \x07분기 지급금액 = 개인점수 × 1점당 기준금액\n* 1점당 기준금액 = 분기 자율항목 가용예산 ÷ 개인점수의 합\n 복지포인트 사용 시 유의사항 \n •사용 가능한 분야 : 건강관리, 자기계발, 여가활동, 가정친화 등\n •사용 불가항목\n - 철도/항공, 인터넷 쇼핑몰 및 인터넷 결제(웹 및 App)\n - \x07세금공과금, 주류판매(유통), 전자상거래(다품목취급), 결제대행(PG), \n상품권판매\n - \x07복권판매, 농협(상품권), 룸살롱, 칵테일/스탠드바, 나이트클럽, 카바레, \n단란주점\n - \x07맥주홀, 유흥주점, 카지노, 비디오/전화방, 총포류판매, 성인용품판매점, \n안마시술소\n - \x07스포츠마사지, 종교단체, 무속/철학관, 귀금속, 금은방, 오락실/PC방\n - \x07각종회비\n •\x07복지포인트는 반드시 일시불 결제를 원칙으로 하며, 할부 결제 시 \n개인카드로 결제 처리됨\n국방부 복지정책과 복지정책협력 | 900-6625\n담당부서',
 '이 표는 국방 관련 복지·숙박 시설 목록을 정리한 것으로 보이며, 컬럼은 각각 **구분**, **시설명**, **홈페이지**를 의미합니다. 포함된 주요 시설은 **국방컨벤션**, **계룡스파텔·ROKAUS호텔**, **해군호텔(서울·평택·제주) 및 해군회관(진해)**, **공군호텔**, **그린나래호텔**, **밀리토피아 호텔 바이마린** 등입니다. 홈페이지 항목은 모두 비어 있어, 표는 시설명 중심의 안내 목록이며 총 **6개 항목(복수 지점 포함)**이 제시되어 있습니다.',
 '장갑차야전정비병, 전차야전정비병, 조리병, 중형차량운전병, 지게차운전병, \n차량야전정비병\n종합행정학교\n군사경찰특기병, 군종특기병, 재정회계병\n포병학교\n자주포정비병\n항공학교\n운항관제반\n특수전학교\n공수기본, 낙하산포장정비\n해군\n기술행정학교\n공병병, 대형수송병, 일반수송병, 중장비수송병, 공병장비운용병, 수송병, \n전기병, 조리병, 추진기관병\n전투병과학교\n갑판병, 전탐병, 정보병, 조타병\n정보통신학교\n전산병 2과정, 전자전병, 정보통신병, 통신병 1과정, 통신병 2과정, \n전자기전병\n특수전전단\n특수전초급(병)\n해난구조교육훈련대대\n해난구조기본과정\n공군\n교육사령부 군수1학교\n항공기기관정비병, 항공기무기정비병, 항공기부속정비병, 항공기제작정비병, \n항공기지상장비정비병, 항공전자장비정비병, 항공탄약정비병, \n항공기기체정비병, 항공장구정비병\n교육사령부 군수2학교\n공병장비운전병(기지건설장비운전병), 급양병, 기계설비병(항공설비병), \n방공포차량운전병, 소방병(항공소방병), 일반차량운전병, 장갑차운전병, \n특수차량운전병, 항공기초과저지병, 항공운수병(항공운수 및 의장병), \n화생방병, 화생방차량운전병, 환경병(환경관리병), 전력설비병, 토목건축병\n방공포병학교\n단거리대공무기운용병, 단거리유도무기운용병, 장거리유도무기발사운용병, \n중거리유도무기발사운용병\n정보통신학교\n지상레이더체계정비병, 보안체계관리병, 전술항공통신체계정비병\n항공우주통제학교\n기상관측병\n* 국가평생교육진흥원의 평가인정 결과에 따라 학점인정 과정이 조정될 수 있으므로, 상세 내용은 \n‘학점은행제’ 홈페이지 확인',
 '이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프로그램 목록**을 정리한 것입니다. 컬럼은 각각 **사업명**, **대상**, **주요 내용**을 의미하며, 사이버교육(사이버아카데미), 취업박람회, 청년장병 뉴스타트 Ⅰ·Ⅱ·Ⅲ(2박3일 소집교육 포함), 창업인식개선교육, 창업멘토링, 국방창업경진대회, 취업컨설팅 등이 포함됩니다. 대상은 주로 **군 복무 중인 전 장병**, **청년장병**, **창업 관심 장병**, **창업희망팀/경진대회 진출팀**, **구직등록 장병** 등으로 구분되며, 맞춤형 컨설팅·면접·취업매칭·설명회·멘토링 같은 실질적 지원이 핵심입니다.',
 '48 \n2026 초급간부 길라잡이\n 초급간부 희망플러스 프로젝트 \n \n\x07초급간부의 ‘재정안정’을 돕기 위해 군인공제회에서 시행하는 재무설계 \n컨설팅, 개인회생비용지원, 생활보조 대출지원 제도\n 주요내용\n구 분\n 지 원 내 용\n재무설계\n컨설팅\n - 대상 : 군인공제회 현직 회원\n* 회원퇴직급여 10구좌(5만원) 이상 가입자\n (수혜인원은 1년간 회원퇴직급여 유지)\n - 인원 : 연 2,000명(비대면 3회 또는 대면 1회)\n - 개인별 자산/부채를 고려한 맞춤형 재무설계 서비스 제공\n* 목표금액 달성, 저축/부채관리, 은퇴설계 등\n - 비용 : 무료\n - 문의 : 02-6956-0790 (한국재무설계 주식회사)\n희망\n플러스론\n - 대상 : 저신용자 10년 이하 초급 간부 (중사, 대위, 7급 이하)\n* 회원퇴직급여 10구좌(5만원) 이상 가입자\n (수혜인원은 대출기간 동안 유지)\n* 신용점수 700점 이상\n (‘나이스 지킴이’에서 무료확인 가능)\n - 인원 : 연 250명\n - 지원내용 : 1인 최대 1,000만원 대출\n * 4.9% 금리(1년 단위 변동) 5년 만기/월 원리금 상환\n - 개인별 신청 (한국캐피탈 홈페이지)\n - 문의 : 02-522-2299 (한국캐피탈)\n개인회생 \n비용지원\n - 대상 : 금융취약자(신용불량자)\n* \x07회원퇴직급여 10구좌(5만원) 이상 가입자\n (수혜인원은 1년간 회원퇴직급여 유지)\n - 인원 : 연 250명\n - 지원내용 : 1인 220만원(부가세 포함) 이상 비용 지원\n - 문의 : 02-6953-3091(법무법인 승앤파트너스)\n-⑦ 초급간부 재정안정지원\n국방부 복지정책과 복지기금결산 | 900-6619\n담당부서',
 '취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧\n국가보훈대상자 등록\n예비군훈련 안내\n상비예비군 제도\n예비역 병 ⇨ 부사관(하사) 임용\nPart 06\n사회적응 지원 분야',
 '01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n17 \n/\n2026 초급간부 길라잡이\n01\nPart\n 개 요\n •관련 법령 : 군인복무기본법 시행령(제9조∼제13조)\n •휴가의 종류 : 연가, 특별휴가, 공가, 청원휴가\n •휴가일수 산정방법 : 토요일·공휴일은 휴가 일수에 미산입\n* \x07동일 사유로 실시한 휴가(공가·청원휴가·특별휴가)의 합산 기간이 30일 이상인 경우는 산입\n 연 가\n •연가 일수 : 연 21일 이내로 한 차례 또는 여러 차례로 나누어 사용 가능\n* \x07실제 복무 기간(개월)에 비례하여 산출\n* \x07근무시간 중 개인용무 외출 필요시 1분 단위 사용 가능, 누계 8시간을 (저축)연가 1일로 계산 \n •\x07연가 저축 : 연가보상비를 지급받고 남은 연가 일수 중 국방부장관이 \n정하는 범위의 연가를 이월·저축 가능\n 특별휴가 \n구 분\n기 간\n위로휴가\n훈련·검열, 특별한 근무로 피로가 심한 군인\n7일 범위\n포상휴가\n모범이 되는 공적이 있는 군인\n10일 범위\n대간첩 작전 유공자 등\n별도 지정\n보상휴가\n전방 경계업무 등 1주일 40시간을 초과하여 \n근무하는 군인\n1개월 3일 범위\n전역 전 휴가\n명예전역·정년전역하는 군인\n3개월 이내\n근속휴가\n각 근속연수에 따라 휴가부여\n•5년 이상 10년 미만\n•10년 이상 20년 미만\n•20년 이상\n3일∼7일 범위\n-⑤ 휴 가',
 '01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n/\n2026 초급간부 길라잡이\n01\nPart\n복무연장 관련 알아두어야 할 사항\n \x07복무연장 지원기간은 임관일 기준으로 장교는 10년, 부사관은 \n7년을 넘지 않는 범위에서 복무연장 신청이 가능하며, 1회 신청시 \n4년 범위 내 연단위로 신청 가능(단, 공군은 1년 단위 지원) \n \x07당해 연도 선발계획을 확인하고 평가요소별 준비 필요\nTip\n 선발일정 : 연 1~2회 \n•육군 : 연 1∼2회(장교 전·후반기/부사관 4월) •해군 : 연 2회(전반기, 후반기)\n•공군 : 연 1회(장교 5월/부사관 4월) •해병 : 연 2회(전반기, 후반기)\n 지원대상\n구 분\n장 교\n부사관\n육 군\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n해 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 6년차\n공 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 5년차\n해 병\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n 선발비율\n•각 군별 중기인력 수준을 고려하여 병과별 적정 비율 산정\n 선발절차\n①선발계획 공지 → ②지원서접수 → ③부대추천 심사 → ④선발심의 → \n⑤합격자 발표\n-①-Ⅱ\n복무연장 지원 및 선발과정\n각 군별 담당\n담당부서']

In [27]:
# testset 생성
from ragas.testset import TestsetGenerator
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
#testsetgenerator 는 gpt-5 이후 버전은 사용할 수 없다. 
## Langchain의 모델과 Embedding 모델 -> ragas에서 사용할 수 있도록 변환(wrapping)
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))
generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
    llm_context="""
- 사람들이 현역병 복지에 대해서 궁금해 할 만한 질문들을 생성한다.
- 데이터셋은 반드시 한국어로 작성한다.
- 데이터셋은 JSON 문법읋 지켜서 작성한다. 특히 구두점은 꼭 지켜야 한다.
- 생성된 내용이나 Document에 JSON문법에 맞지 않는 표현이 있으면 반드시 수정해서 처리한다.
""" 
# 질문/답변을 생성할 때 LLM에게 전달할 system Prompt를 설정
)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_15048\3702810314.py:8: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\Playdata\AppData\Local\Temp\ipykernel_15048\3702810314.py:9: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

In [28]:
testset = generator.generate_with_chunks(
    docs, testset_size=10, # Context 내용 테스트셋 개수(질문 답변 개수)
)

Applying SummaryExtractor: 100%|██████████| 10/10 [00:03<00:00,  3.19it/s]
Applying CustomNodeFilter:   0%|          | 0/10 [00:00<?, ?it/s]Node e17f73cf-cd99-461f-8b93-de0d66134e63 does not have a summary. Skipping filtering.
Node c5fedc65-e467-4f05-861d-e2b018c3865c does not have a summary. Skipping filtering.
Node 5d85ee0b-3bba-4d30-94c8-7c37e171fe5c does not have a summary. Skipping filtering.
Node 7644745e-9170-48a6-b275-1ce554c3ae86 does not have a summary. Skipping filtering.
Node a5505d13-5df9-4f8f-bc9b-4a1f48c45d72 does not have a summary. Skipping filtering.
Node f60e778b-9a8c-4a52-bd09-7286d873a818 does not have a summary. Skipping filtering.
Node 90b34060-764c-4072-a064-5d6950042544 does not have a summary. Skipping filtering.
Node 1358ae46-78d3-40e5-b96b-1a95b3a411d1 does not have a summary. Skipping filtering.
Node 30ce3bec-18c3-49f2-8f5e-a646c7caa648 does not have a summary. Skipping filtering.
Node 84cd5f46-5fec-484e-888c-2ee4965c0814 does not have a summary. Skipping filtering.
Applying CustomNodeFilter: 100%|██████████| 10/10 [00:00<00:00, 1437.83it/s]
Applying EmbeddingExtractor: 100%|██████████| 10/10 [00:00<00:00, 15.03it/s]
Applying ThemesExtractor: 100%|██████████| 10/10 [00:02<00:00,  4.68it/s]
Applying NERExtractor: 100%|██████████| 10/10 [00:01<00:00,  5.97it/s]
Applying CosineSimilarityBuilder: 100%|██████████| 1/1 [00:00<00:00, 234.57it/s]
Applying OverlapScoreBuilder: 100%|██████████| 1/1 [00:00<00:00, 355.30it/s]
Generating personas: 100%|██████████| 3/3 [00:01<00:00,  2.46it/s]
Generating Scenarios: 100%|██████████| 3/3 [00:04<00:00,  1.54s/it]
Generating Samples: 100%|██████████| 12/12 [00:02<00:00,  4.21it/s]

In [29]:
testset

Testset(samples=[TestsetSample(eval_sample=SingleTurnSample(user_input='부사관의 연차별 승진 또는 보직 비율은 어떻게 되나요?', retrieved_contexts=None, reference_contexts=['이 표는 **구분별로 장교와 부사관의 승진·보직 또는 충원 비율**을 연차 기준으로 나눈 내용으로 보입니다. 컬럼은 **‘구분’**(항목/기준), **‘장교’**(장교 대상 적용 비율), **‘부사관’**(부사관 대상 적용 비율)을 의미하며, 표에 제시된 수치로는 장교의 경우 **2년차 60%, 3년차 20%, 5~7년차 20%**, **3년차 70%, 4년차 30%**, **2년차 30%, 3년차 40%, 4년차 30%** 등 연차별 비율이 나타납니다. 또한 일부 항목은 **‘이후 결원 발생 시’**라고 되어 있어, 정해진 연차 비율 적용 후에는 결원 발생 시 추가 충원하는 방식임을 보여줍니다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='표에 따르면 부사관의 연차별 승진 또는 보직 비율은 구분별로 제시되어 있으며, 일부 항목에서는 정해진 연차 비율 적용 후 결원 발생 시 추가 충원하는 방식이 적용됩니다.', rubrics=None, persona_name='Military Personnel Planner', query_style='WEB_SEARCH_LIKE', query_length='MEDIUM'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='농협손해보험은 맞춤형복지제도에서 어떤 역할을 하나요?', retrieved_contexts=None, reference_contexts=['46 \n2026 초급간부 길라잡이\n 개 념 \n\x07하사 이상 현역간부, 군무원 및 공무원 등 개인에게 배정된 복지예산 한도 내에서 \n개인의 욕구와 필요에 따라 복지항목 및 수혜수준을 선택할 수 있는 제도\n* \x07맞춤형복지 예산은 기본항목(단체보험)을 선 계약 후 남은 금액을 개인별 복지점수에 따라 \n자율항목(복지포인트)으로 분기마다 지급\n* \x07맞춤형복지(단체보험, 복지포인트) 관련 자세한 내용은 “IMND 복지포털(웹/APP)”에서 확인 \n가능\n 맞춤형복지 구성 항목\n구분\n기본항목 (단체보험)\n자율항목 (복지포인트)\n내용\n•생명/상해 보험 \n•입·통원 의료비 보장 보험\n•매분기별 복지포인트 지급\n•개인별 자율적 선택사용\n기타\n•’26년 단체보험 계약현황\n - 주 계약 보험사 : 한화손해보험\n - 공동 서비스제공 : \x07삼성화재, 롯데손해보험, \n농협손해보험(자녀)\n•매년 11월 30일까지만 \n 사용 가능 \n (미사용 잔액은 불용처리)\n 이용방법 \n*\x07 \x07주의사항 : 복지포인트 미사용(불용)액 최소화를 위해 신규 임관자 대상 카드 발급 및 11월 말 \n까지 사용토록 관심 필요\n*\x07 \x07단체보험 중 생명·상해 보험은 의무가입 사항이며, 실손보험의 경우 개인실손 가입자에 한해 중복\n가입 제외 신청 시(매년 11월 ~ 익년 1월 中) 적용대상에서 제외 가능(차액은 복지포인트로 지급)\n-⑥ 맞춤형복지제도'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='농협손해보험은 맞춤형복지제도의 단체보험 항목에서 자녀를 대상으로 공동 서비스제공 보험사로 참여하고 있습니다.', rubrics=None, persona_name='HR Benefits Coordinator', query_style='PERFECT_GRAMMAR', query_length='MEDIUM'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='복지정책협력 담당 부서는 어디인가요?', retrieved_contexts=None, reference_contexts=['02\nPart\n생\n활\n편\n의\n \n분\n야\n47 \n2026 초급간부 길라잡이\n 복지포인트 지급 기준 \n구분\n점 수\n비 고\n공통점수\n400점\n대상자 전원 지급\n근속점수\n300점\n근속 1년당 10점, 최대 30년\n가족점수\n배우자 150점, 부양가족 50점/1명당\n (가족점수는 “급여상 가족수당”을 받는 인원만 인정됨)\n* \x07분기 지급금액 = 개인점수 × 1점당 기준금액\n* 1점당 기준금액 = 분기 자율항목 가용예산 ÷ 개인점수의 합\n 복지포인트 사용 시 유의사항 \n •사용 가능한 분야 : 건강관리, 자기계발, 여가활동, 가정친화 등\n •사용 불가항목\n - 철도/항공, 인터넷 쇼핑몰 및 인터넷 결제(웹 및 App)\n - \x07세금공과금, 주류판매(유통), 전자상거래(다품목취급), 결제대행(PG), \n상품권판매\n - \x07복권판매, 농협(상품권), 룸살롱, 칵테일/스탠드바, 나이트클럽, 카바레, \n단란주점\n - \x07맥주홀, 유흥주점, 카지노, 비디오/전화방, 총포류판매, 성인용품판매점, \n안마시술소\n - \x07스포츠마사지, 종교단체, 무속/철학관, 귀금속, 금은방, 오락실/PC방\n - \x07각종회비\n •\x07복지포인트는 반드시 일시불 결제를 원칙으로 하며, 할부 결제 시 \n개인카드로 결제 처리됨\n국방부 복지정책과 복지정책협력 | 900-6625\n담당부서'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='복지정책협력 담당부서는 국방부 복지정책과입니다.', rubrics=None, persona_name='HR Benefits Coordinator', query_style='WEB_SEARCH_LIKE', query_length='SHORT'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='평택에 위치한 국방 관련 복지·숙박 시설에는 무엇이 있습니까?', retrieved_contexts=None, reference_contexts=['이 표는 국방 관련 복지·숙박 시설 목록을 정리한 것으로 보이며, 컬럼은 각각 **구분**, **시설명**, **홈페이지**를 의미합니다. 포함된 주요 시설은 **국방컨벤션**, **계룡스파텔·ROKAUS호텔**, **해군호텔(서울·평택·제주) 및 해군회관(진해)**, **공군호텔**, **그린나래호텔**, **밀리토피아 호텔 바이마린** 등입니다. 홈페이지 항목은 모두 비어 있어, 표는 시설명 중심의 안내 목록이며 총 **6개 항목(복수 지점 포함)**이 제시되어 있습니다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='해군호텔(서울·평택·제주) 및 해군회관(진해)이 포함되어 있으며, 이 중 평택에 위치한 해군호텔이 있습니다.', rubrics=None, persona_name='Military Personnel Planner', query_style='PERFECT_GRAMMAR', query_length='SHORT'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='사회적응 지원 분야에서 청년장병 뉴스타트 프로그램은 어떤 대상에게 어떤 지원을 제공하나요?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧\n국가보훈대상자 등록\n예비군훈련 안내\n상비예비군 제도\n예비역 병 ⇨ 부사관(하사) 임용\nPart 06\n사회적응 지원 분야', '<2-hop>\n\n이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프로그램 목록**을 정리한 것입니다. 컬럼은 각각 **사업명**, **대상**, **주요 내용**을 의미하며, 사이버교육(사이버아카데미), 취업박람회, 청년장병 뉴스타트 Ⅰ·Ⅱ·Ⅲ(2박3일 소집교육 포함), 창업인식개선교육, 창업멘토링, 국방창업경진대회, 취업컨설팅 등이 포함됩니다. 대상은 주로 **군 복무 중인 전 장병**, **청년장병**, **창업 관심 장병**, **창업희망팀/경진대회 진출팀**, **구직등록 장병** 등으로 구분되며, 맞춤형 컨설팅·면접·취업매칭·설명회·멘토링 같은 실질적 지원이 핵심입니다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='사회적응 지원 분야에서 청년장병 뉴스타트 프로그램은 군 복무 중인 전 장병과 청년장병을 대상으로 하며, 2박 3일 소집교육을 포함한 맞춤형 컨설팅, 면접, 취업매칭, 설명회, 멘토링 등 실질적인 취업 및 창업 지원을 제공합니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_abstract_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='장병 경제교욱이랑 사이버아카데미 뭐가 다르나요?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧\n국가보훈대상자 등록\n예비군훈련 안내\n상비예비군 제도\n예비역 병 ⇨ 부사관(하사) 임용\nPart 06\n사회적응 지원 분야', '<2-hop>\n\n이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프로그램 목록**을 정리한 것입니다. 컬럼은 각각 **사업명**, **대상**, **주요 내용**을 의미하며, 사이버교육(사이버아카데미), 취업박람회, 청년장병 뉴스타트 Ⅰ·Ⅱ·Ⅲ(2박3일 소집교육 포함), 창업인식개선교육, 창업멘토링, 국방창업경진대회, 취업컨설팅 등이 포함됩니다. 대상은 주로 **군 복무 중인 전 장병**, **청년장병**, **창업 관심 장병**, **창업희망팀/경진대회 진출팀**, **구직등록 장병** 등으로 구분되며, 맞춤형 컨설팅·면접·취업매칭·설명회·멘토링 같은 실질적 지원이 핵심입니다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='장병 경제교육은 군 복무 중인 장병을 대상으로 경제 관련 교육을 제공하는 프로그램이고, 사이버교육(사이버아카데미)는 온라인으로 다양한 취업 및 창업 지원 교육을 받을 수 있는 프로그램입니다. 두 프로그램 모두 군 복무 중인 장병을 지원하지만, 경제교육은 경제 지식에 초점을 두고, 사이버아카데미는 온라인을 통한 다양한 취업·창업 교육을 제공합니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_abstract_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='사회적응 지원 뭐고 청년장병 뉴스타트 프로그램이랑 무슨 관계 있어요?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧\n국가보훈대상자 등록\n예비군훈련 안내\n상비예비군 제도\n예비역 병 ⇨ 부사관(하사) 임용\nPart 06\n사회적응 지원 분야', '<2-hop>\n\n이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프로그램 목록**을 정리한 것입니다. 컬럼은 각각 **사업명**, **대상**, **주요 내용**을 의미하며, 사이버교육(사이버아카데미), 취업박람회, 청년장병 뉴스타트 Ⅰ·Ⅱ·Ⅲ(2박3일 소집교육 포함), 창업인식개선교육, 창업멘토링, 국방창업경진대회, 취업컨설팅 등이 포함됩니다. 대상은 주로 **군 복무 중인 전 장병**, **청년장병**, **창업 관심 장병**, **창업희망팀/경진대회 진출팀**, **구직등록 장병** 등으로 구분되며, 맞춤형 컨설팅·면접·취업매칭·설명회·멘토링 같은 실질적 지원이 핵심입니다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='사회적응 지원은 군 복무 중이나 전역 예정 장병들이 취업이나 창업 준비할 수 있게 도와주는 분야예요. 여기에는 청년장병 뉴스타트 프로그램도 포함돼 있는데, 이 프로그램은 군 복무 중인 장병이나 청년장병 대상으로 2박 3일 소집교육 같은 실질적 지원을 해줘요.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_abstract_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='사회적응 지원 분야에서 청년장병 뉴스타트 프로그램이 뭐고, 이 프로그램이 군 복무 중 장병들한테 어떤 취업 지원 해주는지 설명해줘.', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧\n국가보훈대상자 등록\n예비군훈련 안내\n상비예비군 제도\n예비역 병 ⇨ 부사관(하사) 임용\nPart 06\n사회적응 지원 분야', '<2-hop>\n\n이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프로그램 목록**을 정리한 것입니다. 컬럼은 각각 **사업명**, **대상**, **주요 내용**을 의미하며, 사이버교육(사이버아카데미), 취업박람회, 청년장병 뉴스타트 Ⅰ·Ⅱ·Ⅲ(2박3일 소집교육 포함), 창업인식개선교육, 창업멘토링, 국방창업경진대회, 취업컨설팅 등이 포함됩니다. 대상은 주로 **군 복무 중인 전 장병**, **청년장병**, **창업 관심 장병**, **창업희망팀/경진대회 진출팀**, **구직등록 장병** 등으로 구분되며, 맞춤형 컨설팅·면접·취업매칭·설명회·멘토링 같은 실질적 지원이 핵심입니다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='사회적응 지원 분야에는 청년장병 뉴스타트 프로그램이 포함되어 있어. 이 프로그램은 군 복무 중인 장병과 전역 예정 장병을 대상으로 하고, 2박 3일 소집교육 같은 다양한 형태로 운영돼. 주요 내용은 맞춤형 컨설팅, 면접, 취업매칭, 설명회, 멘토링 등 실질적인 취업 지원을 제공하는 거야.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_abstract_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='해군 복무연장 지원하려면 어떤 절차 따라야 하고, 해군에서 지원 가능한 특기병 종류는 뭐 있어요?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n/\n2026 초급간부 길라잡이\n01\nPart\n복무연장 관련 알아두어야 할 사항\n \x07복무연장 지원기간은 임관일 기준으로 장교는 10년, 부사관은 \n7년을 넘지 않는 범위에서 복무연장 신청이 가능하며, 1회 신청시 \n4년 범위 내 연단위로 신청 가능(단, 공군은 1년 단위 지원) \n \x07당해 연도 선발계획을 확인하고 평가요소별 준비 필요\nTip\n 선발일정 : 연 1~2회 \n•육군 : 연 1∼2회(장교 전·후반기/부사관 4월) •해군 : 연 2회(전반기, 후반기)\n•공군 : 연 1회(장교 5월/부사관 4월) •해병 : 연 2회(전반기, 후반기)\n 지원대상\n구 분\n장 교\n부사관\n육 군\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n해 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 6년차\n공 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 5년차\n해 병\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n 선발비율\n•각 군별 중기인력 수준을 고려하여 병과별 적정 비율 산정\n 선발절차\n①선발계획 공지 → ②지원서접수 → ③부대추천 심사 → ④선발심의 → \n⑤합격자 발표\n-①-Ⅱ\n복무연장 지원 및 선발과정\n각 군별 담당\n담당부서', '<2-hop>\n\n장갑차야전정비병, 전차야전정비병, 조리병, 중형차량운전병, 지게차운전병, \n차량야전정비병\n종합행정학교\n군사경찰특기병, 군종특기병, 재정회계병\n포병학교\n자주포정비병\n항공학교\n운항관제반\n특수전학교\n공수기본, 낙하산포장정비\n해군\n기술행정학교\n공병병, 대형수송병, 일반수송병, 중장비수송병, 공병장비운용병, 수송병, \n전기병, 조리병, 추진기관병\n전투병과학교\n갑판병, 전탐병, 정보병, 조타병\n정보통신학교\n전산병 2과정, 전자전병, 정보통신병, 통신병 1과정, 통신병 2과정, \n전자기전병\n특수전전단\n특수전초급(병)\n해난구조교육훈련대대\n해난구조기본과정\n공군\n교육사령부 군수1학교\n항공기기관정비병, 항공기무기정비병, 항공기부속정비병, 항공기제작정비병, \n항공기지상장비정비병, 항공전자장비정비병, 항공탄약정비병, \n항공기기체정비병, 항공장구정비병\n교육사령부 군수2학교\n공병장비운전병(기지건설장비운전병), 급양병, 기계설비병(항공설비병), \n방공포차량운전병, 소방병(항공소방병), 일반차량운전병, 장갑차운전병, \n특수차량운전병, 항공기초과저지병, 항공운수병(항공운수 및 의장병), \n화생방병, 화생방차량운전병, 환경병(환경관리병), 전력설비병, 토목건축병\n방공포병학교\n단거리대공무기운용병, 단거리유도무기운용병, 장거리유도무기발사운용병, \n중거리유도무기발사운용병\n정보통신학교\n지상레이더체계정비병, 보안체계관리병, 전술항공통신체계정비병\n항공우주통제학교\n기상관측병\n* 국가평생교육진흥원의 평가인정 결과에 따라 학점인정 과정이 조정될 수 있으므로, 상세 내용은 \n‘학점은행제’ 홈페이지 확인'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='해군 복무연장 지원하려면 먼저 선발계획 공지 보고, 지원서 접수하고, 부대추천 심사 받고, 선발심의 거쳐서 합격자 발표 나와요. 해군에서 지원 가능한 특기병 종류는 기술행정학교에서 공병병, 대형수송병, 일반수송병, 중장비수송병, 공병장비운용병, 수송병, 전기병, 조리병, 추진기관병 있고, 전투병과학교에서는 갑판병, 전탐병, 정보병, 조타병, 정보통신학교에서는 전산병 2과정, 전자전병, 정보통신병, 통신병 1과정, 통신병 2과정, 전자기전병, 특수전전단에서는 특수전초급(병), 해난구조교육훈련대대에서는 해난구조기본과정 있어요.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='해군 복무연장 지원하려면 언제 신청해야 하고, 해군에서 조리병이나 갑판병 같은 특기병은 어디서 교육받아야 해?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n/\n2026 초급간부 길라잡이\n01\nPart\n복무연장 관련 알아두어야 할 사항\n \x07복무연장 지원기간은 임관일 기준으로 장교는 10년, 부사관은 \n7년을 넘지 않는 범위에서 복무연장 신청이 가능하며, 1회 신청시 \n4년 범위 내 연단위로 신청 가능(단, 공군은 1년 단위 지원) \n \x07당해 연도 선발계획을 확인하고 평가요소별 준비 필요\nTip\n 선발일정 : 연 1~2회 \n•육군 : 연 1∼2회(장교 전·후반기/부사관 4월) •해군 : 연 2회(전반기, 후반기)\n•공군 : 연 1회(장교 5월/부사관 4월) •해병 : 연 2회(전반기, 후반기)\n 지원대상\n구 분\n장 교\n부사관\n육 군\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n해 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 6년차\n공 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 5년차\n해 병\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n 선발비율\n•각 군별 중기인력 수준을 고려하여 병과별 적정 비율 산정\n 선발절차\n①선발계획 공지 → ②지원서접수 → ③부대추천 심사 → ④선발심의 → \n⑤합격자 발표\n-①-Ⅱ\n복무연장 지원 및 선발과정\n각 군별 담당\n담당부서', '<2-hop>\n\n장갑차야전정비병, 전차야전정비병, 조리병, 중형차량운전병, 지게차운전병, \n차량야전정비병\n종합행정학교\n군사경찰특기병, 군종특기병, 재정회계병\n포병학교\n자주포정비병\n항공학교\n운항관제반\n특수전학교\n공수기본, 낙하산포장정비\n해군\n기술행정학교\n공병병, 대형수송병, 일반수송병, 중장비수송병, 공병장비운용병, 수송병, \n전기병, 조리병, 추진기관병\n전투병과학교\n갑판병, 전탐병, 정보병, 조타병\n정보통신학교\n전산병 2과정, 전자전병, 정보통신병, 통신병 1과정, 통신병 2과정, \n전자기전병\n특수전전단\n특수전초급(병)\n해난구조교육훈련대대\n해난구조기본과정\n공군\n교육사령부 군수1학교\n항공기기관정비병, 항공기무기정비병, 항공기부속정비병, 항공기제작정비병, \n항공기지상장비정비병, 항공전자장비정비병, 항공탄약정비병, \n항공기기체정비병, 항공장구정비병\n교육사령부 군수2학교\n공병장비운전병(기지건설장비운전병), 급양병, 기계설비병(항공설비병), \n방공포차량운전병, 소방병(항공소방병), 일반차량운전병, 장갑차운전병, \n특수차량운전병, 항공기초과저지병, 항공운수병(항공운수 및 의장병), \n화생방병, 화생방차량운전병, 환경병(환경관리병), 전력설비병, 토목건축병\n방공포병학교\n단거리대공무기운용병, 단거리유도무기운용병, 장거리유도무기발사운용병, \n중거리유도무기발사운용병\n정보통신학교\n지상레이더체계정비병, 보안체계관리병, 전술항공통신체계정비병\n항공우주통제학교\n기상관측병\n* 국가평생교육진흥원의 평가인정 결과에 따라 학점인정 과정이 조정될 수 있으므로, 상세 내용은 \n‘학점은행제’ 홈페이지 확인'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='해군 복무연장 지원은 연 2회(전반기, 후반기) 진행되며, 임관 2년차부터 9년차(장교), 임관 4년차부터 6년차(부사관)까지 신청할 수 있습니다. 해군에서 조리병이나 갑판병 같은 특기병은 각각 기술행정학교(조리병)와 전투병과학교(갑판병)에서 교육을 받게 됩니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='해군 복무연장 지원하려면 지원대상 기간이랑 해군에서 할 수 있는 병과 뭐 있어?', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n/\n2026 초급간부 길라잡이\n01\nPart\n복무연장 관련 알아두어야 할 사항\n \x07복무연장 지원기간은 임관일 기준으로 장교는 10년, 부사관은 \n7년을 넘지 않는 범위에서 복무연장 신청이 가능하며, 1회 신청시 \n4년 범위 내 연단위로 신청 가능(단, 공군은 1년 단위 지원) \n \x07당해 연도 선발계획을 확인하고 평가요소별 준비 필요\nTip\n 선발일정 : 연 1~2회 \n•육군 : 연 1∼2회(장교 전·후반기/부사관 4월) •해군 : 연 2회(전반기, 후반기)\n•공군 : 연 1회(장교 5월/부사관 4월) •해병 : 연 2회(전반기, 후반기)\n 지원대상\n구 분\n장 교\n부사관\n육 군\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n해 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 6년차\n공 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 5년차\n해 병\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n 선발비율\n•각 군별 중기인력 수준을 고려하여 병과별 적정 비율 산정\n 선발절차\n①선발계획 공지 → ②지원서접수 → ③부대추천 심사 → ④선발심의 → \n⑤합격자 발표\n-①-Ⅱ\n복무연장 지원 및 선발과정\n각 군별 담당\n담당부서', '<2-hop>\n\n장갑차야전정비병, 전차야전정비병, 조리병, 중형차량운전병, 지게차운전병, \n차량야전정비병\n종합행정학교\n군사경찰특기병, 군종특기병, 재정회계병\n포병학교\n자주포정비병\n항공학교\n운항관제반\n특수전학교\n공수기본, 낙하산포장정비\n해군\n기술행정학교\n공병병, 대형수송병, 일반수송병, 중장비수송병, 공병장비운용병, 수송병, \n전기병, 조리병, 추진기관병\n전투병과학교\n갑판병, 전탐병, 정보병, 조타병\n정보통신학교\n전산병 2과정, 전자전병, 정보통신병, 통신병 1과정, 통신병 2과정, \n전자기전병\n특수전전단\n특수전초급(병)\n해난구조교육훈련대대\n해난구조기본과정\n공군\n교육사령부 군수1학교\n항공기기관정비병, 항공기무기정비병, 항공기부속정비병, 항공기제작정비병, \n항공기지상장비정비병, 항공전자장비정비병, 항공탄약정비병, \n항공기기체정비병, 항공장구정비병\n교육사령부 군수2학교\n공병장비운전병(기지건설장비운전병), 급양병, 기계설비병(항공설비병), \n방공포차량운전병, 소방병(항공소방병), 일반차량운전병, 장갑차운전병, \n특수차량운전병, 항공기초과저지병, 항공운수병(항공운수 및 의장병), \n화생방병, 화생방차량운전병, 환경병(환경관리병), 전력설비병, 토목건축병\n방공포병학교\n단거리대공무기운용병, 단거리유도무기운용병, 장거리유도무기발사운용병, \n중거리유도무기발사운용병\n정보통신학교\n지상레이더체계정비병, 보안체계관리병, 전술항공통신체계정비병\n항공우주통제학교\n기상관측병\n* 국가평생교육진흥원의 평가인정 결과에 따라 학점인정 과정이 조정될 수 있으므로, 상세 내용은 \n‘학점은행제’ 홈페이지 확인'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='해군 복무연장 지원하려면 장교는 임관 2년차부터 9년차까지, 부사관은 임관 4년차부터 6년차까지 지원할 수 있어. 해군에서 할 수 있는 병과로는 기술행정학교에서 공병병, 대형수송병, 일반수송병, 중장비수송병, 공병장비운용병, 수송병, 전기병, 조리병, 추진기관병이 있고, 전투병과학교에서는 갑판병, 전탐병, 정보병, 조타병이 있어. 정보통신학교에서는 전산병, 전자전병, 정보통신병, 통신병, 전자기전병이 가능하고, 특수전전단에서는 특수전초급(병), 해난구조교육훈련대대에서는 해난구조기본과정도 있어.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='해군 복무연장 지원하려면 임관 몇 년차부터 몇 년차까지 지원 가능한지랑, 해군에서 지원할 수 있는 주요 병과나 특기에는 어떤 것들이 있는지 알려주세요.', retrieved_contexts=None, reference_contexts=['<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n/\n2026 초급간부 길라잡이\n01\nPart\n복무연장 관련 알아두어야 할 사항\n \x07복무연장 지원기간은 임관일 기준으로 장교는 10년, 부사관은 \n7년을 넘지 않는 범위에서 복무연장 신청이 가능하며, 1회 신청시 \n4년 범위 내 연단위로 신청 가능(단, 공군은 1년 단위 지원) \n \x07당해 연도 선발계획을 확인하고 평가요소별 준비 필요\nTip\n 선발일정 : 연 1~2회 \n•육군 : 연 1∼2회(장교 전·후반기/부사관 4월) •해군 : 연 2회(전반기, 후반기)\n•공군 : 연 1회(장교 5월/부사관 4월) •해병 : 연 2회(전반기, 후반기)\n 지원대상\n구 분\n장 교\n부사관\n육 군\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n해 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 6년차\n공 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 5년차\n해 병\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n 선발비율\n•각 군별 중기인력 수준을 고려하여 병과별 적정 비율 산정\n 선발절차\n①선발계획 공지 → ②지원서접수 → ③부대추천 심사 → ④선발심의 → \n⑤합격자 발표\n-①-Ⅱ\n복무연장 지원 및 선발과정\n각 군별 담당\n담당부서', '<2-hop>\n\n장갑차야전정비병, 전차야전정비병, 조리병, 중형차량운전병, 지게차운전병, \n차량야전정비병\n종합행정학교\n군사경찰특기병, 군종특기병, 재정회계병\n포병학교\n자주포정비병\n항공학교\n운항관제반\n특수전학교\n공수기본, 낙하산포장정비\n해군\n기술행정학교\n공병병, 대형수송병, 일반수송병, 중장비수송병, 공병장비운용병, 수송병, \n전기병, 조리병, 추진기관병\n전투병과학교\n갑판병, 전탐병, 정보병, 조타병\n정보통신학교\n전산병 2과정, 전자전병, 정보통신병, 통신병 1과정, 통신병 2과정, \n전자기전병\n특수전전단\n특수전초급(병)\n해난구조교육훈련대대\n해난구조기본과정\n공군\n교육사령부 군수1학교\n항공기기관정비병, 항공기무기정비병, 항공기부속정비병, 항공기제작정비병, \n항공기지상장비정비병, 항공전자장비정비병, 항공탄약정비병, \n항공기기체정비병, 항공장구정비병\n교육사령부 군수2학교\n공병장비운전병(기지건설장비운전병), 급양병, 기계설비병(항공설비병), \n방공포차량운전병, 소방병(항공소방병), 일반차량운전병, 장갑차운전병, \n특수차량운전병, 항공기초과저지병, 항공운수병(항공운수 및 의장병), \n화생방병, 화생방차량운전병, 환경병(환경관리병), 전력설비병, 토목건축병\n방공포병학교\n단거리대공무기운용병, 단거리유도무기운용병, 장거리유도무기발사운용병, \n중거리유도무기발사운용병\n정보통신학교\n지상레이더체계정비병, 보안체계관리병, 전술항공통신체계정비병\n항공우주통제학교\n기상관측병\n* 국가평생교육진흥원의 평가인정 결과에 따라 학점인정 과정이 조정될 수 있으므로, 상세 내용은 \n‘학점은행제’ 홈페이지 확인'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='해군 복무연장 지원은 장교의 경우 임관 2년차부터 9년차까지, 부사관의 경우 임관 4년차부터 6년차까지 가능합니다. 해군에서 지원할 수 있는 주요 병과나 특기로는 기술행정학교에서 공병병, 대형수송병, 일반수송병, 중장비수송병, 공병장비운용병, 수송병, 전기병, 조리병, 추진기관병 등이 있고, 전투병과학교에서는 갑판병, 전탐병, 정보병, 조타병 등이 있습니다. 또한 정보통신학교에서는 전산병, 전자전병, 정보통신병, 통신병, 전자기전병 등이 있으며, 특수전전단의 특수전초급(병)과 해난구조교육훈련대대의 해난구조기본과정도 지원할 수 있습니다.', rubrics=None, persona_name=None, query_style=None, query_length=None), synthesizer_name='multi_hop_specific_query_synthesizer')])

In [30]:
sample1 = testset.samples[0].eval_sample
print("사용자질문:", sample1.user_input)
print("Context:", sample1.reference_contexts)
print("생성된 답변(정답):", sample1.reference)
print("평가대상 RAG의 답변:", sample1.response)
print("평가대상 RAG가 검색한 Context:", sample1.retrieved_contexts)

사용자질문: 부사관의 연차별 승진 또는 보직 비율은 어떻게 되나요?
Context: ['이 표는 **구분별로 장교와 부사관의 승진·보직 또는 충원 비율**을 연차 기준으로 나눈 내용으로 보입니다. 컬럼은 **‘구분’**(항목/기준), **‘장교’**(장교 대상 적용 비율), **‘부사관’**(부사관 대상 적용 비율)을 의미하며, 표에 제시된 수치로는 장교의 경우 **2년차 60%, 3년차 20%, 5~7년차 20%**, **3년차 70%, 4년차 30%**, **2년차 30%, 3년차 40%, 4년차 30%** 등 연차별 비율이 나타납니다. 또한 일부 항목은 **‘이후 결원 발생 시’**라고 되어 있어, 정해진 연차 비율 적용 후에는 결원 발생 시 추가 충원하는 방식임을 보여줍니다.']
생성된 답변(정답): 표에 따르면 부사관의 연차별 승진 또는 보직 비율은 구분별로 제시되어 있으며, 일부 항목에서는 정해진 연차 비율 적용 후 결원 발생 시 추가 충원하는 방식이 적용됩니다.
평가대상 RAG의 답변: None
평가대상 RAG가 검색한 Context: None

In [31]:
# 생성된 Testset을 Pandas DataFrame으로 변환
eval_df = testset.to_pandas()

In [32]:
eval_df.shape

(12, 7)

In [33]:
eval_df

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name
0,부사관의 연차별 승진 또는 보직 비율은 어떻게 되나요?,[이 표는 **구분별로 장교와 부사관의 승진·보직 또는 충원 비율**을 연차 기준으...,"표에 따르면 부사관의 연차별 승진 또는 보직 비율은 구분별로 제시되어 있으며, 일부...",Military Personnel Planner,WEB_SEARCH_LIKE,MEDIUM,single_hop_specific_query_synthesizer
1,농협손해보험은 맞춤형복지제도에서 어떤 역할을 하나요?,"[46 \n2026 초급간부 길라잡이\n 개 념 \n하사 이상 현역간부, 군무원 ...",농협손해보험은 맞춤형복지제도의 단체보험 항목에서 자녀를 대상으로 공동 서비스제공 보...,HR Benefits Coordinator,PERFECT_GRAMMAR,MEDIUM,single_hop_specific_query_synthesizer
2,복지정책협력 담당 부서는 어디인가요?,[02\nPart\n생\n활\n편\n의\n \n분\n야\n47 \n2026 초급간부...,복지정책협력 담당부서는 국방부 복지정책과입니다.,HR Benefits Coordinator,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer
3,평택에 위치한 국방 관련 복지·숙박 시설에는 무엇이 있습니까?,"[이 표는 국방 관련 복지·숙박 시설 목록을 정리한 것으로 보이며, 컬럼은 각각 *...","해군호텔(서울·평택·제주) 및 해군회관(진해)이 포함되어 있으며, 이 중 평택에 위...",Military Personnel Planner,PERFECT_GRAMMAR,SHORT,single_hop_specific_query_synthesizer
4,사회적응 지원 분야에서 청년장병 뉴스타트 프로그램은 어떤 대상에게 어떤 지원을 제공...,[<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧...,사회적응 지원 분야에서 청년장병 뉴스타트 프로그램은 군 복무 중인 전 장병과 청년장...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
5,장병 경제교욱이랑 사이버아카데미 뭐가 다르나요?,[<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧...,장병 경제교육은 군 복무 중인 장병을 대상으로 경제 관련 교육을 제공하는 프로그램이...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
6,사회적응 지원 뭐고 청년장병 뉴스타트 프로그램이랑 무슨 관계 있어요?,[<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧...,사회적응 지원은 군 복무 중이나 전역 예정 장병들이 취업이나 창업 준비할 수 있게 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
7,"사회적응 지원 분야에서 청년장병 뉴스타트 프로그램이 뭐고, 이 프로그램이 군 복무 ...",[<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧...,사회적응 지원 분야에는 청년장병 뉴스타트 프로그램이 포함되어 있어. 이 프로그램은 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer
8,"해군 복무연장 지원하려면 어떤 절차 따라야 하고, 해군에서 지원 가능한 특기병 종류...",[<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n...,"해군 복무연장 지원하려면 먼저 선발계획 공지 보고, 지원서 접수하고, 부대추천 심사...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer
9,"해군 복무연장 지원하려면 언제 신청해야 하고, 해군에서 조리병이나 갑판병 같은 특기...",[<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n...,"해군 복무연장 지원은 연 2회(전반기, 후반기) 진행되며, 임관 2년차부터 9년차(...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer
10,해군 복무연장 지원하려면 지원대상 기간이랑 해군에서 할 수 있는 병과 뭐 있어?,[<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n...,"해군 복무연장 지원하려면 장교는 임관 2년차부터 9년차까지, 부사관은 임관 4년차부...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer
11,"해군 복무연장 지원하려면 임관 몇 년차부터 몇 년차까지 지원 가능한지랑, 해군에서 ...",[<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n...,"해군 복무연장 지원은 장교의 경우 임관 2년차부터 9년차까지, 부사관의 경우 임관 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer

In [34]:
row_idx = 0
q = eval_df.loc[row_idx, 'user_input']
resp = chain.invoke(q)

In [35]:
# resp
resp['response']

'부사관의 연차별 승진 또는 보직 비율은 다음과 같습니다.\n\n- **2년차 30%**\n- **3년차 40%**\n- **4년차 30%**\n\n또한 일부 항목은 **이후 결원 발생 시**로 제시되어 있어, 정해진 연차 비율 적용 후에는 결원 발생 시 추가 충원하는 방식입니다.'

In [36]:
# resp
resp['retrieved_context']

['이 표는 **구분별로 장교와 부사관의 승진·보직 또는 충원 비율**을 연차 기준으로 나눈 내용으로 보입니다. 컬럼은 **‘구분’**(항목/기준), **‘장교’**(장교 대상 적용 비율), **‘부사관’**(부사관 대상 적용 비율)을 의미하며, 표에 제시된 수치로는 장교의 경우 **2년차 60%, 3년차 20%, 5~7년차 20%**, **3년차 70%, 4년차 30%**, **2년차 30%, 3년차 40%, 4년차 30%** 등 연차별 비율이 나타납니다. 또한 일부 항목은 **‘이후 결원 발생 시’**라고 되어 있어, 정해진 연차 비율 적용 후에는 결원 발생 시 추가 충원하는 방식임을 보여줍니다.',
 '이 표는 **각 군(육군·해군·공군)의 장교/부사관 장기복무 선발 제도**를 정리한 것으로, 장기복무 선발 시 얻는 혜택과 함께 **평가요소 및 배점 기준**을 보여줍니다. 혜택으로는 **소령(상사) 진출 기회**, **계급별 정년(소령 50세, 상사 53세)**, **군사교육 선발 조건**, **국외연수·국방무관·UN PKO 등 해외근무 기회**가 포함됩니다.  \n\n표의 핵심 컬럼은 **구분(군/계급/복무연차)**, **계(총점)**, 그리고 **상훈·근무평정·교육성적·부대평가·추천·면접·체력검정·잠재역량평가·기술/자격·위원회 심사** 같은 세부 평가항목이며, 총점은 대체로 **100점(공군 부사관은 90점)** 기준으로 구성됩니다. 예를 들어 육군 장교는 **2~3년차 100점**, **5년차 이상 100점**으로 나뉘고, 해군 장교/부사관과 공군 장교/부사',
 '이 표는 각 계급 간 진급을 위한 **최소 복무기간**과 **연령 상한**을 정리한 기준표입니다. 컬럼은 **병장→하사, 하사→중사, 중사→상사, 중위→대위, 대위→소령, 소령→중령**의 진급 구간을 뜻하며, 예를 들어 병장→하사는 **병장으로 2년(예비역 1년차부터)**, 하사→중사는 **7년**, 중사→상사는 **12년** 복무가 필요합니다. 연령 기준은 각 구간별로 **병장→하사 만 37세 이하, 하사→중사 만 42세 이하, 중사→상사 만 50세 이하, 중위→대위 만 40세 이하, 대위→소령 만 43세 이하, 소령→중령 만 50세 이하**로 제시되어 있습니다.',
 '이 표는 **장교와 부사관의 임관 후 경과 연차별 구분**을 보여주는 자료로, 각 항목에서 **임관 2년차부터 9년차까지**의 범위를 공통적으로 제시하고 있습니다. 컬럼은 **구분**, **장교**, **부사관**으로 구성되어 있으며, 직군별로 동일한 연차 기준을 적용하는 형태입니다. 다만 현재 추출된 표에서는 세부 수치나 추가 항목명이 보이지 않고, **임관 2~9년차**라는 기간 정보가 핵심 내용으로 나타납니다.',
 '이 표는 **육군 간부 선발 또는 평가 시 항목별 배점 기준**을 정리한 것으로 보이며, 대상은 **장교와 부사관**으로 나뉘고 각자의 **복무연차(장교 2~3년, 5년차 이상 / 부사관 3~4년, 5년차 이상)**에 따라 평가 비중이 달라집니다. 전체 배점은 모두 **100점**이며, 평가 항목은 **근무평정, 교육성적, 상훈, 부대평가, 부대추천, 면접평가, 체력검정, 잠재역량, 질적평가**로 구성됩니다. 예를 들어 장교 2~3년차는 **부대추천 30점, 근무평정 25점, 면접평가 10점, 체력검정 5점** 등이 배정되고, 장교 5년차 이상은 **근무평정 40점**으로 비중이 커집니다. 부사관은 3~4년차에 **근무평정 35점, 부대추천 15점** 등이 배정되며, 5년차 이상은 **근무평정 50점, 부대평가 10점, 부대추천 0점** 등으로 구성되어 있습니다.']

In [37]:
# 모든 testset의 데이터데 대한 llm 응답과 retriever의 검색 겷과를 추가
response_list = []
retrieved_context_list = []

for user_input in eval_df['user_input']:
    resp = chain.invoke(user_input)
    response_list.append(resp["response"])
    retrieved_context_list.append(resp["retrieved_context"])

In [38]:
print(len(response_list), len(retrieved_context_list))

12 12

In [39]:
response_list

['정보가 부족해 답을 할 수없습니다.',
 '정보가 부족해 답을 할 수없습니다.',
 '정보가 부족해 답을 할 수없습니다.',
 '평택에 관련된 국방 복지·숙박 시설로는 **해군호텔(평택)**이 있습니다.  \n해당 내용은 Context의 표에서 **해군호텔(서울, 평택, 제주)**로 제시되어 있습니다.',
 '청년장병 뉴스타트 프로그램은 **당해 연도 전역예정장병인 청년장병(간부 중심)**을 대상으로 하며, **취업역량 강화와 취업률 향상**을 위해 **채용 단계별 프로그램**을 제공합니다.\n\n주요 지원은 다음과 같습니다.\n- **초기상담 및 컨설팅 안내**\n- **진로방향·목표점검**\n- **역량·강점 분석**\n- **입사서류 클리닉**\n- **모의면접**\n- **채용정보 제공**\n- **직무·기업분석**\n- **희망기업 알선**\n- **직장적응지원**\n- **경력개발지원**\n- **취업성공사례관리**\n- **취업기업관리**\n\n또한 유형별로는:\n- **뉴 스타트Ⅰ형**: 취업역량 기본과정\n- **뉴 스타트Ⅱ형**: 취업준비 심화과정, 1:1 컨설팅 및 취업매칭 지원\n- **뉴 스타트Ⅲ형**: 채용 설명회, 일자리 매칭데이·공직 채용 설명회·창업 설명회 제공\n\n',
 '장병 경제교육과 사이버아카데미는 **목적과 교육 내용이 다릅니다.**\n\n- **장병 경제교육**:  \n  병사 봉급 인상에 따른 **자산 형성, 재무관리, 신용관리, 금융사기 예방** 등을 위한 경제교육입니다.  \n  대상은 **육·해·공군, 해병대 장병 및 훈련기관 교육생**이고, **오프라인/온라인**으로 운영됩니다.\n\n- **사이버아카데미**:  \n  전역예정장병의 **전직준비와 생애설계 역량 강화**를 위한 **온라인 상시학습시스템**입니다.  \n  취업역량, 진로설정, 전직준비, 직무, 자격, 어학, AI디지털역량 등 **취업·창업 준비 중심**의 교육을 제공합니다.\n\n즉,  \n**장병 경제교육은 ‘금융·경제 관리’ 중심**,  \n**사이버아카데미는 ‘전역 후 진로·취업 준비’ 중심**입니다.',
 '사회적응 지원은 **전역 전후 장병이 사회로 돌아가 적응하도록 돕는 지원 분야**를 뜻합니다. 제공된 context에서는 사회적응 지원 분야에 다음 내용이 포함됩니다.\n\n- 취업 및 창업 지원\n- 장병 경제교육\n- 국민연금 군 복무 크레딧\n- 국가보훈대상자 등록\n- 예비군훈련 안내\n- 상비예비군 제도\n- 예비역 병 → 부사관(하사) 임용\n\n청년장병 뉴스타트 프로그램과의 관계는, **뉴스타트가 사회적응 지원 분야 안에 포함되는 취업 지원 프로그램**이라는 점입니다.  \ncontext에 따르면 뉴스타트는:\n\n- **당해 연도 전역예정장병 청년장병(간부 중심)**을 대상으로 하고,\n- **취업역량 강화 및 취업률 향상**을 목표로 하며,\n- **취업준비, 채용설명회, 취업매칭, 사후관리**까지 단계별로 지원합니다.\n\n즉, **사회적응 지원**은 큰 범주이고, **청년장병 뉴 스타트**는 그 안에서 **취업을 중심으로 사회 진출을 돕는 세부 프로그램**입니다.',
 '청년장병 뉴스타트(New start) 프로그램은 **당해 연도 전역예정 장병, 특히 청년장병(간부 중심)**을 대상으로 **취업역량 강화와 취업률 향상**을 목표로 운영되는 **채용 단계별 취업지원 프로그램**입니다.\n\n군 복무 중 장병에게 제공되는 취업 지원 내용은 다음과 같습니다.\n\n- **뉴스타트 Ⅰ형(취업역량 기본과정)**\n  - 채용동향 분석\n  - 입사지원서 작성\n  - 인적성 검사\n  - 성공적인 면접\n  - 집단상담\n  - 수료 후 **개인별 맞춤 컨설팅 및 취업매칭 지원**\n\n- **뉴스타트 Ⅱ형(취업준비 심화과정)**\n  - 전역 후 취업을 원하는 기업과의 **맞춤형 교육**\n  - **개인별 1:1 컨설팅**\n  - **취업매칭**\n  - 전역 후 취업연계\n  - 수료 후 **개인별 맞춤 컨설팅 및 취업매칭 지원**\n\n- **뉴스타트 Ⅲ형(채용 설명회)**\n  - **기업 채용 설명회 등 일자리 매칭 행사**\n  - **공직 채용 설명회**\n  - **창업 설명회**\n  - 대기업, 중소기업, 공기업 등 다양한 채용정보 제공\n\n즉, 뉴스타트 프로그램은 군 복무 중 장병들에게 **취업 준비 교육, 1:1 상담, 입사지원서·면접 지원, 채용정보 제공, 취업매칭, 사후관리**까지 연계해 주는 취업지원 프로그램입니다.',
 '정보가 부족해 답을 할 수없습니다.',
 '해군 복무연장은 **연 2회(전반기, 후반기)** 신청합니다.  \n다만 **정확한 신청 시기**는 context에 구체적으로 제시되어 있지 않습니다.  \n\n해군의 **기능사 필기시험 면제 교육과정**은  \n- **기술행정학교**: 자동차정비초급, 전기초급, 보수초급·중급, **한식조리**, 추기초급  \n- **해난구조대**: 해난구조기본  \n으로 안내되어 있습니다.\n\n질문하신 **조리병**은 context상 **기술행정학교의 한식조리 과정**에서 교육받는 것으로 보입니다.  \n하지만 **갑판병의 교육기관**은 context에 명확히 나오지 않아 답할 수 없습니다.',
 '정보가 부족해 답을 할 수없습니다.',
 '정보가 부족해 답을 할 수없습니다.']

In [40]:
retrieved_context_list

[['이 표는 **구분별로 장교와 부사관의 승진·보직 또는 충원 비율**을 연차 기준으로 나눈 내용으로 보입니다. 컬럼은 **‘구분’**(항목/기준), **‘장교’**(장교 대상 적용 비율), **‘부사관’**(부사관 대상 적용 비율)을 의미하며, 표에 제시된 수치로는 장교의 경우 **2년차 60%, 3년차 20%, 5~7년차 20%**, **3년차 70%, 4년차 30%**, **2년차 30%, 3년차 40%, 4년차 30%** 등 연차별 비율이 나타납니다. 또한 일부 항목은 **‘이후 결원 발생 시’**라고 되어 있어, 정해진 연차 비율 적용 후에는 결원 발생 시 추가 충원하는 방식임을 보여줍니다.',
  '이 표는 **각 군(육군·해군·공군)의 장교/부사관 장기복무 선발 제도**를 정리한 것으로, 장기복무 선발 시 얻는 혜택과 함께 **평가요소 및 배점 기준**을 보여줍니다. 혜택으로는 **소령(상사) 진출 기회**, **계급별 정년(소령 50세, 상사 53세)**, **군사교육 선발 조건**, **국외연수·국방무관·UN PKO 등 해외근무 기회**가 포함됩니다.  \n\n표의 핵심 컬럼은 **구분(군/계급/복무연차)**, **계(총점)**, 그리고 **상훈·근무평정·교육성적·부대평가·추천·면접·체력검정·잠재역량평가·기술/자격·위원회 심사** 같은 세부 평가항목이며, 총점은 대체로 **100점(공군 부사관은 90점)** 기준으로 구성됩니다. 예를 들어 육군 장교는 **2~3년차 100점**, **5년차 이상 100점**으로 나뉘고, 해군 장교/부사관과 공군 장교/부사',
  '이 표는 각 계급 간 진급을 위한 **최소 복무기간**과 **연령 상한**을 정리한 기준표입니다. 컬럼은 **병장→하사, 하사→중사, 중사→상사, 중위→대위, 대위→소령, 소령→중령**의 진급 구간을 뜻하며, 예를 들어 병장→하사는 **병장으로 2년(예비역 1년차부터)**, 하사→중사는 **7년**, 중사→상사는 **12년** 복무가 필요합니다. 연령 기준은 각 구간별로 **병장→하사 만 37세 이하, 하사→중사 만 42세 이하, 중사→상사 만 50세 이하, 중위→대위 만 40세 이하, 대위→소령 만 43세 이하, 소령→중령 만 50세 이하**로 제시되어 있습니다.',
  '이 표는 **장교와 부사관의 임관 후 경과 연차별 구분**을 보여주는 자료로, 각 항목에서 **임관 2년차부터 9년차까지**의 범위를 공통적으로 제시하고 있습니다. 컬럼은 **구분**, **장교**, **부사관**으로 구성되어 있으며, 직군별로 동일한 연차 기준을 적용하는 형태입니다. 다만 현재 추출된 표에서는 세부 수치나 추가 항목명이 보이지 않고, **임관 2~9년차**라는 기간 정보가 핵심 내용으로 나타납니다.',
  '이 표는 **육군 간부 선발 또는 평가 시 항목별 배점 기준**을 정리한 것으로 보이며, 대상은 **장교와 부사관**으로 나뉘고 각자의 **복무연차(장교 2~3년, 5년차 이상 / 부사관 3~4년, 5년차 이상)**에 따라 평가 비중이 달라집니다. 전체 배점은 모두 **100점**이며, 평가 항목은 **근무평정, 교육성적, 상훈, 부대평가, 부대추천, 면접평가, 체력검정, 잠재역량, 질적평가**로 구성됩니다. 예를 들어 장교 2~3년차는 **부대추천 30점, 근무평정 25점, 면접평가 10점, 체력검정 5점** 등이 배정되고, 장교 5년차 이상은 **근무평정 40점**으로 비중이 커집니다. 부사관은 3~4년차에 **근무평정 35점, 부대추천 15점** 등이 배정되며, 5년차 이상은 **근무평정 50점, 부대평가 10점, 부대추천 0점** 등으로 구성되어 있습니다.'],
 ['46 \n2026 초급간부 길라잡이\n 개 념 \n\x07하사 이상 현역간부, 군무원 및 공무원 등 개인에게 배정된 복지예산 한도 내에서 \n개인의 욕구와 필요에 따라 복지항목 및 수혜수준을 선택할 수 있는 제도\n* \x07맞춤형복지 예산은 기본항목(단체보험)을 선 계약 후 남은 금액을 개인별 복지점수에 따라 \n자율항목(복지포인트)으로 분기마다 지급\n* \x07맞춤형복지(단체보험, 복지포인트) 관련 자세한 내용은 “IMND 복지포털(웹/APP)”에서 확인 \n가능\n 맞춤형복지 구성 항목\n구분\n기본항목 (단체보험)\n자율항목 (복지포인트)\n내용\n•생명/상해 보험 \n•입·통원 의료비 보장 보험\n•매분기별 복지포인트 지급\n•개인별 자율적 선택사용\n기타\n•’26년 단체보험 계약현황\n - 주 계약 보험사 : 한화손해보험\n - 공동 서비스제공 : \x07삼성화재, 롯데손해보험, \n농협손해보험(자녀)\n•매년 11월 30일까지만 \n 사용 가능 \n (미사용 잔액은 불용처리)\n 이용방법 \n*\x07 \x07주의사항 : 복지포인트 미사용(불용)액 최소화를 위해 신규 임관자 대상 카드 발급 및 11월 말 \n까지 사용토록 관심 필요\n*\x07 \x07단체보험 중 생명·상해 보험은 의무가입 사항이며, 실손보험의 경우 개인실손 가입자에 한해 중복\n가입 제외 신청 시(매년 11월 ~ 익년 1월 中) 적용대상에서 제외 가능(차액은 복지포인트로 지급)\n-⑥ 맞춤형복지제도',
  '이 표는 **복지제도 중 보험성 혜택의 구성**을 보여주며, 컬럼은 **구분**, **기본항목(단체보험)**, **자율항목(복지포인트)**로 나뉩니다. 기본항목에는 **생명/상해 보험**과 **입·통원 의료비 보장 보험**이 포함되어 있고, **’26년 단체보험 계약현황**으로는 **주 계약 보험사 한화손해보험**, 공동 서비스제공은 **삼성화재, 롯데손해보험, 농협손해보험(자녀)**로 표시되어 있습니다. 자율항목(복지포인트) 칸은 비어 있어, 이 표는 주로 **단체보험의 보장 항목과 계약 보험사 정보를 정리한 내용**입니다.',
  'Part 05 재해보상 분야\n62 2026 병 복지 길라잡이\n 병 무료 상해보험(나라사랑카드 서비스)\n개 요\n • 대상 / 가입절차 : 나라사랑카드를 발급한 현역병(상근포함) / 자동가입\n • 보험기간 : 현역입대일 ~ 전역일 24 : 00\n * 기간 중 나라사랑카드 해지 시에는 보험의 혜택을 받을 수 없음.\n보험혜택\n구 분\n내 용\n하나은행\n(하나손해보험)\nㅇ 대상 : 현역병(육·해·공·해병대), 상근예비역\n - (부대 밖 : 휴가·외출·외박) 대중교통수단 이용 중 상해사망/\n상해후유장해 발생 시 최대 4억원\n - (부대 밖 : 휴가·외출·외박) 상해사망/상해후유장해 발생 시\n최대 5천만원\n - (부대 안·밖) 폭발, 화재로 인한 상해사망/상해후유장해 \n발생 시 최대 4억원\n화상진단비 (최대20만원), 화상수술비(최대 50만원)\n - (복무기간 內) 사이버금융범죄 금전 손해의 70% 보상 (최대 3백만원)\n착오송금 회수비용보상 (최대 7백만원) \nIBK기업은행\n(현대해상)\nㅇ 대상 : 현역병(육·해·공·해병대), 상근예비역\n - (부대 밖 : 휴가·외출·외박) 대중교통수단 이용 중 상해사망/\n상해후유장해 발생 시 최대 3억원\n - (부대 밖 : 휴가·외출·외박) 상해사망/상해후유장해 발생 시\n최대 1억원\n - (부대 안·밖) 화재, 폭발, 붕괴로 인한 상해사망/상해후유장해\n발생 시 최대 1억원\n자연재해 상해사망, 상해후유장해 최대 3천만원\n신한은행\n(신한EZ손해보험)\nㅇ 대상 : 현역병(육·해·공·해병대), 상근예비역\n - (부대 밖 : 휴가·외출·외박) 대중교통수단 이용 중 상해사망/\n상해후유장해 발생 시 최대 3억원\n - (부대 밖 : 휴가·외출·외박) 상해사망/상해후유장해 발생 시\n최대 1억원\n - (부대 안·밖) 화재, 폭발, 붕괴로 인한 상해사망/상해후유장해\n발생 시 최대 1억원',
  '2026 병 복지 길라잡이 63\n • 하나은행, IBK기업은행, 신한은행의 나라사랑카드를 3개 모두 발급받아 \n소지하고 있는 병사는 중복 보상이 가능함 / 따라서, 가능한 3개 카드 모두 \n발급을 받는 것이 본인에게 유리(연회비 없음)\n • 보험 상세내용은 보험사 약관을 따르므로, 반드시 보험사 약관 확인\n보험금 신청\n • 보상 여부 및 보험금 신청 문의\n - 하나손해보험 (하나은행) ☞ 1566-3000\n - 현대해상 (IBK기업은행) ☞ 02-2097-2911\n - 신한EZ손해보험 (신한은행) ☞ 1544-9686',
  '2026 병 복지 길라잡이 11\n나라사랑카드\n \n개 요\n \n구 분\n하나은행\nIBK기업은행\n신한은행\n역할 및 \n기능\n(공통)\n◦전자병역증・전역증\n◦군 급여계좌, 현금・체크카드\n◦군 특화서비스\n- 군 마트(PX) 할인, 병 무료 상해보험서비스 등\n◦일반 할인서비스\n- 대중교통 할인, 편의점 할인, 영화관 할인, OTT 할인, 배달앱 할인,\n 쇼핑 할인 등 \n◦금융 우대 서비스\n- 인터넷ㆍ스마트뱅킹 수수료, ATM현금인출서비스 수수료 면제\n ※ 하나은행, IBK기업은행, 신한은행 카드 3개를 모두 발급 가능(연회비 없음) 하고, 무료 \n상해보험서비스 중복 보장 가능. 단, 3개 카드 모두 발급 시 급여가 지급되는 계좌(카드)를 \n본인이 각 부대 인사(재정)담당관에게 요청하여 지정 필요\n주요 서비스(하나, IBK, 신한 공통)\n • 전자병역증‧ 전역증 탑재\n - 병역증 : 병역판정 검사 시 탑재\n - 전역증 : 전역 시 인사부서에서 나라사랑카드 IC칩에 전역증 탑재 시 존재\n * 나라사랑포털APP으로 본인의 전자병역증·전역증 조회 가능\n (단, 전역증은 부대에서 탑재했을 시)\n • ATM(CD)기기 현금인출 시 수수료 면제\n - 대상 : 나라사랑카드 계좌를 급여계좌로 활용하는 현역병\n - 적용 : 국내 시중은행 전용 ATM기에서 현금인출 시 이용횟수에 관계없이 면제\n * 편의점, 지하철역 등에 있는 제휴 ATM기기(나이스 등)는 수수료면제가\n 불가하며, 수수료가 부과되니 유의'],
 ['02\nPart\n생\n활\n편\n의\n \n분\n야\n47 \n2026 초급간부 길라잡이\n 복지포인트 지급 기준 \n구분\n점 수\n비 고\n공통점수\n400점\n대상자 전원 지급\n근속점수\n300점\n근속 1년당 10점, 최대 30년\n가족점수\n배우자 150점, 부양가족 50점/1명당\n (가족점수는 “급여상 가족수당”을 받는 인원만 인정됨)\n* \x07분기 지급금액 = 개인점수 × 1점당 기준금액\n* 1점당 기준금액 = 분기 자율항목 가용예산 ÷ 개인점수의 합\n 복지포인트 사용 시 유의사항 \n •사용 가능한 분야 : 건강관리, 자기계발, 여가활동, 가정친화 등\n •사용 불가항목\n - 철도/항공, 인터넷 쇼핑몰 및 인터넷 결제(웹 및 App)\n - \x07세금공과금, 주류판매(유통), 전자상거래(다품목취급), 결제대행(PG), \n상품권판매\n - \x07복권판매, 농협(상품권), 룸살롱, 칵테일/스탠드바, 나이트클럽, 카바레, \n단란주점\n - \x07맥주홀, 유흥주점, 카지노, 비디오/전화방, 총포류판매, 성인용품판매점, \n안마시술소\n - \x07스포츠마사지, 종교단체, 무속/철학관, 귀금속, 금은방, 오락실/PC방\n - \x07각종회비\n •\x07복지포인트는 반드시 일시불 결제를 원칙으로 하며, 할부 결제 시 \n개인카드로 결제 처리됨\n국방부 복지정책과 복지정책협력 | 900-6625\n담당부서',
  '2026 병 복지 길라잡이 67\n고용노동부 취업 안내 \n • 주관：전국 102개 고용(복지+)센터(www.workplus.go.kr)\n • 이용대상：전 국민, 전역 후 활용 가능\n • 이용절차\n - 고용(복지+)센터 방문 또는 고용24(www.work24.go.kr)에서 구직 신청\n - 구직자에게 일자리 정보 및 취업특강 등 취업지원 프로그램 제공\n - 국민취업지원제도* 등을 통해 취약계층 대상 통합적인 고용서비스\n (취업상담-직업훈련-취업알선) 제공\n \n* 소득, 재산 등 지원요건 해당 시 생계지원(구직촉진수당) \n < 고용(복지+)센터 구직자 취업지원 서비스 흐름도 > \n<고용24 구직신청>\n- 고용24에서 개인회원으\n로 가입하여 직접 구직\n신청\n- 또는 고용(복지+)센터\n에 방문하여 구직 신청\n서 제출\n<직업상담 및 취업알선>\n- 고용(복지+)센터: 적합한 진\n로선택을 위한 직업상담을 \n실시하고, 그 능력과 취업 \n희망조건에 적합한 일자리\n를 소개하거나 구직기술 향\n상 및 고용정보 제공을 위한 \n취업지원프로그램 등 운영 \n- 구직자는 고용24에서 일자\n리정보를 검색하여 직접 입\n사지원 가능\n<취업 및 결과 통보>\n- 구인, 구직자는 고용24\n으로 채용결과를 직접 \n입력하거나 고용(복지+)\n센터에 채용결과를 통보 \n- 미취업 시 고용(복지+)센\n터에 취업지원서비스 등\n을 다시 신청\n - 훈련비 지원을 위한 국민내일배움카드(직업능력개발계좌) 발급 \n \n* 고용24(www.work24.go.kr)에서 신청 가능(실업자는 먼저 구직 신청을 완료해야 가능)\n \n* 추천 : 국방부, 국가보훈부 / 운영 : 고용노동부\n • 문의처 \n - 고용노동부 고객상담센터 (국번 없이 1350) \n \n* 평일 오전 9시~ 오후 6시 상담(주말 및 공휴일 휴무)\n - 고용24(www.work24.go.kr) 홈페이지',
  '취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧\n국가보훈대상자 등록\n예비군훈련 안내\n상비예비군 제도\n예비역 병 ⇨ 부사관(하사) 임용\nPart 06\n사회적응 지원 분야',
  '생활편의 분야\n-① 초급간부 보수 및 수당안내\n-② 간부 복지혜택\n-③ 일-가정 양립 지원제도\n-④ 초급간부 대상 피복 및 급식 지원\n-⑤ 간부 주거 지원제도\n-⑥ 맞춤형복지제도\n-⑦ 초급간부 재정안정지원\n-⑧ 군인공제회 회원복지부조\n-⑨ 군인공제회 건강검진 제휴 서비스\n-⑩ 군인공제회 콘도 및 제휴 복지 서비스\n-⑪ 장병e음 플랫폼 서비스\n02\nPart',
  '46 \n2026 초급간부 길라잡이\n 개 념 \n\x07하사 이상 현역간부, 군무원 및 공무원 등 개인에게 배정된 복지예산 한도 내에서 \n개인의 욕구와 필요에 따라 복지항목 및 수혜수준을 선택할 수 있는 제도\n* \x07맞춤형복지 예산은 기본항목(단체보험)을 선 계약 후 남은 금액을 개인별 복지점수에 따라 \n자율항목(복지포인트)으로 분기마다 지급\n* \x07맞춤형복지(단체보험, 복지포인트) 관련 자세한 내용은 “IMND 복지포털(웹/APP)”에서 확인 \n가능\n 맞춤형복지 구성 항목\n구분\n기본항목 (단체보험)\n자율항목 (복지포인트)\n내용\n•생명/상해 보험 \n•입·통원 의료비 보장 보험\n•매분기별 복지포인트 지급\n•개인별 자율적 선택사용\n기타\n•’26년 단체보험 계약현황\n - 주 계약 보험사 : 한화손해보험\n - 공동 서비스제공 : \x07삼성화재, 롯데손해보험, \n농협손해보험(자녀)\n•매년 11월 30일까지만 \n 사용 가능 \n (미사용 잔액은 불용처리)\n 이용방법 \n*\x07 \x07주의사항 : 복지포인트 미사용(불용)액 최소화를 위해 신규 임관자 대상 카드 발급 및 11월 말 \n까지 사용토록 관심 필요\n*\x07 \x07단체보험 중 생명·상해 보험은 의무가입 사항이며, 실손보험의 경우 개인실손 가입자에 한해 중복\n가입 제외 신청 시(매년 11월 ~ 익년 1월 中) 적용대상에서 제외 가능(차액은 복지포인트로 지급)\n-⑥ 맞춤형복지제도'],
 ['이 표는 국방 관련 복지·숙박 시설 목록을 정리한 것으로 보이며, 컬럼은 각각 **구분**, **시설명**, **홈페이지**를 의미합니다. 포함된 주요 시설은 **국방컨벤션**, **계룡스파텔·ROKAUS호텔**, **해군호텔(서울·평택·제주) 및 해군회관(진해)**, **공군호텔**, **그린나래호텔**, **밀리토피아 호텔 바이마린** 등입니다. 홈페이지 항목은 모두 비어 있어, 표는 시설명 중심의 안내 목록이며 총 **6개 항목(복수 지점 포함)**이 제시되어 있습니다.',
  '2026 병 복지 길라잡이 23\n • 국군복지단 휴양시설 현황\n구분\n시 설 명\n위 치\n전화번호(군)\n전화번호(일반)\n직영\n서귀포 호텔\n제주 서귀포시\n960-7703\n064-738-0123\n화진포 콘도\n강원 고성군 \n960-7706\n033-682-0500\n청간정 콘도\n강원 고성군 \n822-6470\n033-631-9331\n송 정 콘도\n강원 강릉시 \n940-3881\n033-652-7573\n대 천 콘도\n충남 보령시 \n960-7705\n041-932-6305\n민영\n한 화\n설악, 용인, 대천, 산정호수, \n해운대, 경주, 제주, 평창, 거제\n국군복지단\n예약실\n984-6584\n국군복지단\n예약실\n1577-9800\n내선 “1번”\n금 호\n통영, 화순, 설악, 제주, 아산\n소 노\n설악, 경주, 단양, 홍천, 양양, \n변산, 거제, 삼척, 진도, 여수, \n고양(호텔), 양평\n켄싱턴\n남원, 설악비치, 충주, 경주,\n가평, 설악밸리, 하동, 서귀포\n무 주\n전북무주\n리 솜\n안면도\n엘도라도\n전남신안\n샤인빌(소노캄)\n제주\n보 광\n제주\n웰리힐리\n강원횡성\n영랑호\n강원 속초\n현대수\n강원 속초\n • 각 군 휴양시설 이용방법 : 각 군 홈페이지 참조\n구분\n시 설 명\n홈페이지 주소\n국방부\n국방컨벤션(웨딩)\nwww.mndconvention.co.kr\n육군\n로카우스 호텔, 계룡스파텔\nwelfare.army.mil.kr\n해군\n해군호텔(서울, 평택, 제주), \n해군회관(진해)\nwelfare.navy.mil.kr\n공군\n공군호텔\nwww.airforcehotel.co.kr\n그린나래호텔\nwww.guerinnarae.com\n해병대\n밀리토피아호텔 바이마린(해병대호텔)\nwww.militopiahotelbymarine.com',
  '이 표는 국군복지단에서 이용 가능한 숙박·콘도 시설 목록으로, **시설명**, **위치**, **군 전화번호**, **일반 전화번호**를 정리한 자료입니다. 서귀포 호텔, 화진포 콘도, 청간정 콘도, 송정 콘도, 대천 콘도 등 개별 시설과 함께 한화·금호·소노·켄싱턴 같은 제휴 리조트 브랜드별 이용 가능 지역도 포함되어 있습니다. 대표 연락처로는 서귀포 호텔 960-7703, 화진포 콘도 960-7706, 청간정 콘도 988-7873, 송정 콘도 940-3881, 대천 콘도 960-7705가 기재되어 있으며, 한화 예약실은 984-6499로 표시되어 있습니다.',
  '34 \n2026 초급간부 길라잡이\n•국군복지단 휴양시설 현황\n구분\n시 설 명\n위 치\n전화번호(군)\n전화번호(일반)\n직영\n서귀포 호텔\n제주 서귀포시\n960-7703\n064-738-0123\n화진포 콘도\n강원 고성군 \n960-7706\n033-682-0500\n청간정 콘도\n강원 고성군 \n988-7873\n033-631-9331\n송정 콘도\n강원 강릉시 \n940-3881\n033-652-7573\n대천 콘도\n충남 보령시 \n960-7705\n041-932-6305\n민영\n한 화\n 거제, 경주, 대천, \n산정호수, 설악, 용인, \n제주, 평창, 해운대\n국군복지단\n예약실\n984-6499\n국군복지단\n예약실\n1577-9800\n금 호\n 통영, 화순, 설악, 제주, 아산\n소 노\n 경주, 거제, 고양, 단양,\n변산, 삼척, 설악, 진도,\n양양, 양평, 여수, 홍천\n켄싱턴\n남원, 설악비치, 충주, \n경주, 가평, 설악밸리, \n하동, 서귀포\n무 주\n전북 무주\n리 솜\n안면도\n엘도라도\n전남 신안\n샤인빌\n제주\n보 광\n제주\n웰리힐리\n강원 횡성\n영랑호\n강원 속초\n현대수\n강원 속초\n국방부 복지정책과 복지운영담당 | 900-6617\n담당부서',
  '이 표는 **군 관련 부대/기관별 복지시설(호텔·회관·웨딩시설 등)**과 해당 시설의 **홈페이지 주소**를 정리한 목록입니다. 컬럼은 **구분(국방부·육군·해군·공군·해병대)**, **시설명(국방컨벤션, 로카우스 호텔, 계룡스파텔, 해군호텔, 공군호텔 등)**, **홈페이지 주소**로 구성되어 있습니다. 주요 항목으로는 국방부 1건, 육군 2건, 해군 2건(서울·평택·제주·진해 포함), 공군 2건, 해병대 1건이 포함되어 있으며, 각 시설의 공식 웹사이트를 통해 예약/이용 정보를 확인할 수 있습니다.'],
 ['62 \n2026 초급간부 길라잡이\n-③-Ⅲ\n청년장병 뉴 스타트(New start)\n - \x07(뉴 스타트 미참여자) : 초기상담 통해 뉴 스타트 입교지원 및 대상별 \n취업준비도에 따른 맞춤 컨설팅 및 취업알선 중점\n① 회원 등록 시\n②1:1 컨설팅\n③ 취업알선\n④ 취업성공\n•대상 : 단기복무자\n•초기상담\n•취업프로그램 안내\n•컨설팅 안내\n⇨\n•진로방향/목표점검\n•역량/강점 분석\n•입사서류 클리닉\n•모의면접\n⇨\n•채용정보 제공\n•직무/기업분석\n•희망기업 알선\n⇨\n•직장적응지원\n•경력개발지원\n•취업성공사례관리\n•취업기업관리\n 개 요 \n \x07당해 연도 전역예정장병 청년장병(간부 중심)을 위한 특화 프로그램으로 \n취업역량강화 및 취업률 향상을 목표로 추진되는 채용 단계별 프로그램\n 주요내용\n •뉴 스타트Ⅰ형(취업역량 기본과정)\n구 분\n단과반\n종합반\n목표인원\n•청년장병 2,000명\n기 간\n•1일, 3～6H\n•2박 3일, 18H\n편 성\n•연 60회 이상(단과 20회, 종합반 40회)\n내 용\n•\x07단과 과정 모듈 유형을 선택하여 \n3∼6H 커리큘럼 구성\n•\x07채용동향 분석, 입사지원서 작성, \n인적성 검사, 성공적인 면접, 집단\n상담\n컨설팅 · \n사후관리\n•교육 수료자 대상 개인별 맞춤 컨설팅 및 취업매칭 지원 \n구 분\n•취업맞춤형특기병반\n내 용\n * 맞춤특기병 지원 : 연 4회, 2일 과정\n구분\n내용\n1일차\n(6H)\n•기술직무 이해 및 체험\n - 체험 기술분야 이해(반도체, 스마트팩토리, loT, 전기장치제어 등)\n- 제조 전공정 체험 및 실습\n2일차\n(3H)\n•1:1상담 취업컨설팅(개인별 강점분석, 진로·취업 로드맵)',
  '이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프로그램 목록**을 정리한 것입니다. 컬럼은 각각 **사업명**, **대상**, **주요 내용**을 의미하며, 사이버교육(사이버아카데미), 취업박람회, 청년장병 뉴스타트 Ⅰ·Ⅱ·Ⅲ(2박3일 소집교육 포함), 창업인식개선교육, 창업멘토링, 국방창업경진대회, 취업컨설팅 등이 포함됩니다. 대상은 주로 **군 복무 중인 전 장병**, **청년장병**, **창업 관심 장병**, **창업희망팀/경진대회 진출팀**, **구직등록 장병** 등으로 구분되며, 맞춤형 컨설팅·면접·취업매칭·설명회·멘토링 같은 실질적 지원이 핵심입니다.',
  '이 표는 **뉴 스타트 입교 시 진행되는 절차와 대상**을 정리한 내용입니다. 컬럼은 별도의 수치형 항목보다는 **입교 시 단계별 프로그램/업무 흐름**을 나타내며, 주요 항목은 **대상(단기복무자)**, **컨설팅 안내**, **신청서 접수**, **개인상담**입니다. 즉, 뉴 스타트 프로그램에 **단기복무자가 입교할 때 수행하는 초기 안내 및 상담 절차**를 요약한 표입니다.',
  '01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n63 \n03\nPart\n2026 초급간부 길라잡이\n •뉴 스타트Ⅱ형(취업준비 심화과정)\n구 분\n내 용\n목표인원\n•해당기업 취업을 원하는 청년장병 1,000명\n기 간\n•2박 3일, 18H\n편성/형태\n•연 40회 이상 / 소집(외부연수원), 온라인\n내 용\n•\x07전역예정장병 채용을 원하는 기업과 맞춤형 교육\n•개인별 1:1컨설팅, 취업매칭으로 전역 후 취업연계\n컨설팅 · \n사후관리\n•교육 수료자 대상 개인별 맞춤 컨설팅 및 취업매칭 지원\n •뉴 스타트 Ⅲ형(채용 설명회)\n구 분\n내 용\n기 간\n•\x071일, 2∼4H\n편성/형태\n•\x07연 40회 이상 / 소집(교육원, 외부 시설), 온라인\n일자리 \n매칭데이\n•유형 : 기업 채용 설명회 등 일자리 매칭 행사(연 36회)\n (대기업, 중소기업, 공기업 등 다양한 채용 안내)\n공직 채용 \n설명회\n•유형 : 분야별 공직 설명회(연 2회)\n•내용 : 소방, 경찰, 해양경찰, 공무원, 군무원 등\n창업 \n설명회\n•유형 : 창업설명회(연 2회)\n•내용 : 정부 정책사업 연계, 생계형 창업설명회 등\n 이용방법\n \x07국방전직교육원 홈페이지 회원가입(인터넷) → 일자리지원 HOME → \n 사업별 참가신청 (온라인 개별 신청)\n* 문의 : 뉴 스타트Ⅰ(취업역량 기본과정) 담당 ☎ 031-760-9348\n \n 뉴 스타트Ⅱ(취업준비 심화과정) 담당 ☎ 031-760-9354\n \n 뉴 스타트Ⅲ(채용 설명회) 담당 ☎ 031-760-9344',
  'Part 06 사회적응 지원 분야\n68 2026 병 복지 길라잡이\n • 국방일보 취업정보 게재(매주 화요일) : (http://kookbang.dema.mill.kr/)\n • 온라인(인터넷)을 통한 정보확인\n - 국방전직교육원(www.moti.or.kr) \n - 중소벤처기업진흥공단(www.kosmes.or.kr)\n - 창업진흥원(www.kised.or.kr) \n - 국가보훈부 제대군인지원센터(www.vnet.go.kr)\n - 나라일터(www.gojobs.go.kr) 등\n☎ 문의 : 국방전직교육원(1588-9402) 또는 사·여단 취·창업 담당자\n취업맞춤특기병 특화 프로그램운영\n • 편성 : 연 4회, 2일 과정, 소집교육 / 국방전직교육원, 폴리텍대학\n \n* 연간 및 분기별 교육계획은 국방전직교육원 홈페이지(www.moti.or.kr) 참조\n • 취업맞춤특기병 취업역량 향상 및 체험중심 취업지원 프로그램\n구 분\n내 용 \n구 분\n내 용\n1일차\n(6H)\n기술직무 이해 및 체험\n - 체험 기술분야 이해\n - 제조 전공정 체험·실습\n2일차\n(3H)\n1:1상담 취업컨설팅\n - 개인별 강점분석\n - 진로·취업 로드맵\n☎ 문의 : 국방전직교육원(1588-9402) 또는 사·여단 취·창업 담당자'],
 ['2026 병 복지 길라잡이 69\n장병 경제교육\n개 요\n • 병사 봉급의 급격한 인상 등에 따른 자산 형성과 금융사고 예방 필요성, 50만 \n장병의 원활한 사회 복귀 지원을 위해 ‘찾아가는 경제교육’을 확대하고, 교육 \n콘텐츠·강사진 확충\n장병 경제교육 추진계획\n • 참여기관: 경제교육단체협의회와 회원사인 예금보험공사, 서민금융진흥원, \n신용회복위원회, 군인공제회, 유관기관인 지역경제교육센터 6개 \n교육기관이 협력적 관계로 참여\n • 교육방식 : 온·오프라인 2 track 교육 실시\n - 오프라인: 개별 군 부대에서 수요에 맞는 교육기관에 자율적으로 강의 신청\n→교육기관에서 해당 부대로 강사 파견\n * 경교협은 자체 군 장병 전용 플랫폼을 구축함으로써 모든 교육 내용을 포함해 교육 신청 \n및 평가 등을 수행\n - 온라인 : 기재부가 ’24. 7월에 오픈한 ‘경제배움e+’ 플랫폼을 통해 맞춤형 \n경제교육 콘텐츠 및 상시 학습 환경 제공\n * 경제배움e + 홈페이지(www.econedu.go.kr)-경제교육채널-채널보기-장병 경제교육 채널\n교육 대상\n • 육·해·공군, 해병대 예하부대 장병 및 각 군 훈련기관의 교육생\n * 양성교육 과정(훈련소 및 신병교육)·보수교육 과정 등 통제과목(1h)으로 반영\n교육 내용 * 표준강의안: 군 장병 맞춤형 교제 12편\n • 개인 재무상황 진단, 저축 상품에 대한 이해 등 재무관리, 신용 관리, 금융 \n사기유형 및 예방 방법 등\n교육 신청 * 각 부대 담당자가 신청\n • 경제교육단체협의회 : http://edu-kcee.or.kr 신청\n • 군인공제회 : https://www.mmaa.or.kr/web/main/index.do 신청\n • 지역경제교육센터 : www.econedu.go.kr 지역별 센터 유선 신청',
  '60 \n2026 초급간부 길라잡이\n-③-Ⅰ\n사이버아카데미(구.진로설계교육)\n 개 요 \n\x07 \x07전역예정장병 전직준비 및 생애설계 역량 강화를 위한 온라인 상시학습시스템으로 \n장병 누구나, 언제, 어디서든 수강 가능\n 주요내용\n •취업역량 기본학습\n - 전직교육 및 일자리 사업참여 전 학습을 통한 기본역량 구비 \n - 대상별 교육과정\n구 분\n청년장병(단기 간부+용사)\n중·장기 간부\n진로 분야\n•진로설정 방법\n•경험 기반 강점 발견\n•경력기술서 작성\n•군 경력 연계 진로목표 설정\n•가치 기반 직업 탐색\n•전직계획서 작성\n전직 분야\n•채용정보 탐색\n•구직서류/면접방법\n•대기업/공공기관 취업전략\n•인사담당자 인터뷰\n•산업/기업/직무 분석\n•목표별 취업준비 전략\n•인·적성검사 영역별 이해\n•취·창업 성공 사례\n공통 분야\n•AI디지털역량, 경제, 트렌드\n•시험 대비 어학과정(영어, 중국어, 일본어 등)\n •취업역량 심화학습\n - 희망 분야 및 과정별 학습을 통한 자기주도적 전직역량 향상\n - 분야별 교육과정\n교육 분야\n과 정\n주 요 내 용\n편 수\n총 계\n4,000\n진로 분야\n생애설계\n변화관리, 생애목표설정, 자기경영, 재무관리\n550\n진로\n경험기반 강점발견, 상황별 진로탐색, 경력관리\n550\n전직 분야\n취·창업\n채용트렌드, 구직서류 작성법, 면접전략, 창업로드맵\n550\n직무\n인사, 재무회계, 유통물류, 영업/마케팅\n350\n자격\n취업 연계 자격과정\n700\n공통 분야\n지식\nAI디지털역량, 경제, 트렌드\n600\n어학\n시험 대비 어학과정\n700\n-③ 전역예정장병 취업 및 창업 지원',
  '장갑차야전정비병, 전차야전정비병, 조리병, 중형차량운전병, 지게차운전병, \n차량야전정비병\n종합행정학교\n군사경찰특기병, 군종특기병, 재정회계병\n포병학교\n자주포정비병\n항공학교\n운항관제반\n특수전학교\n공수기본, 낙하산포장정비\n해군\n기술행정학교\n공병병, 대형수송병, 일반수송병, 중장비수송병, 공병장비운용병, 수송병, \n전기병, 조리병, 추진기관병\n전투병과학교\n갑판병, 전탐병, 정보병, 조타병\n정보통신학교\n전산병 2과정, 전자전병, 정보통신병, 통신병 1과정, 통신병 2과정, \n전자기전병\n특수전전단\n특수전초급(병)\n해난구조교육훈련대대\n해난구조기본과정\n공군\n교육사령부 군수1학교\n항공기기관정비병, 항공기무기정비병, 항공기부속정비병, 항공기제작정비병, \n항공기지상장비정비병, 항공전자장비정비병, 항공탄약정비병, \n항공기기체정비병, 항공장구정비병\n교육사령부 군수2학교\n공병장비운전병(기지건설장비운전병), 급양병, 기계설비병(항공설비병), \n방공포차량운전병, 소방병(항공소방병), 일반차량운전병, 장갑차운전병, \n특수차량운전병, 항공기초과저지병, 항공운수병(항공운수 및 의장병), \n화생방병, 화생방차량운전병, 환경병(환경관리병), 전력설비병, 토목건축병\n방공포병학교\n단거리대공무기운용병, 단거리유도무기운용병, 장거리유도무기발사운용병, \n중거리유도무기발사운용병\n정보통신학교\n지상레이더체계정비병, 보안체계관리병, 전술항공통신체계정비병\n항공우주통제학교\n기상관측병\n* 국가평생교육진흥원의 평가인정 결과에 따라 학점인정 과정이 조정될 수 있으므로, 상세 내용은 \n‘학점은행제’ 홈페이지 확인',
  '2026 병 복지 길라잡이 35\n군 e-러닝 학습콘텐츠 제공\n • 제공 콘텐츠 : 외국어, 자격증, IT, 취업, 검정고시, 독학사 등\n • 수강 절차 : 장병e음→군 e-러닝→일반강좌 \n • 제공 콘텐츠 세부내용(’25년 기준)\n구 분\n강 좌 내 역\n자격증\n부동산 : 공인중개사, 주택관리사 \n기사: 건축, 기계장비설비·설치, 안전관리, 에너지·기상, 자동차,\n정보기술, 토목, 환경 등\n산업기사: 건축, 기계장비설비·설치, 안전관리, 에너지·기상, 자동차, \n정보기술, 토목, 환경 등\n기능사: 건축, 기계장비설비·설치, 안전관리, 에너지·기상, 자동차, \n정보기술, 토목, 환경, 조리, 조경, 제과·제빵 등\n기타 : 한국사, 물류 관리, 세무회계 등\n어 학\n영어: TEPS, 토익, 토플, 독해, 문법, 비즈니스, 어휘, 영작문, 청취, 회화\n일본어: 일본어능력시험, 회화, JPT \n중국어: 중국어회화, 수험한자, HSK&TSC\n기타: 프랑스어, 러시아어, 스페인어, 아랍어, 몽골어, 태국어, 독일어, \n베트남어, 인도네시아어 등, 5분 분량의 일일 어학 콘텐츠\nIT/OA\nNetwork · Programming, OS, 웹, 영상제작, 디자인, IT 관련 자격증 등\n취 업\n공무원: 7·9급, 행정직, 세무/관세직, 기술직, 경찰직 등\n기타: 교원임용, 손해평가사, 공인노무사, 행정사, 사회복지사 등\n인문학 /\n기타\n인문학 강좌 및 검정고시·독학사 교과 과목 및 문제풀이, 대학편입 등\n맞춤형 e북 지원 제도\n • 개요 : 군 복무 중 독서와 학습을 통한 자기개발을 지원하기 위해 \n소요 비용의 일부를 지원\n • 대상 : 병 및 상근예비역\n • 지원금액 : 1인당 연간 최대 64,000원(개인부담 20%)\n • 지원분야 : 전자책, 정기구독, 전자책 구매, 학습도서(종이책 가능)\n • 이용방법 : 장병e음 內 제휴업체에서 구매\n * 자세한 내용은 장병e음 - 맞춤형 e북 지원 참조',
  '이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프로그램 목록**을 정리한 것입니다. 컬럼은 각각 **사업명**, **대상**, **주요 내용**을 의미하며, 사이버교육(사이버아카데미), 취업박람회, 청년장병 뉴스타트 Ⅰ·Ⅱ·Ⅲ(2박3일 소집교육 포함), 창업인식개선교육, 창업멘토링, 국방창업경진대회, 취업컨설팅 등이 포함됩니다. 대상은 주로 **군 복무 중인 전 장병**, **청년장병**, **창업 관심 장병**, **창업희망팀/경진대회 진출팀**, **구직등록 장병** 등으로 구분되며, 맞춤형 컨설팅·면접·취업매칭·설명회·멘토링 같은 실질적 지원이 핵심입니다.'],
 ['62 \n2026 초급간부 길라잡이\n-③-Ⅲ\n청년장병 뉴 스타트(New start)\n - \x07(뉴 스타트 미참여자) : 초기상담 통해 뉴 스타트 입교지원 및 대상별 \n취업준비도에 따른 맞춤 컨설팅 및 취업알선 중점\n① 회원 등록 시\n②1:1 컨설팅\n③ 취업알선\n④ 취업성공\n•대상 : 단기복무자\n•초기상담\n•취업프로그램 안내\n•컨설팅 안내\n⇨\n•진로방향/목표점검\n•역량/강점 분석\n•입사서류 클리닉\n•모의면접\n⇨\n•채용정보 제공\n•직무/기업분석\n•희망기업 알선\n⇨\n•직장적응지원\n•경력개발지원\n•취업성공사례관리\n•취업기업관리\n 개 요 \n \x07당해 연도 전역예정장병 청년장병(간부 중심)을 위한 특화 프로그램으로 \n취업역량강화 및 취업률 향상을 목표로 추진되는 채용 단계별 프로그램\n 주요내용\n •뉴 스타트Ⅰ형(취업역량 기본과정)\n구 분\n단과반\n종합반\n목표인원\n•청년장병 2,000명\n기 간\n•1일, 3～6H\n•2박 3일, 18H\n편 성\n•연 60회 이상(단과 20회, 종합반 40회)\n내 용\n•\x07단과 과정 모듈 유형을 선택하여 \n3∼6H 커리큘럼 구성\n•\x07채용동향 분석, 입사지원서 작성, \n인적성 검사, 성공적인 면접, 집단\n상담\n컨설팅 · \n사후관리\n•교육 수료자 대상 개인별 맞춤 컨설팅 및 취업매칭 지원 \n구 분\n•취업맞춤형특기병반\n내 용\n * 맞춤특기병 지원 : 연 4회, 2일 과정\n구분\n내용\n1일차\n(6H)\n•기술직무 이해 및 체험\n - 체험 기술분야 이해(반도체, 스마트팩토리, loT, 전기장치제어 등)\n- 제조 전공정 체험 및 실습\n2일차\n(3H)\n•1:1상담 취업컨설팅(개인별 강점분석, 진로·취업 로드맵)',
  '이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프로그램 목록**을 정리한 것입니다. 컬럼은 각각 **사업명**, **대상**, **주요 내용**을 의미하며, 사이버교육(사이버아카데미), 취업박람회, 청년장병 뉴스타트 Ⅰ·Ⅱ·Ⅲ(2박3일 소집교육 포함), 창업인식개선교육, 창업멘토링, 국방창업경진대회, 취업컨설팅 등이 포함됩니다. 대상은 주로 **군 복무 중인 전 장병**, **청년장병**, **창업 관심 장병**, **창업희망팀/경진대회 진출팀**, **구직등록 장병** 등으로 구분되며, 맞춤형 컨설팅·면접·취업매칭·설명회·멘토링 같은 실질적 지원이 핵심입니다.',
  '01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n63 \n03\nPart\n2026 초급간부 길라잡이\n •뉴 스타트Ⅱ형(취업준비 심화과정)\n구 분\n내 용\n목표인원\n•해당기업 취업을 원하는 청년장병 1,000명\n기 간\n•2박 3일, 18H\n편성/형태\n•연 40회 이상 / 소집(외부연수원), 온라인\n내 용\n•\x07전역예정장병 채용을 원하는 기업과 맞춤형 교육\n•개인별 1:1컨설팅, 취업매칭으로 전역 후 취업연계\n컨설팅 · \n사후관리\n•교육 수료자 대상 개인별 맞춤 컨설팅 및 취업매칭 지원\n •뉴 스타트 Ⅲ형(채용 설명회)\n구 분\n내 용\n기 간\n•\x071일, 2∼4H\n편성/형태\n•\x07연 40회 이상 / 소집(교육원, 외부 시설), 온라인\n일자리 \n매칭데이\n•유형 : 기업 채용 설명회 등 일자리 매칭 행사(연 36회)\n (대기업, 중소기업, 공기업 등 다양한 채용 안내)\n공직 채용 \n설명회\n•유형 : 분야별 공직 설명회(연 2회)\n•내용 : 소방, 경찰, 해양경찰, 공무원, 군무원 등\n창업 \n설명회\n•유형 : 창업설명회(연 2회)\n•내용 : 정부 정책사업 연계, 생계형 창업설명회 등\n 이용방법\n \x07국방전직교육원 홈페이지 회원가입(인터넷) → 일자리지원 HOME → \n 사업별 참가신청 (온라인 개별 신청)\n* 문의 : 뉴 스타트Ⅰ(취업역량 기본과정) 담당 ☎ 031-760-9348\n \n 뉴 스타트Ⅱ(취업준비 심화과정) 담당 ☎ 031-760-9354\n \n 뉴 스타트Ⅲ(채용 설명회) 담당 ☎ 031-760-9344',
  '취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧\n국가보훈대상자 등록\n예비군훈련 안내\n상비예비군 제도\n예비역 병 ⇨ 부사관(하사) 임용\nPart 06\n사회적응 지원 분야',
  '이 표는 **뉴 스타트 입교 시 진행되는 절차와 대상**을 정리한 내용입니다. 컬럼은 별도의 수치형 항목보다는 **입교 시 단계별 프로그램/업무 흐름**을 나타내며, 주요 항목은 **대상(단기복무자)**, **컨설팅 안내**, **신청서 접수**, **개인상담**입니다. 즉, 뉴 스타트 프로그램에 **단기복무자가 입교할 때 수행하는 초기 안내 및 상담 절차**를 요약한 표입니다.'],
 ['이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프로그램 목록**을 정리한 것입니다. 컬럼은 각각 **사업명**, **대상**, **주요 내용**을 의미하며, 사이버교육(사이버아카데미), 취업박람회, 청년장병 뉴스타트 Ⅰ·Ⅱ·Ⅲ(2박3일 소집교육 포함), 창업인식개선교육, 창업멘토링, 국방창업경진대회, 취업컨설팅 등이 포함됩니다. 대상은 주로 **군 복무 중인 전 장병**, **청년장병**, **창업 관심 장병**, **창업희망팀/경진대회 진출팀**, **구직등록 장병** 등으로 구분되며, 맞춤형 컨설팅·면접·취업매칭·설명회·멘토링 같은 실질적 지원이 핵심입니다.',

In [41]:
#
# eval_df에 컬럼으로 추가
#
eval_df['response'] = response_list
eval_df['retrieved_contexts'] = retrieved_context_list
eval_df

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name,response,retrieved_contexts
0,부사관의 연차별 승진 또는 보직 비율은 어떻게 되나요?,[이 표는 **구분별로 장교와 부사관의 승진·보직 또는 충원 비율**을 연차 기준으...,"표에 따르면 부사관의 연차별 승진 또는 보직 비율은 구분별로 제시되어 있으며, 일부...",Military Personnel Planner,WEB_SEARCH_LIKE,MEDIUM,single_hop_specific_query_synthesizer,정보가 부족해 답을 할 수없습니다.,[이 표는 **구분별로 장교와 부사관의 승진·보직 또는 충원 비율**을 연차 기준으...
1,농협손해보험은 맞춤형복지제도에서 어떤 역할을 하나요?,"[46 \n2026 초급간부 길라잡이\n 개 념 \n하사 이상 현역간부, 군무원 ...",농협손해보험은 맞춤형복지제도의 단체보험 항목에서 자녀를 대상으로 공동 서비스제공 보...,HR Benefits Coordinator,PERFECT_GRAMMAR,MEDIUM,single_hop_specific_query_synthesizer,정보가 부족해 답을 할 수없습니다.,"[46 \n2026 초급간부 길라잡이\n 개 념 \n하사 이상 현역간부, 군무원 ..."
2,복지정책협력 담당 부서는 어디인가요?,[02\nPart\n생\n활\n편\n의\n \n분\n야\n47 \n2026 초급간부...,복지정책협력 담당부서는 국방부 복지정책과입니다.,HR Benefits Coordinator,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer,정보가 부족해 답을 할 수없습니다.,[02\nPart\n생\n활\n편\n의\n \n분\n야\n47 \n2026 초급간부...
3,평택에 위치한 국방 관련 복지·숙박 시설에는 무엇이 있습니까?,"[이 표는 국방 관련 복지·숙박 시설 목록을 정리한 것으로 보이며, 컬럼은 각각 *...","해군호텔(서울·평택·제주) 및 해군회관(진해)이 포함되어 있으며, 이 중 평택에 위...",Military Personnel Planner,PERFECT_GRAMMAR,SHORT,single_hop_specific_query_synthesizer,평택에 관련된 국방 복지·숙박 시설로는 **해군호텔(평택)**이 있습니다. \n해...,"[이 표는 국방 관련 복지·숙박 시설 목록을 정리한 것으로 보이며, 컬럼은 각각 *..."
4,사회적응 지원 분야에서 청년장병 뉴스타트 프로그램은 어떤 대상에게 어떤 지원을 제공...,[<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧...,사회적응 지원 분야에서 청년장병 뉴스타트 프로그램은 군 복무 중인 전 장병과 청년장...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,청년장병 뉴스타트 프로그램은 **당해 연도 전역예정장병인 청년장병(간부 중심)**을...,[62 \n2026 초급간부 길라잡이\n-③-Ⅲ\n청년장병 뉴 스타트(New sta...
5,장병 경제교욱이랑 사이버아카데미 뭐가 다르나요?,[<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧...,장병 경제교육은 군 복무 중인 장병을 대상으로 경제 관련 교육을 제공하는 프로그램이...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,장병 경제교육과 사이버아카데미는 **목적과 교육 내용이 다릅니다.**\n\n- **...,[2026 병 복지 길라잡이 69\n장병 경제교육\n개 요\n • 병사 봉급의 급격...
6,사회적응 지원 뭐고 청년장병 뉴스타트 프로그램이랑 무슨 관계 있어요?,[<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧...,사회적응 지원은 군 복무 중이나 전역 예정 장병들이 취업이나 창업 준비할 수 있게 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,사회적응 지원은 **전역 전후 장병이 사회로 돌아가 적응하도록 돕는 지원 분야**를...,[62 \n2026 초급간부 길라잡이\n-③-Ⅲ\n청년장병 뉴 스타트(New sta...
7,"사회적응 지원 분야에서 청년장병 뉴스타트 프로그램이 뭐고, 이 프로그램이 군 복무 ...",[<1-hop>\n\n취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧...,사회적응 지원 분야에는 청년장병 뉴스타트 프로그램이 포함되어 있어. 이 프로그램은 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,"청년장병 뉴스타트(New start) 프로그램은 **당해 연도 전역예정 장병, 특히...",[이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프...
8,"해군 복무연장 지원하려면 어떤 절차 따라야 하고, 해군에서 지원 가능한 특기병 종류...",[<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n...,"해군 복무연장 지원하려면 먼저 선발계획 공지 보고, 지원서 접수하고, 부대추천 심사...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,정보가 부족해 답을 할 수없습니다.,[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n...
9,"해군 복무연장 지원하려면 언제 신청해야 하고, 해군에서 조리병이나 갑판병 같은 특기...",[<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n...,"해군 복무연장 지원은 연 2회(전반기, 후반기) 진행되며, 임관 2년차부터 9년차(...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,"해군 복무연장은 **연 2회(전반기, 후반기)** 신청합니다. \n다만 **정확한...",[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n...
10,해군 복무연장 지원하려면 지원대상 기간이랑 해군에서 할 수 있는 병과 뭐 있어?,[<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n...,"해군 복무연장 지원하려면 장교는 임관 2년차부터 9년차까지, 부사관은 임관 4년차부...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,정보가 부족해 답을 할 수없습니다.,[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n...
11,"해군 복무연장 지원하려면 임관 몇 년차부터 몇 년차까지 지원 가능한지랑, 해군에서 ...",[<1-hop>\n\n01\nPart\n인\n사\n제\n도\n \n근\n무\n \n...,"해군 복무연장 지원은 장교의 경우 임관 2년차부터 9년차까지, 부사관의 경우 임관 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,정보가 부족해 답을 할 수없습니다.,[이 표는 **복무연장(복무연장 신청) 관련 유의사항**을 안내하는 내용이다. 핵심...

In [42]:
# eval_df를 ragas의 평가데이터셋 타입으로 변환
from ragas import EvaluationDataset
eval_dataset = EvaluationDataset.from_pandas(
    eval_df[["user_input", "retrieved_contexts", "response", "reference"]]
)
eval_dataset

EvaluationDataset(features=['user_input', 'retrieved_contexts', 'response', 'reference'], len=12)

In [43]:
#
# 평가
#
from ragas.metrics import (
    LLMContextRecall,
    LLMContextPrecisionWithReference,
    Faithfulness,
    AnswerRelevancy,
)
from ragas import evaluate

C:\Users\Playdata\AppData\Local\Temp\ipykernel_15048\3378832119.py:4: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_15048\3378832119.py:4: DeprecationWarning: Importing LLMContextPrecisionWithReference from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextPrecisionWithReference
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_15048\3378832119.py:4: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_15048\3378832119.py:4: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import (

In [44]:
# 평가할 때 사용할 LLM embedding 모델
eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

metrics = [
    LLMContextRecall(llm=eval_llm),
    LLMContextPrecisionWithReference(llm=eval_llm),
    Faithfulness(llm=eval_llm),
    AnswerRelevancy(llm=eval_llm, embeddings=eval_embeddings)

]
eval_result = evaluate(dataset=eval_dataset, metrics=metrics)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_15048\384477035.py:2: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\Playdata\AppData\Local\Temp\ipykernel_15048\384477035.py:3: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))
Evaluating:  38%|███▊      | 18/48 [02:06<03:54,  7.82s/it]Exception raised in Job[14]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4.1 in organization org-YYuhur6XSTqIwPfGagtPXakj on tokens per min (TPM): Limit 30000, Used 28908, Requested 2104. Please try again in 2.023s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}})
Evaluating:  48%|████▊     | 23/48 [02:32<02:04,  4.97s/it]Exception raised in Job[21]: RateLimitError(Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-4.1 in organization org-YYuhur6XSTqIwPfGagtPXakj on tokens per min (TPM): Limit 30000, Used 28780, Requested 1608. Please try again in 776ms. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}})
Evaluating:  52%|█████▏    | 25/48 [02:43<01:50,  4.80s/it]Exception raised in Job[2]: TimeoutError()
Evaluating:  56%|█████▋    | 27/48 [03:00<02:15,  6.45s/it]Exception raised in Job[6]: TimeoutError()
Exception raised in Job[16]: TimeoutError()
Evaluating:  62%|██████▎   | 30/48 [03:04<01:11,  3.97s/it]Exception raised in Job[18]: TimeoutError()
Exception raised in Job[20]: TimeoutError()
Exception raised in Job[22]: TimeoutError()
Evaluating:  88%|████████▊ | 42/48 [04:00<00:30,  5.11s/it]Exception raised in Job[26]: TimeoutError()
Evaluating:  90%|████████▉ | 43/48 [04:00<00:18,  3.78s/it]Exception raised in Job[28]: TimeoutError()
Evaluating: 100%|██████████| 48/48 [04:52<00:00,  6.10s/it]

In [48]:
eval_result

{'context_recall': 0.7407, 'llm_context_precision_with_reference': 0.6019, 'faithfulness': 0.2857, 'answer_relevancy': 0.3237}

In [49]:
result_df = eval_result.to_pandas()
result_df

,user_input,retrieved_contexts,response,reference,context_recall,llm_context_precision_with_reference,faithfulness,answer_relevancy
0,부사관의 연차별 승진 또는 보직 비율은 어떻게 되나요?,[이 표는 **구분별로 장교와 부사관의 승진·보직 또는 충원 비율**을 연차 기준으...,정보가 부족해 답을 할 수없습니다.,"표에 따르면 부사관의 연차별 승진 또는 보직 비율은 구분별로 제시되어 있으며, 일부...",1.000000,0.887500,NaN,0.000000
1,농협손해보험은 맞춤형복지제도에서 어떤 역할을 하나요?,"[46 \n2026 초급간부 길라잡이\n 개 념 \n하사 이상 현역간부, 군무원 ...",정보가 부족해 답을 할 수없습니다.,농협손해보험은 맞춤형복지제도의 단체보험 항목에서 자녀를 대상으로 공동 서비스제공 보...,1.000000,1.000000,NaN,0.000000
2,복지정책협력 담당 부서는 어디인가요?,[02\nPart\n생\n활\n편\n의\n \n분\n야\n47 \n2026 초급간부...,정보가 부족해 답을 할 수없습니다.,복지정책협력 담당부서는 국방부 복지정책과입니다.,1.000000,1.000000,0.000000,0.000000
3,평택에 위치한 국방 관련 복지·숙박 시설에는 무엇이 있습니까?,"[이 표는 국방 관련 복지·숙박 시설 목록을 정리한 것으로 보이며, 컬럼은 각각 *...",평택에 관련된 국방 복지·숙박 시설로는 **해군호텔(평택)**이 있습니다. \n해...,"해군호텔(서울·평택·제주) 및 해군회관(진해)이 포함되어 있으며, 이 중 평택에 위...",1.000000,0.866667,NaN,0.872953
4,사회적응 지원 분야에서 청년장병 뉴스타트 프로그램은 어떤 대상에게 어떤 지원을 제공...,[62 \n2026 초급간부 길라잡이\n-③-Ⅲ\n청년장병 뉴 스타트(New sta...,청년장병 뉴스타트 프로그램은 **당해 연도 전역예정장병인 청년장병(간부 중심)**을...,사회적응 지원 분야에서 청년장병 뉴스타트 프로그램은 군 복무 중인 전 장병과 청년장...,NaN,0.916667,NaN,0.758829
5,장병 경제교욱이랑 사이버아카데미 뭐가 다르나요?,[2026 병 복지 길라잡이 69\n장병 경제교육\n개 요\n • 병사 봉급의 급격...,장병 경제교육과 사이버아카데미는 **목적과 교육 내용이 다릅니다.**\n\n- **...,장병 경제교육은 군 복무 중인 장병을 대상으로 경제 관련 교육을 제공하는 프로그램이...,NaN,NaN,NaN,0.790361
6,사회적응 지원 뭐고 청년장병 뉴스타트 프로그램이랑 무슨 관계 있어요?,[62 \n2026 초급간부 길라잡이\n-③-Ⅲ\n청년장병 뉴 스타트(New sta...,사회적응 지원은 **전역 전후 장병이 사회로 돌아가 적응하도록 돕는 지원 분야**를...,사회적응 지원은 군 복무 중이나 전역 예정 장병들이 취업이나 창업 준비할 수 있게 ...,1.000000,1.000000,NaN,0.618574
7,"사회적응 지원 분야에서 청년장병 뉴스타트 프로그램이 뭐고, 이 프로그램이 군 복무 ...",[이 표는 **군 복무 중인 장병과 전역 예정 장병을 대상으로 한 취·창업 지원 프...,"청년장병 뉴스타트(New start) 프로그램은 **당해 연도 전역예정 장병, 특히...",사회적응 지원 분야에는 청년장병 뉴스타트 프로그램이 포함되어 있어. 이 프로그램은 ...,NaN,0.950000,1.000000,0.843476
8,"해군 복무연장 지원하려면 어떤 절차 따라야 하고, 해군에서 지원 가능한 특기병 종류...",[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n...,정보가 부족해 답을 할 수없습니다.,"해군 복무연장 지원하려면 먼저 선발계획 공지 보고, 지원서 접수하고, 부대추천 심사...",0.500000,0.000000,0.000000,0.000000
9,"해군 복무연장 지원하려면 언제 신청해야 하고, 해군에서 조리병이나 갑판병 같은 특기...",[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n...,"해군 복무연장은 **연 2회(전반기, 후반기)** 신청합니다. \n다만 **정확한...","해군 복무연장 지원은 연 2회(전반기, 후반기) 진행되며, 임관 2년차부터 9년차(...",0.500000,0.000000,0.714286,0.000000
10,해군 복무연장 지원하려면 지원대상 기간이랑 해군에서 할 수 있는 병과 뭐 있어?,[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n...,정보가 부족해 답을 할 수없습니다.,"해군 복무연장 지원하려면 장교는 임관 2년차부터 9년차까지, 부사관은 임관 4년차부...",0.333333,0.000000,0.000000,0.000000
11,"해군 복무연장 지원하려면 임관 몇 년차부터 몇 년차까지 지원 가능한지랑, 해군에서 ...",[이 표는 **복무연장(복무연장 신청) 관련 유의사항**을 안내하는 내용이다. 핵심...,정보가 부족해 답을 할 수없습니다.,"해군 복무연장 지원은 장교의 경우 임관 2년차부터 9년차까지, 부사관의 경우 임관 ...",0.333333,0.000000,0.000000,0.000000