## 0. Qdrant / Neo4j 테스트셋 로드 및 병합
- 각 노트북(`RAG_evaluation_Qdrant_1.ipynb`, `RAG_evaluation_Neo4j.ipynb`)에서 `eval_df.to_pickle(...)`로 저장해둔 테스트셋을 불러와 병합합니다.
- **이 셀을 가장 먼저 실행**해야 아래 셀들에서 `eval_df`를 참조할 수 있습니다 (지금 노트북은 이 셀이 없어서 `NameError: name 'eval_df' is not defined`가 발생했습니다).

In [7]:
import pandas as pd
import os

# 노트북이 프로젝트 루트(SKN31-3rd-2Team)에 있으므로 상대경로로 충분합니다.
SAVE_DIR = "eval_results"

qdrant_path = os.path.join(SAVE_DIR, "eval_testset_qdrant.pkl")
neo4j_path = os.path.join(SAVE_DIR, "eval_testset_neo4j.pkl")

assert os.path.exists(qdrant_path), f"파일이 없습니다: {os.path.abspath(qdrant_path)}"
assert os.path.exists(neo4j_path), f"파일이 없습니다: {os.path.abspath(neo4j_path)}"

df_qdrant = pd.read_pickle(qdrant_path)
df_neo4j = pd.read_pickle(neo4j_path)

# 컬럼 구성이 동일한지 확인 (user_input, reference_contexts, reference, synthesizer_name, source 등)
assert set(df_qdrant.columns) == set(df_neo4j.columns), (
    f"두 테스트셋의 컬럼이 다릅니다.\nqdrant: {list(df_qdrant.columns)}\nneo4j: {list(df_neo4j.columns)}"
)

eval_df = pd.concat([df_qdrant, df_neo4j], ignore_index=True)
print(eval_df.shape)
print(eval_df["source"].value_counts())
eval_df

(23, 8)
source
qdrant    12
neo4j     11
Name: count, dtype: int64

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name,source
0,9~12월 언제 뭐해요?,"[이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 ...","9~12월에는 범부처 창업경진대회에 참가하고, 12월에 시상식이 진행됩니다.",Office Administrator,MISSPELLED,SHORT,single_hop_specific_query_synthesizer,qdrant
1,군 주거 지원제도에서 국가가 민간주택 전ㆍ월세 지원 시 어떤 방식으로 지원을 제공하...,[02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부...,군 주거 지원제도에서 민간주택 전ㆍ월세 지원은 협약은행에서 전ㆍ월세 자금을 지원하고...,Military Housing Coordinator,PERFECT_GRAMMAR,LONG,single_hop_specific_query_synthesizer,qdrant
2,국내외 학위과정이 뭐에요? 혹시 군에서 지원해주는건가요? 그리고 이게 자기개발이나 ...,[이 표는 **“03 Part 자기개발 및 전직지원 분야”**에 포함된 지원 항목을...,국내·외 학위과정은 군 구성원의 자기개발과 전역 후 진로 준비를 돕기 위해 지원되는...,Office Administrator,MISSPELLED,LONG,single_hop_specific_query_synthesizer,qdrant
3,육군 장기복무 선발계획은 언제 어디에 탑재되나요? 그리고 육군 장기복무 선발 담당 ...,[12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획...,"육군 장기복무 선발계획은 장교의 경우 전반기는 전년도 12월, 후반기는 8월에 각 ...",Office Administrator,MISSPELLED,LONG,single_hop_specific_query_synthesizer,qdrant
4,"육아휴직 제도와 난임 휴가 및 휴직 제도는 각각 어떤 대상과 조건에 따라 적용되며,...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,qdrant
5,육아휴직 제도랑 난임 휴가 및 휴직 제도 차이 뭐에요?,[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,qdrant
6,"육아 시간제 근무와 모성보호시간 제공 제도는 각각 어떤 대상에게 적용되며, 근무시간...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아 시간제 근무는 만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,qdrant
7,"일과 가정의 양립 지원과 가족수당 지원에 대해 궁금한데, 군인 및 군무원이 자녀를 ...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,군인 및 군무원이 일과 가정의 양립을 지원받기 위해 활용할 수 있는 제도에는 육아휴...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,qdrant
8,"해병대사 장기복무 선발 일정이 언제고, 장기복무 관련 문의는 어디로 해야 되는지 알려줘.",[<1-hop>\n\n12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\...,"해병대사 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant
9,해병 장기복무 선발 일정이랑 담당 부서 전화번호가 뭐였더라? 그리고 해병 부사관이 ...,[<1-hop>\n\n12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\...,"해병 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반기 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant
10,"군무원이 자녀를 양육하거나 임신, 출산, 난임 치료 등 가족 관련 상황에서 받을 수...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,"군무원은 자녀 양육, 임신, 출산, 난임 치료 등 다양한 가족 관련 상황에서 여러 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant
11,군무원 난임휴직이랑 육아휴직 차이 뭐에요?,[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,군무원 난임휴직은 난임으로 장기간 치료가 필요한 경우 1년(불가피한 경우 1년 연장...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant
12,대통령령에 따라 사회복무요원 소집이 연기된 사람이 다시 소집될 수 있는 경우는 무엇...,[① 지방병무청장은 사회복무요원 소집 순서가 결정된 사람을 대상으로 복무기관을 정\...,병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령...,Military Incident Reporting Officer,MISSPELLED,LONG,single_hop_specific_query_synthesizer,neo4j
13,지방병무청장의 역할은 무엇인가요?,[① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 ...,지방병무청장은 입영 계획서에 따라 현역입영 통지서를 입영일 7일 전까지 대상자에게 ...,Military Incident Reporting Officer,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer,neo4j
14,"군사경찰부대 뭐하는데, 사고나면 군사경찰부대가 어떻게 해야돼요, 그리고 사고속보는 ...",[① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각 호와 같다. 다만 ...,"사고가 발생하면 사고속보는 제262조에 따라 군사경찰계통으로 보고해야 하고, 사고 ...",Military Personnel Administrator,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer,neo4j
15,국가법령정보센터에서 군 복무 중인 군인과 군무원이 반드시 지켜야 하는 맹세와 관련된...,"[군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세...",국가법령정보센터에서는 군에 복무 중인 군인과 근무 중인 군무원이 국가에 대하여 맹세...,Military Incident Reporting Officer,WEB_SEARCH_LIKE,LONG,single_hop_specific_query_synthesizer,neo4j
16,불침번이 근무 중 이상이 있을 때 당직계통에 어떻게 보고해야 합니까?,"[① 불침번은 건물 내ㆍ외를 완벽히 경계하여야 하며, 근무 중 지정된 위치를 떠나거...","불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, 당직계통의 상관에게 보고하...",Military Personnel Administrator,PERFECT_GRAMMAR,SHORT,single_hop_specific_query_synthesizer,neo4j
17,국방부장관 입영계획서 언제 보내야되? 그리고 급여나 재해보상 관련해서 국방부장관이 ...,[<1-hop>\n\n① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군...,국방부장관은 입영기본 계획서를 입영일 40일 전까지 병무청장 및 해당 군 참모총장에...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j
18,국방부장관이 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여 입영 ...,[<1-hop>\n\n① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군...,"국방부장관은 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여, 입영...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j
19,"국방부 관련 규정에 따라 성희롱 또는 성폭력 사고가 발생했을 때, 보고의 유형과 보...",[<1-hop>\n\n① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각...,성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j
20,"국방부와 각 군 본부에서 성희롱 또는 성폭력 사고가 발생했을 때, 사고 보고의 유형...",[<1-hop>\n\n① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각...,성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j
21,법제처에서 정한 규정에 따라 군인이나 군무원이 포로가 되었을 때 지켜야 하는 맹세 ...,"[<1-hop>\n\n군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음...",군에 복무 중인 군인이나 근무 중인 군무원은 법제처에서 정한 규정에 따라 국가와 민...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j
22,"국가법령정보센터에 따르면, 군 복무 중 포로가 되었을 때 군인이 지켜야 할 행동 원...","[<1-hop>\n\n군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음...","<1-hop>에 따르면, 군 복무 중인 군인이나 군무원은 국가에 대한 맹세에 따라 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j

## 1. 병합된 user_input을 에이전트(`LangGraphChatbot`)에 넣어 response / retrieved_contexts 생성

In [8]:
import sys, os, re, uuid

# 노트북 실행 위치(cwd) = 프로젝트 루트이므로, run_chatbot.py/tools.py를 바로 import 가능
# (혹시 다른 위치에서 커널을 띄웠을 경우를 대비해 루트를 sys.path에 명시적으로 추가)
PROJECT_ROOT = os.getcwd()
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

from dotenv import load_dotenv
load_dotenv(os.path.join(PROJECT_ROOT, ".env"))

from run_chatbot import LangGraphChatbot

bot = LangGraphChatbot(verbose=False)

def split_references(references: list[str]) -> list[str]:
    contexts = []
    for ref in references:
        chunks = re.split(r"--- \[참조 (?:문서|조문) \d+\] ---", ref)
        for c in chunks:
            c = c.strip()
            if c:
                contexts.append(c)
    return contexts

response_list = []
retrieved_context_list = []

for i, user_input in enumerate(eval_df["user_input"], start=1):
    thread_id = f"eval-{uuid.uuid4()}"
    references, answer = bot.ask(user_query=user_input, thread_id=thread_id)
    contexts = split_references(references)

    if not contexts:
        print(f"[경고] {i}번째 질문에서 검색된 context가 없습니다: {user_input}")

    response_list.append(answer)
    retrieved_context_list.append(contexts)

    if i % 5 == 0:
        print(f"진행: {i}/{len(eval_df)}")

eval_df["response"] = response_list
eval_df["retrieved_contexts"] = retrieved_context_list
eval_df

[경고] 1번째 질문에서 검색된 context가 없습니다: 9~12월 언제 뭐해요?
진행: 5/23

Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"

진행: 10/23

Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"

[경고] 14번째 질문에서 검색된 context가 없습니다: 지방병무청장의 역할은 무엇인가요?
진행: 15/23

Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"

진행: 20/23

Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"
Received notification from DBMS server: <GqlStatusObject gql_status='01N01', status_description='warn: feature deprecated with replacement. db.index.vector.queryNodes is deprecated. It is replaced by SEARCH.', position=<SummaryInputPosition line=1, column=1, offset=0>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 0, 'line': 1, 'column': 1}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: "CALL db.index.vector.queryNodes('article_vector_index', $top_k, $query_embedding)\nYIELD node, score\nRETURN node.id AS id, node.name AS name, node.description AS description, score\nORDER BY score DESC"

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name,source,response,retrieved_contexts
0,9~12월 언제 뭐해요?,"[이 표는 **범부처 창업경진대회 참가 일정**을 요약한 것으로, **9~12월에 ...","9~12월에는 범부처 창업경진대회에 참가하고, 12월에 시상식이 진행됩니다.",Office Administrator,MISSPELLED,SHORT,single_hop_specific_query_synthesizer,qdrant,안녕하세요! 저는 박병장입니다. 9월부터 12월까지의 군 생활 일정은 부대마다 다를...,[]
1,군 주거 지원제도에서 국가가 민간주택 전ㆍ월세 지원 시 어떤 방식으로 지원을 제공하...,[02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부...,군 주거 지원제도에서 민간주택 전ㆍ월세 지원은 협약은행에서 전ㆍ월세 자금을 지원하고...,Military Housing Coordinator,PERFECT_GRAMMAR,LONG,single_hop_specific_query_synthesizer,qdrant,군 주거 지원제도에서 국가가 민간주택 전ㆍ월세를 지원하는 방식은 다음과 같습니다. ...,[02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부...
2,국내외 학위과정이 뭐에요? 혹시 군에서 지원해주는건가요? 그리고 이게 자기개발이나 ...,[이 표는 **“03 Part 자기개발 및 전직지원 분야”**에 포함된 지원 항목을...,국내·외 학위과정은 군 구성원의 자기개발과 전역 후 진로 준비를 돕기 위해 지원되는...,Office Administrator,MISSPELLED,LONG,single_hop_specific_query_synthesizer,qdrant,"국내외 학위과정은 군에서 전문인력을 양성하기 위해 제공하는 프로그램으로, 장기복무자...",[56 \n2026 초급간부 길라잡이\n-①-Ⅰ\n국내·외 학위과정 지원\n 개 요...
3,육군 장기복무 선발계획은 언제 어디에 탑재되나요? 그리고 육군 장기복무 선발 담당 ...,[12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획...,"육군 장기복무 선발계획은 장교의 경우 전반기는 전년도 12월, 후반기는 8월에 각 ...",Office Administrator,MISSPELLED,LONG,single_hop_specific_query_synthesizer,qdrant,"장기복무 선발계획은 육군의 경우 장교 전반기 선발은 전년도 12월, 후반기 선발은 ...",[이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 ...
4,"육아휴직 제도와 난임 휴가 및 휴직 제도는 각각 어떤 대상과 조건에 따라 적용되며,...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,qdrant,"육아휴직 제도와 난임 휴가 및 휴직 제도는 각각 다른 대상과 조건에 따라 적용되며,...",[02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부...
5,육아휴직 제도랑 난임 휴가 및 휴직 제도 차이 뭐에요?,[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,qdrant,육아휴직 제도와 난임 휴가 및 휴직 제도는 각각 다른 목적과 조건을 가지고 있습니다...,[02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부...
6,"육아 시간제 근무와 모성보호시간 제공 제도는 각각 어떤 대상에게 적용되며, 근무시간...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,육아 시간제 근무는 만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 ...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,qdrant,육아 시간제 근무와 모성보호시간 제공 제도는 각각 다른 대상을 위해 설계된 제도입니...,[[조문] 과업 후의 지도 (ID: 부대관리훈령::제35조)\n그날 과업종료 시간부...
7,"일과 가정의 양립 지원과 가족수당 지원에 대해 궁금한데, 군인 및 군무원이 자녀를 ...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,군인 및 군무원이 일과 가정의 양립을 지원받기 위해 활용할 수 있는 제도에는 육아휴...,NaN,NaN,NaN,multi_hop_abstract_query_synthesizer,qdrant,안녕하세요! 군인 및 군무원을 위한 일과 가정의 양립 지원 제도와 가족수당에 대해 ...,[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...
8,"해병대사 장기복무 선발 일정이 언제고, 장기복무 관련 문의는 어디로 해야 되는지 알려줘.",[<1-hop>\n\n12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\...,"해병대사 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant,"해병대의 장기복무 선발 일정은 매년 연 1~2회 진행되며, 장교는 전반기와 후반기에...",[10 \n2026 초급간부 길라잡이\n-①-Ⅰ\n장기복무 지원 및 선발과정\n 선...
9,해병 장기복무 선발 일정이랑 담당 부서 전화번호가 뭐였더라? 그리고 해병 부사관이 ...,[<1-hop>\n\n12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\...,"해병 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반기 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant,"해병 장기복무 선발 일정은 매년 전반기와 후반기에 각각 진행되며, 부사관의 경우 전...",[10 \n2026 초급간부 길라잡이\n-①-Ⅰ\n장기복무 지원 및 선발과정\n 선...
10,"군무원이 자녀를 양육하거나 임신, 출산, 난임 치료 등 가족 관련 상황에서 받을 수...",[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,"군무원은 자녀 양육, 임신, 출산, 난임 치료 등 다양한 가족 관련 상황에서 여러 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant,"군무원이 자녀를 양육하거나 임신, 출산, 난임 치료 등 가족 관련 상황에서 받을 수...","[가족수당\n•첫째 월 5만원, 둘째 월 8만원, 셋째 이상 1명당 월 12만원\n..."
11,군무원 난임휴직이랑 육아휴직 차이 뭐에요?,[<1-hop>\n\n02\nPart\n생\n활\n편\n의\n \n분\n야\n43 ...,군무원 난임휴직은 난임으로 장기간 치료가 필요한 경우 1년(불가피한 경우 1년 연장...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,qdrant,난임휴직과 육아휴직은 군무원에게 제공되는 두 가지 다른 형태의 휴직 제도입니다. 각...,[42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임...
12,대통령령에 따라 사회복무요원 소집이 연기된 사람이 다시 소집될 수 있는 경우는 무엇...,[① 지방병무청장은 사회복무요원 소집 순서가 결정된 사람을 대상으로 복무기관을 정\...,병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령...,Military Incident Reporting Officer,MISSPELLED,LONG,single_hop_specific_query_synthesizer,neo4j,"사회복무요원 소집이 연기된 경우, 다시 소집될 수 있는 사유는 다음과 같습니다. \...",[[조문] 사회복무요원의 성실의무 (ID: 병역법::제31조의4)\n사회복무요원은 ...
13,지방병무청장의 역할은 무엇인가요?,[① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군종ㆍ수\n의 분야의 ...,지방병무청장은 입영 계획서에 따라 현역입영 통지서를 입영일 7일 전까지 대상자에게 ...,Military Incident Reporting Officer,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer,neo4j,지방병무청장은 병무 행정의 최전선에서 중요한 역할을 수행하는 직위입니다. 주된 역할...,[]
14,"군사경찰부대 뭐하는데, 사고나면 군사경찰부대가 어떻게 해야돼요, 그리고 사고속보는 ...",[① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각 호와 같다. 다만 ...,"사고가 발생하면 사고속보는 제262조에 따라 군사경찰계통으로 보고해야 하고, 사고 ...",Military Personnel Administrator,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer,neo4j,"군사경찰부대는 군 내에서 법과 질서를 유지하고, 범죄 예방 및 단속, 사고 발생 시...",[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n23 \n...
15,국가법령정보센터에서 군 복무 중인 군인과 군무원이 반드시 지켜야 하는 맹세와 관련된...,"[군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음 각 호와 같이 맹세...",국가법령정보센터에서는 군에 복무 중인 군인과 근무 중인 군무원이 국가에 대하여 맹세...,Military Incident Reporting Officer,WEB_SEARCH_LIKE,LONG,single_hop_specific_query_synthesizer,neo4j,"소대장님, 군 복무 중인 군인과 군무원이 반드시 지켜야 하는 맹세에 대한 법령은 '...","[[조문] 군진수칙 (ID: 부대관리훈령::제15조)\n군에 복무 중인 군인, 근무..."
16,불침번이 근무 중 이상이 있을 때 당직계통에 어떻게 보고해야 합니까?,"[① 불침번은 건물 내ㆍ외를 완벽히 경계하여야 하며, 근무 중 지정된 위치를 떠나거...","불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, 당직계통의 상관에게 보고하...",Military Personnel Administrator,PERFECT_GRAMMAR,SHORT,single_hop_specific_query_synthesizer,neo4j,"어이구, 우리 후임 불침번 근무 중에 이상이 생겼구나? 걱정 마라, 형이 알려줄게....",[Part 03 인사제도/근무 분야\n46 2026 병 복지 길라잡이\n병역감면원서...
17,국방부장관 입영계획서 언제 보내야되? 그리고 급여나 재해보상 관련해서 국방부장관이 ...,[<1-hop>\n\n① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군...,국방부장관은 입영기본 계획서를 입영일 40일 전까지 병무청장 및 해당 군 참모총장에...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j,국방부장관에게 입영계획서를 제출하는 시기는 보통 **2~3월**에 선발 공고가 이루...,[이 표는 예비군/국방 관련 인력의 **선발부터 임용까지의 절차와 일정**을 정리한...
18,국방부장관이 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여 입영 ...,[<1-hop>\n\n① 국방부장관은 법 제58조 및 제59조에 따라 의무ㆍ법무ㆍ군...,"국방부장관은 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여, 입영...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j,"국방부장관님께서는 의무, 법무, 군종, 수의장교 및 기본병과장교의 병적 편입과 관련...",[[조문] 조사ㆍ보고 등 (ID: 군인 재해보상법::제51조)\n국방부장관은 이 법...
19,"국방부 관련 규정에 따라 성희롱 또는 성폭력 사고가 발생했을 때, 보고의 유형과 보...",[<1-hop>\n\n① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각...,성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j,성희롱 및 성폭력 사고 발생 시 보고의 유형과 보고계통은 다음과 같습니다.\n\n1...,[[조문] 성희롱ㆍ성폭력 고충처리부서 지정ㆍ운용 (ID: 부대관리훈령::제248조)...
20,"국방부와 각 군 본부에서 성희롱 또는 성폭력 사고가 발생했을 때, 사고 보고의 유형...",[<1-hop>\n\n① 사고가 발생하였을 때의 보고의 유형 및 보고계통은 다음 각...,성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j,"국방부와 각 군 본부에서 성희롱 또는 성폭력 사고가 발생했을 때, 사고 보고의 유형...",[[조문] 조사 신청 및 접수 (ID: 부대관리훈령::제250조)\n① 성희롱ㆍ성폭...
21,법제처에서 정한 규정에 따라 군인이나 군무원이 포로가 되었을 때 지켜야 하는 맹세 ...,"[<1-hop>\n\n군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음...",군에 복무 중인 군인이나 근무 중인 군무원은 법제처에서 정한 규정에 따라 국가와 민...,NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j,"장교님, 군인이나 군무원이 포로가 되었을 때 지켜야 하는 맹세 내용은 다음과 같습니...","[[조문] 군진수칙 (ID: 부대관리훈령::제15조)\n군에 복무 중인 군인, 근무..."
22,"국가법령정보센터에 따르면, 군 복무 중 포로가 되었을 때 군인이 지켜야 할 행동 원...","[<1-hop>\n\n군에 복무 중인 군인, 근무 중인 군무원은 국가에 대하여 다음...","<1-hop>에 따르면, 군 복무 중인 군인이나 군무원은 국가에 대한 맹세에 따라 ...",NaN,NaN,NaN,multi_hop_specific_query_synthesizer,neo4j,"소대장님, 군 복무 중 포로가 되었을 때 군인이 지켜야 할 행동 원칙은 '부대관리훈...","[[조문] 군진수칙 (ID: 부대관리훈령::제15조)\n군에 복무 중인 군인, 근무..."

## 2. RAGAS 통합 평가

In [9]:
from ragas import EvaluationDataset, evaluate
from ragas.metrics import LLMContextRecall, LLMContextPrecisionWithReference, Faithfulness, AnswerRelevancy
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

eval_dataset = EvaluationDataset.from_pandas(
    eval_df[["user_input", "retrieved_contexts", "response", "reference"]]
)

eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

metrics = [
    LLMContextRecall(llm=eval_llm),
    LLMContextPrecisionWithReference(llm=eval_llm),
    Faithfulness(llm=eval_llm),
    AnswerRelevancy(llm=eval_llm, embeddings=eval_embeddings),
]

eval_result = evaluate(dataset=eval_dataset, metrics=metrics)
result_df = eval_result.to_pandas()
result_df["source"] = eval_df["source"].values  # 출처 컬럼 다시 붙이기
result_df

C:\Users\Playdata\AppData\Local\Temp\ipykernel_29760\2843657565.py:2: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import LLMContextRecall, LLMContextPrecisionWithReference, Faithfulness, AnswerRelevancy
C:\Users\Playdata\AppData\Local\Temp\ipykernel_29760\2843657565.py:2: DeprecationWarning: Importing LLMContextPrecisionWithReference from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextPrecisionWithReference
  from ragas.metrics import LLMContextRecall, LLMContextPrecisionWithReference, Faithfulness, AnswerRelevancy
C:\Users\Playdata\AppData\Local\Temp\ipykernel_29760\2843657565.py:2: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import LLMContextRecall, LLMContextPrecisionWithReference, Faithfulness, AnswerRelevancy
C:\Users\Playdata\AppData\Local\Temp\ipykernel_29760\2843657565.py:2: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import LLMContextRecall, LLMContextPrecisionWithReference, Faithfulness, AnswerRelevancy
C:\Users\Playdata\AppData\Local\Temp\ipykernel_29760\2843657565.py:11: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\Playdata\AppData\Local\Temp\ipykernel_29760\2843657565.py:12: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))
Evaluating:   0%|          | 0/92 [00:00<?, ?it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   2%|▏         | 2/92 [00:01<01:19,  1.13it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:   3%|▎         | 3/92 [00:04<02:37,  1.77s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  12%|█▏        | 11/92 [00:07<00:43,  1.86it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  25%|██▌       | 23/92 [02:55<19:39, 17.09s/it]Exception raised in Job[6]: TimeoutError()
Evaluating:  26%|██▌       | 24/92 [03:00<15:02, 13.27s/it]Exception raised in Job[10]: TimeoutError()
Exception raised in Job[14]: TimeoutError()
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  29%|██▉       | 27/92 [03:01<06:43,  6.20s/it]Exception raised in Job[18]: TimeoutError()
Exception raised in Job[21]: TimeoutError()
Evaluating:  30%|███       | 28/92 [03:04<05:53,  5.52s/it]Exception raised in Job[20]: TimeoutError()
Exception raised in Job[22]: TimeoutError()
Exception raised in Job[24]: TimeoutError()
Evaluating:  36%|███▌      | 33/92 [03:07<02:27,  2.51s/it]Exception raised in Job[26]: TimeoutError()
LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  38%|███▊      | 35/92 [03:10<02:10,  2.29s/it]Exception raised in Job[28]: TimeoutError()
Evaluating:  43%|████▎     | 40/92 [03:37<03:46,  4.36s/it]Exception raised in Job[30]: TimeoutError()
Evaluating:  47%|████▋     | 43/92 [03:45<02:49,  3.45s/it]Exception raised in Job[32]: TimeoutError()
Evaluating:  53%|█████▎    | 49/92 [04:43<05:55,  8.26s/it]Exception raised in Job[34]: TimeoutError()
Evaluating:  55%|█████▌    | 51/92 [04:52<04:15,  6.24s/it]Exception raised in Job[36]: TimeoutError()
Evaluating:  63%|██████▎   | 58/92 [05:39<03:23,  6.00s/it]Exception raised in Job[38]: TimeoutError()
Evaluating:  66%|██████▋   | 61/92 [05:59<03:01,  5.86s/it]Exception raised in Job[40]: TimeoutError()
Exception raised in Job[41]: TimeoutError()
Evaluating:  67%|██████▋   | 62/92 [06:00<02:14,  4.50s/it]Exception raised in Job[42]: TimeoutError()
Evaluating:  71%|███████   | 65/92 [06:04<01:17,  2.87s/it]Exception raised in Job[44]: TimeoutError()
Exception raised in Job[45]: TimeoutError()
Evaluating:  72%|███████▏  | 66/92 [06:04<01:00,  2.34s/it]Exception raised in Job[46]: TimeoutError()
Evaluating:  75%|███████▌  | 69/92 [06:07<00:37,  1.64s/it]Exception raised in Job[50]: TimeoutError()
Evaluating:  77%|███████▋  | 71/92 [06:26<01:45,  5.04s/it]Exception raised in Job[56]: TimeoutError()
Evaluating:  79%|███████▉  | 73/92 [06:43<01:55,  6.08s/it]Exception raised in Job[58]: TimeoutError()
Evaluating:  88%|████████▊ | 81/92 [07:52<00:58,  5.35s/it]Exception raised in Job[70]: TimeoutError()
Evaluating:  90%|█████████ | 83/92 [08:24<01:37, 10.84s/it]Exception raised in Job[72]: TimeoutError()
Evaluating:  92%|█████████▏| 85/92 [08:49<01:20, 11.49s/it]Exception raised in Job[74]: TimeoutError()
Evaluating:  93%|█████████▎| 86/92 [08:55<01:00, 10.03s/it]Exception raised in Job[76]: TimeoutError()
Evaluating:  95%|█████████▍| 87/92 [08:59<00:41,  8.23s/it]Exception raised in Job[78]: TimeoutError()
Evaluating:  96%|█████████▌| 88/92 [09:00<00:23,  5.80s/it]Exception raised in Job[80]: TimeoutError()
Evaluating:  97%|█████████▋| 89/92 [09:04<00:15,  5.27s/it]Exception raised in Job[82]: TimeoutError()
Evaluating: 100%|██████████| 92/92 [09:30<00:00,  6.20s/it]

,user_input,retrieved_contexts,response,reference,context_recall,llm_context_precision_with_reference,faithfulness,answer_relevancy,source
0,9~12월 언제 뭐해요?,[],안녕하세요! 저는 박병장입니다. 9월부터 12월까지의 군 생활 일정은 부대마다 다를...,"9~12월에는 범부처 창업경진대회에 참가하고, 12월에 시상식이 진행됩니다.",0.000000,0.000000,0.000000,0.000000,qdrant
1,군 주거 지원제도에서 국가가 민간주택 전ㆍ월세 지원 시 어떤 방식으로 지원을 제공하...,[02\nPart\n생\n활\n편\n의\n \n분\n야\n45 \n2026 초급간부...,군 주거 지원제도에서 국가가 민간주택 전ㆍ월세를 지원하는 방식은 다음과 같습니다. ...,군 주거 지원제도에서 민간주택 전ㆍ월세 지원은 협약은행에서 전ㆍ월세 자금을 지원하고...,1.000000,1.000000,NaN,0.549566,qdrant
2,국내외 학위과정이 뭐에요? 혹시 군에서 지원해주는건가요? 그리고 이게 자기개발이나 ...,[56 \n2026 초급간부 길라잡이\n-①-Ⅰ\n국내·외 학위과정 지원\n 개 요...,"국내외 학위과정은 군에서 전문인력을 양성하기 위해 제공하는 프로그램으로, 장기복무자...",국내·외 학위과정은 군 구성원의 자기개발과 전역 후 진로 준비를 돕기 위해 지원되는...,1.000000,1.000000,NaN,0.824188,qdrant
3,육군 장기복무 선발계획은 언제 어디에 탑재되나요? 그리고 육군 장기복무 선발 담당 ...,[이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 ...,"장기복무 선발계획은 육군의 경우 장교 전반기 선발은 전년도 12월, 후반기 선발은 ...","육군 장기복무 선발계획은 장교의 경우 전반기는 전년도 12월, 후반기는 8월에 각 ...",1.000000,0.722222,NaN,0.656381,qdrant
4,"육아휴직 제도와 난임 휴가 및 휴직 제도는 각각 어떤 대상과 조건에 따라 적용되며,...",[02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부...,"육아휴직 제도와 난임 휴가 및 휴직 제도는 각각 다른 대상과 조건에 따라 적용되며,...",육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,1.000000,0.416667,NaN,0.589798,qdrant
5,육아휴직 제도랑 난임 휴가 및 휴직 제도 차이 뭐에요?,[02\nPart\n생\n활\n편\n의\n \n분\n야\n43 \n2026 초급간부...,육아휴직 제도와 난임 휴가 및 휴직 제도는 각각 다른 목적과 조건을 가지고 있습니다...,육아휴직 제도는 만 8세 이하 또는 초등학교 2학년 이하 자녀를 양육하는 군인 및 ...,NaN,NaN,NaN,0.579615,qdrant
6,"육아 시간제 근무와 모성보호시간 제공 제도는 각각 어떤 대상에게 적용되며, 근무시간...",[[조문] 과업 후의 지도 (ID: 부대관리훈령::제35조)\n그날 과업종료 시간부...,육아 시간제 근무와 모성보호시간 제공 제도는 각각 다른 대상을 위해 설계된 제도입니...,육아 시간제 근무는 만 8세 이하 또는 초등학교 2학년 이하 자녀가 있는 군인 및 ...,NaN,0.000000,NaN,0.726770,qdrant
7,"일과 가정의 양립 지원과 가족수당 지원에 대해 궁금한데, 군인 및 군무원이 자녀를 ...",[이 표는 군(여군·배우자 포함) 대상의 **임신 전부터 자녀의 성장 단계별(출산~...,안녕하세요! 군인 및 군무원을 위한 일과 가정의 양립 지원 제도와 가족수당에 대해 ...,군인 및 군무원이 일과 가정의 양립을 지원받기 위해 활용할 수 있는 제도에는 육아휴...,NaN,0.873413,NaN,0.729417,qdrant
8,"해병대사 장기복무 선발 일정이 언제고, 장기복무 관련 문의는 어디로 해야 되는지 알려줘.",[10 \n2026 초급간부 길라잡이\n-①-Ⅰ\n장기복무 지원 및 선발과정\n 선...,"해병대의 장기복무 선발 일정은 매년 연 1~2회 진행되며, 장교는 전반기와 후반기에...","해병대사 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반...",NaN,0.833333,NaN,0.517090,qdrant
9,해병 장기복무 선발 일정이랑 담당 부서 전화번호가 뭐였더라? 그리고 해병 부사관이 ...,[10 \n2026 초급간부 길라잡이\n-①-Ⅰ\n장기복무 지원 및 선발과정\n 선...,"해병 장기복무 선발 일정은 매년 전반기와 후반기에 각각 진행되며, 부사관의 경우 전...","해병 장기복무 선발 일정은 장교는 전반기 2월, 후반기 9월이고, 부사관은 전반기 ...",NaN,0.916667,NaN,0.853151,qdrant
10,"군무원이 자녀를 양육하거나 임신, 출산, 난임 치료 등 가족 관련 상황에서 받을 수...","[가족수당\n•첫째 월 5만원, 둘째 월 8만원, 셋째 이상 1명당 월 12만원\n...","군무원이 자녀를 양육하거나 임신, 출산, 난임 치료 등 가족 관련 상황에서 받을 수...","군무원은 자녀 양육, 임신, 출산, 난임 치료 등 다양한 가족 관련 상황에서 여러 ...",NaN,NaN,NaN,0.625887,qdrant
11,군무원 난임휴직이랑 육아휴직 차이 뭐에요?,[42 \n2026 초급간부 길라잡이\n구 분\n주 요 내 용\n난임 휴가\n•난임...,난임휴직과 육아휴직은 군무원에게 제공되는 두 가지 다른 형태의 휴직 제도입니다. 각...,군무원 난임휴직은 난임으로 장기간 치료가 필요한 경우 1년(불가피한 경우 1년 연장...,NaN,NaN,NaN,0.887866,qdrant
12,대통령령에 따라 사회복무요원 소집이 연기된 사람이 다시 소집될 수 있는 경우는 무엇...,[[조문] 사회복무요원의 성실의무 (ID: 병역법::제31조의4)\n사회복무요원은 ...,"사회복무요원 소집이 연기된 경우, 다시 소집될 수 있는 사유는 다음과 같습니다. \...",병무청장은 사회복무요원 소집이 연기된 사람으로서 그 사유가 없어진 사람 등 대통령령...,1.000000,0.250000,NaN,0.778181,neo4j
13,지방병무청장의 역할은 무엇인가요?,[],지방병무청장은 병무 행정의 최전선에서 중요한 역할을 수행하는 직위입니다. 주된 역할...,지방병무청장은 입영 계획서에 따라 현역입영 통지서를 입영일 7일 전까지 대상자에게 ...,0.000000,0.000000,0.000000,0.367923,neo4j
14,"군사경찰부대 뭐하는데, 사고나면 군사경찰부대가 어떻게 해야돼요, 그리고 사고속보는 ...",[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n23 \n...,"군사경찰부대는 군 내에서 법과 질서를 유지하고, 범죄 예방 및 단속, 사고 발생 시...","사고가 발생하면 사고속보는 제262조에 따라 군사경찰계통으로 보고해야 하고, 사고 ...",NaN,0.000000,NaN,0.536853,neo4j
15,국가법령정보센터에서 군 복무 중인 군인과 군무원이 반드시 지켜야 하는 맹세와 관련된...,"[[조문] 군진수칙 (ID: 부대관리훈령::제15조)\n군에 복무 중인 군인, 근무...","소대장님, 군 복무 중인 군인과 군무원이 반드시 지켜야 하는 맹세에 대한 법령은 '...",국가법령정보센터에서는 군에 복무 중인 군인과 근무 중인 군무원이 국가에 대하여 맹세...,1.000000,1.000000,1.000000,0.831895,neo4j
16,불침번이 근무 중 이상이 있을 때 당직계통에 어떻게 보고해야 합니까?,[Part 03 인사제도/근무 분야\n46 2026 병 복지 길라잡이\n병역감면원서...,"어이구, 우리 후임 불침번 근무 중에 이상이 생겼구나? 걱정 마라, 형이 알려줄게....","불침번은 근무 중 이상이 있을 경우 필요한 조치를 하고, 당직계통의 상관에게 보고하...",0.000000,0.000000,0.000000,0.412639,neo4j
17,국방부장관 입영계획서 언제 보내야되? 그리고 급여나 재해보상 관련해서 국방부장관이 ...,[이 표는 예비군/국방 관련 인력의 **선발부터 임용까지의 절차와 일정**을 정리한...,국방부장관에게 입영계획서를 제출하는 시기는 보통 **2~3월**에 선발 공고가 이루...,국방부장관은 입영기본 계획서를 입영일 40일 전까지 병무청장 및 해당 군 참모총장에...,0.500000,0.000000,NaN,0.851761,neo4j
18,국방부장관이 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여 입영 ...,[[조문] 조사ㆍ보고 등 (ID: 군인 재해보상법::제51조)\n국방부장관은 이 법...,"국방부장관님께서는 의무, 법무, 군종, 수의장교 및 기본병과장교의 병적 편입과 관련...","국방부장관은 의무ㆍ법무ㆍ군종ㆍ수의장교 및 기본병과장교의 병적 편입과 관련하여, 입영...",NaN,0.750000,NaN,0.566409,neo4j
19,"국방부 관련 규정에 따라 성희롱 또는 성폭력 사고가 발생했을 때, 보고의 유형과 보...",[[조문] 성희롱ㆍ성폭력 고충처리부서 지정ㆍ운용 (ID: 부대관리훈령::제248조)...,성희롱 및 성폭력 사고 발생 시 보고의 유형과 보고계통은 다음과 같습니다.\n\n1...,성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,0.926667,NaN,0.579220,neo4j
20,"국방부와 각 군 본부에서 성희롱 또는 성폭력 사고가 발생했을 때, 사고 보고의 유형...",[[조문] 조사 신청 및 접수 (ID: 부대관리훈령::제250조)\n① 성희롱ㆍ성폭...,"국방부와 각 군 본부에서 성희롱 또는 성폭력 사고가 발생했을 때, 사고 보고의 유형...",성희롱 또는 성폭력 사고가 발생했을 때에는 일반 사고와 달리 각 군 본부 성고충예방...,NaN,0.596190,NaN,0.756445,neo4j
21,법제처에서 정한 규정에 따라 군인이나 군무원이 포로가 되었을 때 지켜야 하는 맹세 ...,"[[조문] 군진수칙 (ID: 부대관리훈령::제15조)\n군에 복무 중인 군인, 근무...","장교님, 군인이나 군무원이 포로가 되었을 때 지켜야 하는 맹세 내용은 다음과 같습니...",군에 복무 중인 군인이나 근무 중인 군무원은 법제처에서 정한 규정에 따라 국가와 민...,0.428571,0.000000,0.526316,0.613462,neo4j
22,"국가법령정보센터에 따르면, 군 복무 중 포로가 되었을 때 군인이 지켜야 할 행동 원...","[[조문] 군진수칙 (ID: 부대관리훈령::제15조)\n군에 복무 중인 군인, 근무...","소대장님, 군 복무 중 포로가 되었을 때 군인이 지켜야 할 행동 원칙은 '부대관리훈...","<1-hop>에 따르면, 군 복무 중인 군인이나 군무원은 국가에 대한 맹세에 따라 ...",1.000000,0.000000,0.812500,0.900769,neo4j

## 3. 출처(Qdrant / Neo4j)별 평균 점수 비교

In [13]:
metric_cols = ["context_recall", "llm_context_precision_with_reference", "faithfulness", "answer_relevancy"]

summary = result_df.groupby("source")[metric_cols].mean()
summary.loc["total"] = result_df[metric_cols].mean()
summary

,context_recall,llm_context_precision_with_reference,faithfulness,answer_relevancy
source,,,,
neo4j,0.561224,0.320260,0.467763,0.654142
qdrant,0.800000,0.640256,0.000000,0.628311
total,0.660714,0.464258,0.389803,0.640665

## 4. (선택) 결과 저장

In [14]:
result_path = os.path.join(SAVE_DIR, "ragas_eval_result_merged.csv")
result_df.to_csv(result_path, index=False, encoding="utf-8-sig")
print(f"저장 완료: {os.path.abspath(result_path)}")

저장 완료: c:\Users\Playdata\SKN\SKN31-3rd-2Team\eval_results\ragas_eval_result_merged.csv